internal/config/profile.go

This feature for error detection was added on go1.13

CLOUDP-57298: Modernize error detection for file not found

---

internal/cli/atlas_clusters_delete.go
internal/cli/atlas_clusters_delete_test.go
internal/cli/atlas_dbusers_delete.go
internal/cli/atlas_dbusers_delete_test.go
internal/cli/atlas_whitelist_delete.go
internal/cli/atlas_whitelist_delete_test.go
internal/cli/cli.go
internal/cli/cloud_manager_clusters_shutdown.go
internal/cli/cloud_manager_clusters_startup.go
internal/cli/iam_organizations_delete.go
internal/cli/iam_organizations_delete_test.go
internal/cli/iam_projects_delete.go
internal/cli/iam_projects_delete_test.go

This tries to extract some of the repeating blocks so we can reuse them later

CLOUDP-57303: Improve delete commands structure

---

e2e/atlas_whitelist_test.go

_Jira ticket:_ [CLOUDP-57683](https://jira.mongodb.org/browse/CLOUDP-57683)
Create returns the whole list of available entries, e2e can break if something different shows up on the first index

CLOUDP-57683: Improve ip whitelist e2e

---

.drone.yml
e2e/atlas_clusters_test.go

_Jira ticket:_ [CLOUDP-57563](https://jira.mongodb.org/browse/CLOUDP-57563)

CLOUDP-57563: Implementing the e2e test for the command mcli atlas cluster update

---

internal/search/example_search_test.go
internal/search/search_test.go

_Jira ticket:_ [CLOUDP-57723](https://jira.mongodb.org/browse/CLOUDP-57723)

CLOUDP-57723: Add tests and examples to the search pkg

---

internal/cli/atlas_clusters_create.go
internal/cli/atlas_clusters_update.go
internal/cli/atlas_clusters_update_test.go
internal/cli/errors.go
internal/usage/usage.go

_Jira ticket:_ [CLOUDP-54305](https://jira.mongodb.org/browse/CLOUDP-54305)

CLOUDP-54305: CLI: Atlas cluster update via config file

---

e2e/atlas_alertconfig_test.go
internal/cli/atlas_alert_config_create.go
internal/cli/atlas_alert_config_delete.go
internal/cli/atlas_alert_config_delete_test.go
internal/cli/atlas_alert_config_list.go
internal/mocks/mock_alert_configuration.go
internal/store/alert_configuration.go

_Jira ticket_: [CLOUDP-57831](https://jira.mongodb.org/browse/CLOUDP-57831)

CLOUDP-57831: CLI: Deleting an Atlas Alert Configuration

---

.goreleaser.yml

_Jira ticket:_ [CLOUDP-58341](https://jira.mongodb.org/browse/CLOUDP-58341)

CLOUDP-58341: Fix gorelaser brew formula url template

---

e2e/atlas_clusters_test.go
e2e/create_cluster_test.json
internal/cli/atlas_alerts.go
internal/convert/database_user.go
internal/file/file.go
internal/file/file_test.go
internal/fixtures/alert_configs.go
internal/prompts/prompts.go
internal/search/example_search_test.go
internal/search/search_test.go
internal/store/owners.go

_Jira ticket:_ [CLOUDP-58726](https://jira.mongodb.org/browse/CLOUDP-58726)

CLOUDP-58726: Add missing license notice

---

Makefile

_Jira ticket:_ [CLOUDP-58727](https://jira.mongodb.org/browse/CLOUDP-58727)

CLOUDP-58727: Makefile fixes

---

go.mod
go.sum
internal/store/database_users.go

_Jira ticket:_ [CLOUDP-58789](https://jira.mongodb.org/browse/CLOUDP-58789)

CLOUDP-58789: Update Atlas and ops-manager clients

---

internal/cli/atlas_alert_config.go
internal/cli/atlas_alert_config_create.go
internal/cli/atlas_alert_config_list.go
internal/cli/atlas_alerts.go
internal/cli/cloud_manager.go
internal/cli/ops_manager.go
internal/store/alert_configuration.go
internal/store/store.go

_Jira ticket:_ [CLOUDP-57517](https://jira.mongodb.org/browse/CLOUDP-57517)

CLOUDP-57517: List Alert configuration, C/OM

---

.goreleaser.yml

_Jira ticket:_ [CLOUDP-58637](https://jira.mongodb.org/browse/CLOUDP-58637)
_Jira ticket:_ [CLOUDP-58638](https://jira.mongodb.org/browse/CLOUDP-58638)

CLOUDP-58638: Package DEB, CLOUDP-58637: Package RPM

---

go.mod
go.sum
internal/cli/atlas_backups_restores_start_test.go
internal/fixtures/continuous_jobs.go
internal/fixtures/continuous_snapshots.go
internal/mocks/mock_continuous_jobs.go
internal/store/continuous_jobs.go

_Jira ticket:_ [CLOUDP-59263](https://jira.mongodb.org/browse/CLOUDP-59263)

CLOUDP-59263: Update atlas and om client dependencies

---

internal/cli/cli.go

_Jira ticket:_ [CLOUDP-59356](https://jira.mongodb.org/browse/CLOUDP-59356)

CLOUDP-59356: Improving the deleteOpts api in Mongocli

---

e2e/atlas_alerts_test.go

_Jira ticket:_ [CLOUDP-59680](https://jira.mongodb.org/browse/CLOUDP-59680)

CLOUDP-59680: Fixing flaky alert test

---

internal/cli/atlas_backups_restores_list.go
internal/cli/atlas_backups_restores_start.go

_Jira ticket:_ [CLOUDP-59758](https://jira.mongodb.org/browse/CLOUDP-59758)

CLOUDP-59758: Small copy changes for backup

---

internal/cli/ops_manager_automation.go
internal/cli/ops_manager_automation_show.go
internal/cli/ops_manager_automation_show_test.go

_Jira ticket:_ [CLOUDP-59811](https://jira.mongodb.org/browse/CLOUDP-59811)
this command will be hidden, I don't think we want to expose it yet but it helped me debug some things so keeping it around

CLOUDP-59811: Show automation config

---

.evergreen.yml
.goreleaser.yml
Makefile

_Jira ticket:_ [CLOUDP-59940](https://jira.mongodb.org/browse/CLOUDP-59940)
Sample run here https://evergreen.mongodb.com/task/mongocli_master_publish_package_patch_c8d11d9ea8854d3d4c79548e329bd7325043a6c3_5e83102cd6d80a16e2612d77_20_03_31_09_41_01

CLOUDP-59940: Upload dist files to s3

---

internal/cli/cloud_manager.go
internal/cli/ops_manager.go

_Jira ticket:_ [CLOUDP-60018](https://jira.mongodb.org/browse/CLOUDP-60018)

CLOUDP-60018: Add missing commands to cloud manager

---

internal/cli/atlas_dbusers_create.go
internal/cli/atlas_dbusers_update.go
internal/cli/ops_manager_dbusers_create.go
internal/cli/ops_manager_owner_create.go
internal/flags/flags.go

_Jira ticket:_ [CLOUDP-57529](https://jira.mongodb.org/browse/CLOUDP-57529)

CLOUDP-57529: Add short version to username and password flags

---

go.mod
go.sum

_Jira ticket:_ [CLOUDP-60098](https://jira.mongodb.org/browse/CLOUDP-60098)

CLOUDP-60098: Update api clients

---

go.mod
go.sum
internal/convert/automation_config.go
internal/convert/cluster_config.go
internal/search/example_search_test.go
internal/search/search.go

_Jira ticket:_ [CLOUDP-60379](https://jira.mongodb.org/browse/CLOUDP-60379)

CLOUDP-60379: Use OM go client search instead of internal

---

go.mod
go.sum
internal/cli/cloud_manager_clusters_shutdown.go
internal/cli/cloud_manager_clusters_startup.go
internal/cli/ops_manager_dbusers_create.go
internal/cli/ops_manager_dbusers_delete.go
internal/cli/ops_manager_dbusers_delete_test.go
internal/convert/automation_config.go
internal/convert/automation_config_test.go

_Jira ticket:_ [CLOUDP-60397](https://jira.mongodb.org/browse/CLOUDP-60397)

CLOUDP-60397: Use moved method to the om client instead of internal

---

.evergreen.yml
.repo_config.yml

_Jira ticket:_ [CLOUDP-59016](https://jira.mongodb.org/browse/CLOUDP-59016)

CLOUDP-59016: Upload deb to mongo dpkg repo

---

internal/cli/atlas_events_list_test.go
internal/convert/database_user_test.go
internal/convert/randgen.go
internal/fixtures/alerts.go
internal/fixtures/checkpoints.go
internal/fixtures/events.go
internal/fixtures/global_alerts.go
internal/store/indexes.go

Add missing copyright notice headers

---

internal/cli/ops_manager_processes.go
internal/cli/ops_manager_processes_describe.go
internal/cli/ops_manager_processes_describe_test.go
internal/cli/ops_manager_processes_list_test.go
internal/mocks/mock_hosts.go
internal/store/hosts.go

_Jira ticket:_ [CLOUDP-57859](https://jira.mongodb.org/browse/CLOUDP-57859)
```bash
mongocli om processes describe 01f0866f41d6da368a1d1f3c4e23d749 -P om
{
"aliases": [
"172.20.0.3:27017"
],
"authMechanismName": "NONE",
"created": "2020-04-16T09:36:03Z",
"groupId": "5e98249d937cfc52efdc2a9f",
"hostname": "host2",
"id": "01f0866f41d6da368a1d1f3c4e23d749",
"ipAddress": "172.20.0.3",
"lastPing": "2020-04-16T10:23:47Z",
"lastRestart": "2020-04-16T09:50:04Z",
"replicaStateName": "SECONDARY",
"typeName": "REPLICA_SECONDARY",
"version": "4.2.5",
"hasStartupWarnings": true,
"hostEnabled": true,
"journalingEnabled": true,
"logsEnabled": false,
"alertsEnabled": true,
"profilerEnabled": false,
"sslEnabled": false,
"port": 27017,
"uptimeMsec": 2284,
"links": [
{
"rel": "self",
"href": …
```

CLOUDP-57859: Describe the given process, OM

---

.evergreen.yml

_Jira ticket:_ [CLOUDP-60989](https://jira.mongodb.org/browse/CLOUDP-60989)

CLOUDP-60989: Fix package publishing for ubuntu and debian

---

go.mod
go.sum

Update clients to an stable version and stop pointing to master

Update API clients

---

cmd/root.go

If there's an error we already show at the top, the reason this was there was simply because is the basic example from cobra.
This came up in one of our users calls and is a one line fix

CLOUDP-61240: Remove error logging

---

internal/cli/atlas_measurements_disks_describe.go
internal/cli/atlas_measurements_processes.go
internal/cli/ops_manager_measurements_disks_describe.go
internal/cli/ops_manager_measurements_process.go
internal/flags/flags.go

Spotted this doing other things

Clean measurement copy

---

internal/cli/atlas_measurements_processes.go
internal/cli/ops_manager_logs.go
internal/cli/ops_manager_logs_delete.go
internal/cli/ops_manager_logs_delete_test.go
internal/cli/ops_manager_measurements_process.go
internal/description/description.go
internal/mocks/mock_logs.go
internal/store/logs.go

_Jira ticket:_ [CLOUDP-60957](https://jira.mongodb.org/browse/CLOUDP-60957)

CLOUDP-60957: mongocli om logs delete

---

internal/cli/atlas_clusters.go
internal/cli/atlas_clusters_create_test.go
internal/cli/atlas_clusters_pause.go
internal/cli/atlas_clusters_pause_test.go
internal/cli/atlas_clusters_start.go
internal/cli/atlas_clusters_start_test.go
internal/cli/atlas_clusters_update.go
internal/cli/atlas_clusters_update_test.go
internal/mocks/mock_clusters.go
internal/store/clusters.go

[CLOUDP-61529](https://jira.mongodb.org/browse/CLOUDP-61529)

CLOUDP-61529: Pause and Start an atlas cluster

---

cmd/root.go

_Jira ticket:_ [CLOUDP-61709](https://jira.mongodb.org/browse/CLOUDP-61709)
This has come up a couple of times on our user research so let's do it

CLOUDP-61709: Disable usage on error

---

internal/cli/atlas.go
internal/cli/cloud_manager.go
internal/cli/iam.go
internal/cli/ops_manager.go
internal/validate/validate.go
internal/validate/validate_test.go

_Jira ticket:_ [CLOUDP-61711](https://jira.mongodb.org/browse/CLOUDP-61711)
I want later on to start typing our errors so we can offer proper help depending on error but this is a quick win

CLOUDP-61711: Validate API keys presence

---

go.mod
go.sum
internal/cli/atlas_events_list.go
internal/cli/atlas_events_list_test.go
internal/mocks/mock_events.go
internal/store/events.go

_Jira ticket:_ [CLOUDP-61850](https://jira.mongodb.org/browse/CLOUDP-61850)

CLOUDP-61850: Fix listing project events type filter

---

go.mod
go.sum
internal/store/agents.go
internal/store/automation.go
internal/store/clusters.go
internal/store/host_databases.go
internal/store/host_disk_measurements.go
internal/store/host_disks.go
internal/store/host_measurements.go
internal/store/hosts.go
internal/store/organizations.go
internal/store/projects.go

Update the go clients to the latest version

Task: update go clients for ops manager and atlas

---

.evergreen.yml
internal/release/main.go

_Jira ticket:_ [CLOUDP-62033](https://jira.mongodb.org/browse/CLOUDP-62033)
This is part of a bigger effort for making our build available to the website team

CLOUDP-62033: Generate JSON for download center

---

internal/cli/atlas_clusters.go
internal/cli/atlas_clusters_watch.go
internal/cli/atlas_clusters_watch_test.go
internal/cli/ops_manager_automation_watch.go
internal/cli/ops_manager_automation_watch_test.go
internal/description/description.go

_Jira ticket:_ [CLOUDP-57324](https://jira.mongodb.org/browse/CLOUDP-57324)

CLOUDP-57324: Keep polling the automation status and show when changes are done

---

internal/cli/atlas_events_list.go

_Jira ticket:_ [CLOUDP-62055](https://jira.mongodb.org/browse/CLOUDP-62055)

CLOUDP-62055: When listing events error if both orgId and projectId are given

---

.evergreen.yml
.gitignore
Makefile
internal/release/main.go

_Jira ticket:_ [CLOUDP-59024](https://jira.mongodb.org/browse/CLOUDP-59024)
This will let us have a task to release mcli from evg

CLOUDP-59024: List MongoCLI in Download Center

---

.evergreen.yml
wix.json

This let's us package an msi installer with evergreen

Experimental msi packaging

---

.evergreen.yml
.goreleaser.yml
Makefile
RELEASING.md

_Jira ticket:_ [CLOUDP-56392](https://jira.mongodb.org/browse/CLOUDP-56392)
This is only for “daily builds” I need to do a follow up for stable builds but I can’t fully test that without tagging first

CLOUDP-56392: Sign binary for macOS

---

internal/cli/ops_manager_security_enable_test.go
internal/convert/automation_config.go
internal/convert/automation_config_test.go
internal/convert/database_user.go

_Jira ticket:_ [CLOUDP-62567](https://jira.mongodb.org/browse/CLOUDP-62567)

CLOUDP-62567: Enable security fails if only scramsha-256 is given

---

CONTRIBUTING.md
README.md

_Jira ticket:_ [CLOUDP-59259](https://jira.mongodb.org/browse/CLOUDP-59259)

CLOUDP-59259: Add link to users voice page on the README

---

internal/cli/atlas_clusters_create.go
internal/usage/usage.go

_Jira ticket:_ [CLOUDP-63019](https://jira.mongodb.org/browse/CLOUDP-63019)

CLOUDP-63019: Fix continuous backup wording

---

.evergreen.yml
.gitignore
Makefile

_Jira ticket:_ [CLOUDP-62837](https://jira.mongodb.org/browse/CLOUDP-62837)
We had a function to run golang ci but never enable that so that's a bonus thing here

CLOUDP-62837: Output test results in junit format for evergreen

---

build/ci/evergreen.yml
build/package/curator-push.sh
build/package/generate-notices.sh
build/package/rename-pkg.sh
build/package/set-up-gon.sh

Stop using so much embedded bash in evg and have our on set of scripts

Extract some evg shells to proper files

---

.githooks/pre-commit
Makefile
build/package/curator-push.sh
build/package/rename-pkg.sh
build/package/set-up-gon.sh
scripts/add-copy.sh
scripts/fmt.sh

Further work to try to have proper bash files we can lint in the future

Move some make commands to scripts

---

RELEASING.md
scripts/release.sh

task: add a releasing script

---

Makefile
scripts/add-copy.sh
scripts/fmt.sh

feat: add GOPATH to the install make target

---

build/ci/evergreen.yml
build/ci/install-agent-spawn-host.sh

task: update ubuntu version

---

internal/config/const.go
internal/config/profile.go
internal/store/store.go

Allow users to set the ca path

feat: allow ops manager to set ca certificate

---

internal/store/store.go

_Jira ticket:_ [CLOUDP-65742](https://jira.mongodb.org/browse/CLOUDP-65742)

CLOUDP-65742: unauth store creator is not working

---

internal/cli/atlas/atlas.go
internal/cli/cloudmanager/cloud_manager.go
internal/cli/opsmanager/ops_manager.go
internal/config/profile.go

_Jira ticket:_ [CLOUDP-65746](https://jira.mongodb.org/browse/CLOUDP-65746)

CLOUDP-65746: Set the default service for atlas/om/cm commands

---

internal/cli/config/config.go
internal/description/description.go

_Jira ticket:_ [Name of ticket](https://jira.mongodb.org/browse/[name-of-ticket])

CLOUDP-64975: Add a message with link to get keys at the top of the config command

---

internal/cli/organizations/list.go
internal/cli/organizations/list_test.go
internal/cli/projects/list.go
internal/cli/projects/list_test.go
internal/mocks/mock_organizations.go
internal/mocks/mock_profile.go
internal/mocks/mock_projects.go
internal/store/organizations.go
internal/store/projects.go

_Jira ticket:_ [CLOUDP-65299](https://jira.mongodb.org/browse/CLOUDP-65299)

CLOUDP-65299: Add pagination to listing organizations

---

.golangci.yml
e2e/atlas/alerts_test.go

Small change to make the 2e tests of alerts more portable across projects

fix: alerts e2e

---

internal/cli/atlas/clusters_create.go
internal/cli/atlas/clusters_update.go
internal/cli/atlas/logs_download.go
internal/cli/automation/update.go
internal/cli/opsmanager/clusters_apply.go
internal/cli/opsmanager/clusters_create.go
internal/cli/opsmanager/clusters_update.go
internal/cli/opsmanager/diagnose_archive_download.go
internal/cli/opsmanager/logs_jobs_download.go

_Jira ticket:_ [CLOUDP-66606](https://jira.mongodb.org/browse/CLOUDP-66606)

CLOUDP-66606: Improve autocompletion for file flags

---

.golangci.yml
e2e/atlas/alert_settings_test.go
e2e/atlas/alerts_test.go
e2e/atlas/clusters_test.go
e2e/atlas/dbusers_test.go
e2e/atlas/events_test.go
e2e/atlas/logs_test.go
e2e/atlas/metrics_test.go
e2e/atlas/whitelist_test.go
e2e/cloud_manager/alerts_test.go
e2e/cloud_manager/dbusers_test.go
e2e/cloud_manager/events_test.go
e2e/cloud_manager/helper_test.go

_Jira ticket:_ [Name of ticket](https://jira.mongodb.org/browse/[name-of-ticket])
I had a suspicious we weren't linting our e2e files but I could not pin the why, now I know

CLOUDP-66614: Enable linting on e2e tests

---

internal/cli/config/config.go
internal/cli/config/prompt.go
internal/config/const.go
internal/config/profile.go
internal/prompt/prompt.go
internal/validate/validate.go

_Jira ticket:_ [CLOUDP-64978](https://jira.mongodb.org/browse/CLOUDP-64978)
_Jira ticket:_ [CLOUDP-65614](https://jira.mongodb.org/browse/CLOUDP-65614)
Closes #200
If there's an error we fallback to the old ways
New select

CLOUDP-64978: List projects by name on config

---

go.mod
go.sum
internal/cli/atlas/processes_list.go
internal/cli/atlas/processes_list_test.go
internal/mocks/mock_processes.go
internal/store/processes.go

_Jira ticket:_ [CLOUDP-66800](https://jira.mongodb.org/browse/CLOUDP-66800)

CLOUDP-66800: Filter processes by clusterId

---

README.md
cmd/mongocli/mongocli.go

_Jira ticket:_ [CLOUDP-66892](https://jira.mongodb.org/browse/CLOUDP-66892)

CLOUDP-66892: Update README autocomplete docs

---

build/ci/evergreen.yml
build/ci/repo_config.yml

_Jira ticket:_ [CLOUDP-66893](https://jira.mongodb.org/browse/CLOUDP-66893)

CLOUDP-66893: Add ubuntu 20.04 distribution to repo publishing

---

go.mod
go.sum

Adds support for data lake and online archive
_Jira ticket:_ [CLOUDP-66901](https://jira.mongodb.org/browse/CLOUDP-66901)

CLOUDP-66901: Update go clients

---

build/ci/evergreen.yml
e2e/iam/orgs_test.go

_Jira ticket:_ [CLOUDP-66955](https://jira.mongodb.org/browse/CLOUDP-66955)

CLOUDP-66955:Add e2e tests for orgs

---

e2e/atlas/online_archives_test.go
internal/cli/atlas/onlinearchive/online_archive.go
internal/cli/atlas/onlinearchive/pause.go
internal/cli/atlas/onlinearchive/start.go
internal/cli/atlas/onlinearchive/update.go
internal/cli/atlas/onlinearchive/update_test.go
internal/description/description.go

_Jira ticket:_ [CLOUDP-67005](https://jira.mongodb.org/browse/CLOUDP-67005)

CLOUDP-67005: mongocli atlas cluster(s) onlineArchive(s) update <archiveID>

---

internal/store/store.go

_Jira ticket:_ [CLOUDP-67191](https://jira.mongodb.org/browse/CLOUDP-67191)
The atlas client does not provide os information so we'll keep our old version of the user agent

CLOUDP-67191: Don't use go clients user agent

---

e2e/cli.go
e2e/cloud_manager/servers_test.go

_Jira ticket:_ [CLOUDP-67207](https://jira.mongodb.org/browse/CLOUDP-67207)

CLOUDP-67207: Add server list e2e

---

.golangci.yml
e2e/cloud_manager/deploy_replica_set_test.go
e2e/cloud_manager/helper_test.go
e2e/cloud_manager/servers_test.go
go.mod
go.sum
internal/cli/cloudmanager/cloud_manager.go
internal/cli/opsmanager/clusters/apply.go
internal/cli/opsmanager/clusters/apply_test.go
internal/cli/opsmanager/clusters/clusters.go
internal/cli/opsmanager/clusters/create.go
internal/cli/opsmanager/clusters/create_test.go
internal/cli/opsmanager/clusters/delete.go
internal/cli/opsmanager/clusters/delete_test.go
internal/cli/opsmanager/clusters/describe.go
internal/cli/opsmanager/clusters/describe_test.go
internal/cli/opsmanager/clusters/indexes.go
internal/cli/opsmanager/clusters/indexes_create.go
internal/cli/opsmanager/clusters/indexes_create_test.go
internal/cli/opsmanager/clusters/list.go
internal/cli/opsmanager/clusters/list_test.go
internal/cli/opsmanager/clusters/shutdown.go
internal/cli/opsmanager/clusters/shutdown_test.go
internal/cli/opsmanager/clusters/startup.go
internal/cli/opsmanager/clusters/startup_test.go
internal/cli/opsmanager/clusters/update.go
internal/cli/opsmanager/clusters/update_test.go
internal/cli/opsmanager/ops_manager.go
internal/config/profile_integration_test.go

_Jira ticket:_ [CLOUDP-67367](https://jira.mongodb.org/browse/CLOUDP-67367)

CLOUDP-67367: mongocli om clusters delete <name>

---

.github/pull_request_template.md
CONTRIBUTING.md

CLOUDP-67625: Update the CONTRIBUTING.md

---

go.mod
go.sum
internal/cli/opsmanager/ops_manager.go
internal/cli/owner/create.go
internal/store/store.go

_Jira ticket:_ CLOUDP-67735
We are not able to rely on the go client for setting the certificate, so I had to move some of the logic to the cli, I've tested this manually

CLOUDP-67735: Handle ca certificate for digest transport

---

build/ci/evergreen.yml

CLOUDP-68210: Take cluster e2e tests out of the PR suite

---

README.md
RELEASING.md
build/ci/evergreen.yml

CLOUDP-68237: Fix test repo publishing

---

build/ci/evergreen.yml
internal/cli/atlas/search/create.go
internal/cli/atlas/search/describe.go
internal/cli/atlas/search/list.go
internal/cli/atlas/search/update.go

_Jira ticket:_ CLOUDP-67964
```zsh
$ mongocli atlas clusters search indexes create default --clusterName myDemo --db test --collection test --field name:string
Index default created.
```
```zsh
$  mongocli atlas clusters search indexes describe 5f205691e12f20660d9eb1ec --clusterName myDemo
ID				Name		Database	Collection
5f205691e12f20660d9eb1ec	default		test		test
```
```zsh
$  ongocli atlas clusters search indexes list --clusterName myDemo --db test --collection test 
ID				Name		Database	Collection
5f205691e12f20660d9eb1ec	default		test		test
```

CLOUDP-67964: update internal/cli/atlas/search to use the new output

---

go.mod
go.sum
internal/cli/atlas/search/index_opts.go

_Jira ticket:_ CLOUDP-68246
analyzer is only required for string type so trying to force this may be troublesome, for now we are going simple, field:type and use the default advance options

CLOUDP-68246: fix search index creation with static fields

---

internal/cli/atlas/whitelist/create.go
internal/cli/atlas/whitelist/describe.go
internal/cli/atlas/whitelist/list.go

_Jira ticket:_ CLOUDP-68115
```
./bin/mongocli atlas whitelist list
CIDR BLOCK		SECURITY GROUP
13.236.189.10/32
52.63.26.53/32
18.211.240.224/32
18.210.66.32/32
192.168.0.1/32
18.202.2.23/32
sg-0026348ec11780bd1
18.213.24.164/32
54.76.145.131/32
54.69.74.169/32
54.203.157.107/32
10.0.0.0/16
24.185.173.17/32
```
```
./bin/mongocli atlas whitelist describe sg-0026348ec11780bd1
CIDR BLOCK	SECURITY GROUP
sg-0026348ec11780bd1
```
```
./bin/mongocli atlas whitelist describe 192.168.0.1/32
CIDR …
```

CLOUDP-68115: add whitelist simplified format

---

go.mod
go.sum

build(deps): bump go.mongodb.org

---

internal/cli/atlas/processes_list.go

_Jira ticket:_ CLOUDP-68116
```
./bin/mongocli atlas processes list --profile dev
ID							REPLICA SET NAME	SHARD NAME	VERSION
atlas-142xa9-shard-00-00.t9zpy.mongodb-dev.net:27017	atlas-142xa9-shard-0			4.2.8
atlas-142xa9-shard-00-01.t9zpy.mongodb-dev.net:27017	atlas-142xa9-shard-0			4.2.8
atlas-142xa9-shard-00-02.t9zpy.mongodb-dev.net:27017	atlas-142xa9-shard-0			4.2.8
```

CLOUDP-68116: add simplified process list output

---

internal/cli/opsmanager/owner/create.go

_Jira ticket:_ CLOUDP-68324
```zsh
mongocli om owner create --email gb@test.com --firstName Gustavo --lastName Bazan 
? Password: ***************
Owner successfully created.
Personal API Key: <redacted>
Public API Key: jgjxtnjm
Private API Key: <redacted>
```

CLOUDP-68324: Update owner creation to use the simplified format

---

go.mod
go.sum
internal/cli/organizations/create.go
internal/cli/projects/create.go

_Jira ticket:_ CLOUDP-68335
Update of the client needed for this
```zsh
$ mongocli iam projects create "Project 0" --orgId 5f219131a4380e6bd8539b18 -P om
Project '5f219152a4380e6bd8539b2c' created.
Agent API Key: <redacted>
```
```zsh
$ mongocli iam projects create "Project 1" --orgId 5f219131a4380e6bd8539b18 -P om -o json
{
"agentApiKey": "<redacted>",
"hostCounts": {
"arbiter": 0,
"config": 0,
"master": 0,
"mongos": 0,
"primary": 0,
"secondary": 0,
"slave": 0
},
"id": "5f2191c1a4380e6bd8539bca",
"links": [
{
"rel": "self",
"href": "http://mms:8080/api/public/v1.0/groups/5f2191c1a4380e6bd8539bca"
},
{
"rel": "http://mms.mongodb.com/hosts",
"href": "http://mms:8080/api/public/v1.0/groups/5f2191c1a4380e6bd8539bca/hosts"
},
{
"rel": "http://mms.mongodb.com/users",
"href": …
```

CLOUDP-68335: Include Agent API key on project create response

---

go.sum

build(deps): go mod tidy

---

internal/cli/organizations/apikeys/create.go

_Jira ticket:_ CLOUDP-68632
These are actually required, we need to follow up with docs to update the API docs

CLOUDP-68632: mark roles and description as mandatory

---

e2e/iam/helper_test.go
e2e/iam/org_api_key_whitelist_test.go
e2e/iam/project_api_keys_test.go
internal/cli/organizations/apikeys/whitelist/create.go
internal/cli/organizations/apikeys/whitelist/delete.go
internal/cli/projects/apikeys/assign.go

CLOUDP-68637: implement e2e tests for apikeys/whitelist

---

internal/cli/atlas/privateendpoints/descriptions.go
internal/cli/atlas/privateendpoints/private_endpoints.go
internal/cli/atlas/privateendpoints/watch.go
internal/cli/atlas/privateendpoints/watch_test.go

```zsh
mongocli atlas privateEndpoints watch 5f32b8f7c75ab422b17c8bef -P dev
...........................
Private endpoint changes completed.
```

CLOUDP-69105: mongocli atlas privateEndpoints watch

---

RELEASING.md

CLOUDP-69273: [mongocli] Update release instructions

---

go.mod
go.sum
internal/cli/atlas/networking/containers/list.go
internal/cli/atlas/networking/peering/list.go
internal/cli/atlas/networking/peering/list_test.go
internal/mocks/mock_peering_connections.go
internal/store/peering_connections.go

CLOUDP-69438: Update peering list to use --providerName

---

go.mod
go.sum

CLOUDP-69665: [mongocli] chore: update ops manager go client

---

internal/cli/atlas/logs/download.go

_Jira ticket:_ CLOUDP-61742
`./bin/mongocli atlas log download cluster0-shard-00-00.ajlj3.mongodb-dev.net mongodb.gz
`

CLOUDP-61742: setting the extensions of the log files inside .gz downloaded from atlas

---

CONTRIBUTING.md
e2e/cloud_manager/e2e.env.example

CLOUDP-64365: Remove .env file and update CONTRIBUTING.md

---

internal/cli/iam/projects/apikeys/assign.go
internal/cli/iam/projects/apikeys/delete.go
internal/cli/opsmanager/agents/apikeys/create.go
internal/cli/opsmanager/agents/apikeys/delete.go

CLOUDP-70582: projectId flag doesn't set the right property for create agent api key

---

build/ci/evergreen.yml
e2e/atlas/helper_test.go
e2e/atlas/online_archives_test.go
e2e/atlas/processes_test.go

CLOUDP-70718: Test atlas process list

---

internal/validate/validate_test.go

CLOUDP-71324: [mongocli] Add missing tests for the validate package

---

internal/cli/alerts/alerts_test.go
internal/cli/alerts/settings/settings_test.go
internal/cli/cli.go
internal/cli/iam/iam_test.go
internal/cli/opsmanager/clusters/clusters_test.go
internal/cli/opsmanager/dbusers/dbusers_test.go
internal/cli/opsmanager/diagnosearchive/diagnose_archive_test.go
internal/cli/opsmanager/logs/jobs_test.go
internal/cli/opsmanager/logs/logs_test.go
internal/cli/opsmanager/metrics/metrics_test.go
internal/cli/opsmanager/ops_manager_test.go
internal/cli/opsmanager/owner/owner_test.go
internal/cli/opsmanager/processes/processes_test.go
internal/cli/opsmanager/security/security_test.go
internal/cli/opsmanager/servers/servers_test.go

_Jira ticket:_ CLOUDP-71328
This adds a lot of tests, mainly around testing the builder methods of some commands (it's a lot of work to do all)

CLOUDP-71328: Add tests for command builder methods

---

build/ci/evergreen.yml
internal/cli/alerts/alerts_test.go
internal/cli/alerts/settings/settings_test.go
internal/cli/iam/iam_test.go
internal/cli/opsmanager/clusters/clusters_test.go
internal/cli/opsmanager/dbusers/dbusers_test.go
internal/cli/opsmanager/diagnosearchive/diagnose_archive_test.go
internal/cli/opsmanager/logs/jobs_test.go
internal/cli/opsmanager/logs/logs_test.go
internal/cli/opsmanager/metrics/metrics_test.go
internal/cli/opsmanager/ops_manager_test.go
internal/cli/opsmanager/owner/owner_test.go
internal/cli/opsmanager/processes/processes_test.go
internal/cli/opsmanager/security/security_test.go
internal/cli/opsmanager/servers/servers_test.go

CLOUDP-71426: split unit and integration tests

---

internal/cli/atlas/integrations/create/create.go
internal/cli/atlas/integrations/create/create_test.go
internal/cli/atlas/integrations/create/datadog.go
internal/cli/atlas/integrations/create/datadog_test.go
internal/cli/atlas/integrations/create/description.go
internal/cli/atlas/integrations/create/ops_genie.go
internal/usage/usage.go

_Jira ticket:_ CLOUDP-70031
```
./bin/mongocli atlas integrations create DATADOG --apiKey 51c0ef87e9951c3e147accf0eXXXXX -o json
{
"links": [
{
"rel": "self",
"href": "https://cloud-dev.mongodb.com/api/atlas/v1.0/groups/5e4e593f70dfbf1010295836/integrations/DATADOG?pageNum=1\u0026itemsPerPage=100"
}
],
"results": [
{
"type": "PAGER_DUTY",
"serviceKey": "7fd036a6860e41469fe1fa83XXXXX"
},
{
"type": "DATADOG",
"apiKey": "51c0ef87e9951c3e147accf0XXXXXX",
"region": "US"
},
{
"type": "NEW_RELIC",
"licenseKey": "eu01xx5f87268ff5028e69a67f373f1XXXXXXX",
"accountId": "2857404",
"writeToken": "NRII-zpwCnhrDyUojdSJOk2LDvtTXXXXXXX",
"readToken": "NRIQ-MHCu7bPq2xvrrpVvybtWvXXXXXX"
},
{
"type": "OPS_GENIE",
"apiKey": "9255b505-9c55-45a4-893c-XXXXXXXXX",
"region": "EU"
}
],
"totalCount": 4
}
```
``` …
```

CLOUDP-70031: mongocli atlas integration(s) create|update DATADOG

---

internal/cli/atlas/integrations/create/create.go
internal/cli/atlas/integrations/create/create_test.go
internal/cli/atlas/integrations/create/victor_ops.go
internal/cli/atlas/integrations/create/victor_ops_test.go
internal/flag/flags.go
internal/usage/usage.go

_Jira ticket:_ CLOUDP-70034
```
./bin/mongocli atlas integrations create VICTOR_OPS --apiKey 2eb02ae8-a198-431c-aa8a-dd914a5f0b83
Victor Ops integration configured.
```

CLOUDP-70034: mongocli atlas integration(s) create|update VICTOR_OPS

---

internal/cli/atlas/integrations/create/create.go
internal/cli/atlas/integrations/create/create_test.go
internal/cli/atlas/integrations/create/description.go
internal/cli/atlas/integrations/create/flow_dock.go
internal/cli/atlas/integrations/create/flow_dock_test.go
internal/cli/atlas/integrations/create/flowdock.go
internal/cli/atlas/integrations/create/flowdock_test.go
internal/flag/flags.go
internal/usage/usage.go

_Jira ticket:_ CLOUDP-70035
```
~/workspace/mongoCLI git:(CLOUDP-70035) ✗ ./bin/mongocli atlas integrations create FLOWDOCK --apiToken c6855d4443a7e9f45b437784XXXXXX --orgName MONGODB --flowName Main -o json
{
"links": [
{
"rel": "self",
"href": "https://cloud-dev.mongodb.com/api/atlas/v1.0/groups/5e4e593f70dfbf1010295836/integrations/FLOWDOCK?pageNum=1\u0026itemsPerPage=100"
}
],
"results": [
{
"type": "PAGER_DUTY",
"serviceKey": "7fd036a6860e41469fe1XXXXXX"
},
{
"type": "DATADOG",
"apiKey": "51c0ef87e9951c3e147acXXXXX",
"region": "US"
},
{
"type": "NEW_RELIC",
"licenseKey": "eu01xx5f87268ff5028e69a67f3XXXXXX",
"accountId": "2857404",
"writeToken": "NRII-zpwCnhrDyUojdSJOk2LXXXXX",
"readToken": "NRIQ-MHCu7bPq2xvrrpVvybtWvXXXXXXX"
},
{
"type": "OPS_GENIE",
"apiKey": …
```

CLOUDP-70035: mongocli atlas integration(s) create|update FLOWDOCK

---

Makefile
RELEASING.md
e2e/iam/project_teams_test.go
e2e/iam/team_users_test.go
e2e/iam/teams_test.go
internal/cli/iam/projects/teams/update.go

CLOUDP-72403: Update GOLANGCI_VERSION

---

e2e/atlas/helper_test.go
e2e/atlas/integrations_test.go

CLOUDP-72402: Add e2e tests for atlas integrations

---

internal/cli/opsmanager/clusters/indexes_create.go

fix: small help fix to index create

---

.goreleaser.yml

docs: add little comment on why draft on goreleaser

---

examples/ops-manager/update_all_agents.md

Add upgrade all agents example

---

internal/cli/iam/users/invite.go

_Jira ticket:_ CLOUDP-74002
```
./bin/mongocli iam users invite --country IR --email halopey166@wpsavy.com --firstName andrea --lastName test --username halopey166@wpsavy.com
? Password: *****************
The user 'halopey166@wpsavy.com' has been invited.
Invited users do not have access to the project until they accept the invitation.
```

CLOUDP-74002: [mongocli] Invite users should ask for password if the flag is not set

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/pull_request_template.md

Updated the GitHub templates used to populate new PRs and bug reports.

Chore: improve GitHub templates

---

examples/atlas/create-cluster.md
examples/atlas/create-recomended-indexes.md
examples/atlas/log-download.md

- Add example for creating, waiting and getting the connection for a cluster
- Add example fro creating recommended indexes

docs: add examples

---

go.mod
go.sum

 build(deps): bump go.mongodb.org/ops-manager from 0.10.2 to 0.12.0

---

internal/flag/flags.go

Fixed typo in BindPassword

---

internal/cli/atlas/clusters/indexes_create.go
internal/cli/opsmanager/clusters/indexes_create.go

CLOUDP-76451: Remove unique from rolling index creation

---

build/ci/ego
build/ci/install-agent-spawn-host.sh

CLOUDP-76456: Fix testing for cloud manager with remote host

---

internal/convert/rs_config.go
internal/convert/rs_config_test.go

CLOUDP-76844: Discover replica-set protocol when FCV is only set in the processes

---

.drone.yml
Makefile

_Jira ticket:_ CLOUDP-77106
Adding this to make it easier for people wanting to debug

CLOUDP-77106: [mongocli] Add a build target for debugging

---

build/ci/evergreen.yml
e2e/cloud_manager/agent_api_keys_test.go
e2e/cloud_manager/agents_test.go
e2e/cloud_manager/dbusers_test.go
e2e/cloud_manager/deploy_replica_set_test.go
e2e/cloud_manager/deploy_sharded_cluster_test.go
e2e/cloud_manager/helper_test.go
e2e/cloud_manager/servers_test.go

CLOUDP-77112: Add e2e to sharded clusters

---

e2e/atlas/ldap_test.go

The typo in the flag was fixed but the e2e tests were not updated

test: fix ldap e2e test

---

e2e/cloud_manager/feature_policies_test.go
e2e/cloud_manager/helper_test.go

Added featurePolicies e2e tests

Added featurePolicies e2e tests

---

go.mod
go.sum
internal/cli/opsmanager/dbusers/create.go
internal/fixture/automation_configs.go

build(deps): bump go.mongodb.org/ops-manager from 0.14.0 to 0.16.0

---

internal/flag/flags.go

CLOUDP-79713: --SnapshotRetentionDays flag must start with capital S inconsistent with other flags

---

.github/workflows/pr.yml
.golangci.yml
Makefile
e2e/atlas/clusters_test.go
e2e/atlas/logs_test.go
e2e/atlas/metrics_test.go
e2e/atlas/online_archives_test.go
e2e/cloud_manager/helper_test.go
internal/cli/atlas/security/ldap/delete.go
internal/cli/atlas/security/ldap/description.go
internal/cli/opsmanager/admin/backup/blockstore/delete.go
internal/cli/opsmanager/admin/backup/blockstore/description.go
internal/cli/opsmanager/admin/backup/filesystem/delete.go
internal/cli/opsmanager/admin/backup/filesystem/description.go
internal/cli/opsmanager/admin/backup/oplog/delete.go
internal/cli/opsmanager/admin/backup/oplog/description.go
internal/cli/opsmanager/admin/backup/s3/delete.go
internal/cli/opsmanager/admin/backup/s3/description.go
internal/cli/opsmanager/admin/backup/sync/delete.go
internal/cli/opsmanager/admin/backup/sync/description.go
internal/test/test.go

CLOUDP-80160: mongocli] Update golangci-lint

---

.goreleaser.yml

CLOUDP-80314: [mongocli] add license to brew formula

---

internal/cli/atlas/customdbroles/update.go
internal/cli/atlas/customdbroles/update_test.go

CLOUDP-80534: add --append to mongocli atlas customDBRole(s) update <roleName>

---

internal/cli/opsmanager/serverusage/download.go

CLOUDP-80605:add use to the serverUsage Download command

---

e2e/atlas/access_lists_test.go
internal/cli/atlas/accesslists/create.go
internal/cli/atlas/accesslists/create_test.go
internal/cli/atlas/accesslists/delete_test.go
internal/cli/atlas/accesslists/describe.go
internal/cli/atlas/accesslists/describe_test.go
internal/cli/atlas/accesslists/list.go
internal/cli/atlas/accesslists/list_test.go
internal/mocks/mock_project_ip_access_lists.go
internal/store/project_ip_access_lists.go

_Jira ticket:_ CLOUDP-78865
**CREATE**
```
➜  ~/workspace/mongoCLI git:(CLOUDP-78865) ✗ ./bin/mongocli atlas accesslist create 127.0.0.0 --type ipAddress --comment test
Created new IP access list.
```
**LIST**
```
/bin/mongocli atlas accesslist list
CIDR BLOCK          AWS SECURITY GROUP
212.129.77.106/32   N/A
212.129.75.188/32   N/A
172.31.0.0/16       N/A
127.0.0.0/32        N/A
```
**GET**
```
./bin/mongocli atlas accesslist get 127.0.0.0
CIDR BLOCK     SECURITY GROUP
127.0.0.0/32   N/A
```
**DELETE**
```
./bin/mongocli atlas accesslist delete 127.0.0.0
? Are you sure you want to delete: 127.0.0.0 Yes
Project access list entry '127.0.0.0' deleted
```

CLOUDP-78865: [Mongocli - Atlas] Modernize Language: project whitelist to access list

---

.github/workflows/go-test.yml
.github/workflows/golangci-lint.yml
.github/workflows/gotest.yml
.golangci.yml
Makefile

golanci-lint is timing out for some of my tests, we probably have a bigger repo now, updating golangci and improving the github action to avoid the time out

tests: improve linting configuration

---

.githooks/pre-commit
.github/workflows/shellcheck.yml
build/package/curator-push.sh
build/package/generate-msi.sh
build/package/set-up-gon.sh

tests: add shellcheck

---

go.mod
go.sum
internal/cli/atlas/privateendpoints/aws/interfaces/describe.go
internal/cli/atlas/privateendpoints/azure/interfaces/describe.go

CLOUDP-81665: Update privateendpoints to support new status field in atlas

---

cmd/mongocli/mongocli.go
internal/cli/root/builder.go
internal/cli/root/builder_test.go

_Jira ticket:_ CLOUDP-81739
Dynamically loading of commands was not a good idea

CLOUDP-81739: Fix aliases for om and cm

---

internal/convert/process_config.go
internal/convert/process_config_test.go

Missed a couple of places also adding some more tests to capture the missed places

fix: complete set param feature

---

internal/convert/database_user.go
internal/convert/database_user_test.go

CLOUDP-81828: Add support for collections when creating a dbuser

---

.gitignore
build/ci/evergreen.yml
go.sum
internal/docs/main.go

_Jira ticket:_ CLOUDP-82003
This is the initial PoC for generating docs as part of our CI, we still have some coordination to do with docs on how to expand this to match the format they expect

CLOUDP-82003: POC on generating docs as part of our CI

---

e2e/atlas/helper_test.go
internal/cli/atlas/clusters/create.go
internal/flag/flags.go
internal/usage/usage.go

CLOUDP-82118: Add option to enable the bi connector when deploying a cluster

---

.github/CODEOWNERS

CLOUDP-82246: Add a CODEOWNERS file

---

internal/cli/atlas/logs/download.go
internal/cli/atlas/logs/download_test.go

CLOUDP-51068: add mongosqld.gz as valid option for mcli atlas logs download

---

internal/cli/opsmanager/backup/restores_start.go

_Jira ticket:_ CLOUDP-83457
This has probably been broken for a while, the flags were kind of a mess from back when we used to support Atlas as well

CLOUDP-83457: [mongocli] fix required flag for backup restore

---

.github/workflows/go-test.yml
.tool-versions
CONTRIBUTING.md
README.md
build/ci/evergreen.yml
go.mod

CLOUDP-84348: Update mongocli to go 1.16

---

internal/convert/process_config.go
internal/convert/process_config_test.go

CLOUDP-84801: Keep audit log config if only auditLogDestination is set

---

internal/convert/cluster_config.go
internal/convert/cluster_config_test.go
internal/convert/process_config_test.go

_Jira ticket:_ CLOUDP-84841
This seems to be from a time when we were not supporting these values, we would keep the old just in case, that's no longer true

CLOUDP-84841: Allow to update security and setParams

---

internal/cli/atlas/quickstart/prompt.go
internal/cli/atlas/quickstart/quick_start.go

_Jira ticket:_ CLOUDP-85770
**Bug**:
```
mongocli atlas quickstart --clusterName QuckstartCl --provider AWS --region US_EAST_1 --username teerw222 --password changeMe --accessListIp 192.0.2.15 --skipMongosh
We are deploying your cluster...
[Set up your database access details]
[Set up your network access list details]
[Connect to your new cluster]
Creating your cluster... [It's safe to 'Ctrl + C']
```
**Fix:**
```
mongocli atlas quickstart --clusterName QuckstartCl1 --provider AWS --region US_EAST_1 --username teerw2222 --password changeMe --accessListIp 192.0.2.15 --skipMongosh
We are deploying your cluster...
Creating your cluster... [It's safe to 'Ctrl + C']
```

CLOUDP-85770: Fixing bug with quickstart command in non-interactive mode

---

internal/cli/atlas/quickstart/quick_start.go

CLOUDP-85544: Update links to add google analysis parameters

---

.goreleaser.yml
build/package/mac_notarize.sh
build/package/set-up-gon.sh

CLOUDP-84349: Add support for Apple ARM processors

---

build/ci/evergreen.yml
build/package/send-slack-notification.sh

CLOUDP-87410: Add an evergreen task to automatically notify #mongocli of a new release

---

internal/convert/automation_config_test.go
internal/convert/cluster_config_test.go
internal/convert/process_config.go
internal/convert/process_config_test.go
internal/test/fixture/automation_configs.go

CLOUDP-87491: Add support for all of replication options

---

e2e/config/autocomplete_test.go
e2e/config/config_test.go
internal/cli/root/builder.go

_Jira ticket:_ CLOUDP-87493
This is not the first time I break it so adding an e2e test

CLOUDP-87493: Fix an NPE for the autocomplete command

---

internal/release/main.go

```json
{
"previous_releases_link": "https://github.com/mongodb/mongocli/releases",
"release_date": "2021-04-14T13:49:31.803083Z",
"release_notes_link": "https://docs.mongodb.com/mongocli/v1.14.0-22-ga06fb9c/release-notes/",
"tutorial_link": "https://docs.mongodb.com/mongocli/v1.14.0-22-ga06fb9c/quick-start/",
"version": "1.14.0-22-ga06fb9c",
"manual_link": "https://docs.mongodb.com/mongocli/v1.14.0-22-ga06fb9c/",
"platform": [
{
"arch": "x86_64",
"os": "Linux (x86_64)",
"packages": {
"title": "MongoDB CLI",
"links": [
{
"download_link": "https://fastdl.mongodb.org/mongocli/mongocli_1.14.0-22-ga06fb9c_linux_x86_64.tar.gz",
"name": "tar.gz"
}
]
}
},
{
"arch": "x86_64",
"os": "Debian 9 / Ubuntu 16.04 + 18.04 + 20.04",
"packages": {
"title": "MongoDB CLI",
"links": [
{
"download_link": …
```

Updating the json file used to populate the Download Center

---

build/ci/evergreen.yml

Failure: https://evergreen.mongodb.com/task/mongocli_master_release_github_release__v1.15.0_21_04_14_14_18_55

fixed download-msi.sh path

---

.goreleaser.yml
build/ci/evergreen.yml
build/package/download-msi.sh

fix release part 3

---

.goreleaser.yml
build/package/send-slack-notification.sh

fix .goreleaser.yml

---

internal/cli/atlas/clusters/clusters.go
internal/cli/atlas/clusters/clusters_test.go
internal/cli/atlas/clusters/create.go
internal/cli/atlas/clusters/update.go
internal/cli/atlas/quickstart/quick_start.go

CLOUDP-87553: Add infrastructure labels to clusters created via quickstart

---

build/ci/evergreen.yml
internal/release/main.go

Ubuntu 16.04 will reach EOL this month

CLOUDP-87607: [mcli] EOL Ubuntu 16.04

---

.goreleaser.yml
build/ci/evergreen.yml

CLOUDP-87806: fix deb and rpm packages

---

internal/cli/atlas/quickstart/prompt.go
internal/cli/atlas/quickstart/quick_start.go
internal/store/store.go
internal/store/store_test.go
internal/validate/validate.go
internal/validate/validate_test.go

CLOUDP-87818: add validations for quickstart

---

go.mod
go.sum
internal/store/cloud_provider_regions.go

I was expecting dependabot to open this but I think when we point to master it will skip opening a PR. Anyway this needed manual changes so happy it didn't

 build(deps): bump go clients to latest release

---

Makefile

Main change here is exposing `MCLI_VERSION` and `MCLI_GIT_SHA` outside the make so they can be passed, we'll use this to try and move the cli hombrew formula to the core forulae

feat: small make improvements

---

.github/workflows/golangci-lint.yml
Makefile
internal/cli/atlas/quickstart/quick_start.go
internal/convert/rs_config.go

task: bump GOLANGCI_VERSION to 1.40.1

---

.golangci.yml
internal/cli/global_opts_test.go
internal/cli/output_opts.go

feat: enable errorlint

---

RELEASING.md
build/ci/evergreen.yml

CHANGELOG.md  points to the docs changelog, this is to save us from writing things twice we'll redirect people to the docs page if they need to see a changelog

feat: use CHANGELOG.md for release notes

---

internal/mongosh/mongosh_bin.go
internal/mongosh/mongosh_bin_windows.go
internal/mongosh/mongosh_test.go

small improvement to simplify code

feat: conditionally build mongoshBin const

---

internal/cli/config/config.go
internal/cli/config/prompt.go
internal/config/profile.go

Allow users to select their preferred output when doing `mongocli config`

feat: allow users to pick an output format on config

---

.goreleaser.yml

_Jira ticket:_ CLOUDP-88810
It's done on brew side so we can stop doing our own publishing

CLOUDP-88810: Release mongocli on homebrew-core

---

README.md

docs: update home brew instructions

---

go.mod
go.sum

There's a test failing due to some changes to the clients, fixed on the clients and now updating here

task: update go clients

---

e2e/E2E-TESTS.md
e2e/iam/helper_test.go
e2e/iam/org_invitations_test.go
e2e/iam/project_invitations_test.go
go.mod
go.sum
internal/cli/iam/projects/invitations/delete.go
internal/cli/iam/projects/invitations/describe.go
internal/store/project_invitations.go

CLOUDP-93856: Add e2e tests for atlas invitation management

---

build/ci/evergreen.yml
internal/cli/config/config.go
internal/config/const.go
internal/store/access_role.go
internal/store/alert_configuration.go
internal/store/alerts.go
internal/store/custom_dns.go
internal/store/database_roles.go
internal/store/database_users.go
internal/store/events.go
internal/store/integrations.go
internal/store/maintenance.go
internal/store/organizations.go
internal/store/project_ip_access_lists.go
internal/store/projects.go
internal/store/store.go

Add support for Cloud Gov
Evergreen Task: [atlas_gov_generic_e2e](https://evergreen.mongodb.com/task/mongocli_master_e2e_generic_atlas_gov_generic_e2e_patch_fd84d0e3309a5248828f72587fc1026f4ae21612_60e434660305b96bf1bb8361_21_07_06_10_45_59)
_Jira ticket:_ CLOUDP-93399
```
./bin/mongocli config --service=cloudgov
You are configuring a profile for mongocli.
All values are optional and you can use environment variables (MCLI_*) instead.
? Public API Key: ddvzdkiw
? Private API Key: [? for help] ************************************
? Choose a default organization: Test CLI (60e409d39e80a53e4f4163a7)
? Choose a default project: AndreaCLI (60e40e9e9e80a53e4f41686e)
? Default Output Format: json
? Default MongoDB Shell Path: /usr/local/bin/mongosh
Your …
```

CLOUDP-93399: Add support for Cloud Gov

---

internal/store/api_keys.go
internal/store/api_keys_access_list.go
internal/store/cloud_provider_backup.go
internal/store/cloud_provider_regions.go
internal/store/clusters.go
internal/store/containers.go
internal/store/continuous_backup.go
internal/store/data_lake.go
internal/store/default_mongodb_version.go
internal/store/deprected_private_endpoints.go
internal/store/indexes.go
internal/store/ip_info.go
internal/store/ldap_configurations.go
internal/store/logs.go
internal/store/online_archives.go
internal/store/organization_invitations.go
internal/store/peering_connections.go
internal/store/performance_advisor.go
internal/store/private_endpoints.go
internal/store/process_databases.go
internal/store/process_disk_measurements.go
internal/store/process_disks.go
internal/store/process_measurements.go
internal/store/processes.go
internal/store/project_invitations.go
internal/store/search.go
internal/store/teams.go
internal/store/users.go
internal/store/x509_auth_database_users.go

_Jira ticket:_ CLOUDP-94137
Enabling all the mongocli commands for Fedramp as a beta for the v1.18 release.

CLOUDP-94137:  Enable mongocli commands for fedramp

---

internal/cli/opsmanager/agents/list.go

docs: Missing required argument in agents list documentation

---

build/ci/evergreen.yml
build/package/curator-push.sh

CLOUDP-89254: Start publishing on the server 5.0 repos once 5.0 is launched

---

build/ci/evergreen.yml

hopefully fixes the 5.0 repo publishing

fix: fixes the 5.0 repo publishing(?)

---

e2e/E2E-TESTS.md
e2e/cloud_manager/agents_test.go

CLOUDP-94855: Add e2e test for om/cm agent version list

---

e2e/E2E-TESTS.md
e2e/cloud_manager/deploy_replica_set_test.go
e2e/cloud_manager/deploy_sharded_cluster_test.go
go.mod
go.sum
internal/cli/opsmanager/clusters/clusters.go
internal/cli/opsmanager/clusters/clusters_test.go
internal/cli/opsmanager/clusters/reclaim_free_space.go
internal/cli/opsmanager/clusters/reclaim_free_space_test.go
internal/flag/flags.go
internal/usage/usage.go

CLOUDP-93398: Allow to reclaim free space for a cluster

---

internal/cli/atlas/atlas.go
internal/cli/atlas/quickstart/quick_start.go
internal/cli/iam/users/invite.go
internal/config/profile.go

```
➜  ~/workspace/mongoCLI git:(CLOUDP-94313) ✗ ./bin/mongocli atlas quickstart
? Cluster Name [This can't be changed later] Quickstart-1626180399
? Cloud Provider Region US_GOV_EAST_1
We are deploying Quickstart-1626180399...
? Do you want to load sample data into Quickstart-1626180399? Yes
[Set up your database authentication access details]
? Database User Username Quickstart-1626180399
? Database User Password [Press Enter to use an auto-generated password 'SH1pV3NIb3tZ'] SH1pV3NIb3tZ
[Set up your database network access details]
? Access List Entry [Press Enter to use your public IP address …
```

Fix Quickstart for FedRAMP

---

internal/store/cloud_provider_backup.go
internal/store/online_archives.go

CLOUDP-94313: disable online archive for Atlas for gov

---

internal/cli/atlas/datalake/create.go
internal/cli/atlas/datalake/delete.go
internal/cli/atlas/datalake/describe.go
internal/cli/atlas/datalake/update.go

Added annotation doc datalake

---

internal/cli/atlas/customdbroles/create.go
internal/cli/atlas/customdbroles/delete.go
internal/cli/atlas/customdbroles/describe.go
internal/cli/atlas/customdbroles/update.go

Added doc annotation to customdbroles

---

internal/cli/atlas/clusters/connectionstring/describe.go
internal/cli/atlas/clusters/create.go
internal/cli/atlas/clusters/delete.go
internal/cli/atlas/clusters/describe.go
internal/cli/atlas/clusters/indexes/create.go
internal/cli/atlas/clusters/loadSampleData.go
internal/cli/atlas/clusters/onlinearchive/delete.go
internal/cli/atlas/clusters/onlinearchive/describe.go
internal/cli/atlas/clusters/onlinearchive/pause.go
internal/cli/atlas/clusters/onlinearchive/start.go
internal/cli/atlas/clusters/onlinearchive/update.go
internal/cli/atlas/clusters/onlinearchive/watch.go
internal/cli/atlas/clusters/pause.go
internal/cli/atlas/clusters/start.go
internal/cli/atlas/clusters/update.go
internal/cli/atlas/clusters/watch.go

Added doc annotation to atlas cluster

---

internal/cli/atlas/dbusers/certs/list.go
internal/cli/atlas/dbusers/delete.go
internal/cli/atlas/dbusers/describe.go
internal/cli/atlas/dbusers/update.go

Added doc annotation dbusers

---

build/ci/evergreen.yml
e2e/atlas/helper_test.go

_Jira ticket:_ CLOUDP-95632
Evergreen Patch: https://evergreen.mongodb.com/version/60f5328b3e8e863139dfa559

CLOUDP-95632: Add e2e tests for logs and metrics - FedRAMP

---

build/ci/evergreen.yml

_Jira ticket:_ CLOUDP-95663
- [atlas_gov_processes_e2e](https://evergreen.mongodb.com/task/mongocli_master_e2e_atlas_clusters_atlas_gov_processes_e2e_patch_6aedbe10d46ff96b6512f1666eaa9f6e41a1d91b_60f679d856234325f29913eb_21_07_20_07_23_05)
- [atlas_gov_search_e2e](https://evergreen.mongodb.com/task/mongocli_master_e2e_atlas_clusters_atlas_gov_search_e2e_patch_6aedbe10d46ff96b6512f1666eaa9f6e41a1d91b_60f679d856234325f29913eb_21_07_20_07_23_05)
- [atlas_gov_iam_e2e](https://evergreen.mongodb.com/task/mongocli_master_e2e_generic_atlas_gov_iam_e2e_patch_6aedbe10d46ff96b6512f1666eaa9f6e41a1d91b_60f679d856234325f29913eb_21_07_20_07_23_05)

CLOUDP-95663: Add e2e tests FedRamp

---

CONTRIBUTING.md
internal/cli/atlas/customdbroles/create.go

_Jira ticket:_ CLOUDP-93374
[CONTRIBUTING.md](https://github.com/mongodb/mongocli/blob/CLOUDP-93374/CONTRIBUTING.md)

CLOUDP-93374: Define a rule that explains when we should add flags in mongocli

---

internal/docs/main.go

CLOUDP-96262: Document completion commands

---

go.mod
go.sum

Update atlas go client

---

.github/workflows/golangci-lint.yml
Makefile

build (lint): update golangci-lint to 1.42.0

---

e2e/atlas/online_archives_test.go

CLOUDP-98098: fix: atlas_online_archive_e2e

---

e2e/E2E-TESTS.md
e2e/cloud_manager/dbusers_test.go
e2e/cloud_manager/deploy_replica_set_test.go
e2e/cloud_manager/helper_test.go

CLOUDP-98166: Fix cloud manager e2e cluster tests

---

e2e/atlas/clusters_test.go
internal/cli/config/config.go
internal/cli/iam/projects/create.go
internal/cli/iam/users/invite.go
internal/cli/iam/users/invite_test.go
internal/cli/performance_advisor_opts.go
internal/config/profile.go

_Jira ticket:_ CLOUDP-98329
Couple of places we were only checking for cloud service (atlas) making atlas gov fall into the cloud manager/ops manager group

CLOUDP-98329: [mcli] cloudgov fixes

---

e2e/cloud_manager/alerts_test.go
e2e/cloud_manager/helper_test.go

tests: fix e2e tests for cm alerts

---

build/ci/evergreen.yml
e2e/ops_manager/version_manifest_test.go
go.mod
go.sum

Fix `mongocli om versionManifest update` command
_Jira ticket:_ CLOUDP-98804

CLOUDP-98804: Fix update version manifest command

---

.github/ISSUE_TEMPLATE/bug_report.md

Add OM version to the list of required info when submitting a bug

doc: add OM version to the bug report

---

internal/cli/events/orgs_list.go
internal/cli/events/projects_list.go

#807 reminded me I forgot this part when splitting events into two

fix: fix reading org or project id from env/profile for events

---

.github/workflows/go-test.yml
build/ci/evergreen.yml
go.mod

CLOUDP-97861: Update to go 1.17

---

build/ci/evergreen.yml
internal/config/profile.go
internal/store/store.go

CLOUDP-99351: split commercial and gov e2e tests

---

internal/cli/atlas/accesslogs/list.go

This follow up PR addresses this [comment](https://github.com/mongodb/mongocli/pull/825#discussion_r704327678)

Addressed comment in CLOUDP-97430

---

e2e/cli.go

Small quality of life improvement to running e2e locally

test: improve errors for e2e bin

---

docs/command/mongocli-atlas-accessLogs-list.txt
docs/command/mongocli-atlas-accessLogs.txt
docs/command/mongocli-atlas.txt
internal/cli/atlas/accesslogs/access_logs.go
internal/cli/atlas/accesslogs/list.go
internal/usage/usage.go

Addressed Doc comments in #825

Addressed Doc comments in #825

---

.github/workflows/docs.yml

This is about enhancing the error message for the Github Action that checks for our docs.
_Jira ticket:_ CLOUDP-99358

CLOUDP-99358: Improve github action docs error message

---

.github/workflows/docs.yml

Missed this file when updating go

test: update go version for docs workflow

---

build/ci/evergreen.yml
docs/command/mongocli-atlas-quickstart.txt
e2e/atlas/clusters_m0_test.go
e2e/atlas/clusters_test.go
e2e/atlas/helper_test.go
internal/cli/atlas/clusters/create.go
internal/cli/atlas/quickstart/cluster_setup.go
internal/cli/atlas/quickstart/quick_start.go

CLOUDP-92575: Enable M0 instance size for QuickStart command

---

internal/cli/atlas/privateendpoints/aws/watch.go
internal/cli/atlas/privateendpoints/aws/watch_test.go

_Jira ticket:_ CLOUDP-100115
[e2e_atlas_networking](https://evergreen.mongodb.com/build/mongocli_master_e2e_atlas_networking_patch_20cc993b61448889d36e2f631a67fbf9166053b2_613f087e61837d1096eead22_21_09_13_08_14_55)

CLOUDP-100115: Failed Task: mongocli-master-atlas_private_endpoint_e2e/e2e_atlas_networking

---

e2e/iam/atlas_users_test.go
e2e/iam/org_api_key_access_list_test.go
e2e/iam/org_invitations_test.go
e2e/iam/project_invitations_test.go
e2e/iam/project_teams_test.go
e2e/iam/team_users_test.go
e2e/iam/teams_test.go

CLOUDP-100415: Fixed ops manager tests failures

---

e2e/cloud_manager/agent_api_keys_test.go
e2e/cloud_manager/agents_test.go
e2e/cloud_manager/alerts_test.go
e2e/cloud_manager/dbusers_test.go
e2e/cloud_manager/deploy_replica_set_test.go
e2e/cloud_manager/deploy_sharded_cluster_test.go
e2e/cloud_manager/events_test.go
e2e/cloud_manager/feature_policies_test.go
e2e/cloud_manager/helper_test.go
e2e/cloud_manager/maintenance_test.go
e2e/cloud_manager/servers_test.go
e2e/config/autocomplete_test.go
e2e/config/config_test.go

Updated build tags for cloud manager e2e tests

Updated build tags for cloud manager e2e tests

---

go.mod
go.sum

Fixing a bug on doc generation

task: update cobra2snooty to v0.2.3

---

Makefile
build/ci/evergreen.yml
e2e/brew/brew_test.go

Add homebrew like tests to our e2e tests
_Jira ticket:_ CLOUDP-100677

CLOUDP-100677: Add homebrew like tests to our e2e tests

---

Makefile
build/ci/evergreen.yml
e2e/atlas/access_logs_test.go
e2e/atlas/access_roles_test.go
e2e/atlas/atlas_e2e_test_generator_test.go
e2e/atlas/cluster_generator_test.go
e2e/atlas/clusters_file_test.go
e2e/atlas/clusters_flags_test.go
e2e/atlas/clusters_m0_test.go
e2e/atlas/clusters_sharded_test.go
e2e/atlas/clusters_test.go
e2e/atlas/custom_dns_test.go
e2e/atlas/helper_test.go
e2e/atlas/integrations_test.go
e2e/atlas/ldap_test.go
e2e/atlas/logs_test.go
e2e/atlas/maintenance_test.go
e2e/atlas/metrics_test.go
e2e/atlas/online_archives_test.go
e2e/atlas/performance_advisor_test.go
e2e/atlas/private_endpoint_test.go
e2e/atlas/processes_test.go
e2e/atlas/search_test.go
e2e/atlas/serverless_test.go

This change is about generating a new project for each e2e test
_Jira ticket:_ CLOUDP-100678

CLOUDP-100678: Generate project on each atlas e2e test

---

docs/command/mongocli-completion-bash.txt
go.mod
go.sum

docs: update cobra2snooty dependency to fix docs errors

---

build/ci/clean-up-cloud-manager.sh
build/ci/evergreen.yml
build/ci/set-up-cloud-manager.sh

Improve Flakiness of Cloud Manager tests in MongoCLI by creating a new project id for each test run
_Jira ticket:_ CLOUDP-101199

CLOUDP-101199: Improve Flakiness of Cloud Manager tests in MongoCLI

---

.github/workflows/golangci-lint.yml
Makefile
build/ci/evergreen.yml
e2e/atlas/online_archives_test.go
internal/cli/output_opts.go
internal/store/store.go
internal/usage/usage.go

_Jira ticket:_ CLOUDP-105826
Removes the deprecated `ioutil` and `gosec` has some new false positives

CLOUDP-105826: [mongocli] Update golangci-lint to 1.43

---

Makefile

Update the timeout on the fix command to match all other usages of golangci-lint

fix: update fix-lint timeout

---

build/ci/evergreen.yml
build/ci/install-ops-manager-spawn-host.sh

_Jira ticket:_ CLOUDP-108005
This PR fixes the [System Failures](https://evergreen.mongodb.com/task/mongocli_master_e2e_ops_manager_44_ops_manager_4_4_deploy_replica_set_e2e_0c0458c24fe7b05f256ff1114d1c129e1508c02e_21_12_22_09_30_24) we had with the ops manager tests. I will open another PR to fix the replica_set/clusters failures

CLOUDP-108005: Failed Task: mongocli-master-ops_manager_4_4_deploy_replica_set_e2e/e2e_ops_manager_44

---

build/ci/evergreen.yml
build/ci/install-ops-manager-spawn-host.sh
e2e/cloud_manager/deploy_replica_set_test.go
e2e/cloud_manager/helper_test.go

CLOUDP-108006: Failed Task: mongocli-master-ops_manager_4_4_deploy_sharded_cluster_e2e/e2e_ops_manager_44

---

docs/command/mongocli-atlas-clusters-indexes-create.txt
docs/command/mongocli-cloud-manager-clusters-indexes-create.txt
docs/command/mongocli-ops-manager-clusters-indexes-create.txt
internal/cli/opsmanager/clusters/indexes_create.go
internal/usage/usage.go

Improving docs for this command

docs: improve docs for rolling index creation

---

docs/command/mongocli-atlas-backups-snapshots-watch.txt
docs/command/mongocli-atlas-clusters-onlineArchives-watch.txt
docs/command/mongocli-atlas-clusters-watch.txt
docs/command/mongocli-atlas-networking-peering-watch.txt
docs/command/mongocli-atlas-privateEndpoints-aws-watch.txt
docs/command/mongocli-atlas-privateEndpoints-azure-watch.txt
docs/command/mongocli-atlas-privateEndpoints-gcp-watch.txt
docs/command/mongocli-atlas-security-ldap-verify-status-watch.txt
docs/command/mongocli-atlas-serverless-watch.txt
docs/command/mongocli-cloud-manager-automation-watch.txt
docs/command/mongocli-ops-manager-automation-watch.txt
internal/cli/atlas/backup/snapshots/watch.go
internal/cli/atlas/clusters/onlinearchive/watch.go
internal/cli/atlas/clusters/watch.go
internal/cli/atlas/networking/peering/watch.go
internal/cli/atlas/privateendpoints/aws/watch.go
internal/cli/atlas/privateendpoints/azure/watch.go
internal/cli/atlas/privateendpoints/gcp/watch.go
internal/cli/atlas/privateendpoints/watch.go
internal/cli/atlas/security/ldap/watch.go
internal/cli/atlas/serverless/watch.go
internal/cli/opsmanager/automation/watch.go

_Jira ticket:_ [CLOUDP-110093](https://jira.mongodb.org/browse/CLOUDP-110093)

CLOUDP-110093: Update watch command long descriptions

---

.golangci.yml

lint: enable tenv

---

go.mod
go.sum
internal/convert/process_config.go
internal/store/agents.go

CLOUDP-110845: cannot parse error response

---

docs/command/mongocli-atlas-privateEndpoints-gcp-interfaces-describe.txt
docs/command/mongocli-atlas-privateEndpoints-gcp-interfaces.txt
docs/command/mongocli-atlas-privateEndpoints-gcp.txt
internal/cli/atlas/privateendpoints/gcp/gcp.go
internal/cli/atlas/privateendpoints/gcp/interfaces/describe.go
internal/cli/atlas/privateendpoints/gcp/interfaces/describe_test.go
internal/cli/atlas/privateendpoints/gcp/interfaces/interfaces.go
internal/cli/atlas/privateendpoints/gcp/interfaces/interfaces_test.go

_Jira ticket:_ CLOUDP-108870
I "smoke-tested" this by creating a GCP private endpoint in Atlas and running the command:
```
% bin/mongocli atlas privateEndpoints gcp interfaces describe endpoint-1 --endpointServiceId 61eaca605af86411903de1dd
ENDPOINT     STATUS      DELETE REQUESTED
endpoint-1   AVAILABLE   false
```

CLOUDP-108870: Retrieve a specific private endpoint interface

---

docs/command/mongocli-cloud-manager-agents-list.txt
docs/command/mongocli-cloud-manager-servers-list.txt
docs/command/mongocli-ops-manager-agents-list.txt
docs/command/mongocli-ops-manager-servers-list.txt
internal/cli/opsmanager/agents/list.go
internal/cli/opsmanager/agents/list_test.go
internal/cli/opsmanager/servers/list.go
internal/cli/opsmanager/servers/list_test.go
internal/mocks/mock_agents.go
internal/store/agents.go

CLOUDP-110416: add pagination options to agent and server listing

---

e2e/atlas/access_lists_test.go

_Jira ticket:_ [CLOUDP-11518](https://jira.mongodb.org/browse/CLOUDP-111518)
Note: Gov test failing

CLOUDP-11518:Update e2e test to use isolated project

---

e2e/atlas/clusters_m0_test.go
e2e/atlas/helper_test.go

[atlas_clusters_m0_e2e](https://evergreen.mongodb.com/task/mongocli_master_e2e_atlas_clusters_atlas_clusters_m0_e2e_4b4ad609c9a229f1890d0fdced14842bce75744c_22_02_03_15_36_01) is failing on evergreen. This PR fixes the issue.

Fix M0 e2e tests failure

---

internal/cli/auth/login.go
internal/cli/auth/login_test.go
internal/cli/refresher_opts.go
internal/config/profile.go
internal/validate/validate.go

_Jira ticket:_ CLOUDP-112741
Properly handle an invalid refresh token error to be friendly to users, couple of drive by fixes along

CLOUDP-112741: Improve refresh token error when token is expired

---

go.mod
go.sum

_Jira ticket:_ CLOUDP-112815
This ticket updates the om go client to the latest release to get the fix in https://github.com/mongodb/go-client-mongodb-ops-manager/pull/138

CLOUDP-112815: Updating om-go client to latest release

---

internal/cli/auth/login.go
internal/config/profile.go

CLOUDP-113314: Persist custom client config

---

.atlascli.goreleaser.yml
.githooks/pre-commit
.mongocli.goreleaser.yml
build/ci/release.yml

_Jira ticket:_ CLOUDP-113305
This PR aims to enable releasing both mongocli and atlascli with the monorepo goreleaser feature.
I have tested my changes on a fork:
- [MongoCLI](https://github.com/andreaangiolillo/mongocli/releases/tag/untagged-b8f22b085df885c7f390)
- [AtlasCLI](https://github.com/andreaangiolillo/mongocli/releases/tag/untagged-5295c214c87f538f5c75)
**Next Steps:**
- Updating the mongocli evergreen project to run the correct release tasks based on the tag
- Updating PCT to create the tag with the new format
- Updating the README.MD file to include atlascli
- Updating the repository's name

CLOUDP-113305: Update release process to use monorepo

---

build/ci/release.yml

_Jira ticket:_ CLOUDP-113787
The download center evergreen task is not creating the archive.json
The goal of this PR is to fix this evergreen task to generate the download center json for both atlascli and mongocli.
- [mongodb-atlas-cli.json](https://mongodb-mongocli-build.s3.amazonaws.com/mongocli-master/dist/0662dd61f2ab66f66f359fe9e0f2d0bc2112f266_22_02_25_09_29_28/mongodb-atlas-cli.json)
- [mongocli.json](https://mongodb-mongocli-build.s3.amazonaws.com/mongocli-master/dist/0662dd61f2ab66f66f359fe9e0f2d0bc2112f266_22_02_25_09_29_28/mongocli.json)

CLOUDP-113787: [Mongocli] Download center evergreen task is not creating the archive.json

---

build/ci/evergreen.yml
build/ci/release.yml
build/package/rename-pkg.sh

_Jira ticket:_ CLOUDP-113788
Right now the release process depends on the evergreen task "compile" which builds both mongocli and atlascli.
The goal of this PR is to build only the binary used by the release process.

CLOUDP-113788: [Mongocli] Improve the release process by building only the correct binary

---

build/ci/release.yml
build/package/curator-push.sh

_Jira ticket:_ CLOUDP-113791
[MongoCLI] Now that we are releasing both atlascli and mongocli we have to rename the archive.targz_pack from rpm.tgz to atlascli-rmp.tgx and mongocli-rpm.tgx

CLOUDP-113791: [MongoCLI] Now that we are releasing both atlascli and mongocli we have to rename the archive.targz_pack

---

build/ci/release.yml

Mongocli Release tasks is failing with the [error](https://evergreen.mongodb.com/task/mongocli_master_release_mongocli_github_release_mongocli__mongocli_v1.23.0_22_02_28_16_03_15):
`build/package/download-msi.sh: line 21: TOOL_NAME: parameter null or not set`

Fix Release: Added tool_name to download-msi.sh

---

build/ci/release.yml
build/package/send-slack-notification.sh

Issue: We are not passing the `TOOL_NAME` to `send-slack-notification.sh`

Release Fix: Fixed send slack notification step

---

e2e/atlas/dbusers_test.go

_Jira ticket:_ CLOUDP-114040
Gov is changing the minimum password requirement

CLOUDP-114040: Failed Task: mongocli-master-atlas_gov_generic_e2e/e2e_generic

---

internal/version/release_version.go

_Jira ticket:_ CLOUDP-113292
I have tested that the feature still works 
```
./bin/mongocli config ls
A new version of mongocli is available 'v1.23.0'!
To upgrade, see: https://dochub.mongodb.org/core/mongocli-install.
To disable this alert, run "mongocli config set skip_update_check true".
```

CLOUDP-113292: Update repo references in new release alert feature

---

build/ci/evergreen.yml
build/ci/set-up-cloud-manager.sh
build/ci/set-up-ops-manager.sh
cmd/atlas/atlas.go
cmd/mongocli/mongocli.go
e2e/brew/brew_test.go
internal/config/profile.go
internal/config/profile_test.go

_Jira ticket:_ [CLOUDP-114366](https://jira.mongodb.org/browse/CLOUDP-114366)
* While loading the config, if the file doesn't exist, check the old path` ~/.config `and load the file copying to the new path `~/.config/mongocli/config.toml`. 
* ~Note: Still trying to figure out linux test failure - but sending for early review~
* ~Note: some evergreen files need to be updated to address this, but I want to run an e2e test without the change to see this solution working.~

CLOUDP-114248: Store all config files with mongocli folder

---

e2e/atlas/atlas_e2e_test_generator_test.go

This came as I was fixing some of the flaky tests the other day, main change is to fail the whole test when the generation for project fails as we were still trying to run tests even when project creation failed

test: improve test generator

---

docs/mongocli/command/mongocli-cloud-manager-logs-decrypt.txt
docs/mongocli/command/mongocli-cloud-manager-logs.txt
docs/mongocli/command/mongocli-ops-manager-logs-decrypt.txt
docs/mongocli/command/mongocli-ops-manager-logs.txt
internal/cli/opsmanager/logs/decrypt.go
internal/cli/opsmanager/logs/decrypt_test.go
internal/cli/opsmanager/logs/logs_test.go
internal/flag/flags.go
internal/usage/usage.go

_Jira ticket:_[ CLOUDP-114869](https://jira.mongodb.org/browse/CLOUDP-114869)

CLOUDP-114869: Add decrypt command to OM and CM

---

docs/mongocli/command/mongocli-cloud-manager-logs-decrypt.txt
docs/mongocli/command/mongocli-ops-manager-logs-decrypt.txt
internal/cli/opsmanager/logs/decrypt.go
internal/decryption/encrypted_audit_log.go
internal/decryption/header.go
internal/decryption/header_test.go
internal/decryption/log_record.go

Adds validation for the audit log header
_Jira ticket:_ CLOUDP-114717

CLOUDP-114717: Validate Header

---

atlascli.md

_Jira ticket:_ CLOUDP-114684
Updating `atlascli.md` to remove the pre release message

CLOUDP-114684: Update README to include atlascli v1.0.0

---

build/ci/ego

_Jira ticket:_ [CLOUDP-115093](https://jira.mongodb.org/browse/CLOUDP-115093)
* [Patch](https://spruce.mongodb.com/version/62308364d6d80a6348e4b963/tasks)
-  [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)

CLOUDP-115093: Fix setup failure on ubuntu machines

---

internal/cli/root/atlas/builder_test.go
internal/cli/root/mongocli/builder_test.go
internal/latestrelease/finder.go
internal/latestrelease/finder_test.go

_Jira ticket:_ [CLOUDP-115725](https://jira.mongodb.org/browse/CLOUDP-115725)
```
➜  mongocli git:(CLOUDP-115725) mongoclidev config list
PROFILE NAME
default
test
➜  mongocli git:(CLOUDP-115725) make build-atlascli
==> Building atlas binary
go build -ldflags "-s -w -X github.com/mongodb/mongocli/internal/version.GitCommit=59dc12eb62551fb964cb7e7e2676ada5fd2e31c2 -X github.com/mongodb/mongocli/internal/config.ToolName=atlascli -X github.com/mongodb/mongocli/internal/version.Version=1.0.0-next" -o ./bin/atlas ./cmd/atlas
➜  mongocli git:(CLOUDP-115725) ./bin/atlas config list
PROFILE NAME
default
test
```

CLOUDP-115725: AtlasCLI v1.0.0 show the new release alert message

---

internal/cli/root/atlas/builder.go
internal/cli/root/mongocli/builder.go

_Jira ticket:_ CLOUDP-115791
This PR disables the release alert feature when running the `completion` command.

CLOUDP-115791: [CLI] Disable alert feature for completion command

---

docs/mongocli/command/mongocli-cloud-manager-logs-decrypt.txt
docs/mongocli/command/mongocli-ops-manager-logs-decrypt.txt
internal/cli/opsmanager/logs/decrypt.go
internal/cli/opsmanager/logs/decrypt_test.go
internal/decryption/audit_log_line_scanner.go
internal/decryption/audit_log_line_scanner_test.go
internal/decryption/decryption.go
internal/decryption/encrypted_audit_log.go
internal/decryption/header_test.go

Supports BSON file to be decrypted
_Jira ticket:_ CLOUDP-112049

CLOUDP-112049: Support BSON files

---

internal/decryption/decryption.go
internal/decryption/decryption_test.go

Zero LEKs to avoid leaking into memory pages
_Jira ticket:_ CLOUDP-114732

CLOUDP-114732: Zero out LEKs

---

.github/workflows/golangci-lint.yml
Makefile
internal/cli/atlas/livemigrations/options/live_migrations_opts.go
internal/latestrelease/finder_test.go

Updating to latest linter version and fixing some issues caught in the new version

task: update golangci-lint version to 1.44.2

---

e2e/atlas/alerts_test.go

This PR fixes most of the failing alert tests. CM test is still failing though. I will open a follow-up PR to fix it.

Fix alert e2e tests

---

.github/workflows/golangci-lint.yml
Makefile
internal/cli/atlas/livemigrations/options/live_migrations_opts.go
scripts/fix-lint.sh
scripts/lint.sh

This PR updates golanci-lint to [v1.45](https://github.com/golangci/golangci-lint/releases/tag/v1.45.0) and change our lint to consider only changed files instead of all the source code.
**This is how much time `make lint` and `make fix-lint` take without these changes:**
```
time make lint
==> Linting all packages...
golangci-lint run --timeout 5m
internal/cli/atlas/backup/list.go:31: File is not `gofmt`-ed with `-s` (gofmt)
cli.OutputOpts
make: *** [lint] Error 1
make lint  15.95s user 8.70s system 460% cpu 5.357 total
time make fix-lint
==> Fixing lint errors
golangci-lint run --fix --timeout 5m
make fix-lint  17.91s user 9.96s system 449% cpu 6.194 total
```
**This is how much time `make lint`and and `make fix-lint` take with these changes:**
```
time make lint
==> Linting changed go …
```

Update lint to run only on changed file

---

e2e/E2E-TESTS.md
e2e/config/autocomplete_test.go
internal/cli/root/atlas/builder.go

_Jira ticket:_ CLOUDP-115796
**Issue**: Users should be able to run the completion commands without setting credentials.
Failing tests are not related and will be fixed in #1056

CLOUDP-115796: [AtlasCLI] atlas completion is checking for credentials

---

internal/cli/atlas/quickstart/quick_start.go

_Jira ticket:_ [CLOUDP-116166](https://jira.mongodb.org/browse/CLOUDP-116166)
After login, if no API keys exist, the quickstart command fails. We should accept the command if the customer has tokens set. 
Before
```
➜  mongocli git:(CLOUDP-116166) ✗ mongoclidev atlas quickstart
No API credentials set.
? Do you want to create an Atlas account [This will open www.mongodb.com on your browser]? (Y/n)
```
After
```
➜  mongocli git:(registry-PoC) ✗ mongoclidev atlas quickstart
? Cluster Name [This can't be changed later] Quickstart-1647874194
? Cloud Provider Region US_EAST_1
? Do you want to load sample …
```

CLOUDP-116166: Update quickstart auth validation

---

internal/validate/validate.go

_Jira ticket:_ CLOUDP-114862
This PR updates the missing credential error message to include `auth login`
**Before**: 
```
./bin/mongocli atlas cluster ls
Error: missing credentials
To set credentials, run: mongocli config
```
**After**:
```
./bin/atlas cluster ls
Error: this actions requires authentication
To login using your Atlas username and password, run: atlas auth login
To set credentials using API keys, run: atlas config init
```
```
./bin/mongocli atlas cluster ls
Error: this actions requires authentication
To login using your Atlas username and password, run: mongocli auth login
To set credentials using API keys, run: mongocli config
```

CLOUDP-114862: [Atlas CLI / MongoCLI] Improve error handling when user is unathenticated

---

internal/decryption/audit_log_line_scanner_test.go

Handle corrupted BSON
_Jira ticket:_ CLOUDP-114731
This was the best guess I could do by studying https://bsonspec.org/spec.html and using https://cryptii.com/pipes/base64-to-hex

CLOUDP-114731: Handle corrupted BSON

---

internal/cli/root/mongocli/builder.go
internal/cli/root/mongocli/builder_test.go

feat: remove fig integration for mongocli

---

internal/cli/atlas/atlas_darwin.go
internal/cli/atlas/atlas_linux.go
internal/cli/atlas/atlas_windows.go

CLOUDP-117061: [MongoCLI] Update deprecate message with latest from doc team

---

build/ci/evergreen.yml

_Jira ticket:_ CLOUDP-117339
It's been bothering me for a while we had no proper tests results on evergreen, fixing now

CLOUDP-117339: Fix attach.xunit_results

---

internal/cli/atlas/config/config.go
internal/cli/atlas/config/config_test.go

This PR adds the config edit command #1095 to atlascli

Add config edit command to atlascli

---

internal/cli/atlas/atlas_darwin.go

_Jira ticket:_ CLOUDP-117067
Now that the atlas cli brew formula has been merged, we should update the deprecate message for mac to include how to install atlas cli with homebrew

CLOUDP-117067: [MongoCLI] We should update the deprecate message to include brew once the atlascli formula is available

---

internal/store/store.go

_Jira ticket:_ CLOUDP-118221
This PR updates `WithAuthentication` to not parse the access token when programmatic keys are available

CLOUDP-118221: [CLI] We should not parse the access token when programmatic keys are available

---

build/ci/clean-up-cloud-manager.sh
build/ci/evergreen.yml
build/ci/set-up-cloud-manager.sh

Sometimes when tests fail we leave empty cloud manager projects created on our test account, this PR aims to delete these projects on a post-task so we always clean them up.

test: clean up Cloud Manager projects on a post-task

---

Makefile
build/package/docker/docker-build.sh
build/package/download-msi.sh
build/package/generate-download-archive-manifest.sh
build/package/generate-msi.sh
build/package/package.sh
build/package/rename-pkg.sh
build/package/send-slack-notification.sh

**Issue:**
We are adding `-next` to the binary version when the tag is pointing to the current commit. 
**Fix:**
We should add `-next` only when the latest tag is not pointing to the current commit as we were doing before with `git describe`
**Scenarios:**
- When the latest tag is pointing to the current commit:
```
make build-all
==> Building mongocli binary
go build -ldflags "-s -w -X github.com/mongodb/mongocli/internal/version.GitCommit=9f32d3021c9fa30567dd85d32a8dcf6416ed9c59 -X github.com/mongodb/mongocli/internal/config.ToolName=mongocli -X github.com/mongodb/mongocli/internal/version.Version="1.24.1"" -o ./bin/mongocli ./cmd/mongocli
==> Building atlas binary
go build -ldflags "-s -w -X github.com/mongodb/mongocli/internal/version.GitCommit=9f32d3021c9fa30567dd85d32a8dcf6416ed9c59 …
```

Bug: We are adding -next to the binary version when tag is pointing to the commit

---

internal/cli/atlas/quickstart/mongoshell_setup.go
internal/cli/atlas/quickstart/prompt.go
internal/cli/atlas/quickstart/quick_start.go

_Jira ticket:_ [CLOUDP-117303](https://jira.mongodb.org/browse/CLOUDP-117303)
Note: adding only the changes in [this page](https://www.figma.com/proto/RYOrTIaf2ksQsVT0Sp6RYA/Atlas-CLI-onboarding?node-id=1186%3A6201&scaling=min-zoom&page-id=1081%3A4560&starting-point-node-id=1082%3A5576) and related w/ the shell piece, more wording changes coming in another PR.
```shell
➜  mongocli git:(master) ✗ atlasdev quickstart
? Cluster Name [This can't be changed later] Quickstart-1649433079
? Cloud Provider Region US_EAST_1
? Do you want to load sample data into Quickstart-1649433079? No
[Set up your database …
```

CLOUDP-117303: Move mongo shell question to the end of quickstart

---

docs/mongocli/command/mongocli-cloud-manager-logs-decrypt.txt
docs/mongocli/command/mongocli-ops-manager-logs-decrypt.txt
internal/cli/opsmanager/logs/decrypt.go
internal/cli/opsmanager/logs/decrypt_test.go
internal/decryption/decryption.go
internal/decryption/encrypted_audit_log.go
internal/decryption/key_provider_opts.go
internal/decryption/keyproviders/kmip.go
internal/flag/flags.go
internal/usage/usage.go

CLOUDP-119243 add support for KMIP username and password

---

RELEASING.md

Update the RELEASING doc to highlight our internal tooling is now in place

docs: update RELEASING.md

---

internal/cli/root/atlas/builder.go

CLOUDP-120225: [AtlasCLI] we should not show credential error when running "atlas login"

---

internal/cli/atlas/quickstart/quick_start.go

_Jira ticket:_ [CLOUDP-118999](https://jira.mongodb.org/browse/CLOUDP-118999)
Details on the ticket.

CLOUDP-118999: Change automatically generated cluster name

---

internal/cli/atlas/quickstart/quick_start.go
internal/cli/default_setter_opts.go
internal/cli/default_setter_opts_test.go

_Jira ticket:_ [CLOUDP-118467](https://jira.mongodb.org/browse/CLOUDP-118467)
```shell
➜  mongocli git:(CLOUDP-118467) atlasdev config init
You are configuring a profile for atlas.
All values are optional and you can use environment variables (MONGODB_ATLAS_*) instead.
? Public API Key:
? Private API Key: [? for help]
? Default Project ID: 61dc598fd1f07c7b37ba425d
? Default Org ID: 5e429e7706822c6eac4d5970
? Default Output Format:
Your profile is now configured.
You can use [atlas config set] to change these settings at a later time.
```
```shell
➜  mongocli git:(master) ✗ atlasdev login
First, copy your one-time code: FBQJ-WTQM
Next, sign in with your browser and enter the code.
Or go to https://account-dev.mongodb.com/account/connect
Your code will …
```

CLOUDP-118467: Remove mongosh questions

---

docs/atlascli/command/atlas-config-set.txt
docs/mongocli/command/mongocli-config-set.txt
go.mod
go.sum
internal/cli/atlas/config/init.go
internal/cli/auth/login.go
internal/cli/config/config.go
internal/cli/default_setter_opts.go
internal/config/profile.go

CLOUDP-120437: Allow User to Enable/Disable Telemetry

---

examples/atlas/log-download.md
internal/cli/atlas/logs/decrypt.go
internal/cli/atlas/logs/download.go
internal/cli/downloader_opts.go
internal/cli/opsmanager/logs/decrypt.go
internal/cli/opsmanager/serverusage/download.go

This is about changing the way we handle stdout to be as cross-platform as possible, this means where we expected output files we now accept `-` as stdout or `/dev/stdout` for posix.
_Jira ticket:_ CLOUDP-116169

CLOUDP-116169: review use /dev/stdout

---

internal/cli/default_setter_opts.go

CLOUDP-120435: [Atlas CLI] Telemetry - Set Enabled by Default

---

internal/cli/default_setter_opts.go
internal/config/profile.go

CLOUDP-120870: [Atlas CLI] Telemetry - Not to be implemented in mongocli

---

cmd/atlas/atlas.go
internal/telemetry/telemetry.go
internal/telemetry/telemetry_test.go

Track duration and result in CLI
_Jira ticket:_ CLOUDP-120449

CLOUDP-120449: Telemetry - Track Command Duration and Result

---

internal/cli/atlas/quickstart/cluster_setup.go
internal/cli/atlas/quickstart/confirm_cluster_setup.go
internal/cli/atlas/quickstart/confirm_default_setup.go
internal/cli/atlas/quickstart/quick_start.go
internal/cli/atlas/setup/setup_cmd.go
internal/cli/auth/login.go
internal/cli/auth/login_test.go
internal/cli/auth/register.go
internal/cli/auth/register_test.go

_Jira ticket:_ [CLOUDP-121254](https://jira.mongodb.org/browse/CLOUDP-121254)
Prepping the setup command to add register & quickstart functionalities. The purpose here is to keep the dependency of setup and register/quickstart commands but also having clear separation between each.

CLOUDP-121254: Update setup config

---

internal/cli/auth/login.go
internal/cli/auth/register.go
internal/cli/auth/register_test.go

CLOUDP-118714 register flow - regenerate auth code when expired

---

internal/telemetry/telemetry.go

Telemetry - Track Command Alias
_Jira ticket:_ CLOUDP-120450

CLOUDP-120450: Telemetry - Track Command Alias

---

internal/telemetry/telemetry.go

Telemetry - Track CLI Version
_Jira ticket:_ CLOUDP-120456

CLOUDP-120456: Telemetry - Track CLI Version

---

internal/telemetry/telemetry.go

Telemetry - Track Operating System
_Jira ticket:_ CLOUDP-120457

CLOUDP-120457: Telemetry - Track Operating System

---

e2e/atlas/alerts_test.go
e2e/cloud_manager/alerts_test.go

_Jira ticket:_ CLOUDP-121631
This PR is a follow up of #1168 to update the Cloud Manager e2e test

CLOUDP-121631: Changing order to get any closed alert to reduce flakiness

---

internal/telemetry/telemetry.go

Telemetry - Generate and Track Profile ID
_Jira ticket:_ CLOUDP-120452

CLOUDP-120452: Telemetry - Generate and Track Profile ID

---

internal/config/profile.go
internal/telemetry/telemetry.go
internal/telemetry/telemetry_test.go

Telemetry - Track Authentication Method
_Jira ticket:_ CLOUDP-120454
Added refactoring on how we generate events

CLOUDP-120454: Telemetry - Track Authentication Method

---

internal/telemetry/telemetry.go

Telemetry - Track Service
_Jira ticket:_ CLOUDP-120455

CLOUDP-120455: Telemetry - Track Service

---

internal/telemetry/telemetry.go

Telemetry - Track Terminal
_Jira ticket:_ CLOUDP-120459

CLOUDP-120459: Telemetry - Track Terminal

---

internal/cli/auth/register.go
internal/cli/config/config.go
internal/cli/default_setter_opts.go

CLOUDP-121983 Setup profile after register step is completed

---

internal/cli/root/atlas/builder.go
internal/cli/token.go
internal/validate/validate.go

_Jira ticket:_ [CLOUDP-119541
](https://jira.mongodb.org/browse/CLOUDP-119541)
We'll neded to check and validate tokens in setup to evaluate if the command should throw an error or not and we cannot re-use the builder logic. Moving the logic to `token.go`.

CLOUDP-119540: Move token refresh and validation logic

---

go.mod
go.sum
internal/cli/auth/login.go
internal/cli/auth/register.go
internal/cli/auth/register_test.go

CLOUDP-118714 address PR comments

---

cmd/atlas/atlas.go
internal/cli/root/atlas/builder.go
internal/telemetry/event.go
internal/telemetry/event_test.go
internal/telemetry/telemetry.go
internal/telemetry/tracker.go
internal/telemetry/tracker_test.go

Telemetry - Track Events for Help
_Jira ticket:_ CLOUDP-120448

CLOUDP-120448: Telemetry - Track Events for Help

---

cmd/atlas/atlas.go

Telemetry - Track Events for Help, fix invalid flags not being tracked
_Jira ticket:_ CLOUDP-120448

CLOUDP-120448 Telemetry - Track Events for Help (fix)

---

internal/config/profile.go
internal/config/profile_test.go

Telemetry - Support DO_NOT_TRACK Environment Variable
_Jira ticket:_ CLOUDP-121846

CLOUDP-121846: Telemetry - Support DO_NOT_TRACK Environment Variable

---

docs/atlascli/command/atlas-auth-login.txt
docs/mongocli/command/mongocli-auth-login.txt
internal/cli/atlas/setup/setup_cmd.go
internal/cli/auth/login.go
internal/cli/auth/login_test.go
internal/cli/auth/register.go
internal/cli/auth/register_test.go
internal/cli/default_setter_opts.go

CLOUDP-116868: auth login - don't ask for org/proj if already configured

---

docs/atlascli/command/atlas-auth-register.txt
docs/atlascli/command/atlas-auth.txt
docs/atlascli/command/atlas-quickstart.txt
docs/atlascli/command/atlas-setup.txt
docs/atlascli/command/atlas.txt
docs/mongocli/command/mongocli-atlas-quickstart.txt
internal/cli/atlas/setup/setup_cmd.go
internal/cli/auth/register.go
internal/usage/usage.go

_Jira ticket:_ [CLOUDP-122021](https://jira.mongodb.org/browse/CLOUDP-122021)

CLOUDP-122021: Expose register and setup commands

---

internal/cli/auth/login.go
internal/cli/auth/login_test.go

CLOUDP-116868: update skipConfig deprecation message

---

internal/cli/atlas/setup/setup_cmd.go
internal/cli/atlas/setup/setup_cmd_test.go
internal/cli/auth/login.go
internal/cli/auth/login_test.go
internal/cli/auth/register.go
internal/cli/auth/register_test.go

CLOUDP-121809: ask to regenerate device code on login flow

---

internal/cli/atlas/setup/setup_cmd.go
internal/cli/auth/login.go
internal/cli/auth/login_test.go
internal/cli/auth/register.go
internal/cli/auth/register_test.go

_Jira ticket:_ [CLOUDP-121183](https://jira.mongodb.org/browse/CLOUDP-121183)

CLOUDP-121183: Ask before opening the browser

---

internal/cli/atlas/setup/setup_cmd.go
internal/cli/auth/login.go
internal/cli/auth/register.go
internal/cli/auth/register_test.go

Udpdate design and remove browser quesiton

---

internal/cli/auth/login.go
internal/cli/auth/register.go
internal/cli/auth/register_test.go

atlas register: fix init store

---

docs/atlascli/command/atlas-accessLists-create.txt
docs/atlascli/command/atlas-dbusers-create.txt
docs/mongocli/command/mongocli-atlas-accessLists-create.txt
internal/cli/atlas/accesslists/access_lists.go
internal/cli/atlas/accesslists/create.go
internal/cli/atlas/dbusers/create.go
internal/cli/atlas/dbusers/dbusers.go

While I was practicing my presentation I have noticed that some atlascli commands still have mongocli in their descriptions

Fixed description commands

---

internal/store/store.go

fix: use error wrapping for store

---

internal/file/file.go

More creation of sentinel errors on the road to linting them

fix: Improve error handling for the file package

---

internal/cli/auth/logout.go
internal/cli/auth/whoami.go

fix: create a sentinel error for unauthenticated

---

internal/jsonpathwriter/jsonpathwriter.go

fix: Improve error handling for the jsonpathwriter package

---

e2e/atlas/atlas_e2e_test_generator_test.go
e2e/atlas/helper_test.go
e2e/cloud_manager/decryption_kmip_test.go
e2e/cloud_manager/helper_test.go
e2e/iam/helper_test.go

Improving error handling within the e2e package

fix: sentinel errors for e2e package

---

internal/decryption/aes/cbc.go
internal/decryption/aes/gcm.go
internal/decryption/decompress.go
internal/decryption/keyproviders/aws.go

Fixing sentinel errors for the decryption package

fix: sentinel errors for decryption package

---

build/ci/evergreen.yml

Create a e2e_required test variant for mongodb-atlas-cli and move brew tests there
_Jira ticket:_ CLOUDP-122823

CLOUDP-122823: Create a e2e_required test variant

---

internal/cli/atlas/config/init.go
internal/cli/auth/login.go
internal/cli/config/config.go
internal/cli/default_setter_opts.go
internal/config/profile.go
internal/telemetry/tracker.go
internal/telemetry/tracker_test.go

Telemetry - Errors are not tracked in absence of config file
_Jira ticket:_ CLOUDP-122243

CLOUDP-122243: Telemetry - Errors are not tracked in absence of config file

---

internal/cli/atlas/clusters/create.go

CLOUDP-122378 mongodb version can be set only for non-shared clusters

---

cmd/atlas/atlas.go
internal/cli/atlas/quickstart/dbuser_setup.go
internal/telemetry/event.go
internal/telemetry/event_test.go

Telemetry should sanitize text from user input
_Jira ticket:_ CLOUDP-123143
Also, I'm changing the message raised in the original ticket
Before enter
After enter
Before enter
After enter

CLOUDP-123143: Telemetry should sanitize text from user input

---

internal/cli/atlas/quickstart/quick_start.go

We were failing silently if any other error than "free cluster already exists" happens.

Still return error if it is a different one

---

e2e/atlas/alert_settings_test.go

_Jira ticket:_ [CLOUDP-123489](https://jira.mongodb.org/browse/CLOUDP-123489)
New value APPLICATION_ID added to the settings types in Cloud-dev*(updated) broke the test.

CLOUDP-123489: Fix generic test failure

---

internal/config/profile.go

CLOUDP-121000: [Atlas CLI] Telemetry - Remove Feature Flag

---

build/ci/evergreen.yml
e2e/E2E-TESTS.md
e2e/atlas/dbusers_test.go
e2e/atlas/helper_test.go
e2e/atlas/quickstart_test.go
e2e/atlas/setup_force_test.go
internal/cli/atlas/setup/setup_cmd.go

_Jira ticket:_ [CLOUDP-122972](https://jira.mongodb.org/browse/CLOUDP-122972)
* [patch](https://spruce.mongodb.com/task/mongocli_master_e2e_iteractive_atlas_interactive_e2e_patch_53a4581e94008058ac6e47aa271c3289059796b5_628b639e0ae606217b8710b9_22_05_23_10_42_20/tests?execution=0&sortBy=STATUS&sortDir=ASC)

CLOUDP-122972: Add setup force test

---

internal/cli/root/mongocli/builder.go
internal/cli/root/mongocli/builder_test.go

MongoCLI contains a wrong upgrade link
_Jira ticket:_ CLOUDP-123981

CLOUDP-123981: MongoCLI contains a wrong upgrade link

---

internal/cli/auth/register.go

_Jira ticket:_ CLOUDP-123983
Closes #123983

CLOUDP-123983 fix registration when token expires

---

internal/cli/atlas/quickstart/confirm_cluster_setup.go
internal/cli/atlas/quickstart/confirm_default_setup.go
internal/cli/atlas/setup/setup_cmd.go
internal/cli/atlas/setup/setup_cmd_test.go
internal/cli/auth/login.go
internal/cli/auth/login_test.go
internal/cli/auth/register.go
internal/cli/auth/register_test.go

[CLOUDP-123993](https://jira.mongodb.org/browse/CLOUDP-123993)
* Update message formatting to have punctuation.
* Add "Load sample data" to the default settings statement
* Update only happy flows in this PR
* Keeping one space after the design code for readability
* Changed the open browser statement at the end as agreed afterwards
* Not displaying password in the Default settings

CLOUDP-123993: Design updates

---

internal/cli/atlas/quickstart/cluster_setup.go
internal/cli/atlas/quickstart/confirm_default_setup.go
internal/cli/atlas/quickstart/prompt.go
internal/cli/atlas/quickstart/quick_start.go

CLOUDP-119182 fix quickstart disk size info

---

internal/cli/atlas/quickstart/cluster_setup.go

Improve error message for quickstart when no regions are found for a cloud provider
_Jira ticket:_ CLOUDP-123686
Before
```
Error: please provide options to select from
```
After
```
Error: no regions found for cloud provider: GCP
```

CLOUDP-123686: Improve error message for quickstart when no regions are found for a cloud provider

---

cmd/atlas/atlas.go
internal/cli/atlas/quickstart/quick_start.go
internal/cli/atlas/quickstart/quick_start_test.go
internal/cli/atlas/setup/setup_cmd.go
internal/cli/atlas/setup/setup_cmd_test.go
internal/cli/root/atlas/builder.go
internal/cli/root/atlas/builder_test.go
internal/docs/atlascli/main.go
internal/mocks/mock_quick_start.go
internal/sighandle/sighandle.go
internal/telemetry/command.go
internal/telemetry/event.go
internal/telemetry/event_test.go
internal/telemetry/tracker.go

[Atlas CLI] Telemetry - Track User Interrupts
_Jira ticket:_ CLOUDP-122239
based on https://github.com/mongodb/mongodb-atlas-cli/pull/1254

CLOUDP-122239: [Atlas CLI] Telemetry - Track User Interrupts

---

internal/cli/auth/login.go
internal/cli/auth/login_test.go
internal/cli/auth/register_test.go
internal/cli/default_setter_opts.go
internal/mocks/mock_default_opts.go

CLOUDP-122551 Clean up skipConfig usage and improve post login checks

---

internal/cli/atlas/quickstart/quick_start.go
internal/cli/atlas/setup/setup_cmd.go
internal/cli/atlas/setup/setup_cmd_test.go

_Jira ticket:_ [CLOUDP-124556](https://jira.mongodb.org/browse/CLOUDP-124556)

CLOUDP-124556: Improve error message

---

internal/telemetry/tracker.go

Telemetry - Track Prompt Confirm Choice
_Jira ticket:_ CLOUDP-124591

CLOUDP-124591: Telemetry - Track Prompt Confirm Choice

---

cmd/atlas/atlas.go
internal/cli/atlas/quickstart/quick_start.go
internal/cli/atlas/quickstart/quick_start_test.go
internal/cli/atlas/setup/setup_cmd.go
internal/cli/atlas/setup/setup_cmd_test.go
internal/cli/root/atlas/builder.go
internal/mocks/mock_quick_start.go
internal/telemetry/ask.go
internal/telemetry/command.go
internal/telemetry/event.go
internal/telemetry/event_test.go
internal/telemetry/tracker.go
internal/telemetry/tracker_test.go

Telemetry - Enhance prompt tracking to include command that triggered it
_Jira ticket:_ CLOUDP-124592

CLOUDP-124592: Telemetry - Enhance prompt tracking to include command that triggered it

---

go.mod
internal/cli/auth/login.go

_Jira ticket:_ [CLOUDP-125111](https://jira.mongodb.org/browse/CLOUDP-125111)

CLOUDP-125111: Revert color causing windows issue

---

docs/atlascli/command/atlas-clusters-create.txt
docs/mongocli/command/mongocli-atlas-clusters-create.txt
internal/cli/atlas/clusters/create.go

docs: add example for free cluster

---

cmd/atlas/atlas.go
internal/telemetry/command.go

Some errors are not being tracked
_Jira ticket:_ CLOUDP-125776

CLOUDP-125776: Some errors are not being tracked

---

internal/cli/config/set.go
internal/config/profile.go
internal/mongosh/mongosh.go
internal/telemetry/command.go

Enable/disable telemetry in mongosh when changed in atlas cli
_Jira ticket:_ CLOUDP-124943

CLOUDP-124943: Enable/disable telemetry in mongosh when changed in atlas cli

---

build/ci/release.yml

We have never published unstable atlascli 1.1.x releases in the YUM/APT testing repos. This PR fixes it.
_Jira ticket:_ CLOUDP-126069

CLOUDP-126069: Fix unstable atlascli releases

---

docs/atlascli/command/atlas-privateEndpoints-aws-describe.txt
docs/atlascli/command/atlas-privateEndpoints-aws-interfaces-describe.txt
docs/mongocli/command/mongocli-atlas-privateEndpoints-aws-describe.txt
docs/mongocli/command/mongocli-atlas-privateEndpoints-aws-interfaces-describe.txt
internal/cli/atlas/privateendpoints/aws/describe.go
internal/cli/atlas/privateendpoints/aws/describe_test.go
internal/cli/atlas/privateendpoints/aws/interfaces/describe.go

I have added examples and descriptions to the documentation to make the commands more understandable for the users. I also changed the argument name to make it more informative. 
_Jira ticket:_ CLOUDP-124966

[CLOUDP-124966] Update project docs, change argument name

---

build/ci/evergreen.yml
go.sum

Small fixes to evergreen that pop up while explaining how evergreen works

tests: evergreen fixes

---

internal/cli/atlas/backup/backup_test.go
internal/cli/atlas/backup/restores/list.go
internal/cli/atlas/backup/restores/list_test.go
internal/cli/atlas/backup/restores/restores.go
internal/cli/atlas/backup/restores/restores_test.go
internal/cli/atlas/backup/restores/start.go
internal/cli/atlas/backup/restores/start_test.go
internal/cli/atlas/backup/restores_start.go

Improve restore start error message, by validating what is required and what is optional.
_Jira ticket:_ CLOUDP-126517
this PR is also moving all restores operations to it's own package

CLOUDP-126517: Improve restores error message

---

test/e2e/atlas/atlas_e2e_test_generator_test.go

Improve projectID error handling
_Jira ticket:_ CLOUDP-126721

CLOUDP-126721: Improve projectID error handling

---

.golangci.yml
internal/cli/alerts/settings/list_test.go
internal/cli/atlas/dbusers/delete_test.go
internal/cli/atlas/dbusers/describe_test.go
internal/cli/atlas/metrics/metrics.go
internal/cli/atlas/search/update_test.go
internal/cli/atlas/serverless/create.go
internal/cli/iam/organizations/delete_test.go
internal/cli/iam/projects/delete_test.go
internal/cli/iam/projects/users/delete_test.go
internal/cli/metrics_opt.go
internal/cli/opsmanager/clusters/indexes_create_test.go
internal/cli/opsmanager/dbusers/delete_test.go
internal/cli/opsmanager/logs/jobs_delete_test.go
internal/cli/opsmanager/monitoring/stop_test.go
internal/decryption/pem/pkcs8.go
internal/store/telemetry.go
test/e2e/atlas/dbusers_certs_test.go

this is about enforcing consistent imports, they will always follow standard lib, new line, external packages

chore: enforce consistent imports

---

internal/cli/atlas/backup/restores/start.go
internal/cli/atlas/backup/snapshots/create.go
internal/cli/atlas/backup/snapshots/delete.go
internal/cli/atlas/clusters/pause.go
internal/cli/atlas/clusters/start.go
internal/cli/atlas/clusters/update.go
internal/cli/atlas/commonerrors/errors.go
internal/cli/atlas/commonerrors/errors_test.go

Improve error messages for operations not available on shared clusters
_Jira ticket:_ CLOUDP-109908
this PR should only be merged after https://github.com/mongodb/mongodb-atlas-cli/pull/1342

CLOUDP-109908: Improve error messages for operations not available on shared clusters

---

.githooks/pre-commit

git pre commit hook does not add changes made by `make fix-lint` into commit
_Jira ticket:_ CLOUDP-128209
This is how to test it
* make a change at `tools/release/main.go` at line 30
```diff
+// comment without a period
type Opts struct {
```
* commit that change `git commit -m "test"`
* you will end with a commit and a file changed without being committed
```diff
-// comment without a period
+// comment without a period.
type Opts struct {
```
* you will end with a commit including the change straight away
```diff
+// comment without a period.
type Opts struct {
```

CLOUDP-128209: git pre commit hook does not add changes made by make fix-lint into commit

---

docs/atlascli/command/atlas-config-delete.txt
docs/mongocli/command/mongocli-config-delete.txt
internal/cli/config/delete.go

_Jira ticket:_ [CLOUDP-130082](https://jira.mongodb.org/browse/CLOUDP-130082)
While troubleshooting other issues I tried to delete a config and noticed we're not skipping deletion if confirmation answer is "No"
```
➜  mongocli git:(master) atlas config delete default
? Are you sure you want to delete: default No
Profile 'default' deleted
```
After the fix:
```
➜  mongocli git:(fix_delete_confirm) atlasdev config delete apikeys2
? Are you sure you want to delete: apikeys2 No
➜  mongocli git:(fix_delete_confirm) atlasdev config delete apikeys2 --force
Profile 'apikeys2' deleted
➜  mongocli git:(fix_delete_confirm) atlas config delete defaulta
? Are you sure you want to delete: defaulta Yes
Profile 'defaulta' deleted
```

CLOUDP-130082: Fix delete config confirmation

---

test/e2e/atlas/clusters_upgrade_test.go

Small fixes to [this](https://github.com/mongodb/mongodb-atlas-cli/pull/1387) PR.
_Jira ticket:_ [CLOUDP-127622](https://jira.mongodb.org/browse/CLOUDP-127622)

CLOUDP-127622: Change test name, remove unneeded parameter

---

internal/cli/auth/login_test.go
internal/cli/auth/register_test.go
internal/cli/default_setter_opts.go
internal/cli/default_setter_opts_test.go
internal/prompt/config.go

Adds input to filter orgs when users have more than 500 and fix type to filter projects
_Jira ticket:_ CLOUDP-115072
Detected more than 500 orgs
Input ID
Input name filter

CLOUDP-115072: Adds input to filter orgs and type to filter for projects

---

build/ci/evergreen.yml
internal/store/store.go
test/e2e/atlas/atlas_e2e_test_generator_test.go
test/e2e/atlas/cleanup_test.go

Delete atlas projects on a cron job
_Jira ticket:_ CLOUDP-131043

CLOUDP-131043: Delete atlas projects on a cron job

---

.gitignore

We are having issues with the release, this is an attempt to fix it.

fix: goreleaser git dirty state

---

build/ci/release.yml

Run repo tests as part of release process
_Jira ticket:_ CLOUDP-132191

CLOUDP-132191: Run repo tests as part of release process

---

build/ci/release.yml
build/package/docker/meta/rhel9-rpm.Dockerfile
build/package/docker/meta/ubuntu22.04-deb.Dockerfile
build/package/docker/repo/rhel9.Dockerfile
build/package/docker/repo/ubuntu22.04.Dockerfile
build/package/docker/rhel9-rpm.Dockerfile
build/package/docker/ubuntu22.04-deb.Dockerfile
tools/evergreen/main.go

Add RHEL 9.X & Ubuntu 22.04 support for the CLIs
_Jira ticket:_ CLOUDP-131259

CLOUDP-131259: Add RHEL 9.X & Ubuntu 22.04 support for the CLIs

---

build/ci/evergreen-generate-tasks.sh
build/ci/release.yml
tools/genevergreen/main.go

Move post packaging tests to evergreen generate task
_Jira ticket:_ CLOUDP-126564

CLOUDP-126564: Move post packaging tests to evergreen generate task

---

test/e2e/atlas/integrations_test.go

Datadog integration is disabled in cloudgov (followup from https://github.com/mongodb/mongodb-atlas-cli/pull/1417)
_Jira ticket:_ CLOUDP-132962

CLOUDP-132962: Datadog integration is disabled in cloudgov (address comments)

---

build/ci/release.yml
build/ci/repo_config.yaml
tools/genevergreen/main.go

Fix repo configuration for Ubuntu 22 & RHEL 9 and also fix for 6.0 repo
_Jira ticket:_ CLOUDP-133279

CLOUDP-133279: Fix repo configuration for Ubuntu 22 & RHEL 9 and also fix for 6.0 repo

---

build/package/generate-msi.sh

Fix msi generation
_Jira ticket:_ CLOUDP-133279

CLOUDP-133279: Fix msi generation

---

docs/mongocli/command/mongocli-ops-manager-serverUsage-download.txt
go.mod
go.sum
internal/cli/opsmanager/serverusage/download.go
internal/flag/flags.go
internal/usage/usage.go
test/e2e/atlas/helper_test.go
test/e2e/atlas/performance_advisor_test.go

_Jira ticket:_ CLOUDP-132496
Manually tested it works as expected

CLOUDP-132496: MongoCLI server usage download results in only redacted version

---

internal/cli/auth/login.go
internal/cli/auth/login_test.go
internal/cli/auth/register_test.go
internal/cli/default_setter_opts.go

_Jira ticket:_ [CLOUDP-133258](https://jira.mongodb.org/browse/CLOUDP-133258)
```shell
➜  mongocli git:(CLOUDP-133258) atlasdev login
To verify your account, copy your one-time verification code:
4896-7PV8
Paste the code in the browser when prompted to activate your Atlas CLI. Your code will expire after 10 minutes.
To continue, go to https://account.mongodb.com/account/connect
Successfully logged in as bianca.vianadeaguiar+9123@mongodb.com.
➜  mongocli git:(CLOUDP-133258)
```
```shell
➜  mongocli git:(CLOUDP-133258) atlasdev login
To verify your account, copy your one-time verification code:
CR8R-W4FJ
Paste the code in the browser when prompted to activate your Atlas CLI. Your code will expire after 10 minutes.
To continue, go to https://account.mongodb.com/account/connect
Successfully …
```

CLOUDP-133258: Fix registration flow

---

build/package/chocolatey/atlascli.nuspec
build/package/generate-msi.sh
tools/chocolateypkg/main.go
tools/chocolateyupdate/main.go

Chocolatey package description is off, markdown is not rendered
_Jira ticket:_ CLOUDP-133379

CLOUDP-133379: Chocolatey package description is off

---

tools/chocolateypkg/main.go

Addressing comments from https://github.com/mongodb/mongodb-atlas-cli/pull/1423
_Jira ticket:_ CLOUDP-133379

CLOUDP-133379: address comments

---

.gitignore
build/ci/release.yml
build/package/chocolatey/atlascli.nuspec
build/package/generate-msi.sh
tools/chocolateypkg/main.go

Rename atlascli to mongodb-atlas
_Jira ticket:_ CLOUDP-133816

CLOUDP-133816: Rename atlascli to mongodb-atlas

---

build/ci/release.yml

fix tests to verify pkgs were uploaded to repos
_Jira ticket:_ CLOUDP-133383
unfortunately these tests are expected to run during a release so we can only check them during a release

CLOUDP-133383: fix repo tests

---

test/e2e/atlas/alert_settings_test.go

Commenting failing tests temporarily while we troubleshoot the issue in the ticket below. 
_Jira ticket:_ [CLOUDP-135288](https://jira.mongodb.org/browse/CLOUDP-135288)

Remove alerts tests from generic suit temporarily

---

build/ci/release.yml
build/ci/repo_config.yaml
build/package/docker/debian11-deb.Dockerfile
build/package/docker/meta/debian11-deb.Dockerfile
build/package/docker/repo/debian11.Dockerfile
tools/genevergreen/main.go
tools/release/main.go

CLOUDP-136747: Publish the CLI to Debian 11

---

docs/atlascli/command/atlas-dbusers-create.txt
docs/mongocli/command/mongocli-atlas-dbusers-create.txt
internal/cli/atlas/dbusers/create.go

Updates example for atlas db user create command
CLOUDP-134858

(CLOUDP-134858) Updates example for atlas db user create command

---

internal/cli/auth/login.go
internal/cli/auth/login_test.go
internal/cli/auth/register.go
internal/cli/auth/register_test.go

Login to the CLI even if configuration process is not completed, for instance when org and project are not created or user has no orgs or projects to access
_Jira ticket:_ CLOUDP-135263

CLOUDP-135263: Login to the CLI even if configuration process is not completed

---

internal/cli/atlas/privateendpoints/azure/interfaces/describe.go

_Jira ticket:_ CLOUDP-137869
**Issue:**
The command's template was expecting a field called `AzureStatus` while it was returned `Status` instead
```
atlas privateEndpoints azure interfaces describe /subscriptions/d1afd9d5-ee4e-4a50-a508-800cc6515cfa/resourceGroups/private-endpoint-test/providers/Microsoft.Network/privateEndpoints/thiswillwork --endpointServiceId 63319adcce96b26c74392294
Error: template: output:2:63: executing "output" at <.AzureStatus>: can't evaluate field AzureStatus in type *mongodbatlas.InterfaceEndpointConnection
```
**Fix:**
```
./bin/atlas privateEndpoints azure interfaces describe "/subscriptions/d1afd9d5-ee4e-4a50-a508-800cc6515cfa/resourceGroups/private-endpoint-test/providers/Microsoft.Network/privateEndpoints/thiswillwork" --endpointServiceId …
```

CLOUDP-137869: The template of atlas privateEndpoints azure interfaces describe is using the wrong status field

---

docs/atlascli/command/atlas-backups-snapshots-create.txt
docs/mongocli/command/mongocli-atlas-backups-snapshots-create.txt
internal/cli/atlas/backup/snapshots/create.go
internal/usage/usage.go

Wrong help text for Atlas CLI command 'atlas backup snapshots create --help'
_Jira ticket:_ CLOUDP-135434

CLOUDP-135434: Wrong help text for Atlas CLI command 'atlas backup snapshots create --help'

---

internal/cli/global_opts.go
internal/cli/iam/users/describe.go
internal/cli/iam/users/invite.go
internal/prerun/prerun.go

atlas users invite command panics
_Jira ticket:_ CLOUDP-136709

CLOUDP-136709: atlas users invite command panics

---

test/e2e/atlas/alert_settings_test.go

Reenabling disabled tests
_Jira ticket:_ CLOUDP-135608

CLOUDP-135608: Enable alerts test

---

internal/cli/atlas/clusters/clusters.go
internal/cli/atlas/clusters/create.go
internal/cli/atlas/clusters/update.go
internal/cli/atlas/clusters/upgrade.go
internal/cli/atlas/customdbroles/list.go
internal/cli/atlas/quickstart/cluster_setup.go
internal/cli/atlas/quickstart/quick_start.go
internal/cli/atlas/setup/setup_cmd.go

_Jira ticket:_ CLOUDP-138782
Old label for the commands `atlas cluster create`, `atlas cluster update`, `atlas cluster upgrade`:
- labelKey: "Infrastructure Tool" 
- labelValue: "mongoCLI"
**New label** for the commands `atlas cluster create`,`atlas cluster update`, `atlas cluster upgrade`:
- labelKey: "Infrastructure Tool" 
- labelValue: "Atlas CLI"
Old label for the command `atlas cluster setup`:
- labelKey: "Infrastructure Tool" 
- labelValue: "MongoDB CLI Quickstart"
**New label** for the command `atlas cluster setup`:
- labelKey: "Infrastructure Tool" 
- labelValue: "Atlas CLI Setup"
Old label for the command `atlas cluster quickstart`:
- labelKey: "Infrastructure Tool" 
- labelValue: "MongoDB CLI Quickstart"
**New label** for the command `atlas cluster quickstart`:
- labelKey: …

CLOUDP-138782: [Atlas CLI] Update cluster labelling when creating clusters via Atlas CLI

---

build/ci/release.yml

CLOUDP-140307: Fix apt/yum stable release for atlascli

---

docs/atlascli/command/atlas-clusters-availableRegions-list.txt
docs/atlascli/command/atlas-clusters-availableRegions.txt
internal/cli/atlas/clusters/availableregions/list.go

_Jira ticket:_ [CLOUDP-123180](https://jira.mongodb.org/browse/CLOUDP-123180)

CLOUDP-123180: Update command description

---

internal/cli/errors.go

Error text fixup

---

docs/atlascli/command/atlas-customDbRoles-create.txt
docs/mongocli/command/mongocli-atlas-customDbRoles-create.txt
internal/cli/atlas/customdbroles/create.go

Added short small example to clarify syntax.

DOCSP-25561 add example to clarify create customDbRole syntax

---

docs/atlascli/command/atlas-dbusers-describe.txt
docs/mongocli/command/mongocli-atlas-dbusers-describe.txt
internal/cli/atlas/dbusers/describe.go

_Jira ticket:_ DOCSP-26342
- [ x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ x] I have added tests that prove my fix is effective or that my feature works
- [x ] I have added any necessary documentation in document requirements section listed in [CONTRIBUTING.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/CONTRIBUTING.md) (if appropriate)
- [x ] I have addressed the @mongodb/docs-cloud-team comments (if appropriate)
- [ x] I have updated [test/README.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/test/README.md) (if an e2e test has been added)
- [ x] I have run `make fmt` and formatted my code

DOCSP-26342: add examples to dbuser describe

---

docs/atlascli/command/atlas-networking-peering-create-aws.txt
docs/mongocli/command/mongocli-atlas-networking-peering-create-aws.txt
internal/cli/atlas/networking/peering/create/aws.go

[JIRA](https://jira.mongodb.org/browse/DOCSP-26347)

DOCSP-26347: Adding example to AWS Peering Connection Creator

---

docs/atlascli/command/atlas-backups-snapshots-list.txt
docs/mongocli/command/mongocli-atlas-backups-snapshots-list.txt
internal/cli/atlas/backup/snapshots/list.go

DOCSP-26387: added a mongocli  backup list example

---

docs/atlascli/command/atlas-security-ldap-save.txt
docs/mongocli/command/mongocli-atlas-security-ldap-save.txt
internal/cli/atlas/security/ldap/save.go

[Jira](https://jira.mongodb.org/browse/DOCSP-26351)

DOCSP-26351: Adds example.

---

docs/atlascli/command/atlas-config-set.txt
docs/mongocli/command/mongocli-config-set.txt
internal/cli/config/set.go

_Jira ticket:_ [CLOUDP-130926
](https://jira.mongodb.org/browse/CLOUDP-130926)

CLOUDP-130926: Fix atlas config set help

---

Makefile
go.mod
go.sum
internal/kubernetes/operator/config_exporter.go
internal/kubernetes/operator/project/project.go
internal/kubernetes/operator/project/project_test.go
internal/store/operator.go

Added an ability to export Atlas Teams for the kubernetes config generate command
**NOTE**: `mongodb-atlas-kubernetes` dependency is not set to the release version, because the feature is not released yet. A proper version (1.5.0) will be set as soon as it will be released.
_Jira ticket:_ [CLOUDP-145624](https://jira.mongodb.org/browse/CLOUDP-145624)

CLOUDP-145624: Added import for Atlas teams

---

go.mod
go.sum

This seems like a leftover from the operator import

task: run go mod tidy

---

internal/kubernetes/operator/project/project.go
internal/kubernetes/operator/project/project_test.go
internal/store/operator.go

Fixed missing users for `AtlasTeam` resource when running `atlas kubernetes config generate`
_Jira ticket:_ [CLOUDP-149380](https://jira.mongodb.org/browse/CLOUDP-149380)

CLOUDP-149380: Fixed missing users for AtlasTeam resource

---

test/e2e/atlas/atlas_e2e_test_generator_test.go
test/e2e/atlas/helper_test.go
test/e2e/atlas/kubernetes_config_generate_test.go

Unified the way the test for `atlas kubernetes config generate` creates resources in atlas
_Jira ticket:_ [CLOUDP-149121](https://jira.mongodb.org/browse/CLOUDP-149121)

CLOUDP-149121: Unified E2E kubernetes config generate test

---

cmd/atlas/atlas.go

_Jira ticket:_ [CLOUDP-123998](https://jira.mongodb.org/browse/CLOUDP-123998)
```shell
~/workplace/mongocli CLOUDP-123998 *20 ~1 ❯ atlasdev clusters list                                                                                                                                                                                                                                       1.19 09:56:43
? Atlas CLI has found an existing MongoDB CLI configuration file, would you like to copy its content? (destination:/Users/bianca.lisle/Library/Application Support/atlascli/config.toml) Yes
AtlasCLI has copied your MongoCLI configuration to: /Users/bianca.lisle/Library/Application Support/atlascli/config.toml
```
```shell
~/workplace/mongocli CLOUDP-123998 *20 ~1 ❯ atlasdev config --help …
```

CLOUDP-123998: Ask before copying mongocli configuration to AtlasCLI

---

internal/cli/atlas/customdbroles/list.go
internal/cli/atlas/customdbroles/list_test.go

_Jira ticket:_ CLOUDP-151576
This PR updates `atlas customDbRoles list` format to include `inheritedRoles`.
**Now:**
```                                                                                                                                      1.19
./bin/atlas customDbRoles list                                                                                                                                         3s  1.19
NAME         ACTION                       INHERITED ROLES   DB         COLLECTION        CLUSTER
test28       FIND                         N/A               admin      ALL COLLECTIONS   N/A
test29       FIND                         N/A               admin      ALL COLLECTIONS   N/A
test30       FIND                         N/A …
```

CLOUDP-151576: atlas customDbRoles list format does not list inheritedRoles

---

internal/terminal/terminal.go

doc: correct go doc

---

internal/config/profile.go

_Jira ticket:_ CLOUDP-152310
Make `publicKey` visible when using the `atlas config describe <name>` command. This reflects the UI functionality - the public API keys are visible in the Atlas UI.

CLOUDP-152310: Make publicKey visible in profile

---

internal/kubernetes/operator/project/project.go
internal/kubernetes/operator/project/project_test.go

CLOUDP-153344: Fix network peering

---

test/e2e/atlas/atlas_e2e_test_generator_test.go
test/e2e/brew/brew_test.go
test/e2e/cli.go
test/e2e/config/config_test.go

modernizing of some test code to replace usages of `'%s'` with `%q`

test: replace usages of '%s' with %q

---

test/e2e/atlas/clusters_flags_test.go
test/e2e/atlas/clusters_sharded_test.go
test/e2e/atlas/create_cluster_gov_test.json
test/e2e/atlas/create_cluster_test.json
test/e2e/atlas/helper_test.go
test/e2e/atlas/integrations_test.go

CLOUDP-154647: conditionally set the tier for gov or commercial so commercial can be an M10 and gov can be the now available M20

CLOUDP-154647: Reduce cost of Atlas E2E Suite - M30 instances

---

docs/atlascli/command/atlas-setup.txt
internal/cli/atlas/setup/setup_cmd.go
test/e2e/atlas/setup_force_test.go

Add flag for cluster termination protection to `atlas setup` command.
_Jira ticket:_ CLOUDP-156022

CLOUDP-156022: Add cluster termination protection flag to setup

---

test/e2e/atlas/atlas_e2e_test_generator_test.go
test/e2e/atlas/helper_test.go
test/e2e/atlas/kubernetes_config_generate_test.go

CLOUDP-153348: Add k8s atlas e2e tests

---

test/e2e/helper.go

Improve how helper errors are reported to include the output of the command

test: improve error reporting for helper errors

---

internal/kubernetes/operator/config_exporter.go
internal/kubernetes/operator/deployment/deployment.go
internal/kubernetes/operator/project/project.go
test/e2e/atlas/kubernetes_config_generate_test.go

Fix fetching clusters in deleting state
Fix ipAccessList generation for ip-only values
Fix fetching clusters in deleting state
_Jira ticket:_ CLOUDP-156164

CLOUDP-156164:  Fix some kubernetes generate bugs 

---

.github/labeler.yaml
.github/workflows/labeler.yaml

Automatically label issues related to Kubernetes

Automatically label issues related to Kubernetes

---

internal/cli/atlas/kubernetes/config/generate.go
internal/kubernetes/operator/features/crds.go
test/e2e/atlas/atlas_e2e_test_generator_test.go
test/e2e/atlas/helper_test.go
test/e2e/atlas/kubernetes_config_generate_test.go

Fixed labels for kubernetes E2E tests

Fixed labels for kubernetes E2E tests

---

Makefile
build/ci/check-licenses.sh
build/ci/clean-up-cloud-manager.sh
build/ci/evergreen-generate-tasks.sh
build/ci/install-agent-spawn-host.sh
build/ci/install-ops-manager-spawn-host.sh
build/ci/kmip/install.sh
build/ci/lint.sh
build/ci/set-up-cloud-manager.sh
build/ci/set-up-ops-manager.sh
build/ci/ssh-ready.sh
build/package/atlascli_mac_notarize.sh
build/package/atlascli_windows_notarize.sh
build/package/curator-push.sh
build/package/docker/docker-build.sh
build/package/docker/meta/docker-build.sh
build/package/docker/repo/docker-build.sh
build/package/download-msi.sh
build/package/generate-msi.sh
build/package/generate-notices.sh
build/package/mongocli_mac_notarize.sh
build/package/mongocli_windows_notarize.sh
build/package/package.sh
build/package/rename-pkg.sh
build/package/send-slack-notification.sh
scripts/add-copy.sh
scripts/fix-lint.sh
scripts/fmt.sh
scripts/release.sh

Similar to [mongodbatlas-cloudformation-resources/pull/209](https://github.com/mongodb/mongodbatlas-cloudformation-resources/pull/209), adding [shfmt](https://github.com/mvdan/sh) to format sh files
_Jira ticket:_ INTMDB-567

INTMDB-567: Add shfmt to the dev tools to fmt sh files

---

internal/kubernetes/operator/dbusers/dbusers.go
internal/kubernetes/operator/dbusers/dbusers_test.go

Current Atlas CLI creates the same K8S resource name and namespace in some cases. For example, Database usernames "Atlas" and "atlas" will be converted to "atlas", creating different resources with the same name. Here we solve the problem by adding a 5 chars suffix for the resource names that conflict.
_Jira ticket:_ CLOUDP-155373

CLOUDP-155373: Fix k8s DatabaseUser name conflict

---

build/ci/library_owners.json
go.mod
go.sum
internal/cli/root/atlas/builder_test.go
internal/cli/root/mongocli/builder_test.go
internal/latestrelease/finder_test.go
internal/mocks/mock_release_version.go
internal/version/release_version.go

Update the github lib, I'm trying to investigate an issue with slow commands on mongocli and I suspect the version checker to be at fault so updating some libs here

task: update GH lib

---

internal/cli/atlas/quickstart/prompt.go
internal/cli/atlas/quickstart/quick_start.go

CLOUDP-152480: [Atlas CLI] Update copy for loading sample data

---

internal/cli/cloudmanager/cloud_manager.go
internal/cli/iam/iam.go
internal/cli/opsmanager/ops_manager.go
internal/cli/root/atlas/builder.go
internal/store/store.go
internal/telemetry/tracker.go

_Jira ticket:_ CLOUDP-162135
This is  a straight up port of the feature in Atlas CLI, manually tested

CLOUDP-162135: Add debug option to mongocli

---

build/package/powershell/windows_post_package_test.ps1

CLOUDP-163804: Failed Task: mongocli-master-pkg_test_windows/pkg_smoke_tests_windows_atlascli

---

test/e2e/atlas/kubernetes_config_generate_test.go

_Jira ticket:_ CLOUDP-164211
Reviewing the e2e tests for k8s for a spec I noticed there were some issues with some of the test matchers that could be improved as well as moving some the the casting operations to functions as they are reused in multiple tests

CLOUDP-164211: k8s e2e cleanup

---

internal/cli/errors.go

CLOUDP-150028: update error message for the atlas-cli when setup is used multiple times

---

docs/atlascli/command/atlas-backups-schedule-update.txt
internal/cli/atlas/backup/schedule/update.go
internal/cli/atlas/backup/schedule/update_test.go
internal/usage/usage.go

Adds filename to backup schedules command
_Jira ticket:_ CLOUDP-163790

CLOUDP-163790 Update command "backups schedule update"

---

internal/decryption/pem/pkcs8.go

_Jira ticket:_ CLOUDP-164758
trying to solve an error where linting locally for me returns
```
ERRO Running error: 1 error occurred:
* can't run linter goanalysis_metalinter: gofmt: can't extract issues from gofmt diff output "--- /Users/Projects/mongodb-atlas-cli/internal/decryption/pem/pkcs8.go.orig\t2023-03-01 15:17:10\n+++ /Users/Projects/mongodb-atlas-cli/internal/decryption/pem/pkcs8.go\t2023-03-01 15:17:10\n@@ -78,7 +78,7 @@\n \toidD3DESCBC       = asn1.ObjectIdentifier{1, 2, 840, 113549, 3, 7}\n )\n \n-//nolint\n+// nolint\n func DecryptPKCS8PrivateKey(data, password []byte) ([]byte, error) {\n \tvar pki encryptedPrivateKeyInfo\n \tif _, err := asn1.Unmarshal(data, &pki); err != nil {\n": can't parse patch: parsing time "2023-03-01 15:17:10" as "2006-01-02 15:04:05 -0700": cannot …
```

CLOUDP-164758: Correct linting for internal/decryption/pem/pkcs8.go

---

internal/cli/atlas/backup/schedule/update.go

Fixes a bug where updating a backup schedule with Atlas CLI does not properly support setting days for weekly backup
_Jira ticket:_ CLOUDP-164352
Our validation was wrong returning some errors where we have to allow

CLOUDP-164352: Fix updating a backup schedule with Atlas CLI does not properly support setting days for weekly backup

---

docs/atlascli/command/atlas-clusters-update.txt
docs/mongocli/command/mongocli-atlas-clusters-update.txt
internal/cli/atlas/clusters/update.go

This PR updates the documentation of `atlas cluster update` to reflect that the command can be used for multi-region clusters.

Update the "cluster update" documentation to remove 

---

build/ci/release.yml
tools/genevergreen/generate/generate.go

CLOUDP-126561: [AtlasCLI] Move evegreen tests out of EOL OSes

---

docs/atlascli/command/atlas-logs-download.txt
docs/atlascli/command/atlas-maintenanceWindows-clear.txt
docs/atlascli/command/atlas-maintenanceWindows-defer.txt
docs/atlascli/command/atlas-maintenanceWindows-describe.txt
docs/atlascli/command/atlas-maintenanceWindows-update.txt
docs/atlascli/command/atlas-metrics-databases-list.txt
docs/atlascli/command/atlas-metrics-disks-describe.txt
docs/atlascli/command/atlas-metrics-disks-list.txt
docs/atlascli/command/atlas-metrics-processes.txt
docs/mongocli/command/mongocli-atlas-logs-download.txt
docs/mongocli/command/mongocli-atlas-maintenanceWindows-clear.txt
docs/mongocli/command/mongocli-atlas-maintenanceWindows-defer.txt
docs/mongocli/command/mongocli-atlas-maintenanceWindows-describe.txt
docs/mongocli/command/mongocli-atlas-maintenanceWindows-update.txt
docs/mongocli/command/mongocli-atlas-metrics-databases-list.txt
docs/mongocli/command/mongocli-atlas-metrics-disks-describe.txt
docs/mongocli/command/mongocli-atlas-metrics-disks-list.txt
docs/mongocli/command/mongocli-atlas-metrics-processes.txt
internal/cli/atlas/logs/download.go
internal/cli/atlas/maintenance/clear.go
internal/cli/atlas/maintenance/defer.go
internal/cli/atlas/maintenance/describe.go
internal/cli/atlas/maintenance/update.go
internal/cli/atlas/metrics/databases/list.go
internal/cli/atlas/metrics/disks/describe.go
internal/cli/atlas/metrics/disks/list.go
internal/cli/atlas/metrics/processes/processes.go

Adds required role info for metrics, maintenance, and logs commands
https://jira.mongodb.org/browse/DOCSP-28114

(DOCSP-28114) Adds required roles for metrics, maintenance, and logs commands

---

internal/convert/cluster_config_test.go
internal/convert/process_config.go

Fixing issue where DefaultRWConcern was being dropped from mongocli cluster describe/update
Example:
```
mongocli om cluster describe colm-replset-testing --output json
{
"name": "colm-replset-testing",
"processes": [
{
"arbiterOnly": false,
"buildIndexes": true,
"dbPath": "/data/colm-replset-testing",
"defaultRWConcern": {},
"disabled": false,
"featureCompatibilityVersion": "6.0",
"hidden": false,
"hostname": "{redacted}",
"logDestination": "file",
"logPath": "/data/colm-replset-testing/mongodb.log",
"name": "colm-replset-testing_31",
"port": 25000,
"priority": 1,
"processType": "mongod",
"secondaryDelaySecs": 0,
"votes": 1,
"version": "6.0.2"
},
{
"arbiterOnly": false,
"buildIndexes": true,
"dbPath": "/data/colm-replset-testing/rc1",
"defaultRWConcern": {},
"disabled": false, …
```

CLOUDP-155672: Fixing assignment for defaultRWConcern configs

---

docs/atlascli/command/atlas-serverless-backups-snapshots-watch.txt
docs/atlascli/command/atlas-serverless-backups-snapshots.txt
internal/cli/atlas/serverless/backup/snapshots/snapshots.go
internal/cli/atlas/serverless/backup/snapshots/snapshots_test.go
internal/cli/atlas/serverless/backup/snapshots/watch.go
internal/cli/atlas/serverless/backup/snapshots/watch_test.go

Add command "serverless backups snapshots watch"
_Jira ticket:_ CLOUDP-164769

CLOUDP-164769 Add command "serverless backups snapshots watch"
