mongodb/mongodb-atlas-cli

build/ci/release.yml, build/package/chocoupdate.sh
Fixes a bug where we could not release mongocli, basically it was calling `choco push` for both mongocli and atlascli where it should not do it.
_Jira ticket:_ CLOUDP-167098
Closes #1772
=> CLOUDP-167098 Fixes a bug where we could not release mongocli

go.mod, go.sum
Updates cobra2snooty to v0.14.1
https://jira.mongodb.org/browse/DOCSP-28661
=> Updates cobra2snooty to v0.14.1

build/ci/evergreen.yml
configure GOPROXY to use internal artifactory
_Jira ticket:_ CLOUDP-167676
=> CLOUDP-167676: configure GOPROXY to use artifactory

test/e2e/atlas/backup_schedule_test.go
Add e2e tests for "backup schedule"
_Jira ticket:_ CLOUDP-164740
Adds e2e tests for:
- `atlas backup schedule describe`
- `atlas backup schedule update`
- `atlas backup schedule delete`
=> CLOUDP-164740 Add e2e tests for "backup schedule"

internal/cli/atlas/customdns/aws/describe_test.go, internal/cli/atlas/customdns/aws/disable_test.go, internal/cli/atlas/customdns/aws/enable_test.go, internal/mocks/mock_custom_dns.go, internal/store/custom_dns.go, test/e2e/atlas/custom_dns_test.go
Migrate Custom DNS methods to v2 client.
_Jira ticket:_ CLOUDP-167800
=> CLOUDP-167800: Migrate Custom DNS to v2 client

go.mod, go.sum, internal/cli/atlas/customdbroles/create.go, internal/cli/atlas/customdbroles/create_test.go, internal/cli/atlas/customdbroles/custom_db_roles.go, internal/cli/atlas/customdbroles/custom_db_roles_test.go, internal/cli/atlas/customdbroles/describe.go, internal/cli/atlas/customdbroles/describe_test.go, internal/cli/atlas/customdbroles/list.go, internal/cli/atlas/customdbroles/list_test.go, internal/cli/atlas/customdbroles/update.go, internal/cli/atlas/customdbroles/update_test.go, internal/convert/custom_db_role.go, internal/convert/custom_db_role_test.go, internal/kubernetes/operator/project/project.go, internal/kubernetes/operator/project/project_test.go, internal/mocks/mock_atlas_operator_project_store.go, internal/mocks/mock_database_roles.go, internal/store/database_roles.go, test/e2e/atlas/custom_db_roles_test.go
_Jira ticket:_ CLOUDP-# [CLOUDP-167795](https://jira.mongodb.org/browse/CLOUDP-167795)
EVG Patch: https://spruce.mongodb.com/version/6422f5dae3c3319349d1fd5b/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> CLOUDP-167795: Migrate Custom Database Roles CLI stores to v2 sdk

internal/cli/default_setter_opts.go, internal/cli/iam/organizations/list.go, internal/cli/iam/organizations/list_test.go, internal/mocks/mock_default_opts.go, internal/mocks/mock_organizations.go, internal/prompt/config.go, internal/store/organizations.go, test/e2e/iam/orgs_test.go
Draft PR to demonstrate the changes to Organizations list endpoint for Go SDK client upgrade 
_Jira ticket:_ CLOUDP-164969
=> CLOUDP-164969: Migrate Atlas CLI Organizations List endpoint to v2 SDK Client

internal/kubernetes/operator/deployment/deployment.go, internal/kubernetes/operator/deployment/deployment_test.go, internal/mocks/mock_atlas_operator_cluster_store.go, internal/mocks/mock_serverless_private_endpoints.go, internal/store/serverless_private_endpoints.go
Migrate Serverless Private Endpoints commands to v2 client.
_Jira ticket:_ CLOUDP-167805
=> CLOUDP-167805: Migrate serverless private endpoints

build/ci/release.yml
_Jira ticket:_ CLOUDP-169103
Fixes an issue with atlascli release
=> CLOUDP-169103 atlascli issues with release

build/package/chocoupdate.sh
atlascli issues with release (followup from https://github.com/mongodb/mongodb-atlas-cli/pull/1821)
_Jira ticket:_ CLOUDP-169103
=> CLOUDP-169103 atlascli issues with release (2nd)

docs/atlascli/command/atlas-kubernetes.txt, docs/atlascli/command/atlas.txt, internal/cli/atlas/kubernetes/kubernetes.go
[JIRA](https://jira.mongodb.org/browse/DOCSP-28916)
=> (DOCSP-28916) Typo fixes

internal/cli/atlas/metrics/databases/list.go, internal/cli/atlas/metrics/disks/list.go
=> DOCSP-28639: Update list format to include field name

test/e2e/iam/atlas_org_api_key_access_list_test.go, test/e2e/iam/atlas_org_api_keys_test.go, test/e2e/iam/atlas_org_invitations_test.go, test/e2e/iam/atlas_project_api_keys_test.go, test/e2e/iam/atlas_project_invitations_test.go, test/e2e/iam/atlas_project_teams_test.go, test/e2e/iam/atlas_projects_test.go, test/e2e/iam/atlas_team_users_test.go, test/e2e/iam/atlas_teams_test.go, test/e2e/iam/atlas_users_test.go, test/e2e/iam/helper_test.go, test/e2e/iam/org_api_keys_test.go, test/e2e/iam/org_invitations_test.go, test/e2e/iam/project_invitations_test.go, test/e2e/iam/projects_test.go, test/e2e/iam/teams_test.go
_Jira ticket:_ CLOUDP-168386
Addressing [this comment](https://github.com/mongodb/mongodb-atlas-cli/pull/1841#discussion_r1162879235)
Adding e2e test coverage for AtlasCLI Iam commands
=> CLOUDP-168386: Re-create Iam Command e2e tests for AtlasCLI

test/e2e/atlas/search_test.go
_Jira ticket:_ CLOUDP-# [CLOUDP-169109](https://jira.mongodb.org/browse/CLOUDP-169109)
Created the tests based on the documented static and combined mapping examples for Atlas Index creation: https://www.mongodb.com/docs/atlas/atlas-search/define-field-mappings/#static-mapping-example
EVG Patch: https://spruce.mongodb.com/task/mongodb_atlas_cli_master_e2e_atlas_clusters_atlas_search_e2e_patch_0506e355ba2068688fe8855fe9b137205607f471_642c0587e3c331f260813a94_23_04_04_11_10_07/tests?execution=0&sortBy=STATUS&sortDir=ASC
=> CLOUDP-169109: Add additional e2e tests for Atlas Search

test/e2e/atlas/atlas_e2e_test_generator_test.go, test/e2e/atlas/cleanup_test.go, test/e2e/atlas/helper_test.go, test/e2e/atlas/kubernetes_config_generate_test.go
clean up flakes with clusters and network peerings, making sure we delete all those before trying to delete projects
=> fix: flaky cleanup

go.mod, go.sum, internal/store/access_logs.go, internal/store/containers.go, internal/store/data_lake_pipelines.go, internal/store/maintenance.go, internal/store/project_ip_access_lists.go, internal/store/search.go
- Upgrading v2 sdk to latest sdkv2dev
https://github.com/mongodb/go-client-mongodb-atlas/tree/sdkv2dev 
- Addressing several required changes
=> build: upgrade v2client sdk version to latest master

build/ci/evergreen.yml
Fix timeout for backup restores
_Jira ticket:_ CLOUDP-171555
Followup from https://github.com/mongodb/mongodb-atlas-cli/pull/1885
=> CLOUDP-171555 Fix timeout for backup restores

.github/workflows/tidy.yml, go.sum
PR check to make mandatory go mod tidy
_Jira ticket:_ CLOUDP-172698
=> CLOUDP-172698 PR check to make mandatory go mod tidy

internal/store/database_users.go
Removing double query-encoding that causes db users Get to fail
_Jira ticket:_ CLOUDP-172901
Closes #1817
=> CLOUDP-172901: DB Users - Remove double query encoding

docs/mongocli/command/mongocli-cloud-manager-clusters-describe.txt, docs/mongocli/command/mongocli-ops-manager-clusters-describe.txt, internal/cli/opsmanager/clusters/describe.go, internal/cli/opsmanager/clusters/describe_test.go
_Jira ticket:_ CLOUDP-173973
Improve validation of input for clusters given certain conditions will trigger different endpoints with different types
=> CLOUDP-173973: Improve error handling for cluster describe if no output and name is provided

go.mod, go.sum, internal/cli/atlas/performanceadvisor/namespaces/list.go, internal/cli/atlas/performanceadvisor/namespaces/list_test.go, internal/cli/atlas/performanceadvisor/slowquerylogs/list.go, internal/cli/atlas/performanceadvisor/slowquerylogs/list_test.go, internal/cli/atlas/performanceadvisor/suggestedindexes/list.go, internal/cli/atlas/performanceadvisor/suggestedindexes/list_test.go, internal/mocks/atlas/mock_performance_advisor.go, internal/store/access_logs.go, internal/store/atlas/performance_advisor.go
Migration commands for performance advisor
=> CLOUDP-167772: performance advisor commands

internal/cli/atlas/dbusers/certs/create_test.go, internal/cli/atlas/dbusers/certs/list.go, internal/cli/atlas/dbusers/certs/list_test.go, internal/cli/atlas/dbusers/describe_test.go, internal/cli/atlas/dbusers/list.go, internal/cli/atlas/dbusers/list_test.go, internal/cli/atlas/security/customercerts/create_test.go, internal/cli/atlas/security/customercerts/describe.go, internal/cli/atlas/security/customercerts/describe_test.go, internal/kubernetes/operator/dbusers/dbusers.go, internal/kubernetes/operator/dbusers/dbusers_test.go, internal/mocks/mock_clusters.go, internal/mocks/mock_database_users.go, internal/mocks/mock_x509_certificate_store.go, internal/store/database_users.go, internal/store/x509_auth_database_users.go, test/e2e/atlas/dbusers_certs_test.go, test/e2e/atlas/dbusers_test.go
Migration to v2 sdk of: 
- database_users
- x509_auth_database_users
_Jira ticket:_ CLOUDP-167788
=> CLOUDP-167788: Migrate DbUsers and x509 CLI stores to v2 sdk

docs/atlascli/command/atlas-dataLakePipelines-update.txt, internal/cli/atlas/datalakepipelines/create.go, internal/cli/atlas/datalakepipelines/update.go
Address reviews from spec doc
_Jira ticket:_ CLOUDP-173618
=> CLOUDP-173618 Address reviews from spec

internal/cli/atlas/clusters/advancedsettings/describe.go
_Jira ticket:_ CLOUDP-# Story - [CLOUDP-167782](https://jira.mongodb.org/browse/CLOUDP-167782)
Previous Output:
➜  mongodb-atlas-cli git[CLOUDP-167785](https://jira.mongodb.org/browse/CLOUDP-167785)) ✗ bin/atlas clusters advancedSettings describe Cluster0 --projectId 6421987cdc060f20518edb62
MINIMUM TLS   JAVASCRIPT ENABLED   OPLOG SIZE MB
TLS1_2        true                 {<nil> true}
Current Output:
➜  mongodb-atlas-cli git:(CLOUDP-167782) bin/atlas clusters advancedSettings describe Cluster0 --projectId 6421987cdc060f20518edb62        
MINIMUM TLS   JAVASCRIPT ENABLED   OPLOG SIZE MB
TLS1_2        true                 N/A
=> CLOUDP-167782 Migrate "Clusters" CLI stores to v2 sdk

internal/cli/atlas/projects/settings/describe.go, internal/store/atlas/api_keys.go, internal/store/atlas/organizations.go, internal/store/atlas/projects.go, internal/store/cloud_provider_backup.go, internal/store/cloud_provider_backup_serverless.go, internal/store/clusters.go, internal/store/database_users.go, internal/store/online_archives.go, internal/store/organizations.go, internal/store/project_ip_access_lists.go
Addressing comments from https://github.com/mongodb/mongodb-atlas-cli/pull/1865
- removing all instances of  `IncludeCount` (not exposed) in the CLI
- removing inappropriately named package
=> tech: remove unset includeCount for v2 client methods

docs/mongocli/command/mongocli-cloud-manager-metrics-databases-describe.txt, docs/mongocli/command/mongocli-cloud-manager-metrics-disks-describe.txt, docs/mongocli/command/mongocli-cloud-manager-metrics-process.txt, docs/mongocli/command/mongocli-ops-manager-metrics-databases-describe.txt, docs/mongocli/command/mongocli-ops-manager-metrics-disks-describe.txt, docs/mongocli/command/mongocli-ops-manager-metrics-process.txt, internal/cli/atlas/metrics/databases/describe.go, internal/cli/atlas/metrics/disks/describe.go, internal/cli/atlas/metrics/processes/processes.go, internal/cli/metrics_opt.go, internal/cli/metrics_opts_test.go, internal/cli/opsmanager/metrics/databases_describe.go, internal/cli/opsmanager/metrics/disks_describe.go, internal/cli/opsmanager/metrics/process.go
_Jira ticket:_ CLOUDP-174225
Docs improvements based on internal feedback
=> CLOUDP-174225: Add example for metrics command

docs/atlascli/command/atlas-integrations-list.txt, docs/mongocli/command/mongocli-atlas-integrations-list.txt, internal/cli/atlas/integrations/create/datadog.go, internal/cli/atlas/integrations/create/datadog_test.go, internal/cli/atlas/integrations/create/new_relic.go, internal/cli/atlas/integrations/create/new_relic_test.go, internal/cli/atlas/integrations/create/ops_genie.go, internal/cli/atlas/integrations/create/ops_genie_test.go, internal/cli/atlas/integrations/create/pager_duty.go, internal/cli/atlas/integrations/create/pager_duty_test.go, internal/cli/atlas/integrations/create/victor_ops.go, internal/cli/atlas/integrations/create/victor_ops_test.go, internal/cli/atlas/integrations/create/webhook.go, internal/cli/atlas/integrations/create/webhook_test.go, internal/cli/atlas/integrations/describe.go, internal/cli/atlas/integrations/describe_test.go, internal/cli/atlas/integrations/list.go, internal/cli/atlas/integrations/list_test.go, internal/kubernetes/operator/project/project.go, internal/kubernetes/operator/project/project_test.go, internal/mocks/mock_access_logs.go, internal/mocks/mock_atlas_operator_project_store.go, internal/mocks/mock_integrations.go, internal/store/access_logs.go, internal/store/integrations.go, test/e2e/atlas/helper_test.go, test/e2e/atlas/integrations_test.go
_Jira ticket:_ CLOUDP-# [CLOUDP-167799](https://jira.mongodb.org/browse/CLOUDP-167799)
=> CLOUDP-167799:Migrate Third-Party Integrations CLI stores to v2 sdk

go.mod, go.sum, internal/convert/cluster_config.go, internal/convert/cluster_config_test.go, internal/convert/rs_config.go
_Jira ticket:_ CLOUDP-174224
Update lib version to pick up the type changes
=> CLOUDP-174224: Correct type for shard tags

internal/store/atlas/api_keys.go, internal/store/atlas/organization_invitations.go, internal/store/atlas/organizations.go, internal/store/atlas/project_invitations.go, internal/store/atlas/projects.go, internal/store/atlas/users.go, internal/store/cloud_provider_backup.go, internal/store/cloud_provider_backup_serverless.go, internal/store/clusters.go, internal/store/containers.go, internal/store/database_users.go, internal/store/organization_invitations.go, internal/store/organizations.go, internal/store/project_ip_access_lists.go
=> CLOUDP-174371: Add nil check for pointers

internal/cli/atlas/kubernetes/config/generate.go, internal/kubernetes/operator/config_apply.go, internal/kubernetes/operator/features/crds.go, test/e2e/atlas/kubernetes_config_apply_test.go
fix k8s resource mapping
_Jira ticket:_ CLOUDP-175229
=> CLOUDP-175229: fix k8s resource mapping

test/e2e/atlas/clusters_flags_test.go, test/e2e/atlas/search_test.go
Followup from #1932 fixing broken tests
_Jira ticket:_ CLOUDP-171360
=> CLOUDP-171360 Fix tests

go.mod, go.sum, internal/cli/mongocli/serverless/backup/restores/list.go, internal/store/cloud_provider_backup.go, internal/store/cloud_provider_backup_serverless.go
Follow-up on https://github.com/mongodb/mongodb-atlas-cli/pull/1896 
Spec changes to introduce listOptions has been addressed
Additionally, bumping sdkv2 version
_Jira ticket:_ CLOUDP-172920
=> CLOUDP-172920: introduce cloud provider backup list options

docs/atlascli/command/atlas-processes-describe.txt, docs/mongocli/command/mongocli-atlas-processes-describe.txt, go.mod, go.sum, internal/cli/atlas/processes/describe.go, internal/cli/atlas/processes/describe_test.go, internal/cli/atlas/processes/list.go, internal/cli/atlas/processes/list_test.go, internal/mocks/mock_processes.go, internal/store/processes.go, test/e2e/atlas/processes_test.go
Migration to sdkv2 of:
- atlas-processes-describe
- atlas-processes-list
Bumping sdkv2 version to latest
_Jira ticket:_ CLOUDP-172920
=> CLOUDP-172920: processes migration to sdk v2 client

docs/atlascli/command/atlas-customDbRoles-create.txt, docs/mongocli/command/mongocli-atlas-customDbRoles-create.txt, internal/cli/atlas/customdbroles/create.go
_Jira ticket:_ https://jira.mongodb.org/browse/DOCSP-29565
=> DOCSP-29565 Add example using --inheritedRole to customDbRoles create

docs/atlascli/command/atlas-dataLakePipelines-availableSnapshots-list.txt, docs/atlascli/command/atlas-dataLakePipelines-availableSnapshots.txt, docs/atlascli/command/atlas-dataLakePipelines.txt, go.mod, go.sum, internal/cli/atlas/datalakepipelines/availablesnapshots/list.go, internal/cli/atlas/datalakepipelines/availablesnapshots/list_test.go, internal/cli/atlas/datalakepipelines/data_lake_pipelines.go, internal/cli/atlas/datalakepipelines/data_lake_pipelines_test.go, test/e2e/atlas/data_lake_pipelines_test.go
reenable "atlas datalakepipelines availablesnapshots list"
_Jira ticket:_ CLOUDP-178268
=> CLOUDP-178268 reenable "atlas datalakepipelines availablesnapshots list"

docs/atlascli/command/atlas.txt, internal/cli/root/atlas/builder.go
_Jira ticket:_ https://jira.mongodb.org/browse/DOCSP-30068
=> DOCSP-30068 Fix missing punctuation

test/e2e/atlas/metrics_test.go
=> CLOUDP-180311:  CLI errors for monitoring

docs/atlascli/command/atlas-serverless-create.txt, docs/atlascli/command/atlas-serverless-update.txt, go.mod, go.sum, internal/cli/atlas/organizations/apikeys/create.go, internal/cli/atlas/organizations/apikeys/update.go, internal/cli/atlas/organizations/create_atlas.go, internal/cli/atlas/projects/apikeys/assign.go, internal/cli/atlas/projects/apikeys/create.go, internal/cli/atlas/projects/apikeys/create_test.go, internal/cli/atlas/serverless/create.go, internal/cli/atlas/serverless/create_test.go, internal/cli/atlas/serverless/update.go, internal/cli/atlas/serverless/update_test.go, internal/flag/flags.go, internal/mocks/atlas/mock_api_keys.go, internal/store/atlas/api_keys.go, internal/usage/usage.go, test/e2e/atlas/serverless_test.go
Add tags flag to atlas serverless create/update
_Jira ticket:_ CLOUDP-179336
=> CLOUDP-179336 Add tags flag to atlas serverless create/update

internal/cli/atlas/dbusers/update.go, internal/cli/atlas/dbusers/update_test.go, internal/convert/database_user.go, internal/mocks/mock_database_users.go, internal/store/database_users.go
Migrating dbuser update cli command to autogenerated sdk
_Jira ticket:_ CLOUDP-180813
=> CLOUDP-180813: migrate dbuser update

internal/cli/atlas/performanceadvisor/slowquerylogs/list.go, internal/cli/atlas/performanceadvisor/slowquerylogs/list_test.go
Fixing structure changes that were missing in the go template.
=> CLOUDP-181546: slow query logs

docs/atlascli/command/atlas-customDbRoles-create.txt, docs/mongocli/command/mongocli-atlas-customDbRoles-create.txt, internal/cli/atlas/customdbroles/create.go
This PR improves the example for `atlas customDbRoles create` command
_Jira ticket:_ CLOUDP-182875
=> CLOUDP-182875: Improve example for "atlas customDbRoles create" command

docs/atlascli/command/atlas-clusters-delete.txt, docs/mongocli/command/mongocli-atlas-clusters-delete.txt, internal/cli/atlas/clusters/delete.go
Temporarily hide watcher flag for atlas clusters delete in preparation for patch release
=> patch: hide watcher flags for atlas clusters delete

docs/atlascli/command/atlas-kubernetes-config-apply.txt, docs/atlascli/command/atlas-kubernetes-config-generate.txt, docs/atlascli/command/atlas-kubernetes-config.txt, internal/cli/atlas/kubernetes/config/apply.go, internal/cli/atlas/kubernetes/config/generate.go
[JIRA](https://jira.mongodb.org/browse/DOCSP-30263)
=> (DOCSP-30263) Change descriptions of AK8SO config commands.

internal/cli/atlas/clusters/watch.go
_Jira ticket:_ [CLOUDP-181572](https://jira.mongodb.org/browse/CLOUDP-181572)
=> CLOUDP-181572: Fix task atlas_clusters_upgrade_e2e from variant e2e_atlas_clusters

test/e2e/atlas/processes_test.go
Typo fix on e2e test that was introduced in https://github.com/mongodb/mongodb-atlas-cli/pull/2009 
_Jira ticket:_ CLOUDP-184341
=> CLOUDP-184341: e2e fix correct processes list compact flag

docs/atlascli/command/atlas-clusters-delete.txt, docs/mongocli/command/mongocli-atlas-clusters-delete.txt, internal/cli/atlas/clusters/delete.go
_Jira ticket:_  [CLOUDP-185418](https://jira.mongodb.org/browse/CLOUDP-185418)
=> CLOUDP-185418: Enable watcher flags for atlas clusters delete

build/package/.atlascli.goreleaser.yml, build/package/.mongocli.goreleaser.yml
Enable logging when running mac notary
_Jira ticket:_ CLOUDP-185426
=> CLOUDP-185426 Enable logging when running mac notary

docs/atlascli/command/atlas-kubernetes-operator-install.txt, internal/cli/atlas/kubernetes/operator/install.go
Add examples for using the `--import` flag.
_Jira ticket:_ https://jira.mongodb.org/browse/DOCSP-30303
=> DOCSP-30303 Revise guidance for operator install via Atlas CLI

RELEASING.md
=> wiki: Update RELEASING.md Deprecated Manual Release steps

internal/cli/atlas/clusters/update.go, internal/cli/atlas/serverless/update.go
Missing tags on cluster update
_Jira ticket:_ CLOUDP-185754
=> CLOUDP-185754 Missing tags on cluster update

.github/workflows/code-health.yml, build/ci/evergreen.yml, build/ci/release.yml
Move license_check to Github Actions
_Jira ticket:_ CLOUDP-185930
=> CLOUDP-185930 Move license_check to Github Actions

internal/cli/atlas/users/invite.go, test/e2e/iam/atlas_org_invitations_test.go, test/e2e/iam/atlas_orgs_test.go, test/e2e/iam/atlas_project_invitations_test.go, test/e2e/iam/atlas_project_teams_test.go, test/e2e/iam/atlas_projects_test.go, test/e2e/iam/atlas_users_test.go
_Jira ticket:_  [CLOUDP-181568](https://jira.mongodb.org/browse/CLOUDP-181568)
=> CLOUDP-181568 : Replace AtlasCLI v1 models with v2 models in e2e

internal/cli/atlas/organizations/list.go, internal/cli/atlas/projects/list.go, internal/cli/atlas/projects/list_test.go, internal/mocks/atlas/mock_organizations.go, internal/mocks/atlas/mock_projects.go, internal/store/atlas/organizations.go, internal/store/atlas/projects.go
_Jira ticket:_ CLOUDP-# [CLOUDP-181568](https://jira.mongodb.org/browse/CLOUDP-181568)
=> CLOUDP-181568 : Replace remaining AtlasCLI v1 models with v2 models

test/e2e/iam/atlas_users_test.go
IAM user tests are currently failing on dependabot PRs, adding some extra checks to try and debug them
it seems to now be passing here so not sure if a blip on the project or what, it's still worth keeping this change as it imrpvoes some of the test code
=> test: Improve users test to help debug error

test/e2e/iam/atlas_org_api_key_access_list_test.go, test/e2e/iam/atlas_org_api_keys_test.go
We can re-enable this test again
=> test: re-enable current IP test

internal/cli/atlas/clusters/create.go, internal/cli/atlas/clusters/update.go, internal/cli/atlas/clusters/upgrade.go, internal/cli/atlas/quickstart/cluster_setup.go, internal/cli/atlas/serverless/create.go, internal/cli/atlas/serverless/update.go
Resetting tags is not working on Atlas CLI
_Jira ticket:_ CLOUDP-187645
=> CLOUDP-187645 Resetting tags is not working on Atlas CLI

test/e2e/cloud_manager/deploy_sharded_cluster_test.go, test/e2e/cloud_manager/helper_test.go
_Jira ticket:_ CLOUDP-187164
Automation bug has been fixed upstream
=> CLOUDP-187164: [MongoCLI] Enable e2e: deploy_sharded_cluster_test

docs/atlascli/command/atlas-privateEndpoints-azure-interfaces-create.txt, docs/mongocli/command/mongocli-atlas-privateEndpoints-azure-interfaces-create.txt, internal/cli/atlas/privateendpoints/azure/interfaces/create.go
Fixes an example in the docs: removes extra spaces and adds required flag.
_Jira ticket:_ DOCSP-#30266
- [x ] I have run `make fmt` and formatted my code
=> (DOCSP-30266) Removes spaces and adds required flag to example.

.golangci.yml, .tool-versions, CONTRIBUTING.md, build/ci/evergreen.yml, build/ci/release.yml, go.mod, internal/cli/output_opts.go, internal/decryption/keyproviders/aws.go, internal/decryption/kmip/client.go, internal/decryption/log_record.go, internal/file/file.go, internal/file/file_test.go
_Jira ticket:_ CLOUDP-164587
Update go and enable double error wrapping where possible
=> CLOUDP-164587: Upgrade Atlas CLI to go1.20

docs/atlascli/command/atlas-serverless-create.txt, internal/cli/atlas/serverless/create.go
Adding an example for serverless create
=> docs: add serverless example

.github/workflows/docker-release.yml
=> Cloud 188862 personal

docs/atlascli/command/atlas-accessLogs-list.txt, docs/mongocli/command/mongocli-atlas-accessLogs-list.txt, internal/cli/atlas/accesslogs/list.go
Added an example for atlas accesslogs list command.
_Jira ticket:_ DOCSP-27556
=> DOCSP-27556 atlas accesslogs list example

Dockerfile
Update CLI container default command. Container will now run as daemon by default.
More context on how to use the container: https://docs.google.com/document/d/1CXnAY6McdwDPwvVlz_D876c20LYiBluOiLiYS_rHvc0/edit
_Jira ticket:_ [CLOUDP-189426](https://jira.mongodb.org/browse/CLOUDP-189426)
Closes [CLOUDP-189426](https://jira.mongodb.org/browse/CLOUDP-189426)
=> CLOUDP-189426: Update container default command

docs/atlascli/command/atlas-dbusers-create.txt, docs/atlascli/command/atlas-dbusers-update.txt, docs/atlascli/command/atlas-setup.txt, docs/mongocli/command/mongocli-atlas-dbusers-create.txt, docs/mongocli/command/mongocli-atlas-dbusers-update.txt, docs/mongocli/command/mongocli-cloud-manager-dbusers-create.txt, docs/mongocli/command/mongocli-ops-manager-dbusers-create.txt, internal/cli/atlas/dbusers/create.go, internal/cli/atlas/dbusers/describe.go, internal/cli/atlas/dbusers/update.go, internal/cli/atlas/setup/setup_cmd.go, internal/cli/opsmanager/dbusers/create.go, internal/flag/flags.go, internal/usage/usage.go
Clean some unused flags descriptions and correctly use some unused ones
=> docs: improve flag descriptions

docs/atlascli/command/atlas-backups-exports-buckets-create.txt, internal/usage/usage.go
Fixes typo in ianRoldId description
https://jira.mongodb.org/browse/DOCSP-31513
=> (DOCSP-31513) Removes extra 'the' in iamRoleId desc

.github/workflows/docker-release.yml
Updates the docker release pipeline to also push to quay in addition to dockerhub. (Same frequency, same tagging strategy)
Here is a test run of the updated pipeline: https://github.com/mongodb/mongodb-atlas-cli/actions/runs/5714843666/job/15482960226
_Jira ticket:_ CLOUDP-191823
Closes CLOUDP-191823
=> CLOUDP-191823: Push to quay

docs/atlascli/command/atlas-clusters-search-indexes-create.txt, docs/atlascli/command/atlas-clusters-search-indexes-update.txt, docs/mongocli/command/mongocli-atlas-clusters-search-indexes-create.txt, docs/mongocli/command/mongocli-atlas-clusters-search-indexes-update.txt, internal/usage/usage.go
Fix for search index creation is lacking crucial details by linking to the configuration file where the settings are described.
_Jira ticket:_ DOCSP-31836
=> DOCSP-31836 fix for search index creation is lacking crucial details

test/e2e/cloud_manager/agent_api_keys_test.go, test/e2e/cloud_manager/agents_test.go, test/e2e/cloud_manager/dbusers_test.go, test/e2e/cloud_manager/decryption_aws_test.go, test/e2e/cloud_manager/decryption_kmip_test.go, test/e2e/cloud_manager/decryption_localkey_test.go, test/e2e/cloud_manager/deploy_replica_set_test.go, test/e2e/cloud_manager/deploy_sharded_cluster_test.go, test/e2e/cloud_manager/feature_policies_test.go, test/e2e/cloud_manager/helper_test.go, test/e2e/cloud_manager/key_providers_test.go, test/e2e/cloud_manager/maintenance_test.go, test/e2e/cloud_manager/servers_test.go, test/e2e/iam/atlas_project_teams_test.go, test/e2e/iam/atlas_team_users_test.go, test/e2e/iam/project_teams_test.go, test/e2e/iam/team_users_test.go, test/e2e/iam/teams_test.go, test/e2e/ops_manager/version_manifest_test.go
=> CLOUDP-194833: Clean up tags

tools/genevergreen/generate/generate.go, tools/genevergreen/generate/generate_test.go
=> CLOUDP-177520: Start publishing on the server 7.0 repos

docs/atlascli/command/atlas-backups-exports-buckets-create.txt, internal/usage/usage.go
Update docs for Creating an export bucket to s3. Specifically, add link to Atlas docs where we describe how to create and retrieve Cloud Provider role access for Atlas.
_Jira ticket:_ DOCSP-31899
=> DOCSP-31899 Update docs for Creating an export bucket to s3

internal/kubernetes/operator/version/provider.go
=> fix: error message typo

internal/cli/atlas/deployments/deployments.go, internal/cli/atlas/deployments/setup.go, internal/cli/root/atlas/builder.go, internal/cli/root/atlas/builder_test.go, internal/mongosh/mongosh.go, internal/podman/client.go, internal/podman/podman.go, internal/usage/usage.go
=> CLOUDP-196139: implement atlas deployments setup command

internal/cli/atlas/backup/compliancepolicy/setup.go, internal/cli/atlas/backup/compliancepolicy/setup_test.go
Added a confirmation prompt to “atlas backups compliancepolicy setup”
_Jira ticket:_ CLOUDP-194158
=> CLOUDP-194158: Add command “atlas backups compliancepolicy setup” L3 support

CONTRIBUTING.md, Makefile
Adding script to improve manual process of updating go sdk
Context: https://jira.mongodb.org/browse/CLOUDP-196549
=> CLOUDP-196549: script for sdk updates

internal/cli/atlas/deployments/delete.go, internal/cli/atlas/deployments/deployments.go, internal/cli/atlas/deployments/options/deployment_opts.go, internal/cli/atlas/deployments/setup.go, internal/podman/client.go
Interactive
```shell
~/workplace/mongocli CLOUDP-196439 *21 ?4 ❯ atlasdev deployments delete                                                  5s  1.20 22:03:17
? Select a deployment  [Use arrows to move, type to filter, ? for more help]
> myCluster4
myCluster5
myCluster2
```
When using name, confirmation happens
```shell
~/workplace/mongocli CLOUDP-196439 *21 !3 ?7 ❯ atlasdev deployments delete myCluster3                                           11s  1.20 20:04:15
? Are you sure you want to delete: myCluster3 No
Deployment not deleted
~/workplace/mongocli CLOUDP-196439 *21 ?4 ❯ atlasdev deployments delete myCluster3                                                   1.20 20:07:08
? Are you sure you want to delete: myCluster3 (y/N) 
Error: interrupt
~/workplace/mongocli CLOUDP-196439 …
```
=> CLOUDP-196439: Add local deployment delete command

docs/atlascli/command/atlas-kubernetes-config-apply.txt, docs/atlascli/command/atlas-kubernetes-config-generate.txt, docs/atlascli/command/atlas-projects-create.txt, docs/atlascli/command/atlas-projects-settings-describe.txt, docs/atlascli/command/atlas-projects-settings-update.txt, internal/cli/atlas/kubernetes/config/apply.go, internal/cli/atlas/kubernetes/config/generate.go, internal/cli/atlas/projects/create.go, internal/cli/atlas/projects/settings/describe.go, internal/cli/atlas/projects/settings/update.go
Verify AtlasCLI Kubernetes command examples are still up-to-date with the current functionality of the CLI and if accompanying comments are accurate. In particular, to investigate
atlas kubernetes config <cmd> -h
atlas kubernetes operator <cmd> -h
Changes expected will be minor print statement changes or removal/replacement of a examples. No additional tests will be created.
Scope has been expanded to `atlas project <cmd> -h`.
If fixes are too minor to justify, this PR and the corresponding branch can be removed.
_Jira ticket:_ CLOUDP-196759
=> CLOUDP-196759: Updating Kubernetes command help examples

internal/cli/atlas/deployments/setup.go
Auto detect available port
_Jira ticket:_ CLOUDP-197639
so far on my testing, this technique is only picking [ephemeral ports](https://en.wikipedia.org/wiki/Ephemeral_port) I think in some OSs this might not be true given the port assignment happens on a syscall
=> CLOUDP-197639 Auto detect available port

docs/atlascli/command/atlas-alerts-settings-create.txt, docs/atlascli/command/atlas-alerts-settings-update.txt, internal/cli/atlas/alerts/settings/create.go, internal/cli/atlas/alerts/settings/update.go, internal/usage/usage.go, test/e2e/atlas/alert_settings_test.go
Enable file input for create/update alerts config commands
1. Create
```
▶ atlas alerts settings create --file ./alerts.json
{
"created": "2023-09-01T09:25:58Z",
"enabled": true,
"eventTypeName": "JOINED_GROUP",
"groupId": "63b6dd17362d4278259cfa25",
"id": "64f1ae26e2da796d21c80f1f",
"links": [
{
"href": "https://cloud-dev.mongodb.com/api/atlas/v2/groups/63b6dd17362d4278259cfa25/alertConfigs/64f1ae26e2da796d21c80f1f",
"rel": "self"
},
{
"href": "https://cloud-dev.mongodb.com/api/atlas/v2/groups/63b6dd17362d4278259cfa25/alertConfigs/64f1ae26e2da796d21c80f1f/alerts",
"rel": "https://cloud-dev.mongodb.com/alerts"
}
],
"notifications": [
{
"delayMin": 0,
"intervalMin": 30,
"notifierId": "64f1ae26e2da796d21c80f1e",
"typeName": "USER",
"emailEnabled": true,
"smsEnabled": false,
"username": …
```
=> CLOUDP-193639: add file support for create and update

internal/cli/atlas/deployments/options/deployment_opts.go, internal/cli/atlas/deployments/podman/client.go, internal/cli/atlas/deployments/setup.go
Switch to using new mongot-preview image
_Jira ticket:_ CLOUDP-196442
=> CLOUDP-196442 Switch to using new mongot-preview image

internal/cli/atlas/deployments/setup.go
Fix port assignment mac pop up
_Jira ticket:_ CLOUDP-198427
=> CLOUDP-198427 Fix port assignment mac pop up

internal/cli/atlas/deployments/setup.go
=> CLOUDP-198771: use fully qualified docker image names

internal/cli/atlas/deployments/podman/client.go
=> CLOUDP-198798: podman - bind to 127.0.0.1 IP only

internal/cli/atlas/deployments/delete.go, internal/cli/atlas/deployments/options/deployment_opts.go, internal/cli/atlas/deployments/options/deployment_opts_remove.go, internal/cli/atlas/deployments/options/deployment_opts_select.go, internal/cli/atlas/deployments/podman/client.go, internal/cli/atlas/deployments/setup.go
Improve UX of deployments delete command
_Jira ticket:_ CLOUDP-197659
=> CLOUDP-197659 Improve UX of deployments delete command

internal/cli/atlas/deployments/connect.go, internal/cli/atlas/deployments/deployments.go, internal/cli/atlas/deployments/deployments_test.go, internal/cli/atlas/deployments/list_test.go, internal/cli/atlas/deployments/options/deployment_opts.go, internal/cli/atlas/deployments/options/deployment_opts_connect_string.go, internal/cli/atlas/deployments/options/deployment_opts_connect_with.go, internal/cli/atlas/deployments/options/deployment_opts_select.go, internal/cli/atlas/deployments/podman/client.go, internal/cli/atlas/deployments/setup.go, internal/mocks/mock_podman.go
Add atlas deployments connect command (local only)
_Jira ticket:_ CLOUDP-196440
=> CLOUDP-196440 Add atlas deployments connect command (local only)

go.mod, go.sum, internal/cli/atlas/deployments/options/deployment_opts_connect_string.go, internal/cli/atlas/deployments/setup.go
=> CLOUDP-196391: seed replica set using the mongo driver instead of mogosh

internal/cli/atlas/deployments/list.go
=> CLOUDP-199262: update podman statuses

internal/cli/atlas/deployments/setup.go
_Jira ticket:_ CLOUDP-199630
fix NotWritablePrimary err by switching to hello command
=> CLOUDP-199630: fix NotWritablePrimary err by switching to hello command

test/e2e/iam/atlas_users_test.go
Try to reduce invite flakyness by using a bigger random number
=> test: try and reduce invite flakyness

Makefile
Improvements based on using it for  #2243
=> task: improve sdk update make target

internal/cli/atlas/deployments/search/indexes/describe.go, internal/cli/atlas/deployments/search/indexes/describe_test.go, internal/mongodbclient/search_index.go
=> CLOUDP-200157: Addressed feedback from PM

internal/cli/atlas/deployments/list.go, internal/cli/atlas/deployments/list_test.go, internal/cli/atlas/deployments/search/indexes/create.go, internal/cli/atlas/deployments/search/indexes/create_test.go, internal/cli/atlas/deployments/setup.go, test/e2e/atlas/deployments_test.go
write e2e tests for remanning deployment commands
_Jira ticket:_ CLOUDP-200170
=> CLOUDP-200170 write e2e tests for remanning deployment commands

tools/genevergreen/generate/publish.go
Fix deb publishing to publish the correct bin
=> fix: fix deb10 publishing

internal/cli/atlas/deployments/delete.go, internal/cli/atlas/deployments/options/deployment_opts_select.go, internal/cli/atlas/deployments/search/indexes/create.go, internal/cli/atlas/deployments/search/indexes/create_test.go
=> bugfix: add quick UX fixes

internal/cli/atlas/deployments/options/deployment_opts.go, internal/cli/atlas/deployments/scripts/start_mongot.sh
Update mongot image to fetch the correct link
_Jira ticket:_ CLOUDP-196443
=> CLOUDP-196443 Update mongot image to fetch the correct link

internal/cli/atlas/deployments/options/deployment_opts_select.go, internal/cli/atlas/deployments/setup.go
- fix select
- replace skip with cancel
```shell
? How do you want to setup your local MongoDB database? cancel
setup cancelled
```
=> fix: fix select and rename skip to cancel

internal/cli/atlas/deployments/setup.go, internal/cli/atlas/setup/prompt.go, internal/usage/usage.go
[CLOUDP-200479](https://jira.mongodb.org/browse/CLOUDP-200479)
=> CLOUDP-200479: Address bug squash feedback

internal/cli/root/atlas/builder.go
deployment commands should work with or without auth
_Jira ticket:_ CLOUDP-200214
=> CLOUDP-200214: deployment commands should work with or without auth

internal/cli/atlas/deployments/scripts/start_mongod.sh, internal/cli/atlas/deployments/setup.go
Bug:  we've come across a startup warning with our local deployment while using `mongosh`. Here's the warning
```bash
------
The server generated these startup warnings when booting:
2023-09-18T08:39:47.833+00:00: vm.max_map_count is too low
------
```
The issue is that `max_map_count` must be 2* `maxIncomingConnections` (the default `maxIncomingConnections ` was `419430` and the default `max_map_count` is `65530`)
This PR fixes the issue by lowering the `maxIncomingConnections` to `65530/2 = ~32200` (I discussed this value with PM). 
I tested the changes locally and the warning message is no longer there:
```bash
./bin/atlas deployments setup                                                                                                                        6m 53s  1.20  16.18.0
? …
```
=> CLOUDP-200647: [AtlasCLI] Fix vm.max_map_count is too low warning message

internal/cli/atlas/deployments/search/indexes/delete.go, internal/cli/atlas/deployments/search/indexes/describe.go, internal/cli/atlas/deployments/search/indexes/list.go
_Jira ticket:_ CLOUDP-200666
This PR addresses a PM feedback about asking for deployment name before all the other flags in the interactive mode for indexes commands
=> CLOUDP-200666: [AtlasCLI] update order questions interactive mode index commands

internal/cli/atlas/deployments/connect.go, internal/cli/atlas/deployments/delete.go, internal/cli/atlas/deployments/deployments.go, internal/cli/atlas/deployments/setup.go, internal/usage/usage.go
docs corrections based on https://github.com/mongodb/mongodb-atlas-cli/pull/2263/files
_Jira ticket:_ CLOUDP-200398
=> CLOUDP-200398: docs corrections

internal/cli/atlas/deployments/list.go, internal/cli/atlas/deployments/list_test.go, internal/cli/atlas/deployments/options/deployment_opts.go, internal/cli/atlas/deployments/search/indexes/create.go, internal/cli/atlas/deployments/search/indexes/create_test.go, internal/podman/client.go
_Jira ticket:_ [CLOUDP-200329](https://jira.mongodb.org/browse/CLOUDP-200329)
=> CLOUDP-200329: Log podman not found and continue with deployment command

LICENSING-NOTES.txt
add LICENSING-NOTES.txt
_Jira ticket:_ CLOUDP-200397
=> CLOUDP-200397: add LICENSING-NOTES.txt

internal/cli/atlas/deployments/options/deployment_opts.go, internal/cli/atlas/deployments/search/indexes/create.go, internal/cli/atlas/deployments/search/indexes/create_test.go, internal/cli/atlas/deployments/setup.go, internal/mocks/mock_mongodb_client.go, internal/mongodbclient/search_index.go
_Jira ticket:_ [CLOUDP-200720](https://jira.mongodb.org/browse/CLOUDP-200720)
1. Index creation w/ text support + index ID in output
```shell
~/workplace/mongocli CLOUDP-200720 *25 !3 ?1 ❯   atlasdev deployments search indexes create testNew  --deploymentName local5372 --db sample_mflix  --collection embedded_movies  -P oakspa                                                  1.20 17:19:42
Search index created with ID 6509c11780b2f007e6a2a0d2 
```
2. Index creation w/ json support + index ID in output
```shell
~/workplace/mongocli CLOUDP-200720 *25 !3 ?1 ❯   atlasdev deployments search indexes create testNew  --deploymentName local5372 --db sample_mflix  --collection embedded_movies                                                             1.20 17:19:51
{
"collectionName": …
```
=> CLOUDP-200720: Fix reported bugs

build/package/.atlascli.goreleaser.yml
bundle LICENSING-NOTES.txt with goreleaser
_Jira ticket:_ CLOUDP-200397
=> CLOUDP-200397: bundle LICENSING-NOTES.txt with goreleaser

internal/cli/atlas/deployments/deployments.go, internal/cli/atlas/deployments/setup.go
[CLOUDP-201110](https://jira.mongodb.org/browse/CLOUDP-201110)
=> CLOUDP-201110: Update errors

internal/cli/atlas/deployments/diagnostics.go, internal/mocks/mock_podman.go, internal/podman/client.go
Add network to diagnostics commands
_Jira ticket:_ CLOUDP-200646
=> CLOUDP-200646: Add network to diagnostics commands

docs/atlascli/command/atlas-deployments-search-indexes.txt, docs/atlascli/command/atlas-deployments-search.txt, internal/cli/atlas/deployments/search/indexes/indexes.go
CLOUDP-200398: atlas deployments - address PR comments
_Jira ticket:_ CLOUDP-200398
=> CLOUDP-200398: atlas deployments - address PR comments

test/e2e/atlas/deployments_atlas_test.go
=> Fix: fixed failing deployment cluster tests

docs/atlascli/command/atlas-deployments-pause.txt, docs/atlascli/command/atlas-deployments-search-indexes-create.txt, docs/atlascli/command/atlas-deployments-search-indexes-delete.txt, docs/atlascli/command/atlas-deployments-search-indexes-describe.txt, docs/atlascli/command/atlas-deployments-search-indexes-list.txt, docs/atlascli/command/atlas-deployments-setup.txt, docs/atlascli/command/atlas-deployments-start.txt, internal/cli/atlas/deployments/pause.go, internal/cli/atlas/deployments/search/indexes/delete.go, internal/cli/atlas/deployments/search/indexes/delete_test.go, internal/cli/atlas/deployments/search/indexes/describe.go, internal/cli/atlas/deployments/search/indexes/describe_test.go, internal/cli/atlas/deployments/search/indexes/list.go, internal/cli/atlas/deployments/search/indexes/list_test.go, internal/cli/atlas/deployments/start.go, internal/usage/usage.go, test/e2e/atlas/deployments_local_test.go
=> CLOUDP-197019: [ML4] Add logic to atlas indexes commands to include the --type flag

internal/cli/atlas/deployments/list.go, internal/cli/atlas/deployments/list_test.go, internal/cli/atlas/deployments/options/deployment_opts.go
fix deployments start/pause commands
_Jira ticket:_ CLOUDP-201520
=> CLOUDP-201520: fix deployments start/pause commands

internal/cli/atlas/deployments/list.go
_Jira ticket:_[CLOUDP-201526](https://jira.mongodb.org/browse/CLOUDP-201526)
simulating no internet connection example:
```shell
~/workplace/mongocli CLOUDP-201526 *27 ?1 ❯ atlasdev deployments list                                                                                                                                                                                              1.20 13:55:29
NAME        TYPE    MDB VER   STATE
local4944   LOCAL   7.0.1     IDLE
Error: failed to retrieve Atlas deployments with Get "https://cloud.mongodb.com/api/atlas/v2/groups/623202922f697375cac9414a/clusters?includeCount=true&includeDeletedWithRetainedBackups=false&itemsPerPage=500&pageNum=1": dial tcp: lookup cloud.mongodb.com: no such host
```
=> CLOUDP-201526: List deployments even if atlas throw errors

internal/cli/atlas/deployments/options/deployment_opts.go, internal/telemetry/event.go, internal/telemetry/event_test.go
telemetry change anonymous_id property name
_Jira ticket:_ CLOUDP-201346
=> CLOUDP-201346 telemetry change anonymous_id property

internal/cli/atlas/deployments/options/deployment_opts.go, internal/cli/atlas/deployments/scripts/start_mongot.sh, internal/cli/atlas/deployments/search/indexes/create.go, internal/cli/atlas/deployments/setup.go
Update to latest mongot image
_Jira ticket:_ CLOUDP-201542
=> CLOUDP-201542 Update to latest mongot image

build/ci/library_owners.json, go.mod, internal/cli/atlas/deployments/diagnostics.go, internal/cli/atlas/deployments/setup.go, internal/mocks/mock_podman.go, internal/podman/client.go
Update diagnostics command to use container inspect
_Jira ticket:_ CLOUDP-201543
=> CLOUDP-201543 Update diagnostics command to use container inspect

docs/atlascli/command/atlas-deployments-connect.txt, internal/cli/atlas/deployments/connect.go, internal/cli/atlas/deployments/deployments.go, internal/cli/atlas/deployments/options/connect_opts.go, internal/cli/atlas/deployments/options/connect_opts_atlas.go, internal/cli/atlas/deployments/options/connect_opts_local.go, internal/cli/atlas/deployments/options/deployment_opts.go, internal/cli/atlas/deployments/options/deployment_opts_connect_with.go, internal/cli/atlas/deployments/pause.go, internal/cli/atlas/deployments/search/indexes/create.go, internal/cli/atlas/deployments/search/indexes/delete.go, internal/cli/atlas/deployments/search/indexes/describe.go, internal/cli/atlas/deployments/search/indexes/list.go, internal/cli/atlas/deployments/setup.go, internal/cli/atlas/deployments/start.go, internal/compass/compass.go, internal/compass/compass_cmd.go, internal/compass/compass_cmd_windows.go, internal/flag/flags.go, internal/mongosh/mongosh.go, internal/search/search.go, test/e2e/atlas/deployments_atlas_test.go, test/e2e/atlas/deployments_local_test.go
implement `atlas deployments connect --type ATLAS`
_Jira ticket:_ CLOUDP-199422
=> CLOUDP-199422: deployments connect --type ATLAS

internal/cli/atlas/clusters/onlinearchive/create.go
=> CLOUDP-184650 Online Archive CLI create option should allow 3 partition fields

internal/store/store.go
AtlasCLI seg faults when missing public XOR private key
_Jira ticket:_ CLOUDP-188101
=> CLOUDP-188101 AtlasCLI seg faults when missing public XOR private key

docs/atlascli/command/atlas-deployments-delete.txt, internal/cli/atlas/deployments/delete.go, internal/cli/atlas/deployments/delete_test.go, test/e2e/atlas/deployments_atlas_test.go, test/e2e/atlas/deployments_local_test.go
implement atlas deployments delete --type ATLAS
_Jira ticket:_ CLOUDP-199629
=> CLOUDP-199629: atlas deployments delete --type ATLAS

internal/cli/atlas/deployments/connect.go, internal/cli/atlas/deployments/delete.go, internal/cli/atlas/deployments/diagnostics.go, internal/cli/atlas/deployments/list.go, internal/cli/atlas/deployments/list_test.go, internal/cli/atlas/deployments/logs.go, internal/cli/atlas/deployments/options/connect_opts_local.go, internal/cli/atlas/deployments/options/deployment_opts.go, internal/cli/atlas/deployments/options/deployment_opts_pre_run.go, internal/cli/atlas/deployments/options/deployment_opts_select.go, internal/cli/atlas/deployments/pause.go, internal/cli/atlas/deployments/search/indexes/create.go, internal/cli/atlas/deployments/search/indexes/delete.go, internal/cli/atlas/deployments/search/indexes/describe.go, internal/cli/atlas/deployments/search/indexes/list.go, internal/cli/atlas/deployments/setup.go, internal/cli/atlas/deployments/start.go, internal/cli/atlas/deployments/start_test.go, internal/cli/output_opts.go, internal/podman/client.go
_Jira ticket:_ [CLOUDP-201410](https://jira.mongodb.org/browse/CLOUDP-201410)
=> CLOUDP-201410: Display atlas and local deployments on start command

.github/workflows/code-health.yml, .tool-versions, CONTRIBUTING.md, Makefile, build/ci/evergreen.yml, build/ci/release.yml, go.mod, go.sum, internal/cli/atlas/deployments/options/deployment_opts_select.go, internal/cli/atlas/deployments/pause_test.go, internal/cli/atlas/deployments/search/indexes/create_test.go, internal/cli/opsmanager/backup/checkpoints_list_test.go, internal/cli/opsmanager/backup/restores_list_test.go, internal/cli/opsmanager/backup/snapshots/list_test.go, internal/kubernetes/operator/version/provider.go
Add support for latest golang
_Jira ticket: CLOUDP-205691
=> CLOUDP-205691: support go 1.21

build/ci/evergreen.yml, build/ci/release.yml, internal/cli/atlas/deployments/diagnostics.go, internal/cli/atlas/deployments/setup.go, tools/genevergreen/generate/generate.go, tools/genevergreen/main.go
Running local tests against multiple OS versions
_Jira ticket:_ CLOUDP-204056
=> CLOUDP-204056 Running local tests against multiple OS versions

docs/atlascli/command/atlas-deployments-connect.txt, docs/atlascli/command/atlas-deployments-start.txt, docs/atlascli/command/atlas-deployments.txt, internal/cli/atlas/deployments/connect.go, internal/cli/atlas/deployments/start.go
_Jira ticket:_[CLOUDP-205642](https://jira.mongodb.org/browse/CLOUDP-205642)
=> CLOUDP-205642: Add context for atlas deployments start command reference

docs/atlascli/command/atlas-clusters-availableRegions-list.txt, internal/cli/atlas/clusters/availableregions/list.go
=> CLOUDP-206545: Missing list in available regions example

go.mod, go.sum
=> test: fix om6.0 tests

internal/cli/atlas/search/index_opts.go, internal/mongodbclient/search_index.go, test/e2e/atlas/deployments_local_test.go
_Jira ticket:_ [CLOUDP-206159](https://jira.mongodb.org/browse/CLOUDP-206159)
Before fix
```shell
~/workp/mongocli CLOUDP-206159 *29 ?4 ❯ atlas deployments search index create --file ~/Downloads/players.json  --deploymentName local5063
? What type of deployment would you like to work with? local
Error: (UnknownError) "indexes[0].definition.analyzers[0].tokenizer" unrecognized fields ["maxgram", "mingram", "group", "pattern", "maxtokenlength"]
```
After fix
```shell
~/workp/mongocli CLOUDP-206159 *29 ?4 ❯ atlasdev deployments search index create --file ~/Downloads/players.json  --deploymentName local5063
Search index created with ID: 65326992a0eadd14b6b8c24e
```
=> CLOUDP-206159: Fix index creation formatting

internal/cli/atlas/deployments/diagnostics.go
Add `diag`, `diagnostic`and `diags` as aliases
=> Add aliases to diagnostic command

docs/atlascli/command/atlas-logs-download.txt, docs/mongocli/command/mongocli-atlas-logs-download.txt, internal/cli/atlas/deployments/logs.go, internal/cli/atlas/deployments/logs_test.go, internal/cli/atlas/logs/download.go, internal/cli/atlas/logs/download_test.go, internal/flag/flags.go, internal/mocks/mock_logs.go, internal/store/logs.go, internal/usage/usage.go
Add '--decompress' to `atlas logs download` command
_Jira ticket:_ CLOUDP-208220
=> CLOUDP-208220 Add --decompress to atlas logs download command

docs/atlascli/command/atlas-auth-login.txt, docs/atlascli/command/atlas-dbusers-update.txt, docs/atlascli/command/atlas-dbusers.txt, docs/mongocli/command/mongocli-atlas-clusters-loadSampleData.txt, docs/mongocli/command/mongocli-atlas-dbusers-update.txt, docs/mongocli/command/mongocli-atlas-dbusers.txt, docs/mongocli/command/mongocli-auth-login.txt, internal/cli/atlas/clusters/load_sample_data.go, internal/cli/atlas/dbusers/update.go, internal/cli/auth/login.go
=> Skunkworks - AtlasCLI copy and docs (Part 2)

internal/cli/atlas/setup/cluster_setup.go, internal/cli/atlas/setup/dbuser_setup.go, internal/cli/atlas/setup/prompt.go, internal/cli/atlas/setup/setup_cmd.go
[atlas setup by Corry](https://github.com/mongodb/mongodb-atlas-cli/pull/2403/commits/179ebce944c727a32afe085619cf3d04f6899869)
=> Skunkworks - AtlasCLI copy and docs (Part 3)

internal/cli/atlas/deployments/options/connect_opts.go
- swap order and ask customer to pick deployment first
```shell
~/workp/mongocli connect-flow *29 ?6 ❯ atlasdev deployments connect
? Select a deployment local6145 (Local)
? How would you like to connect to local6145? mongosh
```
=> Update order and pick cluster first

docs/atlascli/command/atlas-deployments-pause.txt, docs/atlascli/command/atlas-deployments-start.txt, docs/atlascli/command/atlas-deployments.txt, internal/cli/atlas/deployments/options/connect_opts.go, internal/cli/atlas/deployments/options/deployment_opts_pre_run.go, internal/cli/atlas/deployments/pause.go, internal/cli/atlas/deployments/start.go, internal/cli/atlas/deployments/start_test.go, internal/podman/client.go
Small fixes specially around copy for local development
=> fix: minor local dev fixes

internal/cli/atlas/logs/download.go
Fix Atlas CLI logs downloading wrong dates
_Jira ticket:_ CLOUDP-207190
=> CLOUDP-207190 Fix Atlas CLI logs downloading wrong dates

build/ci/evergreen.yml
Removing snyk task in evergreen, given we are running it twice
_Jira ticket:_ CLOUDP-205259
=> CLOUDP-205259 Removing snyk task in evergreen

docs/atlascli/command/atlas-clusters-onlineArchives-create.txt, docs/atlascli/command/atlas-clusters-onlineArchives-update.txt, docs/mongocli/command/mongocli-atlas-clusters-onlineArchives-create.txt, docs/mongocli/command/mongocli-atlas-clusters-onlineArchives-update.txt, internal/cli/atlas/clusters/onlinearchive/create.go, internal/cli/atlas/clusters/onlinearchive/update.go, internal/flag/flags.go, internal/usage/usage.go
Online Archive CLI create should allow specifying Deletion Age Limit
_Jira ticket:_ CLOUDP-207359
=> CLOUDP-207359 Online Archive CLI create should allow specifying Deletion Age Limit

build/ci/repo_config.yaml, build/package/docker/debian12-deb.Dockerfile, build/package/docker/meta/debian12-deb.Dockerfile, build/package/docker/repo/debian12.Dockerfile, tools/genevergreen/generate/generate.go, tools/genevergreen/generate/generate_test.go, tools/genevergreen/generate/publish.go, tools/release/main.go
Add arm builds for debian
_Jira ticket:_ CLOUDP-203246
=> CLOUDP-203246 Add arm builds for debian

docs/atlascli/command/atlas-accessLists-delete.txt, docs/mongocli/command/mongocli-atlas-accessLists-delete.txt, internal/cli/atlas/accesslists/delete.go
- Missed this last adjustment by Carrie
=> Update access list delete copy

test/e2e/atlas/backup_export_jobs_test.go, test/e2e/atlas/backup_snapshot_test.go, test/e2e/atlas/clusters_upgrade_test.go, test/e2e/atlas/data_federation_db_test.go, test/e2e/atlas/data_federation_query_limit_test.go, test/e2e/atlas/data_lake_pipelines_test.go, test/e2e/atlas/helper_test.go, test/e2e/atlas/kubernetes_operator_install_test.go, test/e2e/atlas/operator_helper_test.go, test/e2e/atlas/project_settings_test.go, test/e2e/atlas/setup_force_test.go
A pass on removing the old client from atlas tests
=> task: remove references to the old client from some tests

docs/atlascli/command/atlas-clusters-onlineArchives-create.txt, docs/atlascli/command/atlas-clusters-onlineArchives-update.txt, docs/atlascli/command/atlas-dataFederation-create.txt, docs/atlascli/command/atlas-dataFederation-update.txt, docs/mongocli/command/mongocli-atlas-clusters-onlineArchives-create.txt, docs/mongocli/command/mongocli-atlas-clusters-onlineArchives-update.txt, go.mod, go.sum, internal/cli/atlas/clusters/onlinearchive/create.go, internal/cli/atlas/clusters/onlinearchive/create_test.go, internal/cli/atlas/clusters/onlinearchive/update.go, internal/cli/atlas/clusters/onlinearchive/update_test.go, internal/usage/usage.go
Add file input for 'atlas clusters onlineArchives create/update'
_Jira ticket:_ CLOUDP-186624
=> CLOUDP-186624 Add file input for 'atlas clusters onlineArchives create/update'

internal/cli/default_setter_opts.go
AtlasCLI config init does not save new output format
_Jira ticket:_ CLOUDP-190027
=> CLOUDP-190027 AtlasCLI config init does not save new output format

docs/atlascli/command/atlas-serverless-create.txt, internal/cli/atlas/serverless/create.go
Fix the example for creating a serverless instance
=> docs: fix serverless create example

test/e2e/iam/atlas_users_test.go
_Jira ticket:_ CLOUDP-210604
The password we were using is no longer valid
=> CLOUDP-210604: Failed Test: mongodb-atlas-cli-master-github.com_mongodb_mongodb-atlas-cli_test_e2e_iam.TestAtlasUsers/atlas_iam_e2e/e2e_generic

internal/cli/default_setter_opts.go
Fix when intermittently orgs are not fetched
_Jira ticket:_ CLOUDP-210634
=> CLOUDP-210634: Fix when intermittently orgs were not fetched

.github/workflows/issues.yml
Fix Jira Creation, follow up from https://github.com/mongodb/mongodb-atlas-cli/pull/2451
_Jira ticket:_ CLOUDP-205862
=> CLOUDP-205862 Fix Jira Creation #2

scripts/update-sdk.sh
amend update sdk script to also update library_owners.json
=> chore: amend update sdk script to also update library_owners.json

tools/genevergreen/generate/generate.go
Enable debian 12 tests
_Jira ticket:_ CLOUDP-209440
=> CLOUDP-209440 Enable debian 12 tests

build/ci/evergreen.yml, test/e2e/atlas/atlas_e2e_test_generator_test.go, test/e2e/atlas/cleanup_test.go, test/e2e/atlas/helper_test.go
Delete protected clusters on clean up
_Jira ticket:_ CLOUDP-211540
=> CLOUDP-211540 Delete protected clusters on clean up

.github/workflows/dependabot.yml, build/ci/library_owners_jira.json
Create Jira tickets for dependabot PRs
_Jira ticket:_ CLOUDP-212931
=> CLOUDP-212931 Create Jira tickets for dependabot PRs

.github/workflows/dependabot.yml
Add checkout to dependabot's github action, follow up from https://github.com/mongodb/mongodb-atlas-cli/pull/2470
_Jira ticket:_ CLOUDP-212931
=> CLOUDP-212931 Add checkout to dependabot's github action

internal/cli/atlas/projects/list_test.go, test/e2e/atlas/alerts_test.go, test/e2e/atlas/atlas_e2e_test_generator_test.go, test/e2e/atlas/cleanup_test.go
clean up is not picking up all projects
=> fix: make clean up pick up all org projects

internal/cli/atlas/clusters/clusters.go, internal/cli/atlas/clusters/clusters_test.go, internal/cli/atlas/clusters/create.go, internal/cli/atlas/clusters/update.go, internal/cli/atlas/clusters/upgrade.go, internal/cli/atlas/setup/cluster_setup.go, internal/cli/atlas/setup/setup_cmd.go
Labels are deprecated and will be removed, doing this clean up in the CLI now
=> fix: remove usages of cluster labels

test/e2e/cloud_manager/helper_test.go
Getting only a generic error for some operations in the cloud manager tests, need the response to confirm some issues
=> tests: improve cloud manager e2e errors

internal/cli/atlas/alerts/acknowledge_test.go, internal/cli/atlas/alerts/describe.go, internal/cli/atlas/alerts/describe_test.go, internal/cli/atlas/alerts/list.go, internal/cli/atlas/alerts/list_test.go, internal/cli/atlas/alerts/settings/create_test.go, internal/cli/atlas/alerts/settings/disable_test.go, internal/cli/atlas/alerts/settings/enable_test.go, internal/cli/atlas/alerts/settings/list.go, internal/cli/atlas/alerts/settings/list_test.go, internal/cli/atlas/alerts/settings/settings.go, internal/cli/atlas/alerts/unacknowledge.go, internal/cli/atlas/alerts/unacknowledge_test.go, internal/cli/list_opts.go, internal/cli/output_opts_test.go, internal/cli/root/atlas/builder.go, internal/decryption/keyproviders/gcp.go, internal/store/logs.go, test/e2e/atlas/data_federation_db_test.go, test/e2e/atlas/kubernetes_config_apply_test.go, test/e2e/atlas/kubernetes_config_generate_test.go, test/e2e/atlas/operator_helper_test.go, test/e2e/atlas/project_settings_test.go
I'm working on consistent imports but is becoming a large PR as some modules needed fixing so splitting some of the easy no-ops changes
=> task: more consistent import alias

docs/atlascli/command/atlas-clusters-upgrade.txt, internal/cli/atlas/clusters/upgrade.go, test/e2e/atlas/clusters_m0_test.go, test/e2e/atlas/clusters_upgrade_test.go, test/e2e/atlas/helper_test.go
_Jira ticket:_ CLOUDP-217563
Allow to upgrade a shared tier to a higher shared tier
=> CLOUDP-217563: Allow to upgrade shared tiers to higher shared tiers

docs/atlascli/command/atlas-streams.txt, docs/atlascli/command/atlas.txt, internal/cli/atlas/streams/streams.go
_Jira ticket:_ CLOUDP-216773
Small copy fix
=> CLOUDP-216773: Tweak Atlas CLI for Atlas Stream Processing

test/e2e/atlas/kubernetes_config_apply_test.go, test/e2e/atlas/kubernetes_config_generate_test.go
Fixing the AKO test I broke with #2500
=> test: fix ako test

internal/telemetry/event.go, internal/telemetry/event_test.go, internal/telemetry/tracker.go
CLOUDP-216213: some telemetry fixes
- track errors for missing device_id
- correctly track authentication type for un-auth 
- start tracking disabling update alerts
=> CLOUDP-216213: [AtlasCLI] device_id is missing from some events in CLI telemetry

internal/kubernetes/operator/features/crds.go
_Jira ticket:_ [CLOUDP-207934](https://jira.mongodb.org/browse/CLOUDP-207934)
=> CLOUDP-207934: Renamed ResourceVersion label for the Atlas operator CRs

docs/atlascli/command/atlas-privateEndpoints-azure-create.txt, docs/atlascli/command/atlas-privateEndpoints-gcp-create.txt, internal/cli/atlas/privateendpoints/aws/create_test.go, internal/cli/atlas/privateendpoints/aws/describe_test.go, internal/cli/atlas/privateendpoints/aws/list_test.go, internal/cli/atlas/privateendpoints/azure/create.go, internal/cli/atlas/privateendpoints/azure/create_test.go, internal/cli/atlas/privateendpoints/azure/describe_test.go, internal/cli/atlas/privateendpoints/azure/list_test.go, internal/cli/atlas/privateendpoints/gcp/create.go, internal/cli/atlas/privateendpoints/gcp/create_test.go, internal/cli/atlas/privateendpoints/gcp/describe_test.go, internal/cli/atlas/privateendpoints/gcp/list_test.go
fix template for create azure/gcp privateEndpoints
_Jira ticket:_ CLOUDP-219151
=> CLOUDP-219151: fix template for create azure/gcp privateEndpoints

test/e2e/atlas/clusters_upgrade_test.go
_Jira ticket:_ CLOUDP-218285
Small clean up on how the upgrade tests works
=> CLOUDP-218285: Failing upgrade tests

build/ci/evergreen.yml, internal/cli/atlas/deployments/list.go, test/e2e/atlas/deployments_local_test.go
Reduce flakyness of the local deployments tests
=> tests: fix flaky local deployment test

go.mod, go.sum
Manually update dependencies that lag proper tagging (intellij did this for me)
=> task: update dependencies without tags

internal/cli/atlas/events/list.go, internal/cli/atlas/events/orgs_list.go, internal/cli/atlas/events/projects_list.go, test/e2e/atlas/events_test.go
Some tests for events were flaking and seems like we were asking for no limits when paging so fixing that
=> fix: handle pagination properly for events

atlascli.md
I found a small typo in the `Fetch source` commands in `atlascli.md`
=> fix: atlascli.md, fixed small mistake in fetch source instructions

internal/cli/atlas/commonerrors/errors.go, internal/cli/atlas/commonerrors/errors_test.go
=> CLOUDP-185092: Add Unit tests for Atlas CLI file commonerrors/errors.go

build/package/.atlascli.goreleaser.yml, build/package/.mongocli.goreleaser.yml
This PR enables [Verifiable Builds in gorelease](https://goreleaser.com/customization/verifiable_builds/). Verifiable Build is needed to use `go version -m <PATH_BINARY>` to generate the CLI SBOM.
> A [verifiable build](https://research.swtch.com/vgo-repro) is one that records enough information to be precise about exactly how to repeat it. All dependencies are loaded via proxy.golang.org, and verified against the checksum database sum.golang.org. A GoReleaser-created verifiable build will include module information in the resulting binary, which can be printed using go version -m mybinary
_Jira ticket:_ CLOUDP-227269
I released a fork of the CLI using goreleaser with Verifiable Builds enabled. Release: https://github.com/andreaangiolillo/mongocli-test/releases/tag/v1.22.24
```bash
• …
```
=> CLOUDP-227269:  Enable Verifiable Builds in gorelease

build/ci/release.yml, build/package/powershell/windows_post_package_test.ps1
Fix failed test pkg_smoke_tests_windows_atlascli
_Jira ticket:_ CLOUDP-226197
=> CLOUDP-226197 Fix failed test pkg_smoke_tests_windows_atlascli

RELEASING.md
This PR updates [RELEASING.md](https://github.com/mongodb/mongodb-atlas-cli/blob/CLOUDP-227360/RELEASING.md) to document how to generate the SBOM for AtlasCLI/MongoCLI binaries
_Jira ticket:_ CLOUDP-227360
=> CLOUDP-227360: Document how to get the AtlasCLI SBOM (container and binaries)

build/package/.atlascli.goreleaser.yml, build/package/.mongocli.goreleaser.yml
MSI is not uploaded in github releases
_Jira ticket:_ CLOUDP-228160
=> CLOUDP-228160 MSI is not uploaded in github releases

docs/atlascli/command/atlas-clusters-create.txt, internal/cli/atlas/clusters/create.go, internal/cli/atlas/clusters/create_test.go, internal/cli/watch_opts.go, internal/watchers/watcher.go
Update message for Cluster Creation Success when --watch flag is not used
_Jira ticket:_ CLOUDP-227758
=> CLOUDP-227758: Update message for Cluster Creation Success

internal/cli/atlas/backup/schedule/delete.go
CLOUDP-228453
Remove redundant prompt
=> CLOUDP-228453: [Atlas CLI] Odd prompts when deleting backup schedule

build/package/.atlascli.goreleaser.yml, build/package/.mongocli.goreleaser.yml
=> fix: disable proxy field

build/package/.atlascli.goreleaser.yml, build/package/.mongocli.goreleaser.yml
=> fix: remove glob file for signing

build/package/.atlascli.goreleaser.yml, build/package/.mongocli.goreleaser.yml
_Jira ticket:_ CLOUDP-226446
This PR adds `archives.rlcp=false` as its default value has changed in the recent gorelease release. This was preventing us from using the latest [v1.24-pro version](https://github.com/goreleaser/goreleaser-pro/releases/tag/v1.24.0-pro). As part of this PR, I have also upgraded the gorelease evergreen tasks to use the latest gorelease release.
Goreleaser tasks [Packaging MongoCLI (goreleaser)](https://evergreen.mongodb.com/task_log_raw/mongodb_atlas_cli_master_goreleaser_mongocli_snapshot_package_goreleaser_patch_71f6bd2489d0fa6fd567dc692d96da8b681082b8_65c60fb01e2d171458d3cfda_24_02_09_11_42_41/0?type=T#L350) [Packaging AtlasCLI (goreleaser)](https://evergreen.mongodb.com/task/mongodb_atlas_cli_master_goreleaser_atlascli_snapshot_package_goreleaser_patch_71f6b …
=> CLOUDP-226446: Add archives.rlcp=false to the goreleaser files

.github/workflows/docker-release.yml
This PR fixes the bugs that were discovered in the latest github action runs https://github.com/mongodb/mongodb-atlas-cli/actions/runs/7844733892
=> fix: fixed bugs in Docker release action

internal/cli/atlas/organizations/invitations/invite.go, internal/cli/atlas/projects/invitations/invite.go, internal/cli/iam/organizations/invitations/invite.go, internal/cli/iam/projects/invitations/invite.go, internal/cli/opsmanager/clusters/delete.go, tools/sdk-usage/main.go
Updating golangci-lint now flag these as invalid
=> task: correct Ids to IDs

tools/release/main.go, tools/templates-checker/astparsing/packageloading.go, tools/templates-checker/templateparsing/templateparsing.go
Fix unused params for anon functions on the tools package
=> task: fix unused args for anon functions

.github/workflows/docker-release.yml
=> fix: Fix bugs with Docker Release Github action

.github/workflows/code-health.yml, Makefile, test/e2e/atlas/atlas_e2e_test_generator_test.go, test/e2e/atlas/helper_test.go
Update to the latest golangci-lint
Some major changes include it now detects unused params in  anon funcs and better detection of ID vs Id
Additionally it includes support for go1.22
=> task: update golangci-lint to 1.56.1

.github/workflows/docker-release.yml
The security team assigned the correct permissions to our release docker user. This PR updates the release github action to use the release docker user.
=> chore: Update docker-release.yml to use the correct credentials

.github/workflows/docker-release.yml
Right now when verify the signature of the AtlasCLI docker image we get `{"identity":{"docker-reference":"index.docker.io/mongodb/apix_test"},`
```bash
COSIGN_REPOSITORY=docker.io/mongodb/signatures cosign verify --private-infrastructure --key=./atlas-cli.pem quay.io/mongodb/atlas@sha256:eac1c76ae35802162190c85197ff0003dfe1562f8765502fb42cd952faa1c0a0
Verification for quay.io/mongodb/atlas@sha256:eac1c76ae35802162190c85197ff0003dfe1562f8765502fb42cd952faa1c0a0 --
The following checks were performed on each of these signatures:
- The cosign claims were validated
- The signatures were verified against the specified public key
[{"critical":{"identity":{"docker-reference":"index.docker.io/mongodb/apix_test"},"image":{"docker-manifest-digest":"sha256:eac1c76ae35802162190c85197ff0003dfe1562f8765 …
```
=> chore: Update docker-release.yml to use the flag `--sign-container-identity`

internal/cli/atlas/search/nodes/list.go, internal/cli/atlas/search/nodes/list_test.go
=> Remarks missed in PR 2629

RELEASING.md
Amend RELEASING.md with Package Managers
_Jira ticket:_ CLOUDP-228898
=> CLOUDP-228898 Amend RELEASING.md with Package Managers

build/ci/evergreen.yml, docs/atlascli/command/atlas-clusters-search-nodes-delete.txt, internal/cli/atlas/search/nodes/create.go, internal/cli/atlas/search/nodes/delete.go, internal/cli/atlas/search/nodes/update.go, test/README.md, test/e2e/atlas/atlas_e2e_test_generator_test.go, test/e2e/atlas/helper_test.go, test/e2e/atlas/search_nodes_spec.json, test/e2e/atlas/search_nodes_spec_update.json, test/e2e/atlas/search_nodes_test.go
Added e2e tests for search nodes.
_Jira ticket:_ CLOUDP-229230
=> CLOUDP-229230: Search nodes e2e tests

internal/store/peering_connections.go, internal/store/private_endpoints.go
=> CLOUDP-229525: allow all api calls for gov

docs/atlascli/command/atlas-backups-compliancePolicy.txt, docs/atlascli/command/atlas-backups.txt, internal/cli/atlas/backup/compliancepolicy/compliancepolicy.go
Removes a line break to resolve a build error on the docs side from our submodule that pulls in the command docs.
https://jira.mongodb.org/browse/DOCSP-37140
=> (DOCSP-37140) Resolves error in rST for atlas backups command page

internal/cli/default_setter_opts.go
fix orgs selection when profile is configured
_Jira ticket:_ CLOUDP-233923
=> CLOUDP-233923: fix orgs selection when profile is configured

build/ci/release.yml, build/package/send-slack-notification.sh
Unique code path for both release and snapshot
_Jira ticket:_ CLOUDP-225725
⚠️ This might have a big impact on release since we are changing code paths, we will monitor next release to make sure code is working. ⚠️
=> CLOUDP-225725 Unique code path for both release and snapshot

tools/genevergreen/generate/generate.go
generated evergreen tasks for publishing with wrong dependency
=> fix: generated evergreen tasks for publishing with wrong dependency

build/ci/release.yml
Remove patch_optional because evergreen was not able to resolve it on git tags
_Jira ticket:_ CLOUDP-234440
=> CLOUDP-234440: Remove patch_optional because evergreen was not able to resolve it on git tags

docs/atlascli/command/atlas-integrations-create-DATADOG.txt, internal/usage/usage.go
Updates documentation for Datadog API Region selection to add Japan AP1 region
Related to this ticket: https://jira.mongodb.org/browse/CLOUDP-229909
_Jira ticket:_ [CLOUDP-234267](https://jira.mongodb.org/browse/CLOUDP-234267)
=> CLOUDP-234267: Update Atlas CLI Docs

internal/cli/atlas/logs/download.go, internal/cli/config/set.go, internal/config/profile.go, internal/file/file.go, internal/mongodbclient/search_index.go, internal/search/search.go, internal/search/search_test.go, internal/validate/validate.go, test/e2e/atlas/kubernetes_config_generate_test.go, tools/sdk-usage/main.go
Clean the search package removing an unused function and replacing string in slice with the new slices package
=> task: clean search usages

.github/workflows/docker-release.yml
Closes #2712
Corrects some typos introduced when fixing the action lint
=> fix: correct docker verification scripts

.github/workflows/docker-release.yml
=> fix: missing env for signing

internal/cli/atlas/clusters/clusters.go, internal/cli/atlas/clusters/clusters_test.go, internal/cli/atlas/logs/logs.go, internal/cli/atlas/logs/logs_test.go, internal/config/profile.go, internal/config/profile_integration_test.go
Remove MongoCLI (followup from https://github.com/mongodb/mongodb-atlas-cli/pull/2716) this should be the last step into removing MongoCLI left overs as part of fork project
_Jira ticket:_ CLOUDP-234527 
=> CLOUDP-234527 Remove MongoCLI 4th followup

docs/command/mongocli-auth-login.txt, internal/cli/auth/login.go, internal/cli/auth/login_test.go, internal/cli/auth/register_test.go
Followup on #2720, made auth login command cloud-manager only
_Jira ticket:_ CLOUDP-236358
=> CLOUDP-236358: [mongocli] Make auth login command cloud-manager only

build/package/.goreleaser.yml
=> fix: disable verifiable build for AtlasCLI

Makefile, build/ci/evergreen-generate-tasks.sh, build/ci/evergreen.yml, build/ci/release.yml, build/package/.goreleaser.yml, build/package/curator-push.sh, build/package/docker/docker-build.sh, build/package/download-win-binaries.sh, build/package/generate-download-archive-manifest.sh, build/package/generate-msi.sh, build/package/package.sh, build/package/rename-pkg.sh, build/package/send-slack-notification.sh, docs/command/mongocli-auth-login.txt, internal/cli/auth/login.go, internal/cli/auth/login_test.go, internal/cli/config/config.go, internal/cli/root/mongocli/builder.go, internal/cli/root/mongocli/builder_test.go, internal/config/profile.go, internal/latestrelease/finder.go, internal/latestrelease/finder_test.go, internal/mocks/mock_release_version.go, internal/usage/usage.go, internal/version/release_version.go, tools/genevergreen/generate/generate_test.go
Got rid of `tool_name` in MongoCLI code and CI
_Jira ticket:_ CLOUDP-236422
=> CLOUDP-236422: [mongocli] remove toolname

docs/command/atlas-organizations-apiKeys-accessLists-delete.txt, internal/cli/atlas/organizations/apikeys/accesslists/delete.go
- Updating description for "entry" in atlas-organizations-apiKeys-accessLists-delete. Since Atlas SDK escapes the value [by default,](https://github.com/mongodb/atlas-sdk-go/blob/103e85c63a7218e985cd43c25d22ffa24c6b0aac/admin/api_programmatic_api_keys.go#L1144) user is not required to use "%2F" for "/" in IP address value in case of a subnet mask.
- Refer https://www.mongodb.com/docs/atlas/cli/stable/command/atlas-organizations-apiKeys-accessLists-delete/
=> doc: Update delete documentation for entry in atlas-organizations-apiKeys-accessLists-delete

build/ci/evergreen-generate-tasks.sh, build/package/generate-msi.sh, tools/genevergreen/generate/generate.go, tools/genevergreen/generate/generate_test.go, tools/genevergreen/generate/publish.go, tools/genevergreen/main.go
Fix packing
_Jira ticket:_ CLOUDP-237136
=> CLOUDP-237136: [mongocli] fix packing

build/ci/release.yml, build/package/download-win-binaries.sh, build/package/windows_notarize.sh
Windows binaries are not signed
_Jira ticket:_ CLOUDP-238518
relates to https://github.com/mongodb/mongodb-atlas-cli/pull/2781
=> CLOUDP-238518: Windows binaries are not signed

test/e2e/atlas/deployments_atlas_test.go
fix Atlas deployments test
_Jira ticket:_ CLOUDP-240596
[Test](https://spruce.mongodb.com/task/mongodb_atlas_cli_master_e2e_atlas_deployments_atlas_deployments_atlas_clusters_e2e_patch_4e8f1bfe316caced77d0f7a5af40b4b5d9dfc5fd_660c534476a242000768fcdd_24_04_02_18_49_43/logs?execution=1)
=> CLOUDP-240596: fix Atlas deployments test

docs/command/atlas-customDbRoles-create.txt, internal/cli/customdbroles/create.go
Adds example command for creating custom role on multiple collections.
_Jira ticket:_ DOCSP-37622
=> DOCSP-37622: Add customDBRoles example for multiple collections

build/package/.goreleaser.yml
Checksum for the Atlas CLI is missing .msi for Windows
_Jira ticket:_ CLOUDP-240399
=> CLOUDP-240399 Checksum for the Atlas CLI is missing .msi for Windows

test/e2e/atlas/decryption_azure_test.go
temporarily disable azure test
_Jira ticket:_ CLOUDP-241760
=> CLOUDP-241760: temporarily disable azure test

.github/dependabot.yml
Add dependabot to mongocli-master branch
_Jira ticket:_ CLOUDP-242970
=> CLOUDP-242970 Add dependabot to mongocli-master branch

test/e2e/atlas/decryption_azure_test.go
Reverts mongodb/mongodb-atlas-cli#2844
=> Revert "CLOUDP-241760: temporarily disable azure test"

internal/kubernetes/operator/project/project.go, internal/kubernetes/operator/project/project_test.go
Use Go stdlib JSON unmarshall to avoid custom conversion of map to matcher object.
_Jira ticket:_ CLOUDP-242978
=> CLOUDP-242978: Convert matcher with json unmarshaling

internal/cli/federatedauthentication/identityprovider/create/oidc.go, test/e2e/atlas/federation_settings_test.go, test/e2e/atlas/helper_test.go, test/e2e/atlas/identity_providers_test.go
_Jira ticket:_ [CLOUDP-244265](https://jira.mongodb.org/browse/CLOUDP-244265)
=> CLOUDP-244265: Add identityProviders E2E

build/ci/release.yml
Change windows test to wait on correct dependency
_Jira ticket:_ CLOUDP-240722
=> CLOUDP-240722 Change windows test to wait on correct dependency

docs/command/atlas-federatedAuthentication-federationSettings-connectedOrgConfigs-describe.txt, docs/command/atlas-federatedAuthentication-federationSettings-connectedOrgConfigs.txt, internal/cli/federatedauthentication/federationsettings/connectedorgsconfigs/connected_orgs_configs.go, internal/cli/federatedauthentication/federationsettings/connectedorgsconfigs/describe.go, internal/cli/federatedauthentication/federationsettings/connectedorgsconfigs/describe_test.go, test/e2e/atlas/identity_providers_test.go
_Jira ticket:_ [CLOUDP-245955](https://jira.mongodb.org/browse/CLOUDP-245955)
=> CLOUDP-245955: Add describe connectedOrgConfigs command

.github/workflows/dependabot.yml, build/ci/library_owners.json
Reverts mongodb/mongodb-atlas-cli#2878
=> Revert "Fix jira ticket creation with dependabot"

docs/command/atlas-users-describe.txt, docs/command/atlas-users-invite.txt, docs/command/atlas-users.txt, internal/cli/users/describe.go, internal/cli/users/invite.go
Changes "MongoDB user" to "Atlas user" for atlas users commands
_Jira ticket:_ https://jira.mongodb.org/browse/DOCSP-38790
=> (DOCSP-38790) Changes MongoDB users to Atlas users for atlas users commands

build/ci/evergreen.yml, docs/command/atlas-dbusers-create.txt, internal/cli/dbusers/create.go, test/e2e/atlas/dbusers_test.go
_Jira ticket:_ [CLOUDP-246401](https://jira.mongodb.org/browse/CLOUDP-246401)
=> CLOUDP-246401: Add dbusers e2e test as we have IDPs now

build/package/package.sh
fixes release problem where go release detects git dirty
=> fix: fixes release problem where go release detects git dirty

build/ci/release.yml, build/package/curator-push.sh, tools/genevergreen/generate/generate.go, tools/genevergreen/generate/generate_test.go
Stop publishing to the server 4.4 repo
_Jira ticket:_ CLOUDP-247419
=> CLOUDP-247419 Stop publishing to the server 4.4 repo

build/ci/release.yml, build/package/curator-push.sh, tools/genevergreen/generate/generate.go, tools/genevergreen/generate/generate_test.go
backport #2921 into `mongocli-master`
_Jira ticket:_ CLOUDP-247419
=> CLOUDP-247419 Stop publishing to the server 4.4 repo (#2921)

docs/command/atlas-customDbRoles-create.txt, docs/command/atlas-customDbRoles-update.txt, internal/usage/usage.go
improve atlas customDbRoles create documentation: add dochub link describing the actions specific to clusters, db or collections
_Jira ticket:_ CLOUDP-249276
=> CLOUDP-249276: improve atlas customDbRoles create documentation

.github/workflows/autoupdate-sdk.yaml, .github/workflows/code-health.yml, .github/workflows/dependabot.yml, .github/workflows/docker-build-test.yml, .github/workflows/docker-release.yml, .github/workflows/issues.yml, .github/workflows/labeler.yaml, .github/workflows/stale.yml
Add https://github.com/GitHubSecurityLab/actions-permissions/tree/main/monitor to determine the least privileged roles we can give actions
=> task: add GH action permission scanner

build/ci/repo_config.yaml
=> CLOUDP-252045: Fix ubuntu version typo

build/package/docker/meta/ubuntu24.04-deb.Dockerfile, build/package/docker/repo/ubuntu24.04.Dockerfile, build/package/docker/ubuntu24.04-deb.Dockerfile
=> CLOUDP-252044: Add missing docker files

internal/cli/deployments/setup.go, internal/podman/client.go
Remove `podman machine init` & `podman machine start`
_Jira ticket:_ CLOUDP-253364
won't be needed because in linux it is not required
=> CLOUDP-253364 Remove `podman machine init` & `podman machine start`

docs/command/atlas-kubernetes-config-generate.txt, internal/kubernetes/operator/features/crds.go
This PR only enables support for the recently released AKO 2.3 and its features
_Jira ticket:_ CLOUDP-238529
=> CLOUDP-238529: CLI supports AKO 2.3.0 resources

internal/mocks/mock_podman.go, internal/podman/client.go
Removed the last networking references in the local dev commands
_Jira ticket:_ CLOUDP-253913
=> CLOUDP-253913: Remove networking completely

docs/command/atlas-federatedAuthentication-federationSettings-connectedOrgConfigs-connect.txt, docs/command/atlas-federatedAuthentication-federationSettings-connectedOrgConfigs-delete.txt, docs/command/atlas-federatedAuthentication-federationSettings-connectedOrgConfigs-describe.txt, docs/command/atlas-federatedAuthentication-federationSettings-connectedOrgConfigs-disconnect.txt, docs/command/atlas-federatedAuthentication-federationSettings-connectedOrgConfigs-list.txt, docs/command/atlas-federatedAuthentication-federationSettings-connectedOrgConfigs-update.txt, docs/command/atlas-federatedAuthentication-federationSettings-identityProvider-create-oidc.txt, docs/command/atlas-federatedAuthentication-federationSettings-identityProvider-delete.txt, docs/command/atlas-federatedAuthentication-federationSettings-identityProvider-describe.txt, docs/command/atlas-federatedAuthentication-federationSettings-identityProvider-list.txt, docs/command/atlas-federatedAuthentication-federationSettings-identityProvider-revokeJwk.txt, docs/command/atlas-federatedAuthentication-federationSettings-identityProvider-update-oidc.txt, internal/cli/federatedauthentication/federationsettings/connectedorgsconfigs/connect.go, internal/cli/federatedauthentication/federationsettings/connectedorgsconfigs/delete.go, internal/cli/federatedauthentication/federationsettings/connectedorgsconfigs/describe.go, internal/cli/federatedauthentication/federationsettings/connectedorgsconfigs/disconnect.go, internal/cli/federatedauthentication/federationsettings/connectedorgsconfigs/list.go, internal/cli/federatedauthentication/federationsettings/connectedorgsconfigs/update.go, internal/cli/federatedauthentication/federationsettings/identityprovider/create/oidc.go, internal/cli/federatedauthentication/federationsettings/identityprovider/delete.go, internal/cli/federatedauthentication/federationsettings/identityprovider/describe.go, internal/cli/federatedauthentication/federationsettings/identityprovider/list.go, internal/cli/federatedauthentication/federationsettings/identityprovider/revokejwk.go, internal/cli/federatedauthentication/federationsettings/identityprovider/update/oidc.go
_Jira ticket:_ CLOUDP-253689
- This PR updates all examples with the missing federationSettings string
=> CLOUDP-253689: Fix federated authentication examples

internal/cli/deployments/connect_test.go, internal/cli/deployments/options/deployment_opts.go, internal/cli/deployments/search/indexes/create_test.go, internal/cli/deployments/search/indexes/delete_test.go, internal/cli/deployments/search/indexes/describe_test.go, internal/cli/deployments/search/indexes/list_test.go, internal/cli/deployments/setup.go, internal/mocks/mock_podman.go, internal/podman/client.go
_Jira ticket:_ CLOUDP-253914#
Remove all volumes in setup.
Verified that everything still works (reasons why volumes were introduced):
- Close laptop lid
- Let laptop go in standby by not using it
- Restart laptop (we could also force push off)
After testing, it seems like everything seems to work perfectly in these situations.
=> CLOUDP-253914: Remove volumes

build/ci/repo_config.yaml, tools/genevergreen/generate/generate.go, tools/genevergreen/generate/generate_test.go, tools/genevergreen/generate/publish.go
Revert ubuntu publishing temporarily for the CLI publishing.
=> Revert ubuntu

internal/container/container.go, internal/container/docker.go, internal/container/podman.go
Implement docker
_Jira ticket:_ CLOUDP-252776
=> CLOUDP-252776 Implement docker

internal/container/container.go, internal/container/docker.go
Fix for list and setup, followup from https://github.com/mongodb/mongodb-atlas-cli/pull/3038
_Jira ticket:_ CLOUDP-252776
=> CLOUDP-252776 Fix for list and setup

internal/cli/deployments/setup.go
Add TOOL environment variable
_Jira ticket:_ CLOUDP-256355
=> CLOUDP-256355 Add TOOL environment variable

build/ci/evergreen.yml, internal/container/podman.go
Create local dev e2e tests for ubuntu
_Jira ticket:_ CLOUDP-253912
=> CLOUDP-253912 Create local dev e2e tests for ubuntu

docs/command/atlas-alerts-settings-create.txt, internal/cli/alerts/settings/create.go
Adds additional example for atlas alerts settings create command.
_Jira ticket:_ [DOCSP-32424](https://jira.mongodb.org/browse/DOCSP-32424)
=> DOCSP-32424 Add additional examples for atlas alerts settings create

docs/command/atlas-serverless-create.txt, docs/command/atlas-serverless-delete.txt, docs/command/atlas-serverless-describe.txt, docs/command/atlas-serverless-list.txt, internal/cli/serverless/create.go, internal/cli/serverless/delete.go, internal/cli/serverless/describe.go, internal/cli/serverless/list.go
Add examples for serverless commands: delete, describe, and list
Fixes type for serverless command: create
_Jira ticket:_ DOCSP-27553
=> DOCSP-27553 Add examples for 4 serverless commands

docs/command/atlas-dataFederation-queryLimits-create.txt, docs/command/atlas-dataFederation-queryLimits.txt, internal/cli/datafederation/querylimits/create.go
Adds Link to the ADF query limits page from the Atlas CLI
_Jira ticket:_ DOCSP-32400
=> DOCSP-32400 add Link to the ADF query limits page from the Atlas CLI docs

docs/command/atlas-privateEndpoints-gcp-delete.txt, docs/command/atlas-privateEndpoints-gcp-describe.txt, docs/command/atlas-privateEndpoints-gcp-watch.txt, internal/cli/privateendpoints/gcp/delete.go, internal/cli/privateendpoints/gcp/describe.go, internal/cli/privateendpoints/gcp/watch.go
=> DOCSP-27615: Correct atlas privateEndpoint gcp examples to use correct ID type

go.mod, go.sum, internal/mongodbclient/search_index.go
Use go-driver search index management helpers instead of createSearchIndexCommand
CLOUDP-199915
=> CLOUDP-199915: Use go-driver search index management helpers instead of createSearchIndex command

build/ci/repo_config.yaml, tools/genevergreen/generate/generate.go, tools/genevergreen/generate/generate_test.go, tools/genevergreen/generate/publish.go
This reverts commit 61be7c683ee7e291a7a89df9f76ccdedca3cbcca.
_Jira ticket:_ CLOUDP-256844
=> CLOUDP-256844: Add Ubuntu 24.04 again

build/ci/release.yml
since we're deprecating rhel70, trying to figure out if we can use the rhel80 curator ahead of time, I tiggered  release tasks but hoping to test more in waterfall
=> chore: update curator to use rhel80

internal/cli/deployments/list_test.go, internal/cli/deployments/options/deployment_opts.go, internal/cli/deployments/options/deployment_opts_select.go, internal/cli/deployments/setup.go, internal/cli/deployments/test/fixture/deployment_local.go, internal/container/docker.go, internal/podman/client.go
Use labels to list containers
_Jira ticket:_ CLOUDP-256535
=> CLOUDP-256535 Use labels to list containers

internal/cli/deployments/connect_test.go, internal/cli/deployments/delete_test.go, internal/cli/deployments/logs_test.go, internal/cli/deployments/options/deployment_opts.go, internal/cli/deployments/options/deployment_opts_select.go, internal/cli/deployments/search/indexes/create_test.go, internal/cli/deployments/search/indexes/delete_test.go, internal/cli/deployments/search/indexes/describe_test.go, internal/cli/deployments/search/indexes/list_test.go
Remove prefix mongod- from container name
_Jira ticket:_ CLOUDP-258754
=> CLOUDP-258754 Remove prefix mongod- from container name

internal/cli/backup/schedule/update.go
Add support for yearly frequencyType on --policy flag for command `atlas backup schedule update`
_Jira ticket:_ CLOUDP-259424
=> CLOUDP-259424 Add support for yearly frequencyType on --policy flag for command `atlas backup schedule update`

build/ci/release.yml
This reverts commit 6c5e239718cd1eb3c09eb4725eb35a1d72b39620.
Reverts this commit as curator is giving a setup failure for all snapshot tests
=> Revert "chore: update curator to use rhel80 (#3062)"

test/e2e/atlas/search_test.go
=> CLOUDP-261049: Fix search e2e tests

build/ci/evergreen.yml
Enable local dev tests in waterfall
=> Enable local dev tests in waterfall

build/ci/release.yml, build/package/docker/meta/docker-build.sh, tools/genevergreen/generate/generate.go, tools/genevergreen/generate/generate_test.go, tools/genevergreen/generate/publish.go
=> CLOUDP-259391: Fix meta package

build/package/.goreleaser.yml, build/package/package.sh
_Jira ticket:_ CLOUDP-252760
- To test my changes, i need to update `goreleaser_pro_tar_gz` in our project settings. To use the tar file generated in https://github.com/goreleaser/goreleaser/releases v2.0.1 
- Changed from https://github.com/goreleaser/goreleaser-pro/releases/download/v1.24.0-pro/goreleaser-pro_Linux_x86_64.tar.gz to https://github.com/goreleaser/goreleaser-pro/releases/download/v2.0.1-pro/goreleaser-pro_Linux_x86_64.tar.gz
=> CLOUDP-252760: Upgrade goreleaser version

internal/cli/deployments/setup.go, internal/cli/deployments/setup_test.go
Always pull the latest version of the unified docker image
_Jira ticket:_ CLOUDP-207842
=> CLOUDP-207842: [AtlasCLI] default new deployments to pick latest MongoDB version

go.mod
Update the go version to avoid possible snyk tickets
This is mostly symbolic since packaging will always be done with the latest available `go` in evg but snyk checks this file so better make it happy
=> task: update go version in go.mod

Makefile
The Makefile lacked a target for the `install` command, resulting in an error when running make install (`Nothing to be done for install`). This PR addresses and resolves that issue.
_Jira ticket:_ CLOUDP-262479
Closes #[CLOUDP-262479]
=> CLOUDP-262479: Missing target for install in the makefile

.github/CODEOWNERS
=> CLOUDP-260974: update codeowners to apix2

internal/cli/deployments/options/deployment_opts_pre_run.go
=> CLOUDP-262690: remove OS deprecation message on windows

cmd/atlas/atlas.go
- remove unnecessary createConfig() function from main
_Jira ticket:_ CLOUDP-262817
=> CLOUDP-262817: Remove createConfig from main

build/ci/evergreen.yml, internal/cli/plugin/install.go, internal/cli/plugin/plugin_asset.go, test/e2e/atlas/plugin_install_test.go
- Add integration tests for `plugin install`
_Jira ticket:_ CLOUDP-264043
=> CLOUDP-264043: Integration tests for plugin install command

internal/cli/plugin/install.go, internal/cli/plugin/plugin_asset.go, internal/cli/plugin/plugin_asset_test.go
- refactor plugin asset commands
- use regex to parse command line arg
_Jira ticket:_ CLOUDP-264335
=> CLOUDP-264335: refactor asset functions

build/ci/evergreen.yml, test/e2e/atlas/plugin_install_test.go, test/e2e/atlas/plugin_run_test.go
- e2e tests for plugin run command
_Jira ticket:_ CLOUDP-264833
=> CLOUDP-264833: e2e tests for plugin run command

.github/CODEOWNERS
_Jira ticket:_ CLOUDP-260974
backport 7b91ed31858eb51348fde070c6b059de7e8384d0
=> CLOUDP-260974: backport 7b91ed31858eb51348fde070c6b059de7e8384d0

build/ci/evergreen.yml, docs/command/atlas-plugin-install.txt, docs/command/atlas-plugin-uninstall.txt, docs/command/atlas-plugin.txt, internal/cli/plugin/install.go, internal/cli/plugin/install_test.go, internal/cli/plugin/list.go, internal/cli/plugin/list_test.go, internal/cli/plugin/plugin.go, internal/cli/plugin/plugin_test.go, internal/cli/plugin/uninstall.go, internal/cli/plugin/uninstall_test.go, internal/plugin/plugin.go, internal/plugin/plugin_manifest.go, internal/plugin/plugin_manifest_test.go, internal/plugin/plugin_test.go, test/e2e/atlas/plugin_install_test.go, test/e2e/atlas/plugin_uninstall_test.go
- Create plugin uninstall command
- e2e tests for uninstall command
- Add validation to plugin discovery functionality to make sure there is all loaded plugins names are unique
- ensure a plugin can only be installed if there is not any plugin with the same name
_Jira ticket:_ CLOUDP-260775
=> CLOUDP-260775: Plugin uninstall command

internal/cli/plugin/list.go
- Fix plugin list template
_Jira ticket:_ CLOUDP-266017
=> CLOUDP-266017: Fix plugin list template

test/e2e/atlas/streams_test.go
consider default sample_stream_solar streams connection in e2e test
_Jira ticket:_ CLOUDP-266119
=> CLOUDP-266119: consider default sample_stream_solar streams connection in e2e test

build/ci/evergreen.yml, internal/cli/plugin/plugin.go, internal/cli/plugin/plugin_github_asset.go, internal/cli/plugin/plugin_github_asset_test.go, internal/cli/plugin/update.go, internal/cli/plugin/update_test.go, test/e2e/atlas/helper_test.go, test/e2e/atlas/plugin_install_test.go, test/e2e/atlas/plugin_uninstall_test.go, test/e2e/atlas/plugin_update_test.go
- e2e tests for plugin update command
- added ability to add version to update command
_Jira ticket:_ CLOUDP-266340
=> CLOUDP-266340: e2e tests for plugin update command

build/ci/evergreen.yml, build/ci/evergreen_common.yml, build/ci/periodic_build.yml
Move Local Deployment RHEL tests to be in a periodic build
_Jira ticket:_ CLOUDP-265391
=> CLOUDP-265391 Move Local Deployment RHEL tests to be in a periodic build

build/ci/evergreen.yml, build/ci/evergreen_common.yml, build/ci/periodic_build.yml
fix dependencies on periodic builds followup from https://github.com/mongodb/mongodb-atlas-cli/pull/3167
_Jira ticket:_ CLOUDP-265391
=> CLOUDP-265391: fix dependencies on periodic builds

build/ci/evergreen.yml, build/ci/evergreen_common.yml, build/ci/periodic_build.yml
Add LocalDev MacOS Tests
_Jira ticket:_ CLOUDP-265392
=> CLOUDP-265392: Add LocalDev MacOS Tests

build/ci/evergreen.yml, build/ci/evergreen_common.yml, build/ci/packer/setup0.ps1, build/ci/packer/setup1.ps1, build/ci/packer/setup2.ps1, build/ci/packer/windows-10-azure.pkr.hcl, build/ci/packer/windows-11-azure.pkr.hcl, build/ci/periodic_build.yml
Create Image job to Build Windows VM Image
_Jira ticket:_ CLOUDP-265393
=> CLOUDP-265393 Create Image job to Build Windows VM Image

tools/genevergreen/generate/generate.go
Reenable Meta package tests
_Jira ticket:_ CLOUDP-261224
=> CLOUDP-261224 Reenable Meta package tests

internal/cli/deployments/search/indexes/create.go, internal/cli/deployments/search/indexes/describe.go, internal/cli/search/create.go, internal/cli/search/describe.go, internal/cli/search/update.go, internal/telemetry/event.go, internal/telemetry/event_test.go
Add Index Type to telemetry
_Jira ticket:_ CLOUDP-263189
=> CLOUDP-263189 Add Index Type to telemetry

test/e2e/atlas/kubernetes_config_generate_test.go
=> CLOUDP-266545: Add sample stream to k8s test expected output

internal/cli/deployments/setup.go, internal/container/docker.go
Add more logs to atlas deployments setup
_Jira ticket:_ CLOUDP-267966
=> CLOUDP-267966 Add more logs to atlas deployments setup

internal/container/docker.go
Add more logs to atlas deployments setup (followup from #3189)
_Jira ticket:_ CLOUDP-267966
=> CLOUDP-267966 Add more logs to atlas deployments setup (step 2)

internal/plugin/plugin_manifest.go
- Fix bug with missing binary field in manifest file
_Jira ticket:_ CLOUDP-222047
=> CLOUDP-268544: Fix bug with missing binary field in manifest file

internal/podman/client.go
fix for something small I've overlooked
=> podman, add hostport to portmapping

CONTRIBUTING.md
=> CLDOUP-267116: Reference example plugin in CONTRIBUTING.md

build/ci/evergreen_common.yml, internal/container/docker.go, internal/container/docker_test.go, test/e2e/atlas/deployments_local_nocli_test.go
Add new test to manage containers created outside of cli
_Jira ticket:_ CLOUDP-265398
=> CLOUDP-265398 Add new test to manage containers created outside of cli

test/e2e/atlas/streams_test.go
=> CLOUDP-268741: Remove test for solar as now it is no longer default

test/e2e/atlas/kubernetes_config_generate_test.go
Remove changes from https://github.com/mongodb/mongodb-atlas-cli/pull/3168, as the sample stream is no longer added by default.
=> CLOUDP-266545: Remove sample stream from k8s test expected output

test/e2e/atlas/atlas_e2e_test_generator_test.go, test/e2e/atlas/cleanup_test.go, test/e2e/atlas/kubernetes_operator_install_test.go
=> CLOUDP-265086: Add PAK deletion to cleanup

internal/plugin/plugin.go
redirect `--help`/`-h` to plugin, instead of handling it in cobra
_Jira ticket:_ CLOUDP-269579
=> Fix issue when passing arguments

docs/command/atlas-accessLogs-list.txt, internal/cli/accesslogs/list.go
Small doc improvement based on feedback
=> docs: improve flag docs for access logs

build/ci/evergreen.yml
Add macOS 13 localdev tests
_Jira ticket:_ CLOUDP-270486
=> CLOUDP-270486 Add macOS 13 localdev tests

build/ci/evergreen.yml
fix for localdev windows tests are not running
=> fix: localdev windows tests are not running

.github/workflows/code-health.yml, .golangci.yml, Makefile, docs/command/atlas-clusters-create.txt, docs/command/atlas-clusters-delete.txt, docs/command/atlas-clusters-search-nodes-create.txt, docs/command/atlas-clusters-search-nodes-delete.txt, docs/command/atlas-clusters-search-nodes-update.txt, docs/command/atlas-deployments-delete.txt, docs/command/atlas-deployments-search-indexes-create.txt, internal/cli/clusters/create.go, internal/cli/clusters/delete.go, internal/cli/deployments/delete.go, internal/cli/deployments/search/indexes/create.go, internal/cli/plugin/plugin_github_asset.go, internal/cli/root/builder_test.go, internal/cli/search/nodes/create.go, internal/cli/search/nodes/delete.go, internal/cli/search/nodes/update.go, internal/cli/watch_opts.go, internal/config/profile_test.go, test/e2e/cli.go
updated golangci-lint to 1.60.3 and fixed new lintintg errors
_Jira ticket:_ CLOUDP-271289
=> CLOUDP-271289: updated golangci-lint to 1.60.3 and fixed new lintintg errors

build/ci/evergreen.yml, internal/compass/compass_bin_windows.go, internal/container/docker.go, internal/mongosh/mongosh.go, internal/podman/client.go, test/e2e/atlas/deployments_local_nocli_test.go, test/e2e/helper.go
Local Atlas Experience with AtlasCLI is stable and covered with E2E on Ubuntu, Debian, RHEL
_Jira ticket:_ CLOUDP-263619
=> CLOUDP-263619 Local Atlas Experience with AtlasCLI is stable and covered with E2E on Ubuntu, Debian, RHEL

build/ci/evergreen.yml
Followup from https://github.com/mongodb/mongodb-atlas-cli/pull/3235 adding Amazon Linux 2023 to localdev tests
_Jira ticket:_ CLOUDP-263619
=> CLOUDP-263619 Add Amazon Linux 2023 to localdev tests

docs/command/atlas-deployments-setup.txt, internal/cli/deployments/setup.go
Add link to docs for 'atlas deployments setup' command
_Jira ticket:_ CLOUDP-269647
=> CLOUDP-269647: Add link to docs for 'atlas deployments setup' command

internal/cli/deployments/diagnostics.go, internal/container/container.go, internal/container/docker.go, internal/container/docker_test.go, internal/container/podman.go, internal/podman/client.go
Update atlas diagnostics command to add more information
_Jira ticket:_ CLOUDP-268554
=> CLOUDP-268554 Update atlas diagnostics command to add more information

internal/cli/deployments/diagnostics.go, internal/container/docker.go
Followup from https://github.com/mongodb/mongodb-atlas-cli/pull/3240 fix atlas deployments inspect errors not showing up
_Jira ticket:_ CLOUDP-268554
=> CLOUDP-268554 Fix atlas deployments inspect errors not showing up

.github/CODEOWNERS, .github/dependabot.yml, .github/workflows/dependabot.yml
mongocli dependabot PR ticket creation is failing (sample PR https://github.com/mongodb/mongodb-atlas-cli/pull/3222)
=> fix: mongocli dependabot PR ticket creation

.github/workflows/dependabot.yml
fix atlascli dependabot PR ticket creation (sample PR https://github.com/mongodb/mongodb-atlas-cli/pull/3247)
=> fix: atlascli dependabot PR ticket creation

docs/command/atlas-deployments-logs.txt, docs/command/atlas-logs-download.txt, docs/command/atlas-streams-instances-download.txt, internal/usage/usage.go
=> CLOUDP-272621: Update log downloads docs

build/ci/evergreen.yml
fix localdev windows tests not running
=> fix: localdev windows tests not running

test/e2e/atlas/deployments_local_auth_test.go, test/e2e/atlas/deployments_local_noauth_test.go, test/e2e/atlas/deployments_local_nocli_test.go
localdev tests are broken they're expecting wrong mdb version
=> fix: localdev tests expecting wrong mdb version

build/ci/evergreen.yml
localdev tasks are stuck waiting for compile which was never scheduled in our periodic build
=> fix: localdev tasks stuck

build/ci/evergreen.yml
followup from https://github.com/mongodb/mongodb-atlas-cli/pull/3267 fixing ubuntu
=> fix: localdev tasks stuck fix for ubuntu

internal/cli/deployments/start.go, internal/cli/deployments/start_test.go
Only show containers that can be started when running `atlas deployments start`
_Jira ticket:_ CLOUDP-275225
=> CLOUDP-275225 Only show containers that can be started when running `atlas deployments start`

docs/command/atlas-dbusers-create.txt, docs/command/atlas-dbusers-update.txt, internal/usage/usage.go
=> updates for ADL september release

internal/cli/deployments/options/deployment_opts_pre_run.go, internal/cli/deployments/search/indexes/list.go
"atlas deployments search index describe" fails with unclear error message when local deployment is paused
_Jira ticket:_ CLOUDP-273727
=> CLOUDP-273727 "atlas deployments search index describe" fails with unclear error message when local deployment is paused

internal/cli/deployments/connect.go, internal/cli/deployments/search/indexes/create.go, internal/cli/deployments/search/indexes/delete.go, internal/cli/deployments/search/indexes/describe.go
Followup from https://github.com/mongodb/mongodb-atlas-cli/pull/3284 more commands fail with unclear error message when local deployment is paused
_Jira ticket:_ CLOUDP-273727
=> CLOUDP-273727 More commands fail with unclear error message when local deployment is paused

.github/workflows/code-health.yml, Makefile, build/ci/evergreen.yml, build/ci/release.yml, go.mod, internal/decryption/log_record.go
=> task: update go version

internal/cli/dbusers/create.go
=> fix: fix variable shadowing

internal/cli/auth/whoami.go, internal/cli/auth/whoami_test.go
improve whoami err message
_Jira ticket:_ CLOUDP-276968
=> CLOUDP-276968: improve whoami err message

internal/cli/clusters/upgrade.go
"atlas clusters upgrade" does not enforce mandatory params
_Jira ticket:_ CLOUDP-276465
=> CLOUDP-276465 "atlas clusters upgrade" does not enforce mandatory params

.github/dependabot.yml, .github/labeler.yaml
set @mongodb/enterprise-advanced as dependabot pr reviewers, add a mongocli label on prs
=> chore: set @mongodb/enterprise-advanced as dependabot pr reviewers

.github/CODEOWNERS
add @mongodb/enterprise-advanced as code owners
=> chore: add @mongodb/enterprise-advanced as code owners

build/ci/evergreen.yml, test/e2e/atlas/cleanup_test.go, test/e2e/atlas/federation_settings_test.go, test/e2e/atlas/helper_test.go
Remove IDPs on cleanup script
_Jira ticket:_ CLOUDP-272605
=> CLOUDP-272605 Remove IDPs on cleanup script

.github/labeler.yaml, .github/workflows/labeler.yaml
update labeler for mongocli
followup from https://github.com/mongodb/mongodb-atlas-cli/pull/3316
=> chore: update labeler mongocli

test/e2e/atlas/clusters_file_test.go
_Jira ticket:_ CLOUDP-272716
Closes #CLOUDP-272716
Will fix this issue in CLOUDP-280777 which was filed as followup
=> CLOUDP-272716: Ignore flaky rolling index test from api

.github/labeler.yaml
Add atlascli label, so we can filer for slack notifications
_Jira ticket:_ CLOUDP-279508
similar to https://github.com/mongodb/mongodb-atlas-cli/pull/3331
=> CLOUDP-279508 Add atlascli label

internal/cli/deployments/options/deployment_opts.go, internal/cli/deployments/options/deployment_opts_telemetry.go, internal/cli/deployments/test/fixture/deployment_local.go, internal/telemetry/event.go, internal/telemetry/event_test.go
extend atlascli telemetry to use localdev image uuid
_Jira ticket:_ CLOUDP-280735
=> CLOUDP-280735 extend atlascli telemetry to use localdev image uuid

docs/command/atlas-teams-users-add.txt, internal/cli/teams/users/add.go
Updates description for `atlas teams users add` to include users who have received an invite to an org.
_Jira ticket:_ [DOCSP-43241](https://jira.mongodb.org/browse/DOCSP-43241)
=> (DOCSP-43241) Updates teams description to include pending users.

internal/cli/deployments/search/indexes/create.go, internal/cli/deployments/search/indexes/create_test.go, internal/cli/deployments/search/indexes/delete.go, internal/cli/deployments/search/indexes/delete_test.go, internal/cli/deployments/search/indexes/describe.go, internal/cli/deployments/search/indexes/describe_test.go, internal/cli/deployments/search/indexes/list.go, internal/cli/deployments/search/indexes/list_test.go, internal/cli/deployments/setup.go, internal/mocks/mock_mongodb_client.go, internal/mongodbclient/client.go, internal/mongodbclient/collection.go
Fix context implementation on mongodbclient
_Jira ticket:_ CLOUDP-283326
=> CLOUDP-283326 Fix context implementation on mongodbclient

internal/cli/deployments/search/indexes/create.go, internal/cli/search/index_opts.go
"atlas deployments search index create --watch" does not watch on correct index
_Jira ticket:_ CLOUDP-283508
followup from https://github.com/mongodb/mongodb-atlas-cli/pull/3376
=> CLOUDP-283508 "atlas deployments search index create --watch" does not watch on correct index

internal/cli/deployments/search/indexes/create.go, internal/cli/deployments/search/indexes/create_test.go, internal/cli/deployments/search/indexes/delete.go, internal/cli/deployments/search/indexes/delete_test.go, internal/cli/deployments/search/indexes/describe.go, internal/cli/deployments/search/indexes/describe_test.go, internal/cli/deployments/search/indexes/list_test.go, internal/mocks/mock_mongodb_client.go, internal/mongodbclient/client.go, internal/mongodbclient/collection.go, internal/mongodbclient/database.go
Remove `admin.ClusterSearchIndex` from `internal/mongodbclient`
_Jira ticket:_ CLOUDP-283328
followup from https://github.com/mongodb/mongodb-atlas-cli/pull/3377
=> CLOUDP-283328 Remove admin.ClusterSearchIndex from internal/mongodbclient

build/package/docker/amazonlinux2023-rpm.Dockerfile, build/package/docker/centos8-rpm.Dockerfile, build/package/docker/debian11-deb.Dockerfile, build/package/docker/debian12-deb.Dockerfile, build/package/docker/meta/amazonlinux2023-rpm.Dockerfile, build/package/docker/meta/centos8-rpm.Dockerfile, build/package/docker/meta/debian11-deb.Dockerfile, build/package/docker/meta/debian12-deb.Dockerfile, build/package/docker/meta/ubuntu20.04-deb.Dockerfile, build/package/docker/meta/ubuntu22.04-deb.Dockerfile, build/package/docker/meta/ubuntu24.04-deb.Dockerfile, build/package/docker/repo/amazonlinux2023.Dockerfile, build/package/docker/repo/centos8.Dockerfile, build/package/docker/repo/debian11.Dockerfile, build/package/docker/repo/debian12.Dockerfile, build/package/docker/repo/ubuntu20.04.Dockerfile, build/package/docker/repo/ubuntu22.04.Dockerfile, build/package/docker/repo/ubuntu24.04.Dockerfile, build/package/docker/ubuntu20.04-deb.Dockerfile, build/package/docker/ubuntu22.04-deb.Dockerfile, build/package/docker/ubuntu24.04-deb.Dockerfile
Fix post package tests failure
_Jira ticket:_ CLOUDP-284804
=> CLOUDP-284804 Fix post package tests failure

build/package/docker/meta/suse15-rpm.Dockerfile, build/package/docker/repo/suse15-rpm.Dockerfile, build/package/docker/suse15-rpm.Dockerfile, tools/genevergreen/generate/generate.go, tools/genevergreen/generate/generate_test.go, tools/genevergreen/generate/publish.go
publish RPMs to SUSE zypper repo
_Jira ticket:_ CLOUDP-282817
=> CLOUDP-282817 publish RPMs to SUSE zypper repo

build/ci/terraform/.terraform.lock.hcl, build/ci/terraform/main.tf
Fix localdev windows tests are getting out of sync
_Jira ticket:_ CLOUDP-284788
=> CLOUDP-284788: Fix localdev windows tests are getting out of sync

internal/cli/setup/confirm_default_setup.go, internal/cli/setup/prompt.go, internal/cli/setup/setup_cmd.go
Update the atlas setup to mimic atlas deployments setup
_Jira ticket:_ CLOUDP-153329
https://github.com/user-attachments/assets/1cf2ae7a-fca7-49d2-8335-7cec6e6fdb40
=> CLOUDP-153329 Update the atlas setup to mimic atlas deployments setup

Makefile
=> Flyby: Make COVERAGE configurable

cmd/atlas/atlas_test.go
this is adding main function to our unit tests, which basically confirms that our codebase compiles properly
=> chore: test main

cmd/atlas/atlas_test.go
followup from https://github.com/mongodb/mongodb-atlas-cli/pull/3430
=> chore: add unit tag to TestMain

internal/cli/clusters/clusters.go, internal/cli/clusters/create.go, internal/cli/clusters/create_test.go, internal/cli/clusters/describe.go, internal/watchers/flex_cluster.go
_Jira ticket:_ CLOUDP-285941
<details>
<summary>Dedicated Cluster </summary>
```bash
./bin/atlas cluster create Test22 --provider AWS --region US_EAST_1 -P prod
Cluster 'Test22' is being created
```
</details>
<details>
<summary>Flex Cluster </summary>
```bash
./bin/atlas cluster create FlexClusterTest --provider AWS --region US_EAST_1 --tier FLEX -P prod
Cluster 'FlexClusterTest' is being created
```
```json
./bin/atlas cluster create FlexClusterTest2 --provider AWS --region US_EAST_1 -P prod --tier FLEX -o json                              
{
"backupSettings": {
"enabled": true
},
"clusterType": "REPLICASET",
"connectionStrings": {},
"createDate": "2024-11-28T16:00:09Z",
"groupId": "663268874ddd3b236fd2f107",
"id": "67489389a5b2f94a614cf079",
"mongoDBVersion": "8.0.3",
"name": …
```
=> CLOUDP-285941: Add the command "Atlas Cluster Flex Create"

build/ci/evergreen.yml
https://github.com/mongodb/mongodb-atlas-cli/pull/3425 broke our periodic builds
=> fix: periodic builds not running

CONTRIBUTING.md
* Change to debug configuration example from `atlas login` to `atlas dbuser create [...]` to show how to deal with multiple args and flags.
* Rewords environment setup section for clarity and readability.
* Adds minor grammar corrections.
=> chore: Minor improvements to CONTRIBUTING.md

.github/workflows/code-health.yml
update code-coverage to use apix-bot and make sticky comments
=> chore: update code-coverage to use apix-bot and make sticky comments

internal/cli/performance_advisor_opts.go, internal/cli/performanceadvisor/namespaces/list.go, internal/cli/performanceadvisor/slowquerylogs/list.go, internal/cli/performanceadvisor/suggestedindexes/list.go
Consolidate cli.PerformanceAdvisorOpts flags
_Jira ticket:_ CLOUDP-287349
=> CLOUDP-287349 Consolidate cli.PerformanceAdvisorOpts flags

internal/compass/compass.go
Atlas CLI shows error message when connecting to deployment through Compass
_Jira ticket:_ CLOUDP-288455
Initially we had a logic to wait for up to 10 seconds to check if compass pid had been closed or not if so return an error. I removed that logic as sometimes in Windows the pid we get is not waiting or being replaced by another pid.
=> CLOUDP-288455 Atlas CLI shows error message when connecting to deployment through Compass

internal/cli/metrics/databases/describe.go
followup from https://github.com/mongodb/mongodb-atlas-cli/pull/3465, compilation is broken
=> fix: compile

internal/telemetry/event.go, internal/telemetry/event_test.go, internal/telemetry/tracker.go
Include the output format in the telemetry information
=> feat: include output format in telemetry

build/package/docker/repo/suse15.Dockerfile
Fix suse15 tests
_Jira ticket:_ CLOUDP-290831
=> CLOUDP-290831 Fix suse15 tests

build/ci/evergreen.yml, build/ci/snyk.yml
Added Snyk evergreen task.
Succesful (manual) run: https://app.snyk.io/org/dev-prod/project/4a92d3e3-9610-4c57-b8a2-9a06ca90b105/history/b22625da-6cd7-494c-a8de-69c3f4308a19
_Jira ticket:_ CLOUDP-284785
=> CLOUDP-284785: Migrate to Snyk CLI

internal/cli/clusters/delete.go
_Jira ticket:_ CLOUDP-287238
```bash
/bin/atlas cluster delete FlexCluster2222 --force --watch -P prod                                                    
Cluster deleted
```
=> CLOUDP-287238: Added watch logic to the `cluster delete command`

build/ci/evergreen.yml
- Added allowed_requesters
- formatting
- build variant rename
_Jira ticket:_ CLOUDP-284785
=> CLOUDP-284785: Snyk CLI: added allowed_requesters

internal/cli/api/api.go
- change `--format` to `--output`
- because of this: change `--output` to `--output-file`
Had to rename some variable from `flag` to something else because of the new import.
_Jira ticket:_ CLOUDP-290334
=> CLOUDP-290334: change --format to --output

internal/cli/api/profile.go, internal/config/profile.go
Add support to save a default api version to user profile
_Jira ticket:_ CLOUDP-288002
=> CLOUDP-288002: Add support to save a default api version to user profile

internal/cli/privateendpoints/aws/interfaces/describe.go, internal/cli/privateendpoints/aws/interfaces/describe_test.go, internal/cli/privateendpoints/azure/interfaces/describe.go, internal/cli/privateendpoints/azure/interfaces/describe_test.go, internal/cli/privateendpoints/gcp/interfaces/describe.go, internal/cli/privateendpoints/gcp/interfaces/describe_test.go, internal/kubernetes/operator/project/privateendpoints.go, internal/kubernetes/operator/project/privateendpoints_test.go, internal/store/private_endpoints.go
=> chore: Fix private endpoints command

docs/command/atlas-clusters-create.txt, internal/cli/clusters/create.go
=> CLOUDP-293595: add flex cluster example to the `atlas cluster create` command

build/ci/evergreen.yml, test/e2e/atlas/search_test.go
Wait for load sample data
_Jira ticket:_ CLOUDP-294676
=> CLOUDP-294676 Wait for load sample data

internal/cli/root/builder.go
- Updated help template to use both Short and Long descriptions
_Jira ticket:_ CLOUDP-294403
=> CLOUDP-294403: [AtlasCLI] incomplete --help for commands

docs/command/atlas-federatedAuthentication-federationSettings-identityProvider-create-oidc.txt, docs/command/atlas-federatedAuthentication-federationSettings-identityProvider-update-oidc.txt, internal/usage/usage.go
Updates values for `--authorizationType` to [match API](https://www.mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/Federated-Authentication/operation/createIdentityProvider) and examples. 
_Jira ticket:_ [DOCSP-45105](https://jira.mongodb.org/browse/DOCSP-45105)
=> (DOCSP-45105) Updates option to match API.

.github/dependabot.yml
Set up dependabot to update all of otel together
=> chore (deps): dependabot update otel together

internal/cli/deployments/options/deployment_opts.go
Addressing https://github.com/mongodb/mongodb-atlas-cli/pull/3575#discussion_r1930902881
=> Drop manual env variable check

tools/api-generator/convert.go, tools/api-generator/fixtures/04-spec-with-overrides.yaml
Change syntax of overrides based on spec update
_Jira ticket:_ CLOUDP-297778
=> CLOUDP-297778 Change syntax of overrides based on spec update

internal/cli/api/api.go, internal/cli/api/flags.go, tools/api-generator/convert.go, tools/api-generator/fixtures/06-spec-with-cli-specific-extensions.yaml
Apply cli specific extensions into generated commands
_Jira ticket:_ CLOUDP-297408
=> CLOUDP-297408 Apply cli specific extensions into generated commands

internal/api/api.go, tools/api-generator/.snapshots/04-spec-with-overrides.yaml.snapshot, tools/api-generator/commands.go.tmpl, tools/api-generator/watcher.go, tools/api-generator/watcher_test.go
Use int for HTTPCode instead of string
_Jira ticket:_ CLOUDP-299213
=> CLOUDP-299213: Use int for HTTPCode instead of string

internal/plugin/plugin.go, internal/telemetry/event.go, internal/telemetry/tracker.go
=> CLOUDP-297225: Add event types

internal/cli/api/api.go, internal/cli/api/watcher.go
- Add `--watcherTimeout` flag where needed
- Update `cli.Watcher` to support timeouts
_Jira ticket:_ CLOUDP-297412
=> CLOUDP-297412: Add --watchTimeout support

.github/workflows/autoupdate-spec.yaml, tools/api-generator/overlays/watchers.yaml
Annotate current watchers
_Jira ticket:_ CLOUDP-297413
Watchers that were not added:
- `/api/atlas/v2/groups/{groupId}/serverless/{clusterName}/backup/restoreJobs` apis: complexity on evaluation ([ref](https://github.com/mongodb/mongodb-atlas-cli/blob/728caa2d90c957497642ea5f40f8a0dc4c04daa4/internal/cli/backup/restores/watch.go#L62))
- `/api/atlas/v2/groups/{groupId}/peers`: complexity on choosing `statusName` or `status` ([ref](https://github.com/mongodb/mongodb-atlas-cli/blob/728caa2d90c957497642ea5f40f8a0dc4c04daa4/internal/cli/networking/peering/watch.go#L71-L81))
- `/api/atlas/v2/groups/{groupId}/pipelines/{pipelineName}/runs`: not found which "main command" would hold `--watch`
=> CLOUDP-297413 Annotate current watchers

build/ci/evergreen.yml
=> CLOUDP-300808: Disable evergreen tasks that require IAM role

test/e2e/atlas/backup_flex_test.go
=> fix: Flex Backup Tests

test/e2e/atlas/atlas_e2e_test_generator_test.go, test/e2e/atlas/backup_flex_test.go
fixes backup tests back to using clusterName as it's expected everywhere
=> fix: revert all backup changes

build/ci/copy.bara.sky.template
=> chore: Fixes destination_files exclude path

internal/cli/plugin/plugin.go, internal/cli/plugin/plugin_test.go
Verify that the plugin system verifies that commands don't override aliases
_Jira ticket:_ CLOUDP-295450
=> CLOUDP-295450 Verify that the plugin system verifies that commands don't override aliases

.github/workflows/dependabot.yml, .github/workflows/issues.yml
fix github actions permissions to set label on dependabot PRs (follow up from https://github.com/mongodb/mongodb-atlas-cli/pull/3672)
=> fix: permissions to set label on dependabot PRs

internal/cli/plugin/plugin_github_asset.go
Adds dochub link to section on plugin install/update in AtlasCLI troubleshoot docs to error message. 
_Jira ticket:_ CLOUDP-297379
=> CLOUDP-297379: Improve plugin error message

build/ci/evergreen.yml
This reverts commit ab09aa457de911fcdc274b2a8487bc54e41d8cc9.
=> Revert "CLOUDP-300808: Disable evergreen tasks that require IAM role …(#3653)

internal/cli/api/api.go
Throw err when both --file and stdin are provided for auto-generated commands
_Jira ticket:_ CLOUDP-303334
=> CLOUDP-303334 Throw err when both --file and stdin are provided for auto-generated commands

.github/workflows/close-jira.yml
=> fix: auto close jira

build/ci/evergreen.yml
Commenting the test until everything is sorted in https://github.com/mongodb/mongodb-atlas-cli/pull/3727
=> fix: comment streams tests until deletion is fixed

tools/cmd/api-generator/convert_commands.go, tools/cmd/api-generator/convert_commands_test.go, tools/cmd/api-generator/convert_metadata.go
=> CLOUDP-302671: Ignore preview versions

tools/cmd/api-generator/convert_metadata.go
fixes https://github.com/mongodb/mongodb-atlas-cli/pull/3734, null schemas may occur
_Jira ticket:_ CLOUDP-306058
=> CLOUDP-306058 fix null schema

tools/cmd/api-generator/overlays/examples_project_ip_access_list.yaml, tools/cmd/docs/metadata.go
Added parameters for project IP access list examples
_Jira ticket:_ CLOUDP-306367
=> CLOUDP-306367: Add parameters to acceslist example

tools/cmd/api-generator/overlays/examples_monitoring_logs.yaml, tools/cmd/docs/metadata.go
Implemented examples for:
- `listAtlasProcesses`
- `getHostLogs`
_Jira ticket:_ CLOUDP-303344
=> CLOUDP-303344: Added Monitoring and Logs examples

test/e2e/atlas/cleanup_test.go, test/e2e/atlas/helper_test.go, test/e2e/atlas/streams_test.go
=> CLOUDP-307074: Add streams deletion to cleanup task

build/ci/evergreen.yml, build/ci/release.yml
Periodic builds don't create foliage tickets
_Jira ticket:_ CLOUDP-305568
Also added `foliage_default_mothra_team` to `cloudp_api_experience_ii` to evergreen project settings
=> CLOUDP-305568 Periodic builds don't create foliage tickets

internal/plugin/plugin.go, internal/plugin/plugin_manifest.go, internal/plugin/plugin_manifest_test.go, internal/plugin/plugin_test.go
- Add alias support for CLI plugins
- Extended tests
_Jira ticket:_ CLOUDP-294149
=> CLOUDP-294149: [AtlasCLI] Add support for aliases in CLI plugins

build/ci/evergreen.yml, test/e2e/atlas_e2e_test_generator_test.go, test/e2e/atlas_org_invitations_test.go, test/e2e/atlas_users_test.go, test/e2e/federation_settings_test.go
=> fix: iam gov tests

docs/command/atlas-deployments-setup.txt, docs/command/atlas-setup.txt, internal/cli/deployments/options/deployment_opts.go, internal/cli/deployments/setup.go, internal/cli/setup/setup_cmd.go, internal/usage/usage.go, internal/vscode/vscode.go, internal/vscode/vscode_cli_bin.go, internal/vscode/vscode_cli_bin_windows.go
Adds new connection option VsCode (MongoDB for VSCode) for `atlas deployment setup` and `atlas setup` commands.
Logic:
1. Deployment is created and connection string generated
2. VsCode extension deeplink is built, adding parameters `connectoinString`, `name` and `utm_soource` for telemetry tracking (if user has telemetry enabled)
3. Deeplink is opened using vsCode CLI
`code --open-url "vscode://mongodb:mongodb-vscode/connectWithURI?connectionString=...` 
1. VsCode opens. 
2. The connection string is saved under the name `<depoyment-name> (<deployment-type>)`
3. The deployment is connected to.
Notes:
* If VsCode or VsCode CLI is not installed, error is returned
* If extension is not installed, AtlasCLI does not provide an error. VsCode will open with a prompt to install the extension.
* …
=> CLOUDP-308811: Adds vscode connection option to deployment setup and setup

Makefile, build/ci/evergreen.yml
Fix e2e cleanup.
Succesful run: https://spruce.mongodb.com/version/680778a1b50d9400072c43f5/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
_Jira ticket:_ CLOUDP-314764
=> CLOUDP-314764: Fix e2e cleanup

.golangci.yml, internal/cli/streams/privatelink/list_test.go, internal/telemetry/read_answer.go, test/e2e/projectsettings/project_settings_test.go, test/internal/helper.go, tools/cmd/templates-checker/templateparsing/validation.go
Enable checks to move to more moderm go pattern using ranges
=> task: enable intrange check

RELEASING.md
Small docs improvement and clean up
=> docs: update RELEASING

docs/command/atlas-alerts-acknowledge.txt, docs/command/atlas-teams-describe.txt, internal/cli/alerts/acknowledge.go, internal/cli/teams/describe.go, internal/cli/users/describe.go
Found a couple of places that can do with the cobra way to check for flag requirements
=> task: improve flag validation to use naive check for mutually exclusive

build/ci/evergreen.yml, build/ci/release.yml, go.mod, internal/api/executor_test.go, internal/api/watcher_test.go, internal/cli/auth/login_test.go, internal/cli/auth/logout_test.go, internal/cli/auth/register_test.go, internal/cli/clusters/watch_test.go, internal/cli/deployments/connect_test.go, internal/cli/deployments/delete_test.go, internal/cli/deployments/list_test.go, internal/cli/deployments/logs_test.go, internal/cli/deployments/pause_test.go, internal/cli/deployments/search/indexes/create_test.go, internal/cli/deployments/search/indexes/delete_test.go, internal/cli/deployments/search/indexes/describe_test.go, internal/cli/deployments/search/indexes/list_test.go, internal/cli/deployments/setup_test.go, internal/cli/deployments/start_test.go, internal/cli/setup/setup_cmd_test.go, internal/store/store_test.go, test/e2e/deploymentsatlas/deployments_atlas_test.go, test/e2e/deploymentslocalauth/deployments_local_auth_test.go, test/e2e/deploymentslocalauthindexdeprecated/deployments_local_auth_index_deprecated_test.go, test/e2e/deploymentslocalnoauth/deployments_local_noauth_test.go, test/e2e/deploymentslocalnocli/deployments_local_nocli_test.go, tools/cmd/api-generator/main_test.go
=> task: update to go 1.24

internal/config/profile.go, internal/oauth/oauth.go
see [CLOUDP-317697](https://jira.mongodb.org/browse/CLOUDP-317697)
=> CLOUDP-317697: support separately configurable account url

internal/cli/plugin/plugin_github_asset_test.go, internal/cli/plugin/update_test.go
=> task: fix linting warnings

build/ci/release.yml
This PR fixes two issues with the initial implementation of Papertrail:
1. product variable was not correctly added to Evergreen expansions resulting in failure when running Papertrail
2. the variable `unstable` was not correctly passed to the function
Previous failing patch: https://parsley.mongodb.com/evergreen/mongodb_atlas_cli_master_goreleaser_atlascli_snapshot_package_goreleaser_ced6b1f38b027a891619be43deb693bb18763cf5_25_05_21_10_40_40/0/all
Current fixed patch: https://parsley.mongodb.com/evergreen/mongodb_atlas_cli_master_test_papertrail_trace_artifacts_patch_ced6b1f38b027a891619be43deb693bb18763cf5_682ddc0974a15900076f24b2_25_05_21_13_58_43/0/all?bookmarks=0,451
_Jira ticket:_ [CLOUDP-319840](https://jira.mongodb.org/browse/CLOUDP-319840)
=> CLOUDP-319840: Fixes papertrail implementation

tools/cmd/api-generator/convert_commands.go, tools/cmd/api-generator/main.go, tools/cmd/api-generator/main_test.go
Made `specToCommands` function by receiving `now` as an argument.
=> fix snapshots for api-generation

build/ci/evergreen.yml
=> CLOUDP-325349: fix atlas_clusters_iss_e2e

internal/cli/clusters/clusters.go, internal/cli/clusters/describe.go, internal/cli/deployments/options/deployment_opts.go, internal/cli/deployments/options/deployment_opts_telemetry.go, internal/cli/deployments/pause.go, internal/cli/deployments/pause_test.go, internal/cli/deployments/start.go, internal/cli/deployments/start_test.go, internal/mocks/mock_deployment_opts_telemetry.go, internal/telemetry/event.go, internal/telemetry/event_test.go
_Jira ticket:_ CLOUDP-322616
- Append cluster type to telemetry data whenever we call autoScaling config enpdoint
=> CLOUDP-322616: add telemetry property 

internal/cli/backup/restores/start.go, internal/cli/backup/restores/start_mock_test.go
=> CLOUDP-288862: Unpin SDK in backup

build/ci/release.yml
[CLOUDP-328661](https://jira.mongodb.org/browse/CLOUDP-328661)
Our release failed with 
```
Command 'papertrail.trace' in function 'trace release artifacts' (step 1.5 of 1) failed: running trace: running papertrail trace: HTTP status code 400: received response: the 'submitter' query parameter must be set
```
[Packaging AtlasCLI (goreleaser)](https://spruce.mongodb.com/version/6863c4bd6cf8cc000767210a/tasks?page=0&sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
=> CLOUDP-328661: update papertrail submitter

internal/cli/root/builder.go, internal/store/store.go, internal/transport/transport.go, test/e2e/brew/brew_test.go
Reverts mongodb/mongodb-atlas-cli#4034
Intended to be merged into feature branch
=> Revert "CLOUDP-329791: Refactor auth check"

.github/workflows/breaking-changes.yaml, tools/cmd/breakvalidator/main.go
follow up from https://github.com/mongodb/mongodb-atlas-cli/pull/4064, porting missing fix
_Jira ticket:_ CLOUDP-279514
=> CLOUDP-279514 fix Detect and block breaking changes

scripts/pre-commit.sh
follow up from https://github.com/mongodb/mongodb-atlas-cli/pull/4071, this fixes pre-commit hook
=> fix: pre-commit hook with unit tests

test/e2e/atlas/search_nodes/searchnodes/search_nodes_test.go
fix search nodes tests
_Jira ticket:_ CLOUDP-336027
=> CLOUDP-336027 fix search nodes tests

build/ci/evergreen.yml
Failed Test: mongodb-atlas-cli-master-TestMain/atlas_backups_flex_e2e/e2e_atlas_backups
_Jira ticket:_ CLOUDP-336555
=> CLOUDP-336555 Failed Test: mongodb-atlas-cli-master-TestMain/atlas_backups_flex_e2e/e2e_atlas_backups

internal/cli/auth/logout.go, internal/cli/auth/logout_mock_test.go, internal/cli/auth/logout_test.go
=> CLOUDP-333260: delete api keys on logout

.github/workflows/update-e2e-tests.yml, CONTRIBUTING.md, Makefile, build/ci/evergreen.yml, test/e2e/atlas/backup/exports/buckets/backupexportbuckets/backup_export_buckets_test.go, test/e2e/atlas/backup/exports/jobs/backupexportjobs/backup_export_jobs_test.go, test/e2e/atlas/backup/flex/backupflex/backup_flex_test.go, test/e2e/atlas/datafederation/db/datafederationdb/data_federation_db_test.go, test/e2e/atlas/datafederation/querylimits/datafederationquerylimit/data_federation_query_limit_test.go, test/e2e/atlas/decrypt/decryptionaws/decryption_aws_test.go, test/e2e/atlas/decrypt/decryptionazure/decryption_azure_test.go, test/e2e/atlas/decrypt/decryptiongcp/decryption_gcp_test.go, test/e2e/atlas/decrypt/decryptionlocalkey/decryption_localkey_test.go, test/e2e/atlas/deployments/atlasclusters/deploymentsatlas/deployments_atlas_test.go, test/e2e/atlas/deployments/atlasclusters/deploymentsatlas/deployments_atlas_test_iss.go, test/e2e/atlas/deployments/local/auth/deprecated/deploymentslocalauthindexdeprecated/deployments_local_auth_index_deprecated_test.go, test/e2e/atlas/deployments/local/auth/new/deploymentslocalauth/deployments_local_auth_test.go, test/e2e/atlas/deployments/local/noauth/deploymentslocalnoauth/deployments_local_noauth_test.go, test/e2e/atlas/deployments/local/nocli/deploymentslocalnocli/deployments_local_nocli_test.go, test/e2e/atlas/deployments/local/seed/deploymentslocalseedfail/deployments_local_seed_fail_test.go, test/e2e/atlas/generic/dbusers/dbusers_test.go, test/internal/atlas_e2e_test_generator.go, test/internal/cleanup_test.go, test/internal/env.go
move env vars from tests into one place
=> refactor: move env vars from tests into one place

internal/cli/auth/logout.go, internal/cli/auth/logout_mock_test.go, internal/cli/auth/logout_test.go
improves the prerun checks and adds more unit tests
=> chore: add more tests to logout before updating to config delete

test/internal/cleanup_test.go
Adds missing profile to cleanup task flow
=> fix: fix cleanup task

docs/command/atlas-auth-login.txt, internal/cli/auth/login.go
Follow-up to #4118 to add note on auth types to login help text
=> chore: login help

scripts/add-e2e-profiles.sh
fixes wrong indentation and defaults e2e tests to cloud-dev
minor cosmetic fix because the config commands add the flags with indentations
```
[__e2e]
ops_manager_url = "https://cloud-dev.mongodb.com/"
output = "plaintext"
private_api_key = "a"
public_api_key = "a"
service = "cloud"
[__e2e_snapshot]
org_id = 'a0123456789abcdef012345a'
project_id = 'b0123456789abcdef012345b'
public_api_key = 'ABCDEF01'
private_api_key = '12345678-abcd-ef01-2345-6789abcdef01'
ops_manager_url = 'http://localhost:8080/'
service = 'cloud'
```
after the fix:
```
[__e2e]
ops_manager_url = "https://cloud-dev.mongodb.com/"
output = "plaintext"
private_api_key = "aa"
public_api_key = "a"
service = "cloud"
[__e2e_snapshot]
org_id = 'a0123456789abcdef012345a'
project_id = 'b0123456789abcdef012345b'
public_api_key = …
```
=> fix: minor fixes to add-e2e-profiles

internal/cli/commonerrors/errors.go, test/e2e/atlas/interactive/setupfailure/setup_failure_test.go, test/e2e/brew/brew/brew_test.go
Align error message with `unauthorized`
=> fix: improve error message for atlas cli unauthorized errors
