mongodb/mongodb-atlas-cli

internal/cli/atlas_alert_config_delete.go

_Jira ticket:_ [CLOUDP-58568](https://jira.mongodb.org/browse/CLOUDP-58568)
We need to start testing stdio

CLOUDP-58568: Deleting alert configs is not asking for confirmation

---

e2e/atlas_clusters_test.go
e2e/create_cluster_test.json
e2e/update_cluster_test.json
internal/cli/atlas_clusters_create.go
internal/cli/atlas_clusters_update.go

_Jira ticket:_ [CLOUDP-57657](https://jira.mongodb.org/browse/CLOUDP-57657)

CLOUDP-57657: Add E2E test for updating an atlas cluster with a file

---

internal/cli/atlas_backups_restores.go
internal/cli/atlas_backups_restores_start.go
internal/cli/atlas_backups_restores_start_test.go
internal/fixtures/continuous_jobs.go
internal/fixtures/continuous_snapshots.go
internal/flags/flags.go
internal/usage/usage.go

_Jira ticket:_ [CLOUDP-57864](https://jira.mongodb.org/browse/CLOUDP-57864)

CLOUDP-57864: Backup: Start a restore job

---

internal/cli/cloud_manager.go
internal/cli/ops_manager_automation.go
internal/cli/ops_manager_automation_status.go
internal/cli/ops_manager_automation_status_test.go
internal/fixtures/automation_status.go
internal/mocks/mock_automation.go
internal/store/automation.go

_Jira ticket:_ [CLOUDP-57630](https://jira.mongodb.org/browse/CLOUDP-57630)

CLOUDP-57630: C/OM automation status

---

.evergreen.yml
CONTRIBUTING.md
Makefile

_Jira ticket:_ [CLOUDP-59277](https://jira.mongodb.org/browse/CLOUDP-59277)
This is the initial set up of the evergreen project, this only compiles and packages and we do nothing with the packages, yet

CLOUDP-59277: Set up evergreen

---

go.mod
go.sum
internal/cli/atlas_alert_config_delete.go
internal/cli/atlas_clusters_delete.go
internal/cli/atlas_dbusers_create.go
internal/cli/atlas_dbusers_delete.go
internal/cli/cli.go
internal/cli/ops_manager_dbusers.go
internal/cli/ops_manager_dbusers_create.go
internal/cli/ops_manager_dbusers_delete.go
internal/cli/ops_manager_dbusers_delete_test.go
internal/convert/automation_config.go
internal/convert/automation_config_test.go
internal/convert/database_user.go
internal/convert/database_user_test.go
internal/fixtures/automation_configs.go
internal/search/example_search_test.go
internal/search/search.go

_Jira ticket:_ [CLOUDP-57841](https://jira.mongodb.org/browse/CLOUDP-57841)

CLOUDP-57841: Delete dbusers C/OM

---

go.mod
go.sum
internal/store/alerts.go

_Jira ticket:_ [CLOUDP-59567](https://jira.mongodb.org/browse/CLOUDP-59567)

CLOUDP-59567: Adding the support of alerts for OM in mcli

---

e2e/atlas_alerts_test.go
go.mod
go.sum
internal/cli/atlas_alerts_list.go
internal/fixtures/alerts.go
internal/mocks/mock_alerts.go
internal/store/alerts.go

_Jira ticket:_ [CLOUDP-59492 t](https://jira.mongodb.org/browse/CLOUDP-59492 )
`./bin/mongocli om alerts list --status OPEN --profile OPS`
```json
{
"links": [
{
"rel": "self",
"href": "http://localhost:9080/api/public/v1.0/groups/5e7b34822e676a3d207a8399/alerts?status=OPEN\u0026pageNum=1\u0026itemsPerPage=100"
}
],
"results": [
{
"id": "5e7b47962e676a3d207a9843",
"groupId": "5e7b34822e676a3d207a8399",
"alertConfigId": "5e7b47692e676a3d207a9809",
"eventTypeName": "USERS_WITHOUT_MULTI_FACTOR_AUTH",
"created": "2020-03-25T11:59:18Z",
"updated": "2020-03-25T12:01:15Z",
"status": "OPEN",
"lastNotified": "2020-03-25T11:59:25Z",
"acknowledgedUntil": "2023-08-17T20:02:15Z",
"acknowledgingUsername": "ydxjuumo"
}
],
"totalCount": 1
}
```
`./bin/mongocli om alerts list --status CLOSED --profile …

CLOUDP-59492 Add the status flag to the alerts list

---

e2e/atlas_alertconfig_test.go
internal/cli/atlas_alerts.go
internal/cli/atlas_alerts_config.go
internal/cli/atlas_alerts_config_create.go
internal/cli/atlas_alerts_config_create_test.go
internal/cli/atlas_alerts_config_update.go
internal/cli/atlas_alerts_config_update_test.go
internal/cli/cli.go
internal/mocks/mock_alert_configuration.go
internal/store/alert_configuration.go

_Jira ticket:_ [CLOUDP-57842](https://jira.mongodb.org/browse/CLOUDP-57842)

CLOUDP-57842:  Update alert configs, Atlas

---

internal/cli/cloud_manager_clusters_list.go

_Jira ticket:_ [CLOUDP-59777](https://jira.mongodb.org/browse/CLOUDP-59777)
Had this issue the other day as I have a project id set in my profile and was trying against om4.2 (4.2 doesn't have the all clusters feature)

CLOUDP-59777: Use profile project id for listing clusters

---

.githooks/pre-commit
internal/cli/ops_manager_security.go
internal/cli/ops_manager_security_enable.go
internal/cli/ops_manager_security_enable_test.go
internal/convert/automation_config.go
internal/convert/automation_config_test.go
internal/convert/cluster_config_test.go
internal/convert/database_user.go
internal/convert/randgen.go
internal/description/description.go

_Jira ticket:_ [CLOUDP-59682](https://jira.mongodb.org/browse/CLOUDP-59682)

CLOUDP-59682: Enable security on C/OM

---

README.md

_Jira ticket:_ [CLOUDP-60401](https://jira.mongodb.org/browse/CLOUDP-60401)

CLOUDP-60401: Update README to use new brew repo

---

.evergreen.yml
etc/repo_config.yml

We were missing an ENV variable, also this removes some unnecessary steps

Fix publish adding NOTARY_KEY_NAME

---

internal/convert/randgen.go

_Jira ticket:_ [CLOUDP-60961](https://jira.mongodb.org/browse/CLOUDP-60961)

CLOUDP-60961: Invalid encoding when generating secure key

---

internal/cli/ops_manager_servers_list.go

_Jira ticket:_ [CLOUDP-61595](https://jira.mongodb.org/browse/CLOUDP-61595)
This was a missed file from the refactor to centralise project id validations

CLOUDP-61595: mongocli ops-manager servers list does not validate project id requirement

---

internal/cli/config.go
internal/cli/ops_manager_servers_list.go

_Jira ticket:_ [CLOUDP-61621](https://jira.mongodb.org/browse/CLOUDP-61621)

CLOUDP-61621: Adding the projectID in mongocli config

---

internal/cli/config.go
internal/validate/validate.go
internal/validate/validate_test.go

Validate the given value is a valid ObjectID

Validate the given project ID is valid

---

.evergreen.yml
Makefile
e2e/atlas/alertconfig_test.go
e2e/atlas/alerts_test.go
e2e/atlas/clusters_test.go
e2e/atlas/dbusers_test.go
e2e/atlas/events_test.go
e2e/atlas/whitelist_test.go
e2e/cloud_manager/alerts_test.go
e2e/cloud_manager/dbusers_test.go
e2e/cloud_manager/events_test.go

Add junit reports to e2e

---

build/ci/evergreen.yml
build/package/generate-msi.sh
wix.json

Move the msi generation to a bash file and add a variant to generate msi for releases

task: Update msi packaging

---

e2e/atlas/whitelist_test.go
internal/cli/atlas/atlas.go
internal/cli/whitelist/create.go
internal/cli/whitelist/create_test.go
internal/cli/whitelist/delete.go
internal/cli/whitelist/delete_test.go
internal/cli/whitelist/describe.go
internal/cli/whitelist/describe_test.go
internal/cli/whitelist/list.go
internal/cli/whitelist/list_test.go
internal/cli/whitelist/whitelist.go
internal/flag/flags.go
internal/usage/usage.go

_Jira ticket:_ [CLOUDP-65292](https://jira.mongodb.org/browse/CLOUDP-65292)

CLOUDP-65292: Enable deleteAfter as an option when create IP whitelist entry

---

.goreleaser.yml
cmd/mongocli/mongocli.go

_Jira ticket:_ [CLOUDP-65942](https://jira.mongodb.org/browse/CLOUDP-65942)

CLOUDP-65942: Add auto complete to brew installer

---

cmd/mongocli/mongocli.go
internal/cli/config/set.go
internal/config/profile.go

_Jira ticket:_ [Improve use of default profile to use any profile available](https://jira.mongodb.org/browse/CLOUDP-66132)
Only a default profile:
```
cat ~/.config/mongocli.toml
[default]
base_url = "http://base_url.com/"
ops_manager_skip_verify = "false"
org_id = "5cac6a2179358edabd12b572"
private_api_key = <>
project_id = "5cac6a2ba6f239298a18a025"
public_api_key = <>
service = "cloud"
```
Gives:
` ./bin/mongocli atlas clusters list `
> Lists the clusters
```
./bin/mongocli atlas clusters list -P …
```

CLOUDP-66132: use any available profile

---

build/ci/evergreen.yml
build/package/curator-push.sh

The LDAP server is no longer supported so auth to barque should just use the service user's API key.
_Jira ticket:_ [CLOUDP-66818](https://jira.mongodb.org/browse/[CLOUDP-66818])

CLOUDP-66818: authenticate to barque using API key

---

internal/cli/atlas/onlinearchive/delete.go
internal/cli/atlas/onlinearchive/delete_test.go
internal/cli/atlas/onlinearchive/describe_test.go
internal/cli/atlas/onlinearchive/list_test.go
internal/cli/atlas/onlinearchive/online_archive.go
internal/cli/atlas/onlinearchive/pause.go
internal/cli/atlas/onlinearchive/pause_test.go
internal/cli/atlas/onlinearchive/start.go
internal/cli/atlas/onlinearchive/start_test.go
internal/description/description.go
internal/store/online_archives.go

_Jira ticket:_ [Name of ticket](https://jira.mongodb.org/browse/[name-of-ticket])
pause 
```zsh
mongocli atlas clusters onlinearchive pause 5f08577acf7bf723975cb4c4 --clusterName testShard
{
"_id": "5f08577acf7bf723975cb4c4",
"clusterName": "testShard",
"collName": "test",
"criteria": {
"dateField": "test",
"expireAfterDays": 3
},
"dbName": "test",
"groupId": "5e429f2e06822c6eac4d59c9",
"partitionFields": [
{
"fieldName": "test",
"fieldType": "date",
"order": 0
}
],
"paused": true,
"state": "PAUSED"
}
```
start
```zsh
mongocli atlas clusters onlinearchive start 5f08577acf7bf723975cb4c4 --clusterName testShard
{
"_id": "5f08577acf7bf723975cb4c4",
"clusterName": "testShard",
"collName": "test",
"criteria": {
"dateField": "test",
"expireAfterDays": 3
},
"dbName": "test",
"groupId": …
```

CLOUDP-66899: mongocli atlas cluster(s) onlineArchive(s) start

---

e2e/atlas/datalake_test.go

_Jira ticket:_ [CLOUDP-67054](https://jira.mongodb.org/browse/CLOUDP-67054)
We started to get errors that we had exceeded the allowed amount of data lakes per project

CLOUDP-67054: Fix delete e2e test for datalake

---

e2e/atlas/logs_test.go
e2e/atlas/metrics_test.go

_Jira ticket:_ [CLOUDP-67058](https://jira.mongodb.org/browse/CLOUDP-67058)
If some of our e2e would fail we would not always clean up the created clusters, this aims to be a more defensive way to make sure the delete function always runs on exit

CLOUDP-67058: Better test clean up

---

internal/cli/atlas/datalake/create.go
internal/cli/atlas/datalake/describe.go
internal/cli/atlas/datalake/list.go
internal/cli/atlas/datalake/update.go

_Jira ticket:_ CLOUDP-67961
```zsh
$ mongocli atlas datalake create myDL -P dev
Data lake 'myDL' created.
```
```zsh
$ mongocli atlas datalake create myDL -P dev
Data lake 'myDL' created.
```
```zsh
$ mongocli atlas datalake describe myDL
Name	State
myDL	UNVERIFIED
```
```zsh
$ mongocli atlas datalake ls
Name	State
myLake	UNVERIFIED
myDL	UNVERIFIED
```

CLOUDP-67961: update internal/cli/atlas/datalake to use the new output format

---

internal/cli/atlas/datalake/describe.go
internal/cli/atlas/datalake/list.go
internal/cli/atlas/onlinearchive/create.go
internal/cli/atlas/onlinearchive/describe.go
internal/cli/atlas/onlinearchive/list.go
internal/cli/atlas/onlinearchive/pause.go
internal/cli/atlas/onlinearchive/start.go
internal/cli/atlas/onlinearchive/update.go
internal/cli/atlas/search/describe.go
internal/cli/atlas/search/list.go

_Jira ticket:_ CLOUDP-67963
```zsh
$ mongocli atlas clusters onlinearchive create --db test --collection test --archiveAfter 3 --partition test:date --clusterName myDemo --dateField test
Online archive '5f205e4f4ace3c78da67dd2a' created.
```
```zsh
$ mongocli atlas clusters onlinearchive ls --clusterName myDemo 
ID				DATABASE	COLLECTION	STATE
5f205e4f4ace3c78da67dd2a	test		test		ACTIVE
```
```zsh
$ mongocli atlas clusters onlinearchive describe 5f205e4f4ace3c78da67dd2a --clusterName myDemo 
ID				CLUSTER		DATABASE	COLLECTION	STATE
5f205e4f4ace3c78da67dd2a	myDemo		test		test		ACTIVE
```

CLOUDP-67963: update internal/cli/atlas/onlinearchive to use the new output

---

Makefile
build/ci/evergreen.yml
e2e/cloud_manager/dbusers_test.go
e2e/cloud_manager/deploy_replica_set_test.go
e2e/cloud_manager/servers_test.go

_Jira ticket:_ CLOUDP-68278
Since we took some tests out of the PR suite we could speed it up a bit more if we don't make cloud manager generic depend on a spawn host

CLOUDP-68278: don't make generic cloud manager tests depend on spawn host

---

internal/cli/opsmanager/servers/list.go

_Jira ticket:_ CLOUDP-68273
```zsh
$ mongocli om servers ls
HOSTNAME	STATE
host0		NO_PROCESSES
host1		NO_PROCESSES
host2		NO_PROCESSES
```

CLOUDP-68273: update internal/cli/opsmanager/servers to use the simplified output

---

internal/cli/atlas/security/customercerts/create.go
internal/cli/atlas/security/customercerts/describe.go

_Jira ticket:_ CLOUDP-68114
Just outputs the plain certificate:
```
./bin/mongocli atlas security customerCerts create --casFile ~/.ssh/bad_pem.pem
Certificate successfully created.
```
```
./bin/mongocli atlas security customerCerts describe
-----BEGIN CERTIFICATE-----
....
bSQR/NrJDA==
-----END CERTIFICATE-----
```

CLOUDP-68114: Add CAS field for security certs

---

internal/cli/cloudmanager/cloud_manager.go
internal/cli/opsmanager/ops_manager.go
internal/cli/opsmanager/processes/describe.go
internal/cli/opsmanager/processes/describe_test.go
internal/cli/opsmanager/processes/list.go
internal/cli/opsmanager/processes/list_test.go
internal/cli/opsmanager/processes/processes.go

_Jira ticket:_ CLOUDP-68318
```
./bin/mongocli om process list -P ops -o ""
ID					TYPE		HOSTNAME	PORT
2ab828e24a8ecb437f8c72a68a9b7c72	NO_DATA		andreaMac	29017
```
```
./bin/mongocli om process describe 2ab828e24a8ecb437f8c72a68a9b7c72 -P ops -o ""
ID					TYPE		HOSTNAME	PORT
2ab828e24a8ecb437f8c72a68a9b7c72	NO_DATA		andreaMac	29017
```

CLOUDP-68318: update cli/opsmanager/processes describe and list to use the simplified output

---

internal/cli/opsmanager/logs/jobs_collect.go
internal/cli/opsmanager/logs/jobs_list.go

_Jira ticket:_ CLOUDP-68272
```zsh
$ mongocli ops-manager logs jobs collect REPLICASET myReplicaSet --sizeRequestedPerFileBytes 10000000 --type MONGODB
Log collection job '5f21966596379e49248ca87f' started successfully.
```
```zsh
$ mongocli om log jobs ls
ID				CREATED AT		EXPIRES AT		STATUS		URL															REDACTED
5f21966596379e49248ca87f	2020-07-29T15:31:49Z	2020-08-28T15:31:49Z	SUCCESS		http://mms:8080/api/public/v1.0/groups/5f219152a4380e6bd8539b2c/logCollectionJobs/5f21966596379e49248ca87f/download	false
```

CLOUDP-68272: update internal/cli/opsmanager/logs to use the simplified format

---

.drone.yml
build/ci/evergreen.yml

CLOUDP-66895: Move snyk scanner to evergreen

---

internal/cli/opsmanager/metrics/databases_list.go
internal/cli/opsmanager/metrics/disks_describe.go
internal/cli/opsmanager/metrics/disks_describe_test.go
internal/cli/opsmanager/metrics/disks_list.go
internal/cli/opsmanager/metrics/process.go

_Jira ticket:_ CLOUDP-68337
```
./bin/mongocli om metric processes ad00123ce121da3bdc7784fdaa5dbf0b --granularity PT30M --period P1DT12H -P ops -o ""
NAME					UNITS		TIMESTAMP			VALUE
PROCESS_CPU_USER			PERCENT		2020-07-29T16:33:23Z		0.5280867
PROCESS_CPU_USER			PERCENT		2020-07-29T17:03:23Z		0.5393118
PROCESS_CPU_USER			PERCENT		2020-07-29T17:33:23Z		0.541945
PROCESS_CPU_USER			PERCENT		2020-07-29T18:33:23Z		0.0053553963
PROCESS_CPU_USER			PERCENT		2020-07-29T19:03:23Z		0.40095562
PROCESS_CPU_USER			PERCENT		2020-07-29T20:03:23Z		0.0018521702
PROCESS_CPU_USER			PERCENT		2020-07-29T21:03:23Z		0.00400066
PROCESS_CPU_USER			PERCENT		2020-07-29T21:33:23Z		0.5555369
PROCESS_CPU_USER			PERCENT		2020-07-29T22:03:23Z		0.2864721
PROCESS_CPU_USER			PERCENT …
```

CLOUDP-68337: internal/cli/atlas/metrics and internal/cli/opsmanager/metrics to use the simplified output

---

internal/cli/atlas/networking/peering/list.go

_Jira ticket:_ CLOUDP-70467
This is the default behaviour of the API, there's not way to get them all, so I'm making this change so it's explicit for users running the command help

CLOUDP-70467: Default networking peering list to AWS to match the API

---

internal/cli/atlas/clusters/indexes_create.go
internal/cli/iam/projects/apikeys/create.go
internal/cli/opsmanager/clusters/indexes_create.go
internal/cli/opsmanager/logs/jobs_collect.go

_Jira ticket:_ CLOUDP-70550
`StringArrayVar` doesn't handle `--role ROLE_1,ROLE2` only `--role ROLE_1 --role ROLE_2` while `StringSliceVar` does

CLOUDP-70550: Allow comma separate values for roles

---

internal/cli/atlas/dbusers/certs/create.go

_Jira ticket:_ CLOUDP-70719
```zsh
$ mongocli atlas dbusers certs create --username test1 -P dev
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
-----BEGIN PRIVATE KEY-----
...
-----END PRIVATE KEY-----
```

CLOUDP-70719: wrong output for create dbuser cert

---

internal/cli/atlas/integrations/create/create.go
internal/cli/atlas/integrations/create/create_test.go
internal/cli/atlas/integrations/create/description.go
internal/cli/atlas/integrations/create/webhook.go
internal/cli/atlas/integrations/create/webhook_test.go
internal/flag/flags.go
internal/usage/usage.go

_Jira ticket:_ CLOUDP-70036
```
./bin/mongocli atlas integrations create WEBHOOK --url https://webhook.site/51a678a8-5c1c-4aed-83e9-93788af154e6 -o json --secret test -o json
{
"links": [
{
"rel": "self",
"href": "https://cloud-dev.mongodb.com/api/atlas/v1.0/groups/5e4e593f70dfbf1010295836/integrations/WEBHOOK?pageNum=1\u0026itemsPerPage=100"
}
],
"results": [
{
"type": "PAGER_DUTY",
"serviceKey": "7fd036a6860e41469fe1fXXXXXX"
},
{
"type": "DATADOG",
"apiKey": "51c0ef87e9951c3e147acXXXXXXX",
"region": "US"
},
{
"type": "NEW_RELIC",
"licenseKey": "eu01xx5f87268ff5028e69a67fXXXXXX",
"accountId": "2857404",
"writeToken": "NRII-zpwCnhrDyUojdSJOkXXXXXXX",
"readToken": "NRIQ-MHCu7bPq2xvrrpXXXXXXXXX"
},
{
"type": "OPS_GENIE",
"apiKey": "9255b505-9c55-45a4-893c-XXXXXXXXXX",
"region": "EU"
},
{ …
```

CLOUDP-70036: mongocli atlas integration(s) create|update WEBHOOK

---

e2e/atlas/integrations_test.go
internal/cli/atlas/integrations/create/victor_ops.go

_Jira ticket:_ CLOUDP-71439
The issue seems to occur only when we do not set the flag --routingKey . This property is optional according to documentation and the atlas UI so this is a problem of the endpoint. I am going to create a ticket for core/iam to verify this behaviour.
In the meantime, I am going to set --routingKey as required.
```
./bin/mongocli atlas integrations create VICTOR_OPS --apiKey 2eb02ae8-a198-431c-aa8a-XXXXXXX -o json --routingKey test
{
"links": [
{
"rel": "self",
"href": "https://cloud-dev.mongodb.com/api/atlas/v1.0/groups/5e4e593f70dfbf1010295836/integrations/VICTOR_OPS?pageNum=1\u0026itemsPerPage=100"
}
],
"results": [
{
"type": "PAGER_DUTY",
"serviceKey": "51c0ef87e9951c3e147accf0e1270"
},
{
"type": "VICTOR_OPS",
"apiKey": "2eb02ae8-a198-431c-aa8a-XXXXXXXX", …
```

CLOUDP-71439: Investigate why atlas integration(s) create|update VICTOR_OPS does not list VICTOR_OPS

---

internal/cli/atlas/integrations/create/webhook.go

_Jira ticket:_ CLOUDP-72054
This property is optional according to documentation and the atlas UI so this is a problem of the endpoint. I am going to create a ticket for core/iam to verify this behaviour.
In the meantime, I am going to set --secret as required.

CLOUDP-72054: Investigate why we are getting an error when we do not set --secret to configure webhook

---

internal/cli/atlas/networking/peering/watch.go
internal/cli/atlas/networking/peering/watch_test.go

_Jira ticket:_ CLOUDP-73125
AWS uses a different field to report status

CLOUDP-73125: mongocli atlas networking peering watch doe snot work for AWS

---

go.mod
go.sum
internal/cli/cloudmanager/cloud_manager.go
internal/cli/cloudmanager/cloud_manager_test.go
internal/cli/opsmanager/automation/describe.go
internal/cli/opsmanager/backup/backup.go
internal/cli/opsmanager/backup/enable.go
internal/cli/opsmanager/backup/enable_test.go
internal/cli/opsmanager/monitoring/enable.go
internal/cli/opsmanager/monitoring/enable_test.go
internal/cli/opsmanager/ops_manager.go
internal/cli/opsmanager/ops_manager_test.go

_Jira ticket:_ CLOUDP-73287
```zsh
$ mongocli om monitoring enable host2
Changes are being applied, please check http://mms:8080/v2/5f43a927c74f75134f354a7a#deployment/topology for status
```
```zsh
$ mongocli om backup enable host2
Changes are being applied, please check http://mms:8080/v2/5f43a927c74f75134f354a7a#deployment/topology for status
```

CLOUDP-73287: allow to enable monitoring or backup agents

---

internal/cli/opsmanager/automation/describe.go
internal/cli/opsmanager/automation/description.go
internal/cli/opsmanager/automation/update.go

_Jira ticket:_ CLOUDP-73535
```
./bin/mongocli om automation
Manage automation configuration for your project.
Usage:
mongocli ops-manager automation [command]
Available Commands:
status      Show the current status of the automation config.
describe    Get the current automation configuration for a project.
update      Update the current automation configuration for a project.
watch       Watch for automation changes to be completed.
Flags:
-h, --help   help for automation
Global Flags:
-P, --profile string   Profile to use from your configuration file.
Use "mongocli ops-manager automation [command] --help" for more information about a command.
```

CLOUDP-73535: Unhide and document automation config get and automation config update

---

build/package/generate-notices.sh

CLOUDP-73709: mongocli brew permissions issue for Linux TGZ - 1.5 & 1.6

---

go.mod
go.sum
internal/cli/config/config.go
internal/cli/iam/organizations/list.go
internal/cli/iam/organizations/list_test.go
internal/flag/flags.go
internal/mocks/mock_organizations.go
internal/store/organizations.go
internal/usage/usage.go

_Jira ticket:_ CLOUDP-74829
Update mcli ORG api calls to use OrganizationsListOptions

CLOUDP-74829: Update mcli ORG api calls

---

go.mod
go.sum
internal/convert/cluster_config.go
internal/convert/cluster_config_test.go
internal/fixture/automation_configs.go

CLOUDP-77170: [mongocli] Preserve args_26 maps when updating a cluster

---

internal/cli/opsmanager/processes/list.go

_Jira ticket:_ CLOUDP-77819
This change sneaked in when I changed the usage, this si a quick fix for the output

CLOUDP-77819: mongocli om process ls is all one line

---

e2e/atlas/helper_test.go
e2e/atlas/logs_test.go
internal/cli/atlas/logs/download.go
internal/cli/atlas/logs/download_test.go

CLOUDP-78065: [mongocli] atlas logs download doesn’t work if --out is not provided

---

e2e/atlas/helper_test.go
go.mod
internal/convert/process_config.go
internal/convert/process_config_test.go

CLOUDP-78654: Missing audit filter on convert

---

internal/cli/atlas/cloudproviders/accessroles/aws/deauthorize.go
internal/cli/atlas/cloudproviders/accessroles/aws/deauthorize_test.go
internal/cli/delete_opts.go
internal/prompt/prompt.go

_Jira ticket:_ CLOUDP-80279
```
./bin/mongocli atlas cloudProviders accessRoles aws deauthorize 5ffd8cc17bd5c049ef1c88f5
? Are you sure you want to deauthorize 5ffd8cc17bd5c049ef1c88f5 Yes
AWS IAM role successfully deauthorized.
```
```
./bin/mongocli atlas cloudProviders accessRoles aws deauthorize 5ffd898d15a4f913021b9305
? Are you sure you want to deauthorize 5ffd898d15a4f913021b9305 No
AWS IAM role not deauthorized.
```

CLOUDP-80279: Add a confirmation message to Deauthorize a Cloud Provider Access Role

---

internal/cli/atlas/privateendpoints/list.go
internal/cli/atlas/privateendpoints/list_test.go
internal/mocks/mock_private_endpoints.go
internal/store/private_endpoints.go
internal/usage/usage.go

_Jira ticket:_ CLOUDP-79631
```
./bin/mongocli atlas privateEndpoint list
ID                         ENDPOINT SERVICE                                          STATUS             ERROR
5f3fb2c58ef2cb1c795cddbb   com.amazonaws.vpce.us-east-2.vpce-svc-09c771f7ad2a628e8   WAITING_FOR_USER
5f999db19900d15068d425c9   com.amazonaws.vpce.us-east-1.vpce-svc-079752da00a0d26a4   WAITING_FOR_USER
5fff12b1fd7c32762a6d7e30   com.amazonaws.vpce.eu-west-1.vpce-svc-074a4307981953ad4   WAITING_FOR_USER
```
```
./bin/mongocli atlas privateEndpoint list --provider AZURE
ID                         ENDPOINT SERVICE         STATUS      ERROR
5fff120253b6064ef7de897e   PrivateLinkServiceName   AVAILABLE
```
```
./bin/mongocli atlas privateEndpoint list --provider AZURE -o json
[
{
"id": …
```

CLOUDP-79631: Retrieve details for all private endpoint service for AWS or Azure in an Atlas project

---

internal/cli/opsmanager/serverusage/organizations/organizations.go

_Jira ticket:_ CLOUDP-80528
`mongocli server usage organization host ls` does not work. The error is due to `organization.go` pointing to the wrong command.

CLOUDP-80528: mongocli server usage organiation host ls pointing to project

---

internal/cli/opsmanager/featurepolicies/list.go

_Jira ticket:_ CLOUDP-80762
Error:
```
mongocli om featurePolicies list -P om
Error: template: output:2:38: executing "output" at <.ExternalManagementSystem.Name>: nil pointer evaluating *opsmngr.ExternalManagementSystem.Name
```
Fix:
```
./bin/mongocli om featurePolicies list -P ops
NAME   SYSTEM ID   POLICY
```

CLOUDP-80762: mongocli om featurePolicies list return an error if not policies are defined in the project

---

cmd/mongocli/mongocli.go
internal/cli/atlas/atlas.go
internal/cli/atlas/clusters/create.go
internal/cli/cloudmanager/cloud_manager.go
internal/cli/iam/iam.go
internal/cli/opsmanager/ops_manager.go
internal/store/store.go

_Jira ticket:_ CLOUDP-81627
Default timeouts were too long for users using ops manager with no access to Atlas and just doing `mongocli --version` could take a long time
I'm handling this in two ways, not longer use of default timeouts and also lowering some of the ones we had. and we'll no longer include the Atlas branch if we don't need to, saving the call completely

CLOUDP-81627: Improve Atlas cluster create dynamic version for limited internet envs

---

e2e/atlas/dbusers_test.go
internal/cli/atlas/dbusers/create.go
internal/cli/atlas/dbusers/update.go
internal/convert/database_user.go
internal/convert/database_user_test.go

_Jira ticket:_ CLOUDP-81757
This was discussed in the spec but it looks like we missed it on the review

CLOUDP-81757: Use correct separator for dbuser scopes

---

internal/cli/atlas/privateendpoints/aws/interfaces/create.go
internal/cli/atlas/privateendpoints/aws/interfaces/delete.go
internal/cli/atlas/privateendpoints/aws/interfaces/delete_test.go
internal/cli/atlas/privateendpoints/aws/interfaces/describe.go
internal/cli/atlas/privateendpoints/aws/interfaces/describe_test.go
internal/cli/atlas/privateendpoints/azure/interfaces/create.go
internal/cli/atlas/privateendpoints/azure/interfaces/delete.go
internal/cli/atlas/privateendpoints/azure/interfaces/delete_test.go
internal/cli/atlas/privateendpoints/azure/interfaces/describe.go
internal/cli/atlas/privateendpoints/azure/interfaces/describe_test.go
internal/flag/flags.go
internal/store/private_endpoints.go
internal/usage/usage.go

_Jira ticket:_ CLOUDP-83534
**DELETE** 
Endpoint: [DELETE /groups/{GROUP-ID}/privateEndpoint/{CLOUD-PROVIDER}/endpointService/{ENDPOINT-SERVICE-ID}/endpoint/{ENDPOINT-ID}](https://docs.atlas.mongodb.com/reference/api/private-endpoints-endpoint-delete-one/)
```
./bin/mongocli atlas privateendpoint aws interface delete --help
Delete a specific AWS private endpoint interface and the related endpoint service for your project.
Usage:
mongocli atlas privateEndpoints aws interfaces delete <atlasPrivateEndpointId> [flags]
Aliases:
delete, rm
Flags:
--force                             Don't ask for confirmation.
-h, --help                              help for delete
--endpointServiceId string   Unique identifier of the private endpoint service for which you want to retrieve a private endpoint. …
```

CLOUDP-83534: mongocli atlas privateEndpoint(s)|privateendpoint(s)aws |azure interface(s) delete privateEndpointId doesn't work as expected

---

internal/validate/validate.go

_Jira ticket:_ CLOUDP-83921
This PR tries to do something similar to how we offer usage on missing args
```bash
mongocli config get
Error: "mongocli config describe" requires 1 argument
Usage:  mongocli config describe <name> [flags]
```
If there are no credentials then we get something like
```bash
mongocli iam projects ls
Error: missing credentials
To set credentials, run: mongocli config
```

CLOUDP-83921: Offer a suggestion when missing credentials

---

Makefile
build/ci/check-licenses.sh
build/ci/evergreen.yml
build/package/generate-notices.sh

_Jira ticket:_ CLOUDP-85231
With go1.16 we no longer need to be hopping dirs t avoid unintended changes to the go.mod file

CLOUDP-85231: No path hacking needed with go1.16

---

internal/cli/alerts/acknowledge_test.go

The failure in `acknowledge_test.go` seem related to `t.Parallel()`.Indeed the mock returns the error even if `wantErr` is false for the test case `forever`
```
ok  	github.com/mongodb/mongocli/internal/cli	0.189s	coverage: 32.3% of statements
&{      <nil>         <nil>   [] <nil> []}
&{      <nil>         <nil>   [] <nil> []}
--- FAIL: TestAcknowledgeOpts_Run (0.00s)
--- FAIL: TestAcknowledgeOpts_Run/forever (0.00s)
acknowledge_test.go:106: 
Error Trace:	acknowledge_test.go:106
Error:      	Received unexpected error:
fake
Test:       	TestAcknowledgeOpts_Run/forever
--- FAIL: TestAcknowledgeOpts_Run/with_error (0.00s)
acknowledge_test.go:98: 
Error Trace:	acknowledge_test.go:98
Error:      	An error is expected but got nil.
Test: …
```

Fixed acknowledge_test.go

---

.githooks/pre-commit
scripts/fmt.sh

Only format changed go on `make fmt`
The `make fmt` command has become extremely slow and this has been bothering me for a while, the `find` function we used to use it's the bottle neck, so changing it to behave in a similar way as we handle the pre-commit and only format changed files
Also drive by fix to the pre commit to not format mocks and re add changed files

feat: improve go fmt calls

---

.golangci.yml
internal/cli/atlas/clusters/create.go
internal/cli/atlas/clusters/delete.go
internal/cli/atlas/dbusers/create.go
internal/cli/atlas/quickstart/quick_start.go
internal/cli/global_opts.go
internal/cli/opsmanager/clusters/delete.go
internal/convert/cluster_config_test.go
internal/convert/process_config.go
internal/convert/process_config_test.go
internal/docs/rest/rest.go
internal/test/fixture/automation_configs.go

`golint` has been deprecated and the recommended replacement is `revive`

feat: replace golint with revive

---

internal/cli/atlas/atlas.go
internal/cli/atlas/clusters/create.go
internal/cli/atlas/quickstart/quick_start.go
internal/cli/atlas_cluster_opts.go
internal/cli/opsmanager/ops_manager.go

Came to fix a typo but a couple of other small fixes showed up
- We have a function to get the current major version from atlas, using that instead of a hardcoded value
- From user feedback we know some users may want to set the tier for the cluster, we won't ask it but a flag is now available for it
- Fix a typo

feat: use Atlas default major version API for quickstart

---

build/ci/evergreen.yml
internal/docs/main.go
internal/docs/rest/rest.go

This PR renames the auto-generated docs output directory from "/reference" to "/command". On the Docs side, we decided that we should still have a separate "/reference" directory for any miscellaneous reference material that we might need to provide in the future.
This also means that the auto-generated command reference pages will have a nice semantic URL like `https://docs.mongodb.com/mongocli/v1.16/command/mongocli-atlas-clusters-create/`
[Docs Staged Example](https://docs-mongodbcom-staging.corp.mongodb.com/mongocli/docsworker-xlarge/autogen-ref-docs/command/mongocli/)
@gssbzn I did my best but please let me know if I missed anything :)

Update docs output folder to /command instead of /reference

---

internal/cli/iam/projects/create.go

fix: fix project creation template

---

go.mod
go.sum
internal/cli/atlas/quickstart/dbuser_setup.go
internal/cli/atlas/quickstart/quick_start.go
internal/flag/flags.go
internal/usage/usage.go

Added a new `--default|Y` flag to the quickstart command.
Default values set by the flag:
- ClusterName: Quickstart-1624002722 (Autogenerated)
- Cloud Provider: AWS
- Tier: M2
- Region: US_EAST_1
- Sample data: No
- DB user Username: Quickstart-1624002776 (Autogenerated)
- DB Password: akxxR3dBZ05n (Autogenerated)
- Access List Entry: Public IP address of the user; None if the call returns an error
- MongoShell: No
_Jira ticket:_ CLOUDP-92550
```
./bin/mongocli atlas quickstart --default
We are deploying Quickstart-1625554688...
Creating your cluster... [It's safe to 'Ctrl + C']
|
Now you can connect to your Atlas cluster …
```

CLOUDP-92550: Add --default flag to the Quickstart command

---

build/ci/evergreen.yml
build/package/send-slack-notification.sh

_Jira ticket:_ CLOUDP-94311
Genertae docs on release and include on our internal announcement a link to it so docs can easily grave them

CLOUDP-94311: Include generated docs in release tasks an notifications

---

internal/usage/usage.go

[JIRA](https://jira.mongodb.org/browse/DOCSP-17411)
Updates the description of the `--service` option in the help and generated docs to include the value `cloudgov`.

(DOCSP-17411): Add support for Atlas Gov

---

internal/cli/root/builder.go
internal/cli/root/builder_test.go

_Jira ticket:_ CLOUDP-94849
With cobra 1.2.0 the completion command is now automagically generated we don't need to do it ourselves

CLOUDP-94849: Use cobra autocomplete instead of internal

---

go.mod
go.sum
internal/config/home.go
internal/config/home_test.go

_Jira ticket:_ CLOUDP-95949
Go has now (since 1.12) native support for this without using cgo

CLOUDP-95949: Stop using go-homedir

---

internal/cli/require/require.go

_Jira ticket:_ CLOUDP-96279
This came from a ticket where users were inadvertently passing more than one parameter and not being aware of this caused them to open the ticket

CLOUDP-96279: Improve arg validation to show number of given args

---

internal/docs/main.go

This is about making `make gen-docs` aware of deleting or renaming commands.
_Jira ticket:_ CLOUDP-93453
changed `make gen-docs`

CLOUDP-93453: Cater for deleting commands

---

internal/cli/atlas/quickstart/access_list_setup.go
internal/cli/atlas/quickstart/quick_start.go
internal/validate/validate.go

Quickstart Improvements from Product Design & Research:
- CLOUDP-95678: Allow adding multiple IP addresses in the interactive mode
- CLOUDP-95677: Update the error message for the cluster name to include used rules.
_Jira ticket:_ CLOUDP-95678

Quickstart Improvements from Product Design & Research

---

internal/config/profile_test.go
internal/validate/validate_test.go

test: use t.Setenv instead of os.Setenv

---

docs/command/mongocli-atlas-quickstart.txt
internal/cli/atlas/quickstart/cluster_setup.go
internal/cli/atlas/quickstart/confirm_cluster_setup.go
internal/cli/atlas/quickstart/prompt.go
internal/cli/atlas/quickstart/quick_start.go
internal/cli/atlas/quickstart/quick_start_test.go

* Confirm before makign a cluster with quickstart
* Add summary of changes before creating cluster
_Jira ticket:_ CLOUDP-95673
Command:
```
bin/mongocli atlas quickstart --profile=atlas-dev --tier M0
? Cluster Name [This can't be changed later] Quickstart-1632214919
? Cloud Provider Region US_EAST_1
? Do you want to load sample data into Quickstart-1632214919? No
[Set up your database authentication access details]
? Database User Username Quickstart-1632214919
? Database User Password [Press Enter to use an auto-generated password '<REDACTED>'] <REDACTED>
[Set up your database network access details] …
```

CLOUDP-95673: Quickstart cluster creation confirmation

---

.goreleaser.yml
build/package/generate-msi.sh

Add missing commit info to msi windows package

fix: add missing commit info to msi windows package

---

docs/command/mongocli-ops-manager-owner-create.txt
internal/cli/alerts/settings/create.go
internal/cli/opsmanager/owner/create.go

_Jira ticket:_ CLOUDP-108533
Owner creation takes no arg so `cobra.OnlyValidArgs` is not correct, we should use `require.NoArgs`

CLOUDP-108533: Use correct arg validation for owner creation

---

build/ci/evergreen.yml
build/package/mac_notarize.sh

CLOUDP-110092: [MongoCLI] update macOs service to v3.1.0 and use env variables instead of flags for the creds

---

e2e/atlas/atlas_e2e_test_generator_test.go
internal/cli/atlas/privateendpoints/gcp/delete.go

_Jira ticket:_ CLOUDP-110355
This PR increases the number of attempts to delete an atlas project as, after testing, I have noticed that deleting completely a GCP private endpoint takes up to 4 minutes.

CLOUDP-110355: E2E Atlas Networking Tests is failing

---

e2e/atlas/private_endpoint_test.go

This PR removes most of the AWS regions used by aws private endpoint e2e tests. We keep only the ones that we are sure to work on cloud-dev.
```
[2022/01/21 11:06:56.978] === RUN   TestPrivateEndpointsAWS/Create
[2022/01/21 11:06:56.978]     private_endpoint_test.go:78:
[2022/01/21 11:06:56.978]         	Error Trace:	private_endpoint_test.go:78
[2022/01/21 11:06:56.978]         	Error:      	Received unexpected error:
[2022/01/21 11:06:56.978]         	            	exit status 1
[2022/01/21 11:06:56.978]         	Test:       	TestPrivateEndpointsAWS/Create
[2022/01/21 11:06:56.978]         	Messages:   	Error: POST https://cloud-dev.mongodb.com/api/atlas/v1.0/groups/61ea93cf8206834ad49a9228/privateEndpoint/endpointService: 400 (request "ATLAS_GENERAL_ERROR") Reason: No Capacity. …
```

Fix no Capacity error in private endpoint e2e tests

---

internal/config/profile.go

Redact tokens when using `mongocli config describe`

fix: redact tokens when using config commands

---

docs/command/mongocli-auth-login.txt
docs/command/mongocli-auth-logout.txt
docs/command/mongocli-auth-whoami.txt
docs/command/mongocli-auth.txt
docs/command/mongocli.txt
internal/cli/auth/logout.go
internal/cli/root/builder.go
internal/cli/root/builder_test.go

_Jira ticket:_ CLOUDP-111671
Enables the auth set of commands and adds a couple of hidden shortcuts

CLOUDP-111671: [mongocli] Enable auth commands

---

go.mod
go.sum
internal/cli/auth/login.go
internal/cli/auth/login_test.go
internal/cli/auth/logout.go
internal/cli/auth/logout_test.go
internal/cli/auth/whoami.go
internal/config/profile.go
internal/mocks/mock_login.go
internal/mocks/mock_logout.go
internal/store/store.go
internal/store/store_test.go
internal/validate/validate.go
internal/validate/validate_test.go

_Jira ticket:_ CLOUDP-112072
Depends on https://github.com/mongodb/go-client-mongodb-atlas/pull/277
- Encapsulate JWT parsing to only expose the subject (what we care)
- Refactor configuration to expose the Access struct from the atlas sdk so we can reuse the whole information when refreshing tokens

CLOUDP-112072: Improve cli credential (jwt) handling

---

build/ci/release.yml
internal/flag/flags.go
internal/release/main.go
internal/release/main_test.go

_Jira ticket:_ CLOUDP-114066
Issue: We are not adding the release version when generating the download center json file.
```json
{
"previous_releases_link": "https://github.com/mongodb/mongocli/releases",
"release_date": "2022-02-28T17:01:01.938089Z",
"release_notes_link": "https://docs.mongodb.com/mongocli/v/release-notes/",
"tutorial_link": "https://docs.mongodb.com/mongocli/v/quick-start/",
"version": "",
"manual_link": "https://docs.mongodb.com/mongocli/v/",
"platform": [
{
"arch": "x86_64",
"os": "Linux (x86_64)",
"packages": {
"title": "MongoDB CLI",
"links": [
{
"download_link": "https://fastdl.mongodb.org/mongocli/mongocli__linux_x86_64.tar.gz",
"name": "tar.gz"
}
]
}
},
```
**New download center JSON files:**
- [mongodb-atlas-cli.json](https://mongodb-mongocli-build.s3.amazonaws.c …

CLOUDP-114066: [MongoCLI] The json file of the download center doesn’t contain the release version

---

docs/atlascli/command/atlas-clusters-create.txt
docs/atlascli/command/atlas-clusters.txt
docs/atlascli/command/atlas-config-init.txt
docs/atlascli/command/atlas-config-set.txt
docs/atlascli/command/atlas-config.txt
docs/atlascli/command/atlas.txt
docs/mongocli/command/mongocli-atlas-clusters-create.txt
docs/mongocli/command/mongocli-atlas-clusters.txt

_Jira ticket:_ CLOUDP-112245
After merging #975, doc test is failing on master. This PR adds missing doc changes that were merged into master before #975. These doc changes have been already approved by Doc team so we don't need to wait for their approval.

CLOUDP-112245: Add missing docs

---

CONTRIBUTING.md
go.mod
go.sum
internal/cli/figautocomplete/fig_autocomplete.go
internal/cli/figautocomplete/fig_autocomplete_test.go
internal/cli/opsmanager/clusters/unmanage.go
internal/cli/performanceadvisor/slowoperationthreshold/slow_operation_threshold.go
internal/cli/root/atlas/builder.go
internal/cli/root/atlas/builder_test.go
internal/cli/root/mongocli/builder.go
internal/cli/root/mongocli/builder_test.go

Add Fig integration to generate a fig spec when `mongocli fig-autocomplete` is run.
This is far by actually providing the full integration with autocomplete repo, but I prefer to split it in smaller PRs that can be merged faster.

feat: add `fig-autocomplete` subcommand

---

build/ci/evergreen.yml
build/ci/release.yml

In #1014 we started using `git tag --sort=committerdate` which is not available for git version 1.8.3.1, the version
shipped with Red Hat 7 ([error](https://evergreen.mongodb.com/task_log_raw/mongocli_master_e2e_ops_manager_44_ops_manager_4_4_deploy_replica_set_e2e_5db0fa1d7119cbe3dfe2846583efef62ad6b6b12_22_03_04_11_42_46/0?type=T#L21)).
This PR updates our evergreen tests to use Rhel 8

Upgrating evergreen hosts to Rhel 8

---

internal/cli/atlas/config/init.go
internal/cli/auth/login.go
internal/cli/auth/login_test.go
internal/cli/config/config.go
internal/cli/config/config_test.go
internal/cli/config_opts.go
internal/cli/default_setter_opts.go
internal/test/test.go

_Jira ticket:_ CLOUDP-114507
I spent quite some time trying to add a test to avoid this happening again but can't say I have found a good way to do it, having to pass things from stdin to the commands makes it complicated

CLOUDP-114507: [MongoCLI] mongocli config --service ops-manager is not adding ops_manager_url to config

---

build/ci/release.yml

Atas msi release task failed because we were adding the msi file to the wrong folder in the download center s3 bucket ([error](https://evergreen.mongodb.com/task_log_raw/mongocli_master_release_atlascli_msi_release_msi__atlascli_v0.0.1_22_03_04_16_11_31/0?type=T#L123)).
This PR adds the atlascli msi file in the same mongocli folder in the download center s3 bucket

Release Fix: Updated download center s3 bucket name

---

build/ci/release.yml

Issue: I have previously commented out the step where we were uploading the atlascli binaries in the download center s3 bucket because I thought we had to wait for the go-ahead from the marketing team. Long story short, we (APIx) are responsible for the mongocli folder on the download center s3 bucket so as long as we provide the `download_center.json` file with correct paths to the binaries to the marketing team, we are granted.
This PR removes the commented step in the atlascli release process.

Release Fix: Upload atlascli binaries in the s3 bucket

---

internal/cli/auth/login.go
internal/cli/auth/login_test.go

fix: fix copy for the login command

---

docs/atlascli/command/atlas-logs-decrypt.txt
docs/atlascli/command/atlas-logs-keyProviders-list.txt
docs/atlascli/command/atlas-logs-keyProviders.txt
docs/mongocli/command/mongocli-cloud-manager-logs-decrypt.txt
docs/mongocli/command/mongocli-ops-manager-logs-decrypt.txt
internal/cli/atlas/atlas.go
internal/cli/atlas/logs/decrypt.go
internal/cli/atlas/logs/decrypt_test.go
internal/cli/atlas/logs/key_providers.go
internal/cli/atlas/logs/key_providers_test.go
internal/cli/atlas/logs/list_key_provider.go
internal/cli/atlas/logs/list_key_provider_test.go
internal/cli/atlas/logs/logs.go
internal/cli/atlas/logs/logs_test.go
internal/cli/opsmanager/logs/decrypt.go
internal/cli/opsmanager/logs/decrypt_test.go
internal/cli/opsmanager/logs/logs_test.go
internal/flag/flags.go
internal/usage/usage.go

_Jira ticket:_ [CLOUDP-114869](https://jira.mongodb.org/browse/CLOUDP-114869)
Commands:
`atlas logs keyProviders list --file test`
`atlas logs decrypt --file test`
* Note: adding commands only to atlascli
* Note: code for keyProviders list the same as ops-manager/cloud-manager
```
➜  mongocli git:(CLOUDP-114869) ./bin/atlas logs decrypt --file tst
tst
mongocli git:(CLOUDP-114869) ./bin/atlas logs decrypt --help
Decrypts a log file with the provided local key file or KMIP files.
Usage:
atlas logs decrypt [flags]
Examples:
$ atlas decrypt --file logPath --out resultPath --awsAccessKey accessKey --awsSecretKey secretKey --awsSessionToken sessionToken
Flags:
--awsAccessKey string           AWS Access Key ID that is part of long-term credentials.
--awsSecretKey string           AWS Secret …
```

CLOUDP-114869: Add atlascli commands

---

.atlascli.goreleaser.yml

_Jira ticket:_ CLOUDP-115561
During my testing of the release candidate, I have noticed that we are not setting the tool name at build time when releasing atlas cli.
```
atlas --version
mongocli version: 1.0.0-rc0
git version: 87da56233dfcd1d13aa99b98381f2cbc8e50b010
Go version: go1.17
os: linux
arch: amd64
compiler: gc
ubuntu@ip-10-0-1-10:~$
```
**Solution:**
This PR adds the atlascli tool name at build time in the release process.
```
atlas --version
atlascli version: 1.0.0-rc0
git version: f7d27912cf2cc0151a692fdc74699228b033cf67
Go version: go1.17
os: darwin
arch: amd64
compiler: gc
```

CLOUDP-115561: [Atlas CLI] Add toolName in goreleaser

---

internal/cli/root/atlas/builder_test.go
internal/cli/root/mongocli/builder_test.go
internal/latestrelease/finder.go

While testing, noticed that since we discard pre-releases, atlaslci was returning nil and crashing. Added a fix and tests for both mongocli and atlascli
```
➜  mongocli git:(atlascli-npe-fix) ✗ ./bin/atlas config list
PROFILE NAME
default
test
```

Fix NPE for AtlasCLI and add tests

---

.atlascli.goreleaser.yml
.mongocli.goreleaser.yml

_Jira ticket:_ CLOUDP-115583
We had set the flag `prerelease: true` in the atlascli goreleaser file as a precaution. Now that we are ready to release v1.0.0 we have to set `prerelease` to `auto`
See [goreleaser doc](https://goreleaser.com/customization/release/#github)
```
prerelease: auto
```

CLOUDP-115583: [AtlasCLI] Update go releaser for the stable release

---

docs/mongocli/command/mongocli-config.txt
internal/cli/config/config.go
internal/validate/validate.go

_Jira ticket:_ CLOUDP-115605
**Issue**: users can only run the config command with `--service ops-manager` or `--service cloud-manager`. If they try to run `config --service opsmanager` they are not able to config mongocli with ops manager
**The goal of this PR is to allow users to use `opsmanager`, `om`, `cloudmanager`, and `cm` with the `mongocli config` command.**
```
./bin/mongocli config --help
Configure settings in a user profile.
All settings are optional. You can specify settings individually by running:
$ mongocli config set --help
You can also use environment variables (MCLI_*) when running the tool.
To find out more, see the documentation: https://docs.mongodb.com/mongocli/stable/configure/environment-variables/.
Usage:
mongocli config [flags]
mongocli config [command] …
```

CLOUDP-115605: [MongoCLI] Improve config command to accept opsmanager

---

internal/cli/opsmanager/logs/list_key_provider.go
internal/cli/opsmanager/logs/list_key_provider_test.go
internal/decryption/decryption.go
internal/decryption/encrypted_audit_log.go

Implement `mongocli om logs keyProvider list` command
_Jira ticket:_ CLOUDP-112126
Run `mongocli om logs keyProvider list --file test.json`
Result:
```
local: Filename = localKey
kmip: Unique Key ID = "uniqueKeyID" Kmip Server Name = "kmipServerName" Kmip Port = "kmipPort" Key Wrap Method = "get"
```
`test.json`
```json
{"ts":{"$date":{"$numberLong":"1644232049921"}},"version":"0.0","compressionMode":"zstd","keyStoreIdentifier":{"provider":"local","filename":"localKey"},"encryptedKey":{"$binary":{"base64":"+yjPCaKKE1M8fZmPGzGHkyfHYxaw34okpavsHzpd8iPVx2+JjOhXwXw5E2FdI5Rcb5JgmcPUFRPISh/7Si1R/g==","subType":"0"}},"MAC":"qE9fUsGK0EuRrrCRAQAAAAAAAAAAAAAA","auditRecordType":"header"}
{"ts":{"$date":{"$numberLong":"1644232049922"}},"log":"1Lu4o8XVMM/Rg7GKAQAAAAEAAAAAAAAA/8t …
```

CLOUDP-112126: logs keyProvider list command

---

internal/decryption/decryption.go
internal/decryption/header.go
internal/decryption/log_record.go

Validate encrypted audit log records
_Jira ticket:_ CLOUDP-112093
Error results will be unformatted example:
```json
{"uuid":{"$binary":{"base64":"+mOPbB12RDGgTsXXjR8R/A==","subType":"04"}},"local":{"isSystemUser":true},"roles":[],"result":0,"ts":{"$date":"2022-02-07T11:07:29.922Z"},"atype":"startup","remote":{"isSystemUser":true},"users":[],"param":{"options":{"auditLog":{"path":"auditLog.json","compressionMode":"zstd","destination":"file","format":"JSON","localAuditKeyFile":"localKey"}}}}
logRecordIdx missmatch, expected: 2, actual: 3
{"atype":"createCollection","users":[],"param":{"ns":"admin.system.version"},"result":0,"ts":{"$date":"2022-02-07T11:07:30.645Z"},"uuid":{"$binary":{"base64":"+mOPbB12RDGgTsXXjR8R/A==","subType":"04"}},"local":{"isSystemUser":true},"r …
```

CLOUDP-112093: Validate encrypted audit log records

---

e2e/atlas/alerts_test.go
e2e/cloud_manager/alerts_test.go

This PR fixes the failing alerts tests.
**Proposed changes**: we don't check for the alert type but only its status (we need an open alert to test the acknowled|unacknowled commands)

Update alerts e2e tests to not consider alert type

---

internal/cli/auth/login.go

_Jira ticket:_ CLOUDP-117256
```bash
./bin/mongocli login
First, copy your one-time code: DWXF-R48Q
Next, sign in with your browser and enter the code.
Or go to https://account.mongodb.com/account/connect
Your code will expire after 10 minutes.
Error: authentication timed out
```

CLOUDP-117256: Improve expired code handling

---

e2e/brew/brew_test.go
internal/cli/root/atlas/builder.go

running `atlas help` used to require credentials

fix: allow help commands in atlas

---

internal/cli/atlas/atlas.go
internal/cli/atlas/quickstart/prompt.go
internal/cli/atlas/quickstart/quick_start.go
internal/cli/root/atlas/builder.go

_Jira ticket:_ CLOUDP-118459
```bash
./bin/atlas quickstart -P asdasdasd
Error: this action requires authentication
To log in using your Atlas username and password, run: atlas auth login
To set credentials using API keys, run: atlas config init
```

CLOUDP-118459: [cli] quickstart should verify authentication the same as other commands

---

internal/cli/auth/login.go
internal/cli/auth/login_test.go
internal/cli/auth/register.go
internal/cli/auth/register_test.go

_Jira ticket:_ [CLOUDP-120668](https://jira.mongodb.org/browse/CLOUDP-120668)
```shell
➜  mongocli git:(CLOUDP-120668) atlasdev auth register --help
Register with MongoDB Atlas.
Usage:
atlas auth register [flags]
Examples:
To start the interactive setup:
$ atlas auth register
Flags:
--gov          Register to Atlas for Government.
-h, --help         help for register
--noBrowser    Don't try to open a browser session.
--skipConfig   Skip profile configuration.
Global Flags:
-P, --profile string   Profile to use from your configuration file.
```
```shell
➜  mongocli git:(CLOUDP-120668) atlasdev auth register
Create and verify your MongoDB Atlas account from the web browser and return to Atlas CLI after activation.
```

CLOUDP-120668: Add register command skeleton

---

internal/config/profile.go

_Jira ticket:_ CLOUDP-120923
A very simple way to allow telemetry in atlascli only if an environment variable is set, eg:
`% export MONGODB_ATLAS_TELEMETRY_FEATURE_FLAG=true`
Once development is complete and we are ready to roll out telemetry this will be removed (CLOUDP-121000)

CLOUDP-120923: [Atlas CLI] Telemetry - Add Feature Flag

---

docs/atlascli/command/atlas-teams.txt
docs/atlascli/command/atlas-users.txt
docs/mongocli/command/mongocli-iam-teams.txt
docs/mongocli/command/mongocli-iam-users.txt
internal/cli/iam/organizations/invitations/invitations.go
internal/cli/iam/projects/invitations/invitations.go
internal/cli/iam/teams/teams.go
internal/cli/iam/users/users.go

CLOUDP-121186: [AtlasCLI] Update commands's description that still have ops manager

---

CONTRIBUTING.md
e2e/atlas/alerts_test.go

Current E2E relies on an open alert being present on the env, which cannot be guaranteed. Changing the tests to instead rely on a closed alert, of which at least 1 should always be present.

CLOUDP-121631: Changing order to get any closed alert to reduce flakiness

---

docs/atlascli/command/atlas-clusters-create.txt
docs/atlascli/command/atlas-clusters-update.txt
docs/atlascli/command/atlas-clusters-watch.txt
docs/mongocli/command/mongocli-atlas-clusters-update.txt
internal/cli/atlas/clusters/clusters.go
internal/cli/atlas/clusters/create.go
internal/cli/atlas/clusters/update.go
internal/cli/atlas/clusters/watch.go

_Jira ticket:_ CLOUDP-122260
**Issue:** Some atlascli cluster commands still have mongocli in their descriptions.
**Fix:**
```
./bin/atlas cluster create --help
To get started quickly, specify a name for your cluster, a cloud provider, and a region to deploy a three-member replica set with the latest MongoDB server version.
For full control of your deployment, or to create multi-cloud clusters, provide a JSON configuration file with the --file flag.
Usage:
atlas clusters create [name] [flags]
Examples:
Deploy a three-member replica set in AWS:
$ atlas cluster create <clusterName> --projectId <projectId> --provider AWS --region US_EAST_1 --members 3 --tier M10 --mdbVersion 5.0 --diskSizeGB 10
Deploy a three-member replica set in AZURE:
$ atlas cluster create <clusterName> --projectId …
```

CLOUDP-122260: Update atlascli cluster commands description

---

.golangci.yml
internal/cli/auth/login.go
internal/cli/auth/login_test.go
internal/cli/auth/register.go
internal/cli/auth/register_test.go
internal/cli/config/edit.go
internal/cli/default_setter_opts.go
internal/cli/global_opts.go
internal/cli/performance_advisor_opts.go
internal/config/profile.go
internal/decryption/keyproviders/kmip.go
internal/latestrelease/finder.go
internal/store/store_test.go

Enabling some extra linters that I find myself repeating on recent PRs
- [early-return](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#early-return)
- [unused-receiver](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unused-receiver)
- [constant-logical-expr](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#constant-logical-expr)
- [confusing-naming](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#confusing-naming)
- [unnecessary-stmt](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unnecessary-stmt)
- [imports-blacklist](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#imports-blacklist) for github.com/pkg/errors

lint: enable extra revive linters

---

docs/atlascli/command/atlas-quickstart.txt
docs/atlascli/command/atlas-setup.txt
docs/mongocli/command/mongocli-atlas-quickstart.txt
internal/cli/atlas/quickstart/quick_start.go
internal/cli/atlas/setup/setup_cmd.go
internal/usage/usage.go

_Jira ticket:_ [CLOUDP-87997](https://jira.mongodb.org/browse/CLOUDP-87997)
```shell
➜  mongocli git:(CLOUDP-87997) ✗ atlasdev quickstart --currentIp -P apiKeys
Cluster Name:                           Cluster95626
Cloud Provider and Region:              AWS - US_EAST_1
Database Username:                      Cluster95626
Allow connections from (IP Address):    37.228.237.17
? Do you want to set up your first free database in Atlas with default settings (it's free forever)? Yes
We are deploying Cluster95626...
Please store your database authentication access details in a secure location: 
username: Cluster95626 
password: U1declNZQklU
Creating your cluster... [It's safe to 'Ctrl + C']
Creating your cluster... [It's safe to 'Ctrl + C']
Cluster created.
Loading sample data …
```

CLOUDP-87997: Add currentIp flag to quickstart and setup

---

internal/convert/cluster_config.go
internal/convert/errors.go
internal/convert/rs_config.go

Improves error handling for the convert package based on go 1.13 error practices

fix: error handling convert package

---

.github/workflows/golangci-lint.yml
Makefile
cmd/atlas/atlas.go
cmd/mongocli/mongocli.go
internal/cli/atlas/logs/logs.go
internal/cli/atlas/quickstart/access_list_setup.go
internal/cli/atlas/quickstart/quick_start.go

Improvement for some examples that are given as part of commands, to ensure the correct cli (mongocli/atlas cli) help text is returned.
Example in quickstart:
```
atlas quickstart
We could not find your public IP address. To add your IP address run:
atlas accesslist create
...
```
_Jira ticket:_ CLOUDP-123153

CLOUDP-123153: Cleanup help text to remove mongocli for atlas specific commands

---

build/ci/evergreen.yml
internal/cli/atlas/quickstart/confirm_cluster_setup.go
internal/cli/atlas/quickstart/confirm_default_setup.go
internal/cli/atlas/quickstart/quick_start.go
internal/cli/atlas/quickstart/quick_start_test.go
internal/cli/auth/login.go

Part of the bug squash and design feedback
Removing the double statement `Creating your cluster... [It's safe to 'Ctrl + C']`
```shell
➜  mongocli git:(remove_extra_print) atlasdev setup
you are already authenticated with an account (bianca.vianadeaguiar+1234569@mongodb.com)
run "atlas auth setup --profile <profile_name>" to create a new Atlas account on a new Atlas CLI profile
Cluster Name:				Cluster53972
Cloud Provider and Region:		AWS - US_EAST_1
Database User Username:			Cluster53972
Allow connections from (IP Address):	37.228.237.17
? Do you want to set up your first free database in Atlas with default settings (it's free forever)? Yes
We are deploying Cluster53972...
Please store your database authentication access details in a secure location:
Database User …
```

Address design feedback

---

internal/cli/atlas/quickstart/quick_start.go
internal/cli/auth/logout.go
internal/cli/auth/logout_test.go
internal/usage/usage.go

Adds a hidden flag for users who want to keep the config file after logging out.
* Note: Merge only after the Telemetry PR. I don't want to add this to the release.
[CLOUDP-123490)](https://jira.mongodb.org/browse/CLOUDP-123490)

CLOUDP-123490: Hidden keep flag

---

internal/telemetry/event.go
internal/telemetry/event_test.go
internal/telemetry/tracker.go

Telemetry - Track Prompt Select Choice
_Jira ticket:_ CLOUDP-123316

CLOUDP-123316: Telemetry - Track Prompt Select Choice

---

internal/cli/atlas/quickstart/quick_start.go
internal/cli/atlas/quickstart/quick_start_test.go
internal/cli/atlas/setup/setup_cmd.go
internal/cli/atlas/setup/setup_cmd_test.go
internal/cli/auth/register_test.go
internal/cli/auth/status.go
internal/cli/auth/status_test.go
internal/cli/root/atlas/builder.go

_Jira ticket:_ [CLOUDP-124560](https://jira.mongodb.org/browse/CLOUDP-124560)
```shell
➜  mongocli git:(CLOUDP-124560) ✗ atlasdev quickstart -P oie --force
Error: this action requires authentication
To log in using your Atlas username and password, run: atlas auth login
To set credentials using API keys, run: atlas config init
```
```shell
➜  mongocli git:(CLOUDP-124560) ✗ atlasdev quickstart -P oie
This action requires authentication.
To verify your account, copy your one-time verification code:
Y66W-KR6P
Paste the code in the browser when prompted to activate your Atlas CLI. Your code will expire after 10 minutes.
To continue, go to https://account.mongodb.com/account/connect
```

CLOUDP-124560: Add login to quickstart

---

internal/cli/atlas/quickstart/quick_start_test.go
internal/cli/atlas/setup/setup_cmd_test.go
internal/cli/auth/login_test.go
internal/cli/auth/register_test.go
internal/cli/auth/status.go
internal/cli/auth/status_test.go
internal/telemetry/event_test.go
internal/test/test.go

_Jira ticket:_ [CLOUDP-122445](https://jira.mongodb.org/browse/CLOUDP-122445)

CLOUDP-122445: Clean up config after tests 

---

internal/decryption/audit_log_line_scanner_test.go
internal/decryption/header_test.go

Audit logs tests starting failing locally for me. the deep equals we implemented was failing for some reason, i managed to fix this by moving to `github.com/go-test/deep` so the error was probably on the byte generation we were using 
Additional "drive by"s to improve how we were doing matrix test as we were not naming them (which added complexity on debugging the failure) and we were not nesting them in a `t.Run` call back

tests: fix tests for audit_log_line_scanner_test

---

internal/cli/atlas/quickstart/access_list_setup.go
internal/cli/atlas/quickstart/cluster_setup.go
internal/cli/atlas/quickstart/confirm_cluster_setup.go
internal/cli/atlas/quickstart/dbuser_setup.go
internal/cli/atlas/quickstart/quick_start.go
internal/cli/atlas/quickstart/quick_start_test.go

_Jira ticket:_ [CLOUDP-118914](https://jira.mongodb.org/browse/CLOUDP-118914)
```shell
➜  mongocli git:(CLOUDP-118914) atlasdev quickstart --clusterName cs
Cluster Name:				cs
Cloud Provider and Region:		AWS - US_EAST_1
Database User Username:			Cluster85670
Load sample data:			Yes
Allow connections from (IP Address):	184.75.19.146
? Do you want to set up your first free database in Atlas with default settings (it's free forever)? No
? Cloud Provider Region US_EAST_2
? Do you want to load sample data into cs? No
[Set up your database authentication access details. Store them in a secure location.]
? Database User Username my_username
? Database …
```

 CLOUDP-118914: Save selected values and ask setup in a loop

---

internal/sighandle/sighandle.go

Fix race condition for sighandle
_Jira ticket:_ CLOUDP-125763

CLOUDP-125763: Fix race condition for sighandle

---

internal/cli/atlas/privateendpoints/aws/describe.go
internal/validate/validate.go

Follow up to #1313
```bash
./bin/atlas privateendpoints aws describe 6c 
Error: the provided value '6c' is not a valid ID
```

CLOUDP-124966: validate arg is an objectID

---

.golangci.yml

We don't use any go 1.18 feature (generics) so we can ping the go version in golangci lint to 1.17 and get rid of the following warnings
```
golangci-lint run --fix
WARN [linters context] bodyclose is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649.
WARN [linters context] noctx is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649.
WARN [linters context] rowserrcheck is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649.
WARN [linters context] structcheck is disabled because of go1.18. You can …
```

fix: remove golangci-lint warnings

---

Makefile
build/ci/check-licenses.sh
build/ci/evergreen-generate-tasks.sh
build/ci/evergreen.yml
build/ci/release.yml
build/package/generate-notices.sh

golangci-lint isn't properly installed by Makefile, this PR changes the install location to be `$GOPATH/bin` instead of `/path/to/mongodb-atlas-cli/bin` and adds it to `$PATH` when running commands.
_Jira ticket:_ CLOUDP-126655
This PR changes:
- the installation directory of golangci-lint to be in GOPATH (`go env GOPATH`) which makes it globally available
- added missing tool into `make setup` (`github.com/google/go-licenses`)
- made GOPATH consistent across all tasks in evergreen

CLOUDP-126655: golangci-lint isn't properly installed by Makefile

---

internal/cli/atlas/clusters/watch.go
internal/cli/watch_opts.go

Adds exponential backoff when watching a cluster to avoid a problem when the cluster becomes unavailable for a few seconds during the upgrade process. It happens because the upgrade endpoint logic is as follows:
1. find a cluster to upgrade
2. copy all the data to a new cluster
3. delete the old cluster
4. rename the new cluster
Between steps 3 and 4, there are a few seconds when the cluster with the name that we're watching for is not available. This PR fixes this issue by waiting exponentially to check if the upgrade process is still in progress.
**Important**: This feature will only allow the `watch` command to recover from 404 for up to 7 seconds. If it takes longer for the server to respond, the command needs to be re-run. 
_Jira ticket:_ …

CLOUDP-127992: Add exponential backoff when watching a cluster

---

build/ci/evergreen.yml
test/e2e/atlas/backup_export_buckets_test.go
test/e2e/atlas/backup_test.go
test/e2e/atlas/helper_test.go

Adds e2e test for "atlas backup exports buckets" command.
_Jira ticket:_ [CLOUDP-131035](https://jira.mongodb.org/browse/CLOUDP-131035)

CLOUDP-131035: Add e2e test for "atlas backup exports buckets" commands

---

test/e2e/atlas/helper_test.go
test/e2e/atlas/integrations_test.go

Datadog integration is disabled in cloudgov
_Jira ticket:_ CLOUDP-132962

CLOUDP-132962: Datadog integration is disabled in cloudgov

---

docs/mongocli/command/mongocli-ops-manager-serverUsage-organizations-hosts-list.txt
docs/mongocli/command/mongocli-ops-manager-serverUsage-projects-hosts-list.txt
internal/cli/opsmanager/serverusage/organizations/hosts/list.go
internal/cli/opsmanager/serverusage/projects/hosts/list.go

_Jira ticket:_ CLOUDP-132456
For these APIs the default starting page is zero(0)

CLOUDP-132456: MongoCLI pagination for endpoint starts with 1 by default

---

docs/atlascli/command/atlas-clusters-create.txt
docs/atlascli/command/atlas-clusters-update.txt
docs/atlascli/command/atlas-clusters-upgrade.txt
docs/mongocli/command/mongocli-atlas-clusters-create.txt
docs/mongocli/command/mongocli-atlas-clusters-update.txt
internal/usage/usage.go

Adds link to docs page on config files wherever the description of the -f flag appears in docs
_Jira ticket:_ DOCSP-24648

(DOCSP-24648) Add docs link to config file page

---

docs/atlascli/command/atlas-config-edit.txt
docs/atlascli/command/atlas-config.txt
docs/mongocli/command/mongocli-config-edit.txt
docs/mongocli/command/mongocli-config.txt
internal/cli/config/edit.go

CLOUDP-134983: [AtlasCLI] Add command to allow customer to open config file on their default editor

---

docs/atlascli/command/atlas-liveMigrations-create.txt
docs/atlascli/command/atlas-liveMigrations-validation-create.txt
docs/mongocli/command/mongocli-atlas-liveMigrations-create.txt
docs/mongocli/command/mongocli-atlas-liveMigrations-validation-create.txt
internal/cli/atlas/livemigrations/options/live_migrations_opts.go
internal/cli/atlas/livemigrations/validation/create.go
internal/cli/atlas/livemigrations/validation/create_test.go

_Jira ticket:_ [HELP-37776](https://jira.mongodb.org/browse/HELP-37776)
**Description:**
This PR adds the **--force** flag to `atlascli livemigrations create` to skip the confirmation prompt when `--drop` is provided
**Without --force**
```
atlas liveMigrations validation create --clusterName "quartermaster-sandbox" --migrationHost cmhqa3-qmdata1016.cmhqa3.indeed.net --sourceCACertificatePath "/etc/pki/ca-trust/source/anchors/Indeed-Second-Certificate-Authority.crt" --sourceClusterName "context" --sourceProjectId 623b483b48614d5ebc80720f --sourceUsername "mms-automation" --sourcePassword "xxx" --drop
? Are you sure you want to drop the destination collections? (y/N) n
```
**With --force**
```
./bin/atlas livemigrations create --clusterName "quartermaster-sandbox" --migrationHost …
```

HELP-37776: [Atlas CLI] prompt error with garbage characters in tty

---

docs/atlascli/command/atlas-backups-exports-buckets-create.txt
internal/cli/atlas/backup/exports/buckets/create.go

CLOUDP-136376: Example for create bucket using Atlas CLI has typo

---

internal/cli/atlas/customdbroles/describe.go
internal/cli/atlas/customdbroles/list.go
test/e2e/atlas/custom_db_roles_test.go

_Jira ticket:_ CLOUDP-138980
Issue:
```
atlas customDbRoles list                                                                                                                                                      1.18
Error: template: output:3:38: executing "output" at <.Db>: can't evaluate field Db in type mongodbatlas.Resource
```
Fix:
```
./bin/atlas customDbRoles list                                                                                                                                                1.18
NAME         ACTION                       DB         COLLECTION        CLUSTER
tesr         FIND                         test                         N/A
tesr         INSERT                       test                         N/A
tesr         REMOVE …
```

CLOUDP-138980: [AtlasCLI] The atlas customDbRoles list format does not works

---

test/e2e/atlas/integrations_test.go

_Jira ticket:_ CLOUDP-140746
The intel team has recently added validation on the datalog key. This PR updates our datalog e2e test to use the correct format for the apilkey
[Test failing on master](https://evergreen.mongodb.com/task/mongocli_master_e2e_generic_atlas_generic_e2e_d774519a1fd8d7cb88c4f726a83fec2b9316f0db_22_10_18_07_53_25):
```
[2022/10/18 07:57:17.402] === RUN   TestIntegrations/Create_DATADOG
[2022/10/18 07:57:17.402]     integrations_test.go:68:
[2022/10/18 07:57:17.402]         	Error Trace:	/data/mci/5bed9a0a59ac7567180f2df5d99c4c47/src/github.com/mongodb/mongodb-atlas-cli/test/e2e/atlas/integrations_test.go:68
[2022/10/18 07:57:17.402]         	Error:      	Received unexpected error:
[2022/10/18 07:57:17.402]         	            	exit status 1
[2022/10/18 …
```

CLOUDP-140746: Fix integration e2e tests

---

docs/atlascli/command/atlas-networking-peering-create-azure.txt
docs/mongocli/command/mongocli-atlas-networking-peering-create-azure.txt
internal/cli/atlas/networking/peering/create/azure.go

- [DOCSP-26348](https://jira.mongodb.org/browse/DOCSP-26348) adds example for the network peering azure create command

DOCSP-26348 Add examples for atlas networking peering azure create

---

tools/atlasclidocs/main.go
tools/mongoclidocs/main.go

Remove hack to document autocompletion now that my change upstream has finally been released

task: update doc generation with latest cobra features

---

build/ci/evergreen.yml

_Jira ticket:_ CLOUDP-148788
Lint task is failing on evergreen and it is blocking us to merge other PRs and to release AtlasCLI. Since the golanglint is not failing on github actions, let's remove the task while we work on a fix in https://jira.mongodb.org/browse/CLOUDP-149030

CLOUDP-149030: Remove lint task

---

docs/atlascli/command/atlas-liveMigrations-create.txt
docs/atlascli/command/atlas-liveMigrations-validation-create.txt
docs/mongocli/command/mongocli-atlas-liveMigrations-create.txt
docs/mongocli/command/mongocli-atlas-liveMigrations-validation-create.txt
internal/cli/atlas/livemigrations/create_test.go
internal/cli/atlas/livemigrations/cutover.go
internal/cli/atlas/livemigrations/options/live_migrations_opts.go
internal/cli/atlas/livemigrations/validation/create_test.go
internal/store/live_migrations.go

_Jira ticket:_ CLOUDP-148788
This came out in https://jira.mongodb.org/browse/HELP-40211. The cutover command is passing the `orgId` instead of the `projectId`

CLOUDP-148788: [AtlasCLI] cutover command is using orgId instead of projectId

---

docs/atlascli/command/atlas-backups-restores-list.txt
docs/atlascli/command/atlas-backups-restores-start.txt
docs/atlascli/command/atlas-backups-snapshots-create.txt
docs/atlascli/command/atlas-backups-snapshots-delete.txt
docs/atlascli/command/atlas-backups-snapshots-describe.txt
docs/atlascli/command/atlas-backups-snapshots-watch.txt
docs/mongocli/command/mongocli-atlas-backups-restores-list.txt
docs/mongocli/command/mongocli-atlas-backups-restores-start.txt
docs/mongocli/command/mongocli-atlas-backups-snapshots-create.txt
docs/mongocli/command/mongocli-atlas-backups-snapshots-delete.txt
docs/mongocli/command/mongocli-atlas-backups-snapshots-describe.txt
docs/mongocli/command/mongocli-atlas-backups-snapshots-watch.txt
internal/cli/atlas/backup/restores/list.go
internal/cli/atlas/backup/restores/start.go
internal/cli/atlas/backup/snapshots/create.go
internal/cli/atlas/backup/snapshots/delete.go
internal/cli/atlas/backup/snapshots/describe.go
internal/cli/atlas/backup/snapshots/watch.go

Backfills docs content for atlas backups and atlas backups snapshots commands
_Jira tickets:_ 
https://jira.mongodb.org/browse/DOCSP-16590
https://jira.mongodb.org/browse/DOCSP-16591
https://jira.mongodb.org/browse/DOCSP-16593
https://jira.mongodb.org/browse/DOCSP-16594
https://jira.mongodb.org/browse/DOCSP-16595
https://jira.mongodb.org/browse/DOCSP-16596
https://jira.mongodb.org/browse/DOCSP-16597

(DOCSP-16595) Backfills content for atlas backups and backups snapshots commands

---

build/ci/evergreen.yml
test/e2e/cloud_manager/agent_api_keys_test.go
test/e2e/cloud_manager/agents_test.go
test/e2e/cloud_manager/dbusers_test.go
test/e2e/cloud_manager/decryption_aws_test.go
test/e2e/cloud_manager/decryption_kmip_test.go
test/e2e/cloud_manager/decryption_localkey_test.go
test/e2e/cloud_manager/deploy_replica_set_test.go
test/e2e/cloud_manager/deploy_sharded_cluster_test.go
test/e2e/cloud_manager/feature_policies_test.go
test/e2e/cloud_manager/helper_test.go
test/e2e/cloud_manager/key_providers_test.go
test/e2e/cloud_manager/maintenance_test.go
test/e2e/cloud_manager/servers_test.go
test/e2e/iam/atlas_users_test.go
test/e2e/iam/org_api_key_access_list_test.go
test/e2e/iam/org_invitations_test.go
test/e2e/iam/project_invitations_test.go
test/e2e/iam/project_teams_test.go
test/e2e/iam/team_users_test.go
test/e2e/iam/teams_test.go
test/e2e/ops_manager/version_manifest_test.go

_Jira ticket:_ CLOUDP-136638
This PR adds e2e tests for OM 6.0:
- adds a new evergreen variant [E2E Ops Manager 6.0 Tests](https://evergreen.mongodb.com/build/mongocli_master_e2e_ops_manager_60_patch_0bab6af3693c0b366873e98ef86ffca1703530e5_63ac1fad2a60ed3b5d0b4f4b_22_12_28_10_51_26)
- adds a new e2e tag: `om60`
- removes the e2e tag `om44` as it is no longer supported

CLOUDP-136638: Add OM 6.0 E2E tests for MongoCLI

---

docs/atlascli/command/atlas-backups-exports-jobs-describe.txt
docs/atlascli/command/atlas-backups-exports-jobs.txt
internal/cli/atlas/backup/exports/jobs/decribe.go
internal/cli/atlas/backup/exports/jobs/describe_test.go
internal/flag/flags.go
internal/usage/usage.go

_Jira ticket:_  [CLOUDP-149874](https://jira.mongodb.org/browse/CLOUDP-149874)
Following [this related change](https://github.com/mongodb/go-client-mongodb-atlas/pull/331/files) to the go SDK client, the parameter names of the `CloudProviderSnapshotExportJobsServiceOp` GET request `projectID, clusterName, exportJobID string` will correspond to the [public doc](https://www.mongodb.com/docs/atlas/reference/api/cloud-backup/export/get-one-export-job/)
```
GET /groups/{GROUP-ID}/clusters/{CLUSTER-NAME}/backup/exports/{EXPORT-JOB-ID}
```
In this PR, I have updated the references to use `ExportJobID` rather than `bucketId` for consistency with the go client and public docs
- For backwards compatibility, set `bucketId` as an alias for `jobId`, to avoid introducing breaking changes

CLOUDP-149874: Replace export job bucketId with jobId flag

---

docs/atlascli/command/atlas-dataLakes-create.txt
docs/atlascli/command/atlas-dataLakes-delete.txt
docs/atlascli/command/atlas-dataLakes-describe.txt
docs/atlascli/command/atlas-dataLakes-list.txt
docs/atlascli/command/atlas-dataLakes-update.txt
docs/atlascli/command/atlas-dataLakes.txt
docs/mongocli/command/mongocli-atlas-dataLakes-create.txt
docs/mongocli/command/mongocli-atlas-dataLakes-delete.txt
docs/mongocli/command/mongocli-atlas-dataLakes-describe.txt
docs/mongocli/command/mongocli-atlas-dataLakes-list.txt
docs/mongocli/command/mongocli-atlas-dataLakes-update.txt
docs/mongocli/command/mongocli-atlas-dataLakes.txt
internal/cli/atlas/datalake/create.go
internal/cli/atlas/datalake/delete.go
internal/cli/atlas/datalake/describe.go
internal/cli/atlas/datalake/list.go
internal/cli/atlas/datalake/update.go
internal/usage/usage.go

Backfills docs content for dataLakes commands and updates descriptions and flags to reference Atlas Data Federation
_Jira ticket:_
https://jira.mongodb.org/browse/DOCSP-16646
https://jira.mongodb.org/browse/DOCSP-16647
https://jira.mongodb.org/browse/DOCSP-16648
https://jira.mongodb.org/browse/DOCSP-16649
https://jira.mongodb.org/browse/DOCSP-16650

(DOCSP-16646) Backfills docs content for atlas dataLakes commands

---

test/e2e/cloud_manager/feature_policies_test.go
test/e2e/cloud_manager/maintenance_test.go
test/e2e/iam/project_invitations_test.go
test/e2e/iam/project_teams_test.go
test/e2e/iam/projects_test.go

Fix is live and we can re-enable the tests

tests: re-enable skipped tests

---

internal/cli/atlas/backup/exports/buckets/create.go

Add an extra validation for AWS IAM role ID as we have had a couple of support cases that assume is in the AWS format when it's an ObjectID

feat: validate iamRoleID is an object ID

---

examples/atlas/create-cluster.md
examples/atlas/create-recomended-indexes.md
examples/atlas/log-download.md
examples/atlas/rename-cluster.md

Update examples to use atlas CLI and add example for multi cloud cluster
I had the json for multicloud cluster laying around and decided to add it here

docs: update examples to use atlas cli

---

build/ci/evergreen.yml

For the clean up task there's no point to stepback as a failure to clean up will probably keep failing on previous runs

test: don't stepback on cleanup

---

internal/convert/process_config.go

_Jira ticket:_ CLOUDP-155672
We missed a place to copy the settings between the automation config and the internal cluster state

CLOUDP-155672: cli ops manager clusters don't show default RW concern

---

test/e2e/atlas/setup_force_test.go

Remove cluster termination test from setup e2e test. Will add it back in future PR.
_Jira ticket:_ [CLOUDP-154706](https://jira.mongodb.org/browse/CLOUDP-156407)
The `update` command cannot be used on shared clusters. Removing this check first, and then will add support for toggling cluster termination protection through the `upgrade` command too, until Atlas team confirms that this is the intended way of dealing with termination protection for shared clusters.

CLOUDP-156407: Remove cluster termination protection test

---

docs/atlascli/command/atlas-clusters-upgrade.txt
internal/cli/atlas/clusters/upgrade.go
internal/cli/atlas/clusters/upgrade_test.go
test/e2e/atlas/clusters_flags_test.go
test/e2e/atlas/clusters_upgrade_test.go

This was an outstanding ticket for enabling cluster termination protection through the CLI.
Added flags for cluster termination protection to `upgrade` command. Shared clusters can only be modified through the `upgrade` command. Adding these flags to ensure that users can disable termination protection for clusters created through `quickstart` and `setup` until Atlas confirms this as being the way to do it.
_Jira ticket:_ CLOUDP-156746

CLOUDP-156746: Add termination protection flags for upgrade

---

build/ci/evergreen.yml

Setting so failures of the k8s e2e tests default to the k8s team

test: default the ownwership of atlas_kubernetes_e2e to k8s

---

test/e2e/atlas/alert_settings_test.go

Fix failing test by replacing matcher from equals to one that ignores order

test: fix failing matcher tests

---

docs/mongocli/command/mongocli-iam-globalAccessLists-create.txt
docs/mongocli/command/mongocli-iam-globalAccessLists-delete.txt
docs/mongocli/command/mongocli-iam-globalAccessLists-describe.txt
docs/mongocli/command/mongocli-iam-globalAccessLists-list.txt
docs/mongocli/command/mongocli-iam-globalAccessLists.txt
docs/mongocli/command/mongocli-iam-globalApiKeys-create.txt
docs/mongocli/command/mongocli-iam-globalApiKeys-delete.txt
docs/mongocli/command/mongocli-iam-globalApiKeys-describe.txt
docs/mongocli/command/mongocli-iam-globalApiKeys-list.txt
docs/mongocli/command/mongocli-iam-globalApiKeys-update.txt
docs/mongocli/command/mongocli-iam-globalApiKeys.txt
internal/cli/iam/globalaccesslists/create.go
internal/cli/iam/globalaccesslists/delete.go
internal/cli/iam/globalaccesslists/describe.go
internal/cli/iam/globalaccesslists/list.go
internal/cli/iam/globalapikeys/create.go
internal/cli/iam/globalapikeys/delete.go
internal/cli/iam/globalapikeys/describe.go
internal/cli/iam/globalapikeys/list.go
internal/cli/iam/globalapikeys/update.go

Backfills docs content for globalApiKeys and globalAccessLists commands.
This is the last PR for [this backfill epic](https://jira.mongodb.org/browse/DOCSP-16432) (however, 2 epics remain for CM and OM specific commands).
https://jira.mongodb.org/browse/DOCSP-16828
https://jira.mongodb.org/browse/DOCSP-16829
https://jira.mongodb.org/browse/DOCSP-16830
https://jira.mongodb.org/browse/DOCSP-16831
https://jira.mongodb.org/browse/DOCSP-16833
https://jira.mongodb.org/browse/DOCSP-16834
https://jira.mongodb.org/browse/DOCSP-16835
https://jira.mongodb.org/browse/DOCSP-16836
https://jira.mongodb.org/browse/DOCSP-16837

(DOCSP-16828) Backfills docs content for globalApiKeys and globalAccessLists commands

---

docs/atlascli/command/atlas-clusters-failover.txt
internal/cli/atlas/clusters/failover.go

Fixes incorrect example showing in docs for atlas clusters failover
https://jira.mongodb.org/browse/DOCSP-28054

(DOCSP-28054) Docs for atlas clusters failover shows example for clusters delete

---

internal/cli/atlas/quickstart/quick_start.go
internal/cli/atlas/setup/setup_cmd.go
internal/cli/atlas/setup/setup_cmd_test.go
internal/cli/auth/login.go
internal/cli/auth/login_test.go
internal/cli/auth/register.go
internal/cli/auth/register_test.go
internal/cli/refresher_opts.go

_Jira ticket:_ CLOUDP-162861
Trying to clean up auth login/register and setup is becoming too complected due to a big amount of technical debt and inter-dependency, starting small with a small clean up of unnecessary methods that expose a lot of the issues I'm seeing
I'll pause trying to fix the unit tests deleting config files after this PR since it's becoming bigger and I have other tickets to look at

CLOUDP-162861: Remove unnnecessary new constructors from the auth pkg

---

docs/atlascli/command/atlas-config-set.txt
docs/mongocli/command/mongocli-config-set.txt
internal/cli/config/set.go

Removes Long text with values for both Atlas CLI and MCLI, adds flag description text that specifies which values are supported for each CLI.
https://jira.mongodb.org/browse/DOCSP-28066

(DOCSP-28066) Calls out OM-only property values in atlas config set docs

---

docs/atlascli/command/atlas-organizations-apiKeys-accessLists-create.txt
docs/atlascli/command/atlas-organizations-apiKeys-accessLists-delete.txt
docs/mongocli/command/mongocli-iam-organizations-apiKeys-accessLists-create.txt
docs/mongocli/command/mongocli-iam-organizations-apiKeys-accessLists-delete.txt
internal/cli/iam/organizations/apikeys/accesslists/create.go
internal/cli/iam/organizations/apikeys/accesslists/delete.go
internal/store/ip_info.go
test/e2e/iam/org_api_key_access_list_test.go

_Jira ticket:_ CLOUDP-161161
Manually tested, adding e2e has a limitation as the backend won't let you remove the callers IP address

CLOUDP-161161: [Atlas CLI] Add support for --curentIp on API access list for organizations

---

internal/jsonpathwriter/jsonpathwriter.go

_Jira ticket:_ CLOUDP-164354
Pass the result of jsonpath to our json printer so it prints pretty json instead of go structs 
Before 
```bash
atlas projects ls  -o json-path="$.results[0]"
map[created:2020-02-20T10:02:42Z id:<redacted> links:[map[href:https://cloud.mongodb.com/api/atlas/v1.0/groups/<redacted> rel:self]] name:CLI ANDREA orgId:<redacted>]
```
```bash
./bin/atlas projects ls -o json-path="$.results[0]"
{
"created": "2020-02-20T10:02:42Z",
"id": "<redacted>",
"links": [
{
"href": "https://cloud-dev.mongodb.com/api/atlas/v1.0/groups/<redacted>",
"rel": "self"
}
],
"name": "CLI ANDREA",
"orgId": "<redacted>"
}
```

CLOUDP-164354: Fix json-path parsing to output json

---

cmd/atlas/atlas.go
cmd/mongocli/mongocli.go

_Jira ticket:_ CLOUDP-136038
```bash
./bin/atlas --help
Use atlas command help for information on a specific command
For more information, refer to the docs: https://www.mongodb.com/docs/atlas/cli/stable/
```
```bash
./bin/mongocli --help
Use mongocli command help for information on a specific command
For more information, refer to the docs: https://www.mongodb.com/docs/mongocli/stable/
```

CLOUDP-136038: Add a main docs link to $ atlas -help command

---

go.mod
go.sum
internal/cli/iam/organizations/describe_test.go

Updating mongodb-atlas-client v2 version to latest. 
Done checks and all renames would affect CLI in any way as we never include and list return models as they are.

fix: update client library to latest

---

CONTRIBUTING.md

As putting actual vscode file to the repo might recieve some of the pushback I have decided to document vscode debug setup.

fix: add contributing guide for debugging

---

.golangci.yml
internal/store/organizations.go

See: https://jira.mongodb.org/browse/CLOUDP-161495
TL:DR - there are so many false positives for bodyclose that this rule only works when stream is opened only within the same golang scope (same code block). Any functions, or external library response objects are reported as errors.
Considering the very poor maintenance of the rule (those issues were reported years ago) I recomend to disable rule rather than adding +400 exceptions. 
This PR is an alternative to current approach:
Supplying extra defer for all sdk calls (which would result in noop as body is closed already)

CLOUDP-161495: disable bodyclose rule

---

test/e2e/iam/atlas_orgs_test.go

Disable create/delete org e2e tests due to too many linked orgs on the testing org. Will revert once resolved.

CLOUDP-165609: Disabling tests failing due to environmental issue

---

docs/atlascli/command/atlas-metrics-processes.txt
docs/mongocli/command/mongocli-atlas-metrics-processes.txt
internal/cli/atlas/metrics/processes/processes.go
internal/usage/usage.go

As part of the CLI backfill, we added the wrong values accepted for the atlas metrics processes command. This PR fixes that error and points them to the OpenAPI spec.
https://jira.mongodb.org/browse/DOCSP-28202

(DOCSP-28202) Changes values accepted for atlas metrics processes command

---

go.mod
go.sum
internal/cli/iam/organizations/describe.go
internal/cli/iam/organizations/describe_test.go
internal/cli/output_opts.go
internal/store/organizations.go
internal/store/store.go

Updating the migration of Atlas CLI Organizations commands to the auto-generated v2 atlas SDK
Added conditional template generation
Other options we considered were 
- Creating a new store for each v2 endpoint
- Creating a new implementation of a store interface for each v2 endpoint
We opted to go with the `interface` + conditional template generation as an approach for ease of integration.
We have many commands to migrate and test, and in many cases, very few changes will be required for this approach.
If/when we end up separating mongoCLI and atlasCLI at a later stage, the removal of the on-prem template and the `store isAtlas false` cases should be straightforward 
_Jira ticket:_ CLOUDP-164969

CLOUDP-164969: Migrate Atlas CLI Organizations Client to v2 SDK Client

---

internal/cli/atlas/quickstart/quick_start.go
internal/cli/atlas/setup/setup_cmd.go
internal/cli/auth/login.go
internal/cli/auth/login_test.go
internal/cli/auth/register.go

Login/Register/Quickstart/Setup flows: fixed an issue where oauth flow was initialized before the command opts and the oauth access profile were synchronized. One of the side-effects was that some command opts were ignored (e.g. isGov)
_Jira ticket:_ CLOUDP-163723
* configured access tokens, org and proj
* redirected to https://account.mongodbgov.com/account/login?fromURI=https://account.mongodbgov.com/account/connect
* got error `Error: already authenticated with an account (xxx@mongodb.com)\nTo log out, run: atlas auth logout`
* got error `Error: already authenticated with an account (xxx@mongodb.com)\nTo log out, run: atlas auth logout`
* token was refreshed, then got error `Error: already authenticated with an account (xxx@mongodb.com)\nTo log out, run: atlas auth logout`
* `Error: …

CLOUDP-163723: fix login with isGov flag

---

build/ci/evergreen.yml

Expand `go_env` variables in the unit-test task env so that the GOPROXY is correctly set.
Before, we were expanding `go_options` which has an `env` section (go_env) but this was overwritten by the env section unit-test task already had. 
Tested locally with `evergreen evaluate build/ci/evergreen.yml`.
_Jira ticket:_ CLOUDP-167676

CLOUDP-167676: fix evergreen env for unit tests

---

build/ci/evergreen.yml
internal/cli/atlas/serverless/backup/restores/create.go
test/README.md
test/e2e/atlas/backup_export_buckets_test.go
test/e2e/atlas/backup_export_jobs_test.go
test/e2e/atlas/backup_serverless_test.go
test/e2e/atlas/backup_snapshot_test.go
test/e2e/atlas/helper_test.go
test/e2e/atlas/serverless_test.go

Add e2e tests for "serverless backups" commands
_Jira ticket:_ CLOUDP-164770
- Adding tests
- Added validation for delivery type on `atlas serverless backup restore create`
- Made backup tests run in parallel

CLOUDP-164770 Add e2e tests for "serverless backups" commands

---

docs/atlascli/command/atlas-backups-restores-start.txt
docs/atlascli/command/atlas-backups-snapshots-create.txt
docs/atlascli/command/atlas-backups-snapshots-delete.txt
docs/atlascli/command/atlas-clusters-advancedSettings-update.txt
docs/atlascli/command/atlas-clusters-pause.txt
docs/atlascli/command/atlas-clusters-start.txt
docs/atlascli/command/atlas-clusters-update.txt
docs/atlascli/command/atlas-clusters.txt
docs/atlascli/command/atlas-serverless-backups-restores-create.txt
docs/mongocli/command/mongocli-atlas-backups-restores-start.txt
docs/mongocli/command/mongocli-atlas-backups-snapshots-create.txt
docs/mongocli/command/mongocli-atlas-backups-snapshots-delete.txt
docs/mongocli/command/mongocli-atlas-clusters-pause.txt
docs/mongocli/command/mongocli-atlas-clusters-start.txt
docs/mongocli/command/mongocli-atlas-clusters-update.txt
docs/mongocli/command/mongocli-atlas-clusters.txt
internal/cli/atlas/backup/restores/start.go
internal/cli/atlas/backup/snapshots/create.go
internal/cli/atlas/backup/snapshots/delete.go
internal/cli/atlas/clusters/advancedsettings/update.go
internal/cli/atlas/clusters/pause.go
internal/cli/atlas/clusters/start.go
internal/cli/atlas/clusters/update.go
internal/cli/atlas/commonerrors/errors.go
internal/cli/atlas/serverless/backup/restores/create.go

_Jira ticket:_ [CLOUDP-169985](https://jira.mongodb.org/browse/CLOUDP-169985)
When running atlas cluster commands against M0 clusters, an unhelpful error message is displayed: `Error: cluster update is not supported, try 'atlas cluster upgrade' command.`
- Modify the error message to clarify that these commands are only available for M10+ clusters
- Update the documentation for these commands to explicitly mention this limitation
```bash
atlas cluster pause Cluster13464                                                                                                                        1.19  16.18.0 bazel 5.4.0
Error: cluster update is not supported, try 'atlas cluster upgrade' command
```
```bash
atlas cluster pause Cluster13464 …
```

CLOUDP-169985: [AtlasCLI] Update the error message for commands that work only for M10+ clusters

---

internal/cli/atlas/maintenance/describe_test.go
internal/cli/atlas/maintenance/update.go
internal/kubernetes/operator/project/project.go
internal/kubernetes/operator/project/project_test.go
internal/mocks/mock_atlas_operator_project_store.go
internal/mocks/mock_maintenance.go
internal/store/maintenance.go
test/e2e/atlas/maintenance_test.go

_Jira ticket:_ CLOUDP-# [CLOUDP-167790](https://jira.mongodb.org/browse/CLOUDP-167790)
EVG Patch: https://spruce.mongodb.com/version/642c31ad850e61fcf29ddb68/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

CLOUDP-167790: Migrate Maintenance Windows CLI stores to v2 sdk

---

docs/atlascli/command/atlas-clusters-search-indexes-list.txt
docs/mongocli/command/mongocli-atlas-clusters-search-indexes-list.txt
internal/cli/atlas/search/create_test.go
internal/cli/atlas/search/describe_test.go
internal/cli/atlas/search/index_opts.go
internal/cli/atlas/search/list.go
internal/cli/atlas/search/list_test.go
internal/cli/atlas/search/update_test.go
internal/mocks/mock_search.go
internal/store/search.go
test/e2e/atlas/search_test.go

_Jira ticket:_ CLOUDP-# [CLOUDP-167793](https://jira.mongodb.org/browse/CLOUDP-167793)
EVG Patch: https://spruce.mongodb.com/version/6421cc400ae606fcdcda3b85/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

CLOUDP-167793:Migrate Atlas Search CLI stores to v2 sdk

---

.gitignore

If we do not want vscode specific configuration in the repository we need to add configuration to gitignore as otherwise it can be pushed my mistake.

chore: add vscode config to git ignore

---

internal/cli/auth/login.go

_Jira ticket:_ CLOUDP-172415
Found this out while testing a report
Manually tested using a custom client id works again as expected

CLOUDP-172415: handle client id when using a custom one

---

build/ci/evergreen.yml

Adjust test timeout for backup restores, all examples I've found that passed with a red on evergreen had a context canceled message meaning a timeout, extending it on the evergreen task.
_Jira ticket:_ CLOUDP-171555
moving forward to extend the timeout of a task we should extend both together:
- E2E_TIMEOUT this is sent to the gotestsum -timeout ${E2E_TIMEOUT}
- timeout_secs: evergreen config to override (per task) main `exec_timeout_secs`

CLOUDP-171555 Adjust test timeout for backup restores

---

docs/atlascli/command/atlas-liveMigrations-create.txt
docs/atlascli/command/atlas-liveMigrations-validation-create.txt
docs/atlascli/command/atlas-liveMigrations-validation-describe.txt
docs/mongocli/command/mongocli-atlas-liveMigrations-create.txt
docs/mongocli/command/mongocli-atlas-liveMigrations-validation-create.txt
docs/mongocli/command/mongocli-atlas-liveMigrations-validation-describe.txt
internal/cli/atlas/livemigrations/create.go
internal/cli/atlas/livemigrations/create_test.go
internal/cli/atlas/livemigrations/describe.go
internal/cli/atlas/livemigrations/describe_test.go
internal/cli/atlas/livemigrations/link/create.go
internal/cli/atlas/livemigrations/link/create_test.go
internal/cli/atlas/livemigrations/options/live_migrations_opts.go
internal/cli/atlas/livemigrations/validation/create.go
internal/cli/atlas/livemigrations/validation/create_test.go
internal/cli/atlas/livemigrations/validation/describe.go
internal/cli/atlas/livemigrations/validation/describe_test.go
internal/mocks/mock_live_migration_link_tokens.go
internal/mocks/mock_live_migration_validations.go
internal/mocks/mock_live_migrations.go
internal/store/live_migration.go
internal/store/live_migration_link_tokens.go
internal/store/live_migrations.go

Upgrade of sdk to v2 for:
- live_migration
- live_migration_link_tokens
- live_migrations
Excludes migration of CreateLiveMigrationCutover, which is missing the Validation model in the responseBody 
(to be addressed in a separate PR)
_Jira ticket:_ CLOUDP-167778

CLOUDP-167778: migrate 'cloud migration service' CLI stores to v2 sdk

---

docs/atlascli/command/atlas-serverless-backups-snapshots-describe.txt
internal/cli/atlas/serverless/backup/snapshots/describe.go
internal/cli/atlas/serverless/backup/snapshots/describe_test.go
internal/cli/atlas/serverless/backup/snapshots/watch.go
internal/cli/atlas/serverless/backup/snapshots/watch_test.go
internal/cli/mongocli/serverless/backup/snapshots/describe.go
internal/cli/mongocli/serverless/backup/snapshots/describe_test.go
internal/cli/mongocli/serverless/backup/snapshots/watch.go
internal/cli/mongocli/serverless/backup/snapshots/watch_test.go
internal/mocks/mock_cloud_provider_backup_serverless.go
internal/store/cloud_provider_backup_serverless.go
test/e2e/atlas/backup_serverless_test.go

_Jira ticket:_ CLOUDP-# [CLOUDP-172413](https://jira.mongodb.org/browse/CLOUDP-172413)
EVG Patch: https://spruce.mongodb.com/version/644bbb8d0305b999d95593e6/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

CLOUDP-172413: cloud_provider_backup_serverless Describer cmd migration

---

internal/store/logs.go

_Jira ticket:_ CLOUDP-# [CLOUDP-177800](https://jira.mongodb.org/browse/CLOUDP-177800)
Reverting the DownloadLog API migration as the API needs thorough testing and the debug logs have no information about the reason for failure.
Created https://jira.mongodb.org/browse/CLOUDP-178273 to migrate the API to v2

CLOUDP-177800: e2e_atlas_clusters Failure

---

build/ci/evergreen.yml
test/e2e/atlas/atlas_e2e_test_generator_test.go

_Jira ticket:_ CLOUDP-179008
enable foliage to only open a ticket per task and not per test

CLOUDP-179008: Only create foliage tickets for the task and not test on cleanup

---

test/e2e/atlas/atlas_e2e_test_generator_test.go
test/e2e/atlas/backup_restores_test.go
test/e2e/atlas/cleanup_test.go
test/e2e/atlas/helper_test.go
test/e2e/atlas/online_archives_test.go
test/e2e/atlas/quickstart_test.go
test/e2e/atlas/setup_force_test.go

_Jira ticket:_ CLOUDP-179042
- Remove some usages of `t.Parallel` as I think they were causing some concurrency issues.
- Wait for cluster deletion on interactive commands, it seems we can't delete projects while clusters are being delete and we need to wait
- Restores not sure how it got fix, added some logs to try and debug and now it passes

CLOUDP-179042: Failed Build Variant: mongodb-atlas-cli-master/e2e_atlas_backups

---

docs/atlascli/command/atlas-dataLakePipelines-availableSnapshots.txt
docs/atlascli/command/atlas-dataLakePipelines.txt
internal/cli/atlas/datalakepipelines/availablesnapshots/available_snapshots.go

Removes an extra space in the short description of a command as it causes issues for our Snooty builds on docs
_Jira ticket:_
https://jira.mongodb.org/browse/DOCSP-30186

(DOCSP-30186) Removes extra space that causes an error in the docs builds

---

internal/cli/atlas/clusters/availableregions/list.go
internal/cli/atlas/clusters/availableregions/list_test.go
internal/cli/atlas/clusters/region_tier_autocomplete.go
internal/cli/atlas/clusters/region_tier_autocomplete_test.go
internal/cli/atlas/quickstart/cluster_setup.go
internal/mocks/mock_cloud_provider_regions.go
internal/mocks/mock_clusters.go
internal/search/search.go
internal/search/search_test.go
internal/store/cloud_provider_regions.go
internal/store/clusters.go

SDKv2 Migration of ListCloudProviderRegions
_Jira ticket:_ CLOUDP-172196

CLOUDP-172196: migrate ListCloudProviderRegions

---

internal/kubernetes/operator/install_resources.go
test/e2e/atlas/helper_test.go
test/e2e/atlas/kubernetes_config_generate_test.go
test/e2e/atlas/kubernetes_operator_install_test.go

`kubernetes operator install` fails when configuring the installation of a single targeted and watched namespace.
This PR deduplicates configurable namespaces to proper configure the operator installation.
_Jira ticket:_ [CLOUDP-179267](https://jira.mongodb.org/browse/CLOUDP-179267)

CLOUDP-179267: Fix operator single namespace installation

---

docs/atlascli/command/atlas-performanceAdvisor-namespaces-list.txt
docs/atlascli/command/atlas-performanceAdvisor-slowQueryLogs-list.txt
docs/atlascli/command/atlas-performanceAdvisor-suggestedIndexes-list.txt
internal/cli/atlas/performanceadvisor/namespaces/list.go
internal/cli/atlas/performanceadvisor/slowquerylogs/list.go
internal/cli/atlas/performanceadvisor/suggestedindexes/list.go
internal/usage/usage.go

Adding extended documentation for the atlas cli explaining how to get process values. 
Explain to the users how to get the exact value of the process id.
In the long run we  should consider having dedicated command or introduce suggestions.

CLOUDP-181258: document way to obtain performance advisor processId

---

test/e2e/atlas/backup_export_jobs_test.go
test/e2e/atlas/backup_snapshot_test.go
test/e2e/atlas/clusters_file_test.go
test/e2e/atlas/clusters_m0_test.go
test/e2e/atlas/clusters_sharded_test.go
test/e2e/atlas/clusters_upgrade_test.go
test/e2e/atlas/quickstart_test.go
test/e2e/atlas/setup_force_test.go

Changing the message that the e2e test look for after using `atlas clusters delete` command.
_Jira ticket:_ CLOUDP-182905

CLOUDP-182905: Fix e2e tests 

---

docs/atlascli/command/atlas-clusters-sampleData-load.txt
internal/cli/atlas/clusters/sampledata/load.go

Adds missing example from atlas clusters sampleData load command
_Jira ticket:_
https://jira.mongodb.org/browse/DOCSP-27290

(DOCSP-27290) Adds example command for atlas clusters sampleData load

---

internal/cli/atlas/accesslists/create.go
internal/cli/atlas/accesslists/create_test.go
internal/cli/atlas/alerts/acknowledge.go
internal/cli/atlas/datalakepipelines/availablesnapshots/list.go
internal/convert/database_user.go
internal/pointer/pointer.go
internal/time/time.go
internal/time/time_test.go

For v1 SDK, timestamps were sent from the SDK as strings and only parsed once they reached the API 
Since migrating to autogenerated v2 Go SDK, timestamps are sent as `time.Time` structs, meaning we need to parse 
The end result is that we are using a different parser since moving to the v2 SDK, which needs to support some custom layouts that were supported by the API for the v1 SDK
_Jira ticket:_ CLOUDP-183519

CLOUDP-183519: introduce custom handling for valid ISO-8601 timestamps

---

docs/atlascli/command/atlas-liveMigrations-create.txt
docs/mongocli/command/mongocli-atlas-liveMigrations-create.txt
internal/cli/atlas/livemigrations/create.go
internal/cli/atlas/livemigrations/describe.go
internal/store/live_migrations.go

_Jira ticket:_ CLOUDP-# [CLOUDP-183839](https://jira.mongodb.org/browse/CLOUDP-183839)
Changed the response template for liveMigration create and describe commands.

CLOUDP-183839: Atlas Cli liveMigrations create doesn't parse output correctly after creating

---

tools/chocolateyupdate/main.go

Currently blocking AtlasCLI release 1.7.4
https://evergreen.mongodb.com/task/mongodb_atlas_cli_master_release_atlascli_msi_release_msi__atlascli_v1.7.4_23_06_15_16_38_36
```
Chocolatey v2.0.0  
Default push source configuration is not set. Please pass a source to push to, such as --source=https://push.chocolatey.org/
2023/06/16 09:05:19 exit status 1 
Command 'subprocess.exec' in function 'update choco' failed: process encountered problem: exit code 1. 
Task completed - FAILURE. 
```
[Last release](https://evergreen.mongodb.com/task_log_raw/mongodb_atlas_cli_master_release_atlascli_msi_release_msi__atlascli_v1.7.3_23_06_09_13_48_51/0?type=T#L174) used Chocolatey v1.2.1 
[This release](https://evergreen.mongodb.com/task_log_raw/mongodb_atlas_cli_master_release_atlascli_msi_release_msi__atla …

CLOUDP-185078: Address AtlasCLI release failure due to Chocolatey push source configuration

---

.golangci.yml
tools/sign/main.go

Enable and fix wastedassign and usestdlibvars
wastedassign will catch unused variables and usestdlibvars will favor usage of known standard consts instead of custom values

lint: enable wastedassign and usestdlibvars

---

docs/atlascli/command/atlas-users-invite.txt
internal/cli/atlas/users/describe.go
internal/cli/atlas/users/invite.go

After moving these commands to be atlas only we can remove some of the conditions we do for ops manager

fix: clean up atlas user commands

---

docs/atlascli/command/atlas-quickstart.txt
docs/atlascli/command/atlas-setup.txt
docs/mongocli/command/mongocli-atlas-quickstart.txt
internal/cli/atlas/quickstart/cluster_setup.go
internal/cli/atlas/quickstart/quick_start.go
internal/cli/atlas/quickstart/quick_start_test.go
internal/cli/atlas/setup/setup_cmd.go
internal/cli/atlas/setup/setup_cmd_test.go
test/e2e/atlas/setup_force_test.go

add --tag flag to quickstart and setup commands
_Jira ticket:_ CLOUDP-186602

CLOUDP-186602: add --tag flag to quickstart and setup commands

---

build/ci/evergreen.yml

Sharded cluster used to depend on RS to avoid concurrent modification of the automation agent but each test now creates a dedicated project so it's safe to run them in parallel

test: remove RS dependency for sharded test

---

test/e2e/atlas/helper_test.go
test/e2e/atlas/setup_fail_test.go
test/e2e/atlas/setup_failure_test.go
test/e2e/atlas/setup_force_test.go

Failure flow tests that were added:
- invalid projectID test
- invalid public key test
- invalid private key test
Flags that are now tested:
- `--accessListIp`
- `--projectId`
A full description of changes can be found in the JIRA ticket.
_Jira ticket:_ CLOUDP-187016
Not sure if I should supplement the `test/README.md` since none of the other commands have variations with flags and/or environment variables.

CLOUP-187016: Improve e2e test coverage for atlas setup command

---

internal/cli/atlas/quickstart/quick_start.go
internal/cli/atlas/setup/setup_cmd.go

- Added `-Y`/`--default` flag to `atlas setup`
- marked the new flag as hidden
_Jira ticket:_ CLOUDP-187018

CLOUDP-187018: atlas setup: add -Y (--default) flag and mark it as hidden

---

Dockerfile
internal/config/profile.go
internal/oauth/oauth.go
internal/store/store.go

Adds a host parameter to the UserAgent, which defaults to "native". If the CLI is run from the docker container the host parameter is set to "container".
Jira ticket: CLOUDP-187063
Closes: CLOUDP-187063
Testing was done manually by using a local throwaway pipeline.

CLOUDP-187063: Override agent for Dockerized AtlasCLI

---

internal/cli/opsmanager/clusters/list.go
internal/cli/opsmanager/clusters/list_test.go
internal/cli/output_opts.go
test/e2e/cloud_manager/deploy_replica_set_test.go

_Jira ticket:_ CLOUDP-189213
Correctly handle empty output (plaintext) when defaulting to json

CLOUDP-189213: mongocli om clusters ls doesn't account for explit empty output

---

internal/cli/atlas/privateendpoints/create.go
internal/cli/atlas/privateendpoints/delete.go
internal/cli/atlas/privateendpoints/describe.go
internal/cli/atlas/privateendpoints/interfaces/create.go
internal/cli/atlas/privateendpoints/interfaces/delete.go
internal/cli/atlas/privateendpoints/interfaces/describe.go
internal/cli/atlas/privateendpoints/list.go
internal/cli/atlas/privateendpoints/watch.go

Request from a HELP ticket - Removing `mongocli` from privateendpoints deprecation message 
_Jira ticket:_ CLOUDP-192622

CLOUDP-192622: Atlas CLI deprecation message referring to mongocli

---

CONTRIBUTING.md

Updated SDK versioning section in the Contributing. 
Added support for Versioned API/Major versions.
> NOTE: This PR is going to be part of the wider SDK/CLI maintenance plan
Extension of the SDK maintenance plan
https://github.com/mongodb/atlas-sdk-go/pull/143/files

CLOUDP-186948: cli and sdk maintenance plan

---

.github/dependabot.yml

New PRs with updates are never created because of the limits we currently have on dependabot for active PRs. This PR does changes the limit as a short countermeasure.  In the long run, we should consider tweaking our config or check for more powerful tools like renovate

fix: dependabot limit for PRs

---

.github/dependabot.yml

fix: move to 20 prs for dependabot

---

.github/dependabot.yml

Just an idea to help us with more frequent and efficient PR reviews.
NOTE: Dependabot is quite limited in that regard. Renovate is much more powerful and also free.

fix: introduce PR groups for dependabot

---

CONTRIBUTING.md
tools/sdk-usage/main.go

Going thru all operations and comparing the list with the atlas SDK is an extremely time-consuming effort. 
Our API changes a lot of we need a way to automate our list of tested SDK methods. 
> NOTE: This change is an improvement for a short-term solution. In the long term, we going to look into reducing reliance on Atlas CLI for SDK testing and stability.
I used the generated output of this PR in the https://github.com/mongodb/atlas-sdk-go/pull/161
In future, we can add operations to existing file instead of creating new one.

CLOUDP-194380: generate stable operations go SDK in atlas CLI

---

.github/workflows/issues.yml

Automatically create jira issues for every github issue. All project and assignments are already set properly and tested locally.
> NOTE: automation will require setting up the following secrets:
```
JIRA_API_TOKEN: {token}
ASSIGNEE_JIRA_TICKET: Cloud AtlasCLI Escalation
```

CLOUDP-192357: automation for creation of jira issues in atlas CLI

---

internal/cli/atlas/backup/compliancepolicy/compliancepolicy.go
internal/cli/atlas/backup/compliancepolicy/compliancepolicy_test.go
internal/cli/atlas/backup/compliancepolicy/copyprotection.go
internal/cli/atlas/backup/compliancepolicy/setup.go
internal/cli/atlas/backup/compliancepolicy/setup_test.go
internal/usage/usage.go
test/README.md
test/e2e/atlas/backup_compliancepolicy_test.go

Add the command `atlas backups compliancepolicy setup`. 
A confirmation prompt will be added after L1 support has been added for all of the operations.
```
$ bin/atlas backups compliancepolicy setup -f ./test.json
Your backup compliance policy has been set up with the following configuration:
Project:                          64b034b236930362b0c8d36b
Authorized e-mail:                firstname.lastname@example.com
Copy protection enabled:          false
Encryption at rest enabled:       false
Point-in-Time restores enabled:   false
Restore window days:              0
POLICIES
ID                         FREQUENCY INTERVAL   FREQUENCY TYPE   RETENTION
64b16beffcaed70cfbd5f520   -                    daily            5 days
64ba452852594888bd5b7070   6                    hourly           2 …
```

CLOUDP-193348: Add command "atlas backups compliancepolicy setup" L1 support

---

CONTRIBUTING.md

Kickstarting some of the documentation by explaining patterns we use in the Atlas CLi. 
This is by no means complete but it does provide minimal level of information that one needs to get started.

docs: minimal contributing documentation

---

.github/workflows/docker-release.yml

Determine latest CLI tag with a GH Action instead of the script that was in place before. Better because:
- no need to fetch the whole repository
- gets rid of the set-output (which will be deprecated soon)
- a bit more explicit what is going on
Successful test run: https://github.com/mongodb/mongodb-atlas-cli/actions/runs/5961619860/job/16171199792

Get latest cli tag with Action

---

internal/telemetry/event.go
internal/telemetry/event_test.go
internal/telemetry/tracker.go

Adds UserAgent and HostName to the DefaultCommandOptions in the CLI telemetry to make them visible in Amplitude.
_Jira ticket:_ CLOUDP-196563
Closes CLOUDP-196563

CLOUDP-196563: Add Docker Container Metric to Amplitude Atlas CLI Telemetry

---

internal/cli/atlas/deployments/setup.go
internal/cli/root/atlas/builder.go
internal/flag/flags.go
internal/mongosh/mongosh.go
internal/usage/usage.go

Adding questions based on design
_Jira ticket:_ CLOUDP-196435
https://github.com/mongodb/mongodb-atlas-cli/assets/1765216/f0fd16a0-f04a-47d3-8f28-899f6bef5f31

CLOUDP-196435 Add local-only setup command UX

---

internal/cli/atlas/deployments/setup.go

Fix port detection is not detecting system-wide ports in use
_Jira ticket:_ CLOUDP-197638

CLOUDP-197638 Fix port detection is not detecting system-wide ports in use

---

docs/atlascli/command/atlas-alerts-settings-create.txt
docs/atlascli/command/atlas-alerts-settings-update.txt
internal/cli/atlas/alerts/settings/create.go
internal/cli/atlas/alerts/settings/update.go

Our examples were always failing validation errors on the backend.
We might use https://github.com/aerogear/charmil#charmil-validator for validating invalid examples/changed flags on PR level.

DOCSP-32891: update example with missing flag

---

internal/cli/atlas/deployments/deployments.go
internal/cli/atlas/deployments/deployments_test.go
internal/cli/atlas/deployments/diagnostics.go
internal/mocks/mock_podman.go
internal/podman/client.go

_Jira ticket:_ [CLOUDP-197667](https://jira.mongodb.org/browse/CLOUDP-197667)
```shell
~/workplace/mongocli CLOUDP-197667 *22 ?1 ❯ atlasdev deployments diagnostics  --output json > out.json                                                                                                                             1.20 13:55:17
```
<details>
```
{
"Logs": {
"Mongod": null,
"Mongot": null,
"Podman": [
{
"AutoRemove": false,
"Command": [
"/bin/sh",
"-c",
"echo $KEYFILECONTENTS \u003e $KEYFILE \u0026\u0026 \\\n                   chmod 400 $KEYFILE \u0026\u0026 \\\n                   python3 /usr/local/bin/docker-entrypoint.py \\\n                                          --transitionToAuth \\\n                                          --dbpath $DBPATH \\\n …
```

CLOUDP-197667: Add deployments diagnostics command

---

go.mod
go.sum

These are used for evg testing and don't have a stable release so dependabot doesn't pick them up 
Task generation still works as excepted for shrub
Test config whcih uses the simulated terminal still works as expected

task: update unversioned libs

---

internal/podman/client.go

_Jira ticket:_ CLOUDP-199970
The `atlas deployment setup` fails with a NPE in the `client.Diagnostics` if the user did not run `podman machine init`
```log
goroutine 1 [running]:
--
github.com/mongodb/mongodb-atlas-cli/internal/podman.(*client).Diagnostics(0x0?, {0x104fd2720, 0x14000511230})
/Users/andrea.angiolillo/workspace/mongodb-atlas-cli/internal/podman/client.go:171 +0x460
github.com/mongodb/mongodb-atlas-cli/internal/cli/atlas/deployments.(*SetupOpts).planSteps(0x14000996c00, {0x104fd2720?, 0x14000511230?})
/Users/andrea.angiolillo/workspace/mongodb-atlas-cli/internal/cli/atlas/deployments/setup.go:192 +0x38
github.com/mongodb/mongodb-atlas-cli/internal/cli/atlas/deployments.(*SetupOpts).createLocalDeployment(0x14000996c00, {0x104fd2720, 0x14000511230}) …
```

CLOUDP-199970: [AtlasCLI] null pointer error when running atlas deployment setups

---

internal/cli/atlas/search/create_test.go
internal/cli/atlas/search/index_opts.go

[CLOUDP-200469](https://jira.mongodb.org/browse/CLOUDP-200469)
```shell
~/workp/mongocli CLOUDP-200469 *24 !1 ?1 ❯ atlasdev deployments search index create --file tst.json           1.20 
Error: failed to parse JSON file due to unexpected end of JSON input
~/workp/mongocli CLOUDP-200469 *24 !1 ?1 ❯ atlasdev deployments search index create --file tst.json           1.20 
Error: failed to parse JSON file due to invalid character '}' after object key
```

CLOUDP-200469: Improve wording when file is invalid

---

internal/cli/atlas/deployments/connect.go
internal/cli/atlas/deployments/delete.go
internal/cli/atlas/deployments/deployments.go
internal/cli/atlas/deployments/list.go
internal/cli/atlas/deployments/search/indexes/create.go
internal/cli/atlas/deployments/search/indexes/delete.go
internal/cli/atlas/deployments/search/indexes/describe.go
internal/cli/atlas/deployments/search/indexes/indexes.go
internal/cli/atlas/deployments/search/indexes/list.go
internal/cli/atlas/deployments/search/search.go
internal/cli/atlas/deployments/setup.go

group deployments commands:
_Jira ticket:_ CLOUDP-201089

CLOUDP-201089: group deployments commands

---

internal/cli/atlas/deployments/setup.go
internal/podman/client.go

skip podman machine init when running in linux
tested on Mac and RHEL8
_Jira ticket:_ CLOUDP-200481

CLOUDP-200481: skip podman machine init for linux

---

docs/atlascli/command/atlas-deployments-search-indexes-create.txt
docs/atlascli/command/atlas-deployments-search-indexes-delete.txt
docs/atlascli/command/atlas-deployments-search-indexes-describe.txt
docs/atlascli/command/atlas-deployments-search-indexes-list.txt
internal/cli/atlas/deployments/search/indexes/create.go
internal/cli/atlas/deployments/search/indexes/delete.go
internal/cli/atlas/deployments/search/indexes/describe.go
internal/cli/atlas/deployments/search/indexes/describe_test.go
internal/cli/atlas/deployments/search/indexes/list.go
internal/cli/atlas/deployments/search/indexes/list_test.go
internal/mongodbclient/search_index.go

_Jira ticket:_ [CLOUDP-201297](https://jira.mongodb.org/browse/CLOUDP-201297)
Local
```shell
~/workp/mongocli CLOUDP-201297 *28 !3 ?2 ❯ atlasdev deployments search index describe 652530a4b59e137f714584da
? What type of deployment would you like to work with? local
? Select a deployment local4461
ID                         NAME   DATABASE       COLLECTION        STATUS
652530a4b59e137f714584da   test   sample_mflix   embedded_movies   BUILDING
~/workp/mongocli CLOUDP-201297 *28 !3 ?2 ❯ atlasdev deployments search index describe 652530a4b59e137f714584da --output json
? What type of deployment would you like to work with? local
? Select a deployment local4461
{
"collectionName": "embedded_movies",
"database": "sample_mflix",
"indexID": "652530a4b59e137f714584da",
"name": "test",
"status": …
```

CLOUDP-201297: Add json output flag to index commands

---

internal/store/atlas/performance_advisor.go

Add missing namespaces checks. Review other performance advisor commands for missing namespaces.
Closes CLOUDP-202232
Verified locally. Namespace is sent.
Could not extend e2e tests.
It is hard to verify in e2e due to nature of the command/API

CLOUDP-202232: add missing namespaces to suggestedIndexes command

---

internal/cli/workflows/flags.go
internal/cli/workflows/flags_test.go

Improve test by first checking if error and failing early and second by using `deep.Equal` instead of reflect as it has. abetter API for diffs

test: clean up workflow test

---

build/ci/evergreen.yml
build/ci/release.yml

Change the version on evergreen to remove the patch. This will remove need for us to do numerous code bumps.

CLOUDP-205691: update evergreen version

---

docs/atlascli/command/atlas-dbusers-update.txt
docs/mongocli/command/mongocli-atlas-dbusers-update.txt
internal/cli/atlas/dbusers/update.go
internal/cli/atlas/dbusers/update_test.go

_Jira ticket:_ CLOUDP-205313
**Before fix:**
```
{"detail":"No user with username arn:aws:iam::**********:user/my-test-user exists.","error":404,"errorCode":"USERNAME_NOT_FOUND","parameters":["arn:aws:iam::**********:user/my-test-user"],"reason":"Not Found"}
Error: https://cloud-dev.mongodb.com/api/atlas/v2/groups/**********/databaseUsers/admin/arn:aws:iam::**********:user%2Fmy-test-user PATCH: HTTP 404 Not Found (Error code: "USERNAME_NOT_FOUND") Detail: No user with username arn:aws:iam::**********:user/my-test-user exists. Reason: Not Found. Params: [arn:aws:iam::**********:user/my-test-user]
Exiting.
```
**After fix:** 
```
{"awsIAMType":"USER","databaseName":"$external","groupId":"**********","labels":[],"ldapAuthType":"NONE","links":[{"href":"https://cloud.mongodb.com/api/atlas/v2/gr …
```

CLOUDP-205313: patch dbuser update to support external DB

---

.github/workflows/code-health.yml

Fix linter cache by disabling Go cache as it's duplicated and not needed. It helps to reduce errors logs in linter "prepare environment" step and reduce lint run duration.
same change as in: https://github.com/mongodb/terraform-provider-mongodbatlas/pull/1555
Example of previous errors:

chore: Fix linter cache

---

.github/workflows/autoupdate-sdk.yaml
Makefile
scripts/update-sdk.sh

I have noticed that we are behind with sdk updates for the CLI.
This PR introduces a job that will run once a week and automatically reduce boilerplate work.
I also fixed a bug in the Golang proxy that improperly handles such large major versions :)
https://github.com/mongodb/mongodb-atlas-cli/pull/2394

task: automatically update atlas sdk go

---

internal/cli/iam/globalapikeys/create.go
internal/cli/iam/globalapikeys/create_test.go
internal/cli/iam/globalapikeys/describe_test.go
internal/cli/iam/globalapikeys/list_test.go
internal/cli/iam/globalapikeys/update.go
internal/cli/iam/globalapikeys/update_test.go
internal/store/blockstores.go
internal/store/feature_control_policies.go
internal/store/file_systems.go
internal/store/global_api_keys.go
internal/store/oplog.go
internal/store/s3_blockstores.go
internal/store/sync.go
test/e2e/atlas/cleanup_test.go
test/e2e/cloud_manager/alerts_test.go
test/e2e/cloud_manager/events_test.go

Move some ops manager/cloud manager actions to only use the ops manager lib and reduce references to the legacy atlas client

task: move global apis to use only ops manager libs

---

cmd/atlas/atlas.go

Issue: CLOUDP-201369
Resolving issue that prevents a user opening their config when there is a formattign error, due to an error being considered fatal. Instead, updating to 
give the user steps to resolve.
Before:
```
atlas config list
2023/10/26 18:43:58 error loading config: While parsing config: toml: expected character =
```
After: 
```
./bin/atlas config list
2023/10/26 18:43:36 error loading config: While parsing config: toml: expected character =. Please run `atlas config init` to reconfigure your profile
PROFILE NAME
```
Resetting a broken config:
```
./bin/atlas config list
2023/10/27 09:26:32 error loading config: While parsing config: toml: expected character =. Please run `atlas config init` to reconfigure your profile
PROFILE NAME
➜  mongodb-atlas-cli git:(CLOUDP-201369) …
```

CLOUDP-201369: Allowing config to be opened even if parsing not possible

---

go.mod
go.sum
internal/cli/opsmanager/backup/checkpoints_list_test.go
internal/cli/opsmanager/backup/restores_list_test.go
internal/cli/opsmanager/backup/restores_start.go
internal/cli/opsmanager/backup/restores_start_test.go
internal/cli/opsmanager/backup/snapshots/list_test.go
internal/cli/opsmanager/clusters/indexes_create.go
internal/cli/opsmanager/livemigrations/link/create.go
internal/cli/opsmanager/livemigrations/link/create_test.go
internal/cli/opsmanager/metrics/databases_describe_test.go
internal/cli/opsmanager/metrics/databases_list_test.go
internal/cli/opsmanager/metrics/disks_describe_test.go
internal/cli/opsmanager/metrics/disks_list_test.go
internal/cli/opsmanager/metrics/process_test.go

Another pass at removing some old references to the old SDK

feat: remove references to atlas client from ops manager commands

---

docs/atlascli/command/atlas-clusters-search-indexes-describe.txt
docs/atlascli/command/atlas-clusters-search-indexes-list.txt
docs/atlascli/command/atlas-deployments-list.txt
docs/atlascli/command/atlas-deployments-search-indexes-describe.txt
docs/atlascli/command/atlas-deployments-search-indexes-list.txt
docs/mongocli/command/mongocli-atlas-clusters-search-indexes-describe.txt
docs/mongocli/command/mongocli-atlas-clusters-search-indexes-list.txt
go.mod
go.sum
internal/cli/atlas/deployments/search/indexes/create_test.go
internal/cli/atlas/deployments/search/indexes/describe.go
internal/cli/atlas/deployments/search/indexes/describe_test.go
internal/cli/atlas/deployments/search/indexes/list.go
internal/cli/atlas/deployments/search/indexes/list_test.go
internal/cli/atlas/search/describe.go
internal/cli/atlas/search/index_opts.go
internal/cli/atlas/search/list.go
internal/mongodbclient/search_index.go

Add support for vectorSearch in atlas clusters search indexes create and atlas deployments search indexes create
_Jira ticket:_ CLOUDP-204057

CLOUDP-204057: support for vectorSearch

---

test/e2e/atlas/helper_test.go

Add more logs for cleanup, given evergreen is showing `exit status 1` without much explanation
_Jira ticket:_ CLOUDP-211696

CLOUDP-211696 Add more logs for cleanup

---

test/e2e/atlas/cleanup_test.go
test/e2e/atlas/helper_test.go

Skip serverless cleanup on gov
_Jira ticket:_ CLOUDP-211696

CLOUDP-211696 Skip serverless cleanup on gov

---

docs/atlascli/command/atlas-deployments-search-indexes-create.txt
docs/atlascli/command/atlas-deployments-search-indexes-delete.txt
docs/atlascli/command/atlas-deployments-search-indexes-describe.txt
docs/atlascli/command/atlas-deployments-search-indexes-list.txt
docs/atlascli/command/atlas-deployments-setup.txt
internal/cli/atlas/deployments/connect.go
internal/cli/atlas/deployments/options/connect_opts.go
internal/cli/atlas/deployments/options/connect_opts_atlas.go
internal/cli/atlas/deployments/options/deployment_opts.go
internal/cli/atlas/deployments/options/deployment_opts_connect_string.go
internal/cli/atlas/deployments/scripts/start_mongod.sh
internal/cli/atlas/deployments/search/indexes/create.go
internal/cli/atlas/deployments/search/indexes/delete.go
internal/cli/atlas/deployments/search/indexes/describe.go
internal/cli/atlas/deployments/search/indexes/list.go
internal/cli/atlas/deployments/setup.go
internal/flag/flags.go
internal/mocks/mock_mongodb_client.go
internal/mongodbclient/database.go
internal/mongodbclient/user.go
internal/podman/client.go
internal/usage/usage.go
test/e2e/atlas/deployments_local_test.go

* add support for auth for local deployments
* add --bindIpAll flag, which allows running local dev inside a docker image
_Jira ticket:_ CLOUDP-212880
[e2e test](https://spruce.mongodb.com/task/mongodb_atlas_cli_master_e2e_required_atlas_deployments_local_e2e_patch_2345231d78e89a06918a52ed5a4067bf7a43e99d_656492205623436eb5e65118_23_11_27_12_57_08/tests?execution=0&sortBy=STATUS&sortDir=ASC)

CLOUDP-212880: local dev - add support for auth and --bindIpAll flag

---

docs/atlascli/command/atlas-backups-compliancePolicy-copyProtection-disable.txt
docs/atlascli/command/atlas-backups-compliancePolicy-copyProtection-enable.txt
docs/atlascli/command/atlas-backups-compliancePolicy-copyProtection.txt
docs/atlascli/command/atlas-backups-compliancePolicy-describe.txt
docs/atlascli/command/atlas-backups-compliancePolicy-enable.txt
docs/atlascli/command/atlas-backups-compliancePolicy-encryptionAtRest-disable.txt
docs/atlascli/command/atlas-backups-compliancePolicy-encryptionAtRest-enable.txt
docs/atlascli/command/atlas-backups-compliancePolicy-encryptionAtRest.txt
docs/atlascli/command/atlas-backups-compliancePolicy-pointInTimeRestores-enable.txt
docs/atlascli/command/atlas-backups-compliancePolicy-pointInTimeRestores.txt
docs/atlascli/command/atlas-backups-compliancePolicy-policies-describe.txt
docs/atlascli/command/atlas-backups-compliancePolicy-policies-ondemand-create.txt
docs/atlascli/command/atlas-backups-compliancePolicy-policies-ondemand-describe.txt
docs/atlascli/command/atlas-backups-compliancePolicy-policies-ondemand-update.txt
docs/atlascli/command/atlas-backups-compliancePolicy-policies-ondemand.txt
docs/atlascli/command/atlas-backups-compliancePolicy-policies-scheduled-create.txt
docs/atlascli/command/atlas-backups-compliancePolicy-policies-scheduled-describe.txt
docs/atlascli/command/atlas-backups-compliancePolicy-policies-scheduled.txt
docs/atlascli/command/atlas-backups-compliancePolicy-policies.txt
docs/atlascli/command/atlas-backups-compliancePolicy-setup.txt
docs/atlascli/command/atlas-backups-compliancePolicy.txt
docs/atlascli/command/atlas-backups.txt
internal/cli/atlas/backup/compliancepolicy/compliancepolicy.go
internal/cli/atlas/backup/compliancepolicy/encryptionatrest/disable.go
internal/cli/atlas/backup/compliancepolicy/encryptionatrest/enable.go
internal/cli/atlas/backup/compliancepolicy/encryptionatrest/encryptionatrest.go
internal/usage/usage.go

_Jira ticket:_ [CLOUDP-196976](https://jira.mongodb.org/browse/CLOUDP-196976)

CLOUDP-196976: Publish compliancePolicy commands

---

.github/workflows/code-health.yml
Makefile

I'm trying to enable some linters for consistent imports so making a drive by to update to the latest bug fixes

task: update golangci-lint to 1.55.2

---

test/e2e/atlas/backup_compliancepolicy_copyprotection_test.go
test/e2e/atlas/backup_compliancepolicy_describe_test.go
test/e2e/atlas/backup_compliancepolicy_enable_test.go
test/e2e/atlas/backup_compliancepolicy_pitrestore_test.go
test/e2e/atlas/backup_compliancepolicy_policies_describe_test.go
test/e2e/atlas/backup_compliancepolicy_setup_test.go
test/e2e/atlas/helper_test.go

Fix a typo `compliancepolicyEntity` -> `compliancePolicyEntity`

task: fix const name typo for bcp

---

test/e2e/atlas/backup_export_jobs_test.go
test/e2e/atlas/backup_snapshot_test.go
test/e2e/atlas/deployments_atlas_test.go
test/e2e/atlas/setup_force_test.go

Remove duplication of cluster watch commands for the helper function

test: reuse watch function across tests

---

internal/cli/default_setter_opts.go

Getters on the new SDK are nil safe, we should prefer to use those

task: simplify nil check for total count

---

docs/atlascli/command/atlas-networking-containers-delete.txt
docs/atlascli/command/atlas-networking-containers.txt
internal/cli/atlas/networking/containers/delete.go

DOCSP-34594 clarify use case for deleting network containers

---

internal/kubernetes/operator/deployment/deployment.go
internal/kubernetes/operator/deployment/deployment_test.go

Added Deployment tags for the `atlas kubernetes config generate` command
_Jira ticket:_ [CLOUDP-196956](https://jira.mongodb.org/browse/CLOUDP-196956)

CLOUDP-196956: Added Deployments Tags generation

---

docs/atlascli/command/atlas-streams-instances-update.txt
internal/cli/atlas/streams/instance/update.go

_Jira ticket:_ CLOUDP-#213429
Fixes typo in example text within atlascli update instance.
Updated text:
`atlas streams instance update MyInstance --provider AWS --region VIRGINIA_USA`

fix: typo in atlas streams instance update help

---

internal/kubernetes/operator/deployment/deployment_test.go
internal/kubernetes/operator/install.go
internal/kubernetes/operator/project/project.go
internal/kubernetes/operator/project/project_test.go

Due to https://github.com/mongodb/mongodb-atlas-kubernetes/pull/1316 the pointer API there will not be available to consumers. This change moves the Kubernetes code not to rely on that soon disappearing API and instead use the local pointer helper available in the CLI already.
There seem to be no more code affected by the above PR:
```shell
% grep -r mongodb-atlas-kubernetes/pkg/util                         
grep: bin/atlas: binary file matches
% grep -r mongodb-atlas-kubernetes/v2/pkg/util
%
```
_Jira ticket:_ CLOUDP-222001

CLOUDP-222001: Migrate to CLI's own pointer helper

---

internal/cli/atlas/clusters/upgrade.go

_Jira ticket:_ CLOUDP-222794
Small change for clearer API error message
The clusters upgrade command is using the [upgradeSharedCluster](https://www.mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/Clusters/operation/upgradeSharedCluster) operation, where M0 is not listed as valid value for "instanceSizeName" 
See documented providerSettings.instanceSizeName field for specific examples
Current behaviour makes an API call to retrieve the resource, then sets opts
If M0 is retrieved and no tier is set in opts, we want a clearer API message stating that M0 is not valid
Current API response:
```
400 (request "CLUSTER_PROVIDER_DOES_NOT_SUPPORT_BI_CONNECTOR") The BI Connector is not supported with the specified cluster provider.
```
After this change:
```
400 (request …
```

CLOUDP-222794: check isTenant on cluster upgrade

---

Makefile

I've noticed that the "developer setup" target `setup` in our `Makefile` doesn't setup the git hooks.
Added the `link-git-hooks` target as a dependency of `setup`

Added link-git-hooks to the developer setup target in Makefile

---

cmd/mongocli/mongocli.go
internal/cli/atlas/clusters/region_tier_autocomplete.go
internal/cli/atlas/processes/process_autocomplete.go
internal/cli/config/delete.go
internal/cli/config/describe.go
internal/cli/config/rename.go
internal/cli/profile.go
internal/cli/root/atlas/builder.go
internal/config/profile.go
internal/config/profile_integration_test.go
internal/config/profile_test.go
test/e2e/atlas/helper_test.go
test/e2e/atlas/profile_test.go

Profiles containing dots (`.`) break the CLI.
This PR disallows the usage of dots in profile names.
_Jira ticket:_ CLOUDP-137380
Added `e2e` tests to verify multiple valid and invalid profile names. I'm doing this using the `atlas auth who --profile [profile-name]` command because this command doesn't cause any side-effects. It also doesn't matter if you're actually logged in or not.

CLOUDP-137380: [CLI] profile names with dots(.) break the cli

---

internal/cli/atlas/accesslogs/list_test.go
internal/cli/atlas/clusters/list_test.go
internal/cli/atlas/datalakepipelines/create_test.go
test/e2e/atlas/helper_test.go

CLOUDP-226164: Small drive-bys after some conversations with @tibulca

CLOUDP-226164: Fix clusters tests to use the new SDK

---

internal/templatewriter/templatewriter.go
internal/templatewriter/templatewriter_test.go

handle safely pointers of slices in the output templates
_Jira ticket:_ CLOUDP-226171

CLOUDP-226171: handle safely pointers of slices in the output templates

---

scripts/update-sdk.sh

_Jira ticket:_ CLOUDP-221977
Don't use "latest" as this can have issues with go.dev caches, using the tag directly should avoid go cache 
Tested locally the script works as expected

CLOUDP-221977: New released Atlas Go SDK can't be used until several hours later

---

build/package/generate-download-archive-manifest.sh

This PR updates the release logic not to update the [download centre](https://www.mongodb.com/try/download/atlascli) when pre-releasing AtlasCLI. A pre-release is a release with a GitHub Tag that includes `-pre`, for example `atlascli/v1.2.3-pre` or `mongocli/v1.2.3-pre`. Example pre-release https://github.com/andreaangiolillo/mongocli-test/releases
These changes allow us to run pre-release the CLI with PCT or by pushing the pre-release tag to the repo.
_Jira ticket:_ CLOUDP-228171

CLOUDP-228171: Update the release logic to skip pushing binary to download center if pre-releasing

---

internal/cli/opsmanager/logs/jobs_list.go

This template: [internal/cli/atlas/privateendpoints/aws/interfaces/describe.go:30:6](https://github.com/mongodb/mongodb-atlas-cli/blob/a7deee87bb8d68a1e6085f0067a679fcb8489e24/internal/cli/atlas/privateendpoints/aws/interfaces/describe.go#L46).
Is referring to a field `Url` which was renamed [a while ago](https://github.com/mongodb/go-client-mongodb-ops-manager/commit/a49c3a36369741f45037f55ed658db1742bd1982#diff-5c807e2c947d60cec925c404bb49befffa9688244d3786286d5036cabffee2af) to `DownloadURL`.
I've updated the template accordingly
_Jira ticket:_ CLOUDP-228643

Fixed broken template field name in ops-manager (URL -> DownloadURL)

---

test/e2e/atlas/access_lists_test.go
test/e2e/atlas/access_logs_test.go
test/e2e/atlas/atlas_e2e_test_generator_test.go
test/e2e/atlas/backup_export_buckets_test.go
test/e2e/atlas/backup_export_jobs_test.go
test/e2e/atlas/backup_restores_test.go
test/e2e/atlas/backup_schedule_test.go
test/e2e/atlas/backup_snapshot_test.go
test/e2e/atlas/clusters_flags_test.go
test/e2e/atlas/clusters_sharded_test.go
test/e2e/atlas/data_federation_db_test.go
test/e2e/atlas/deployments_atlas_test.go
test/e2e/atlas/deployments_local_auth_test.go
test/e2e/atlas/deployments_local_test.go
test/e2e/atlas/helper_test.go
test/e2e/atlas/kubernetes_config_generate_test.go
test/e2e/atlas/kubernetes_operator_install_test.go
test/e2e/atlas/live_migrations_test.go
test/e2e/atlas/search_test.go
test/e2e/atlas/setup_force_test.go
test/e2e/atlas/streams_test.go

Linting update now flags unused params on anonymous functions, first of a couple of PRs fixing this (splitting to make the review easy), this one targets the test folder

task: fix unused args for anon functions

---

internal/store/search_nodes.go

Found a small issue caused by a merge:
`CreateSearchNodes` was calling `UpdateAtlasSearchDeployment` instead of `CreateAtlasSearchDeployment`

Call CreateAtlasSearchDeployment in CreateSearchNodes

---

docs/atlascli/command/atlas-backups-exports-jobs-create.txt
docs/atlascli/command/atlas-clusters-create.txt
docs/atlascli/command/atlas-clusters-update.txt
docs/atlascli/command/atlas-clusters-upgrade.txt
docs/atlascli/command/atlas-deployments-setup.txt
docs/atlascli/command/atlas-projects-create.txt
docs/atlascli/command/atlas-serverless-create.txt
docs/atlascli/command/atlas-serverless-update.txt
docs/atlascli/command/atlas-setup.txt
go.mod
go.sum

This PR addresses the issues the docs team had with the documentation generated for flags of the type `stringToString`.
1. Fixed the issues in [cobra2snooty@0.18.1](https://github.com/mongodb-labs/cobra2snooty/releases/tag/v0.18.1)
2. Upgraded cobra2snooty
3. Ran 'make gen-docs'
_Jira ticket:_ CLOUDP-230973

CLOUDP-230973: Addressed issues with stringToString

---

internal/store/organizations.go

Adds ItemsPerPage in orgs list

fix: Adds ItemsPerPage in orgs list

---

internal/cli/atlas/clusters/delete.go
internal/cli/atlas/deployments/delete.go
internal/cli/atlas/serverless/delete.go

_Jira ticket:_ CLOUDP-210224
Cluster
```bash
/bin/atlas clusters delete Cluster0 
? Confirm your backup settings before terminating your cluster.
Are you sure you want to terminate Cluster0, this action cannot be undone? (y/N) 
```
Serverless
```bash
./bin/atlas serverless delete Cluster0
? This operation will delete the instance, all of its data, and any associated backups.
Are you sure you want to terminate Cluster0, this action cannot be undone? (y/N) 
```

CLOUDP-210224: More detailed message when deleting an instance

---

.golangci.yml
internal/kubernetes/operator/config_exporter.go
internal/kubernetes/operator/features/crds.go
internal/kubernetes/operator/install_resources.go
internal/kubernetes/operator/project/project.go
internal/kubernetes/operator/version/provider.go
internal/store/project_ip_access_lists.go

Remove the ignored rules from the k8s package and do some small fixes

task: don't ignore linting for the k8s package

---

.github/actionlint-matcher.json
.github/workflows/code-health.yml
.github/workflows/dependabot.yml
.github/workflows/docker-release.yml

inspired by https://github.com/mongodb/terraform-provider-mongodbatlas/pull/1988
Add a linter for GH actions
Example run

task: add actionlint to GH action

---

internal/cli/global_opts.go
internal/store/store.go

Delete some Ops Manager/Cloud manager only things related to custom http transport

task: remove some ops manager only functions

---

internal/cli/atlas/projects/describe_test.go
internal/cli/default_setter_opts.go
internal/kubernetes/operator/install.go
internal/prompt/config.go
internal/store/atlas/store.go
internal/store/default_mongodb_version.go
internal/store/live_migration.go
internal/store/peering_connections.go
internal/store/projects.go
internal/store/serverless_instances.go
internal/store/store.go

Clean some usages of ops manager in the store

task: some store clean ups from ops manager references

---

internal/cli/atlas/clusters/create_test.go
internal/cli/atlas/clusters/update_test.go
test/e2e/atlas/atlas_e2e_test_generator_test.go
test/e2e/atlas/backup_export_jobs_test.go
test/e2e/atlas/backup_snapshot_test.go
test/e2e/atlas/clusters_file_test.go
test/e2e/atlas/clusters_flags_test.go
test/e2e/atlas/clusters_sharded_test.go
test/e2e/atlas/create_cluster_gov_test.json
test/e2e/atlas/create_cluster_test.json
test/e2e/atlas/helper_test.go

CLOUDP-231607: update mdb version to 7.0

---

internal/cli/default_setter_opts.go
internal/cli/default_setter_opts_test.go
internal/prompt/config.go

Remove the ops manager org select

task: clean up unused om org select

---

build/ci/evergreen.yml

CLOUDP-236543: Disable e2e_local_deployments

---

build/ci/evergreen.yml

This branch doesn't run podman or docker so we can move back to the more available host

tas: go back to rhel80 for mongocli

---

internal/cli/output_opts.go
internal/cli/output_opts_test.go

Remove the unused transformation output needed when we migrated to the auto generated SDK, this is not needed for mongocli

task: remove the unused output format for SDK migration

---

internal/cli/global_opts.go
internal/cli/refresher_opts.go
internal/config/profile.go
internal/config/profile_test.go
internal/store/store.go

Atlas leftover for configuration and profile settings

task: delete Atlas dead code

---

internal/cli/atlas/customdbroles/create.go
internal/convert/custom_db_role.go
internal/convert/custom_db_role_test.go

CLOUDP-237474: properly handle db names with dots

CLOUDP-237474: AtlasCLI fails to support collection names with dots for custom roles

---

internal/kubernetes/operator/deployment/deployment.go
internal/kubernetes/operator/deployment/deployment_test.go

When generating configuration/YAML for the Atlas Kubernetes Operator via the CLI, and the deployment is a shared/tenant cluster, read only fields (such as biConnector) are still exported and the operator tries to apply them. This results in an error from the Atlas API, as readonly attributes cannot be set.
This change means that when we are generating configuration for a shared cluster, we remove the readonly fields to avoid this issue; replicating the logic already used in the CLI [here](https://github.com/mongodb/mongodb-atlas-cli/blob/master/internal/cli/atlas/clusters/clusters.go#L82).
_Jira ticket:_ [CLOUDP-237545](https://jira.mongodb.org/browse/CLOUDP-237545)

CLOUDP-237545: Ignore tenant readonly fields for Kubernetes generation

---

build/ci/release.yml
build/package/download-win-binaries.sh
build/package/windows_notarize.sh

Windows binaries are not signed
_Jira ticket:_ CLOUDP-238518

CLOUDP-238518: Windows binaries are not signed

---

build/ci/evergreen.yml

EVG is stuck on the 8.9 hosts and we can go back to 80 since we don't need podman

task: go back to rhel80 for since we don't run podman tests anymore

---

internal/cli/atlas/customdbroles/create.go

[CLOUDP-238828](https://jira.mongodb.org/browse/CLOUDP-238828)
Before
```shell
❯ atlas customDbRoles create testnew2 --privilege FIND@sample_restaurants."test3",FIND@sample_restaurants."test4" -P cloud-dev --debug
2024/03/20 17:17:28
POST /api/atlas/v2/groups/5efda6aea3f2ed2e7dd6ce05/customDBRoles/roles HTTP/1.1
Host: cloud-dev.mongodb.com
User-Agent: atlascli/1.17.0 (darwin;arm64;native)
Content-Length: 250
Accept: application/vnd.atlas.2023-01-01+json
Content-Type: application/vnd.atlas.2023-01-01+json
Accept-Encoding: gzip
{"actions":[{"action":"FIND","resources":[{"cluster":false,"collection":"test3","db":"sample_restaurants"}]},{"action":"FIND","resources":[{"cluster":false,"collection":"test4","db":"sample_restaurants"}]}],"inheritedRoles":[],"roleName":"testnew2"}
2024/03/20 …
```

CLOUDP-238828: Join actions on customDbRole creation

---

internal/cli/refresher_opts.go

_Jira ticket:_ [CLOUDP-218000](https://jira.mongodb.org/browse/CLOUDP-218000)
```shell
❯ atlasdev clusters list
Error: session expired
Please note that your session expires periodically. If you use Atlas CLI for automation, see https://www.mongodb.com/docs/atlas/cli/stable/atlas-cli-automate/ for best practices.
To login, run: atlas auth login
```

CLOUDP-218000: Update AtlasCLI login expiration notification

---

internal/cli/atlas/setup/setup_cmd_test.go
internal/cli/auth/login.go
internal/cli/auth/login_test.go
internal/cli/auth/logout.go
internal/cli/auth/logout_test.go
internal/cli/auth/register.go
internal/cli/auth/register_test.go
internal/config/profile_test.go
internal/mocks/mock_login.go
internal/mocks/mock_logout.go

There were a couple of bugs on various tests depending on global state of the cli config and leaking into the actual config file causing unexpected deletions
Fixing by not depending on the global state

tests: don't delete my profile when testing

---

internal/cli/atlas/datalakepipelines/create.go
internal/cli/atlas/datalakepipelines/update.go
internal/cli/atlas/security/ldap/save.go
internal/cli/atlas/serverless/create.go
internal/cli/atlas/serverless/update.go
internal/cli/atlas/setup/cluster_setup.go
internal/kubernetes/operator/project/project.go
internal/podman/client.go

Ran some IDEA code inspection tools and found these as recommended fixes 
prefer `var mySlice []string` over `mySlice := []string{}`, it also helped linting flag usages where we could pre-allocate the size of the slice

task: use the recommended slice initialization

---

internal/cli/atlas/events/list.go
internal/cli/atlas/events/list_test.go
internal/cli/atlas/events/orgs_list.go
internal/cli/atlas/events/orgs_list_test.go
internal/cli/atlas/events/projects_list.go
internal/cli/atlas/events/projects_list_test.go
internal/convert/time.go
test/e2e/atlas/events_test.go

_Jira ticket:_ [CLOUDP-238932](https://jira.mongodb.org/browse/CLOUDP-238932)
closes #2793 
```shell
❯ atlasdev  events projects list --output json --projectId  5efda6aea3f2ed2e7dd6ce05 --maxDate 2024-03-18T15:00:03+00:00Z --minDate 2024-03-18T14:40:03+00:00Z --limit 1 --page 1
Error: parsing time "2024-03-18T15:00:03+00:00Z" as "2006-01-02T15:04:05-0700": cannot parse "+00:00Z" as "-0700", supported timestamp formats examples: 2006-01-02T15:04:05Z07:00, 2006-01-02T15:04:05-0700
```

CLOUDP-238932: Validate maxDate and minDate before running command

---

internal/cli/atlas/commonerrors/errors_test.go

Correctly compare the errors using `errors.Is`

tests: correct error comparison

---

internal/log/log.go

Small warning fix on mixing pointer and non-pointer receivers

task: don't mix pointer and non pointer receivers

---

internal/cli/atlas/backup/exports/buckets/create.go
internal/cli/atlas/backup/exports/jobs/create.go
internal/cli/auth/login.go
internal/cli/auth/whoami.go
internal/cli/config/edit.go
internal/cli/config/list.go
internal/cli/config/rename.go
internal/cli/config/set.go
internal/cli/refresher_opts.go
internal/cli/root/atlas/builder.go
internal/cli/root/atlas/builder_test.go
internal/config/profile.go
internal/validate/validate.go

remove `config.BinName` since it's always atlas and the value can now be inline

task: remove config.BinName

---

internal/cli/deployments/search/indexes/create.go
internal/mocks/mock_search.go
internal/store/search.go
test/e2e/atlas/deployments_atlas_test.go

fix search index create watcher for Atlas deployments
_Jira ticket:_ CLOUDP-240596
Testing:
* Atlas deployment: https://spruce.mongodb.com/task/mongodb_atlas_cli_master_e2e_atlas_deployments_atlas_deployments_atlas_clusters_e2e_patch_07319bbad7ef2b9d622be191947b63f4efc256fd_660c07c0bd7dd000079b2ccc_24_04_02_13_27_29/logs?execution=0
* Local deployment: https://spruce.mongodb.com/task/mongodb_atlas_cli_master_e2e_local_deployments_atlas_deployments_local_noauth_e2e_patch_07319bbad7ef2b9d622be191947b63f4efc256fd_660c07c0bd7dd000079b2ccc_24_04_02_13_27_29/logs?execution=0

CLOUDP-240596: fix search index create watcher for Atlas deployments

---

.github/dependabot.yml
.github/workflows/autoupdate-sdk.yaml
scripts/update-sdk.sh

Update SDK update process to handle minor versions and create jiras
_Jira ticket:_ CLOUDP-240677

CLOUDP-240677 Update SDK update process to handle minor versions and create jiras

---

test/e2e/atlas/kubernetes_config_generate_test.go

Fixed E2E test failure introduced by https://github.com/mongodb/mongodb-atlas-cli/pull/2812

HELP-56667: Fixed e2e k8s test failure

---

docs/command/atlas-streams-instances-create.txt
internal/cli/streams/instance/create.go
internal/cli/streams/instance/create_test.go
internal/usage/usage.go
test/e2e/atlas/streams_test.go

- Introduce a new optional flag, `--tier` for the Atlas Stream Processing create instance command.
- This value defaults to `SP30`, in the coming months we will support `SP10` as well.
- Note, the public API already supports receiving this value. 
```
To get started quickly, specify a name, a cloud provider, and a region to configure an Atlas Stream Processing instance.To use this command, you must authenticate with a user account or an API key with the Project Owner role.
Usage:
atlas streams instances create <name> [flags]
Examples:
atlas streams instance create myProcessor --projectId 5e2211c17a3e5a48f5497de3 --provider AWS --region VIRGINIA_USA --tier SP30
Flags:
-h, --help               help for create
-o, --output string      Output format. Valid values are json, json-path, …
```

CLOUDP-219248: Support --tier in Atlas Stream Instance Create command

---

build/package/.goreleaser.yml

Backport #2836 into [mongocli-master](https://github.com/mongodb/mongodb-atlas-cli/tree/mongocli-master)

CLOUDP-240399 Checksum for the Atlas CLI is missing .msi for Windows (#2836)

---

test/e2e/iam/atlas_users_test.go

Tests are flaky because of duplicate invitations, try and reduce flakyness by introducing a per run var handled by evergreen into the email we use

test: try reduce user invite flake

---

build/ci/evergreen.yml
test/e2e/atlas/atlas_e2e_test_generator_test.go
test/e2e/atlas/kubernetes_config_apply_test.go
test/e2e/atlas/kubernetes_config_generate_test.go
test/e2e/atlas/kubernetes_operator_install_test.go

Try to improve kube tests times by splitting into two tasks
Before 1 task ~30 min
Now 2 tasks in parallel where the slowest takes ~18min

task: split kube test into two tasks

---

build/ci/evergreen.yml
cmd/atlas/atlas.go
internal/config/profile.go
internal/config/profile_test.go

CLOUDP-248054: Stop copying mongocli config into atlascli

---

docs/command/atlas-kubernetes-config-generate.txt
internal/kubernetes/operator/config_exporter.go
internal/kubernetes/operator/config_exporter_test.go
internal/kubernetes/operator/features/crds.go
internal/kubernetes/operator/features/validator.go
internal/mocks/mock_atlas_operator_feature_validator.go
test/e2e/atlas/kubernetes_config_apply_test.go
test/e2e/atlas/operator_helper_test.go

This change improves how Kubernetes operator tests behave when a new version is released.
Now is possible to bump the operator version, add any new changes/fixes and rely on the supported version, avoiding
breaking CI pipeline
_Jira ticket:_ CLOUDP-249261

CLOUDP-249261: improve AKO backward compatibility for CI

---

internal/cli/root/builder.go

Fix difference between `atlas whoami` and `atlas auth whoami`
_Jira ticket:_ CLOUDP-250828

CLOUDP-250828 Fix difference between `atlas whoami` and `atlas auth whoami`

---

internal/cli/deployments/delete_test.go
internal/cli/deployments/diagnostics.go
internal/cli/deployments/options/deployment_opts.go
internal/cli/deployments/options/deployment_opts_remove.go
internal/cli/deployments/pause.go
internal/cli/deployments/pause_test.go
internal/cli/deployments/start.go
internal/cli/deployments/start_test.go

_Jira ticket:_ CLOUDP-253084
Refactored delete command to use the new unified image.
Also, fixed collateral damage in other commands, which were impacted by removing references to MongoT and removing some networking functionality. Other commands will be fully refactored in separate PRs.
Ran `atlas deploy setup` and then deleted the local development

CLOUDP-253084: Refactored delete command

---

internal/cli/deployments/pause.go
internal/cli/deployments/pause_test.go

_Jira ticket:_ : Refactor command: Pause
Refactored `atlas deployment pause` to the unified docker container approach.
- Call stop container instead of killing mongod inside of the container
1. Created a local deployment
2. Paused it
3. Restarted using console and retried, everything works as expected

CLOUDP-253088: Refactor command: Pause

---

internal/cli/deployments/delete_test.go
internal/cli/deployments/options/deployment_opts_remove.go
internal/mocks/mock_podman.go
internal/podman/client.go

_Jira ticket:_ CLOUDP-253943
Simplified the delete deployment logic by using `rm -v` instead of manually removing volumes.

CLOUDP-253943: Simplify delete logic (volumes)

---

tools/genevergreen/generate/generate.go
tools/genevergreen/generate/generate_test.go

_Jira ticket:_  CLOUDP-252044
- Curator fails because the new ubuntu image is under MDB 8.0
- This PR adds MDB 8.0 for test generation and tries to start using MDB 8.0 for the publishing tasks, we can't test as this is non-patcheable. But here is a [patch](https://spruce.mongodb.com/version/666973d90d7f250008d96fdc/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) with packaging/post-packaging tasks. I believe the patch would only succeed after the publishing.

fix: Add MDB 8.0

---

internal/cli/deployments/setup.go
internal/container/container.go
internal/container/docker.go
internal/container/podman.go
internal/mocks/mock_container.go
internal/mocks/mock_podman.go
internal/podman/client.go

_Jira ticket:_ CLOUDP-256305
- Fix the issue where podman ignores the healthcheck defined in our unified docker image
- Wait for the healthcheck to be ready when running the setup command (this is the same behavior like we have in the master branch right now)

CLOUDP-256305: SETUP: Wait for container to become healthy

---

tools/genevergreen/generate/generate.go
tools/genevergreen/generate/generate_test.go
tools/genevergreen/generate/publish.go

_Jira ticket:_ CLOUDP-257881
Removes publishing of debian11, amazon2 and rhel70 from the 8.0 repository as they [fail](https://spruce.mongodb.com/version/mongodb_atlas_cli_master_atlascli_v1.24.0_66744fd1eb66df000792d29d/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) and won't be supported.

CLOUDP-257881-map: Skip some of the publishing in some versions

---

cmd/atlas/atlas.go

- Only call *root-Builder()* once in main and pass it to functions that previously called it
- Make execute function private
_Jira ticket:_ CLOUDP-260149

CLOUDP-260149: Call root.Builder() only once in main and make execute method private

---

docs/command/atlas-security-ldap-verify-status.txt
docs/command/atlas-security-ldap-verify.txt
internal/cli/security/ldap/status.go
internal/cli/security/ldap/verify.go

Adds missing docs TOC entries for two commands that are currently orphan pages in the docs
https://jira.mongodb.org/browse/DOCSP-41063

(DOCSP-41063) Adds missing TOC entries for orphan pages

---

build/package/docker/meta/docker-build.sh

_Jira ticket:_ CLOUDP-259391
It was failing because it was hardcoded to fetch the files in 5.0 repo, but noble only exists on 8.0
Error:
```shell
[2024/07/10 06:47:46.334] 4.207 E: The repository 'https://repo.mongodb.org/apt/ubuntu noble/mongodb-org/5.0 Release' does not have a Release file.
```

CLOUDP-259391: Fix ubuntu meta building

---

internal/cli/deployments/setup.go
internal/cli/deployments/setup_test.go

- Added unit tests for `atlas deployment setup`
- Fixed an issue I've discovered while implementing the unit tests. When a deployment already exists we print "deployment already exists" and then delete the deployment we found and exit.
_Jira ticket:_ CLOUDP-200390

CLOUDP-200390: [ML3] atlas deployments setup unit test

---

internal/cli/auth/auth.go
internal/cli/auth/auth_test.go
internal/cli/auth/login.go
internal/cli/auth/login_test.go

- Move auth command builder to separate file
- Move auth unit test to separate file 
_Jira ticket:_ CLOUDP-261265

CLOUDP-261265: Refactor auth command to be consistent with other commands

---

build/package/.goreleaser.yml

- Make docker a debendency on debian based systems.
- Add docker to the suggestions on fedora based systems.
_Jira ticket:_ CLOUDP-261264

CLOUDP-261264: remove podman as a recommondation on debian based distros

---

internal/cli/deployments/list_test.go
internal/cli/deployments/options/deployment_opts_post_run.go
internal/cli/deployments/pause_test.go
internal/cli/deployments/start_test.go
internal/container/container.go
internal/container/docker.go
internal/container/podman.go

- Fixed docker error message
- Fixed post_run_opts to:
- use container engine, get rid of reference to podman
- show message if docker or podman is not installed, not only podman
- Fix broken tests
_Jira ticket:_ CLOUDP-262694

CLOUDP-262694: Fix dockerNotFound error message.

---

build/ci/library_owners.json
go.mod
internal/compass/compass.go
internal/compass/compass_bin_darwin.go
internal/compass/compass_bin_linux.go
internal/compass/compass_bin_windows.go

Use the windows register set by the compass installer.
If the registry value is not set, try the path too.
_Jira ticket:_ CLOUDP-262686

CLOUDP-262686: In windows we can't find Compass hence cli does not launch it

---

internal/convert/automation_config.go
internal/convert/automation_config_test.go

_Jira ticket:_ [CLOUDP-263807](https://jira.mongodb.org/browse/CLOUDP-263807)
Created a replica set of 3 servers, shutdown one of them
before the change:
```{
"name": "replSet1",
"processes": [
{
"arbiterOnly": false,
"buildIndexes": true,
"dbPath": "/data/srv1",
"disabled": false, <<-- HERE
"featureCompatibilityVersion": "7.0",
"hidden": false,
"hostname": "ip-172-31-1-67.eu-west-1.compute.internal",
"logDestination": "file",
"logPath": "/data/srv1/mongodb.log",
"name": "replSet1_5",
"port": 28001,
"priority": 1,
"processType": "mongod",
"secondaryDelaySecs": 0,
"votes": 1,
"version": "7.0.12"
},
{
"arbiterOnly": false,
"buildIndexes": true,
"dbPath": "/data/srv3",
"disabled": false, <<-- HERE
"featureCompatibilityVersion": "7.0",
"hidden": false,
"hostname": …
```

CLOUDP-263807: process disabled flag

---

build/ci/release.yml

Description:
The MongoCLI release is [failing](https://github.com/mongodb/mongodb-atlas-cli/blob/66cd30cf8fa3fca0a30b0cac0098c2add2850c0f/build/package/windows_notarize.sh#L29) because of the version of podman that is running on rhel80 which is 1.0.5. This PR updates the mongocli release task to use rhel90 which is running v4.8.3

fix: update mongocli release task to use rhel90

---

test/e2e/atlas/cleanup_test.go

CLOUDP-266477: cleanup test data federations from default project
_Jira ticket:_ CLOUDP-266477

CLOUDP-266477: cleanup test data federations from default project

---

internal/cli/deployments/connect_test.go
internal/cli/deployments/options/deployment_opts_connect_string.go
internal/cli/deployments/search/indexes/create_test.go
internal/cli/deployments/search/indexes/delete_test.go
internal/cli/deployments/search/indexes/describe_test.go
internal/cli/deployments/search/indexes/list_test.go
internal/cli/deployments/setup.go
internal/cli/deployments/setup_test.go
internal/container/container.go
internal/container/docker.go
internal/container/docker_test.go
internal/container/podman.go
internal/podman/client.go
internal/podman/container_inspect.go

- Removed logic to allocate a port in the CLI
- Implemented logic for docker / podman
- Wrote new tests 
- Improved `updateFields` to use actually published ports and not config (this contains the random port chosen by docker/podman)
- Fixed / updated existing tests
_Jira ticket:_ CLOUDP-265397

CLOUDP-265397: [CLI] Move random port binding to docker instead of doing in the cli

---

internal/kubernetes/operator/deployment/deployment.go
internal/kubernetes/operator/deployment/deployment_test.go
test/e2e/atlas/kubernetes_config_apply_test.go
test/e2e/atlas/kubernetes_config_generate_test.go

`atlas kubernetes config generate` now exports mongodb major version for AtlasDeployments
blocked by: https://github.com/mongodb/mongodb-atlas-cli/pull/3168 

CLOUDP-266174: kubernetes config generate to export mongodb major version

---

internal/cli/deployments/list_test.go
internal/cli/deployments/options/deployment_opts_pre_run.go
internal/cli/deployments/setup_test.go
internal/cli/deployments/test/fixture/deployment_local.go
internal/container/container.go
internal/container/docker.go
internal/container/podman.go
internal/mocks/mock_container.go
internal/mocks/mock_podman.go
internal/podman/client.go

Add warning for docker engine/podman minimum versions.
_Jira ticket:_ CLOUDP-268553
- Tested locally
- Updated unit tests

CLOUDP-268553: Add warning for docker engine/podman minimum versions

---

internal/cli/datalakepipelines/delete.go
internal/cli/datalakepipelines/list.go
internal/cli/datalakepipelines/pause.go
internal/cli/datalakepipelines/start.go
internal/cli/datalakepipelines/trigger.go
internal/cli/datalakepipelines/update.go
internal/cli/datalakepipelines/watch.go

_Jira ticket:_ CLOUDP-272726
This ensures the warning also shows up for the commands:
```shell
➜  mongodb-atlas-cli git:(CLOUDP-272726) ./bin/atlas dataLakePipelines list                                   
Command "list" is deprecated, Data Lake Pipelines is deprecated. Please see: https://dochub.mongodb.org/core/data-lake-deprecation.
ID    NAME   STATE
```

CLOUDP-272726: Deprecate datalakes pipeline commands

---

internal/plugin/plugin.go
test/e2e/atlas/plugin_run_test.go

- Disable flag parsing for plugin commands.
- Additional integration tests
- Updated the example plugin to support arbitrary flags: https://github.com/mongodb/atlas-cli-plugin-example/pull/15
PR by @mmarcon #3269 + some additional integration tests.
I could have managed to push my changes to the original PR, hence the new PR.
_Jira ticket:_ [CLOUDP-274948](https://jira.mongodb.org/browse/CLOUDP-274948)

CLOUDP-274948: Atlas CLI's plugin system does not support passing flags to plugins

---

internal/cli/datafederation/logs.go
test/e2e/atlas/data_federation_db_test.go

1. Reproduced the error by adding an integration test: [evergreen-run](https://spruce.mongodb.com/task/mongodb_atlas_cli_master_e2e_atlas_datafederation_atlas_datafederation_db_e2e_patch_e304af62c5de36478f8aa116ba3e0473772cd569_66f5643fad09cf00077bdeac_24_09_26_13_40_25?execution=0&sortBy=STATUS&sortDir=ASC)
2. Fixed the issue: [evergreen-run](https://spruce.mongodb.com/task/mongodb_atlas_cli_master_e2e_atlas_datafederation_atlas_datafederation_db_e2e_patch_e304af62c5de36478f8aa116ba3e0473772cd569_66f56763441a820007e28d2e_24_09_26_13_53_47?execution=0&sortBy=STATUS&sortDir=ASC)
_Jira ticket:_ CLOUDP-275630

CLOUDP-275630: [AtlasCLI] NilPointer exception when downloading datafederation logs

---

internal/cli/clusters/watch.go
internal/cli/clusters/watch_test.go
internal/decryption/log_record.go

`atlas cluster watch` does not return a `404` after running `atlas cluster upgrade`.
However, I did encounter a `401` because the bearer token expires within the time that the cluster is done upgrading.
- removed 404 check
- added bearer token refresh logic when hitting 401
_Jira ticket:_ CLOUDP-277610

CLOUDP-277610: [AtlasCLI] Clusters watch is broken when using atlas upgrade

---

internal/cli/output_opts.go

Fix executing "output" at <.Results>
_Jira ticket:_ CLOUDP-270626
the current implementation of `internal/cli/organizations/list.go`
is
```go
const listTemplate = `ID	NAME{{range valueOrEmptySlice .Results}}
{{.Id}}	{{.Name}}{{end}}
`
func (opts *ListOpts) Run() error {
r, err := opts.store.Organizations(opts.newOrganizationListOptions())
if err != nil {
return err
}
return opts.Print(r)
}
```
if we update to something like
```go
func (opts *ListOpts) Run() error {
r, err := opts.store.Organizations(opts.newOrganizationListOptions())
if err != nil {
return err
}
r = nil
return opts.Print(r)
}
```
we start getting the error `Error: template: output:1:15: executing "output" at <.Results>: nil pointer evaluating *admin.PaginatedOrganization.Results` which is exactly …

CLOUDP-270626 Fix executing "output" at <.Results>

---

internal/cli/deployments/options/deployment_opts.go
internal/cli/deployments/search/indexes/list.go

This PR fixes the discrepancy in `atlas deployments search indexes list` and `atlas clusters search indexes list` where the deployment command returns an error if the cluster is in the UPDATING state.
_Jira ticket:_ CLOUDP-278196
I was able to reproduce the issue
```bash
atlas clusters search indexes list --clusterName Cluster0 --collection listingsAndReviews --db sample_airbnb                                
ID                         NAME      DATABASE        COLLECTION           TYPE
670e63122b37bb42dc933cf7   default   sample_airbnb   listingsAndReviews   search
atlas deployments search indexes list -P dev --deploymentName Cluster0 --db sample_airbnb --collection listingsAndReviews                                
Error: deployment is in unexpected state: UPDATING
```
and I tested that …

CLOUDP-278196: Discrepancy in "atlas deployments search indexes list" and "atlas clusters search indexes list"

---

internal/kubernetes/operator/config_exporter.go
test/e2e/atlas/kubernetes_config_generate_test.go

_Jira ticket:_ CLOUDP-278912
The Atlas CLI Kubernetes config export should not fail when there is no Federated Auth configured.

CLOUDP-278912: Export without Fed Auth

---

internal/kubernetes/operator/config_exporter.go
internal/kubernetes/operator/deployment/deployment.go
internal/kubernetes/operator/deployment/deployment_test.go

Fixed the error when exporting a serverless instance on GCP, because of unsupported PE for GCP.
_Jira ticket:_ [CLOUDP-278461](https://jira.mongodb.org/browse/CLOUDP-278461)

CLOUDP-278461: Kubernetes Operator - Fixed Serverless PE export for GCP provider

---

internal/cli/deployments/logs.go
internal/cli/deployments/logs_test.go

After selecting an atlas deployment, prompt `--host` and `--name` when they're not provided, instead of failing the command.
_Jira ticket:_ CLOUDP-275876

CLOUDP-275876: UX: atlas deployment logs

---

internal/cli/deployments/setup.go

Quote connection string
_Jira ticket:_ CLOUDP-200470
Expected change in output
```diff
Deployment Name   local491
MongoDB Version   8.0
Creating your cluster local491 [this might take several minutes]
1/3: Starting your local environment...
2/3: Downloading the latest MongoDB image to your local environment...
3/3: Creating your deployment local491...
Deployment created!
- Connection string: mongodb://localhost:57981/?directConnection=true
+ Connection string: "mongodb://localhost:57981/?directConnection=true"
connection skipped
```

CLOUDP-200470 Quote connection string

---

internal/cli/deployments/setup.go

"atlas deployments setup" simplify progress message
_Jira ticket:_ CLOUDP-276101
Expected change in output
```diff
Deployment Name   local491
MongoDB Version   8.0
- Creating your cluster local491 [this might take several minutes]
+ Creating your cluster local491
1/3: Starting your local environment...
2/3: Downloading the latest MongoDB image to your local environment...
3/3: Creating your deployment local491...
Deployment created!
Connection string: mongodb://localhost:57981/?directConnection=true
connection skipped
```

CLOUDP-276101 "atlas deployments setup" simplify progress message

---

test/e2e/atlas/atlas_e2e_test_generator_test.go

The logs indicate that the same key is deleted twice; the second time, it fails because it's already deleted.
Logs
> [2024/10/30 22:05:20.169]     cleanup_test.go:87: Deleting key with ID: 67226be6c43fdd4259ed21a6
[2024/10/30 22:05:20.169]     cleanup_test.go:87: Deleting key with ID: 67226be6c43fdd4259ed21a6
[2024/10/30 22:05:20.252] Error: https://cloud-dev.mongodb.com/api/atlas/v2/orgs/5efda682a3f2ed2e7dd6cde4/apiKeys/67226be6c43fdd4259ed21a6 DELETE: HTTP 400 Bad Request (Error code: "API_KEY_NOT_FOUND") Detail: No API key with ID 67226be6c43fdd4259ed21a6 exists. Reason: Bad Request. Params: [67226be6c43fdd4259ed21a6], BadRequestDetail:
I have changed the code to create a unique list of keys and then delete them.
_Jira ticket:_ CLOUDP-281885

CLOUDP-281885: atlas_cleanup_e2e fails

---

internal/cli/deployments/options/deployment_opts_pre_run.go

Error: currently there are no deployments when atlas deployments are present
_Jira ticket:_ CLOUDP-279322
this change is scoping state checks to local deployments only

CLOUDP-279322 Error: currently there are no deployments when atlas deployments are present

---

test/e2e/atlas/atlas_e2e_test_generator_test.go

We clean up keys in 2 places concurrently, there's some overlap. Make deleting keys more resilient

E2E cleanup Make deleting keys more resilient

---

docs/command/mongocli-cloud-manager-clusters-create.txt
docs/command/mongocli-cloud-manager-clusters-update.txt
docs/command/mongocli-ops-manager-clusters-create.txt
docs/command/mongocli-ops-manager-clusters-update.txt
internal/cli/opsmanager/clusters/create.go
internal/cli/opsmanager/clusters/update.go

Adds dochub links to cluster config file docs
Note: To my knowledge there is no way to hyperlink in the .go file parameters
_Jira ticket:_ DOCSP-41212

DOCSP-41212: Add dochub links to cluster configuration file page

---

Makefile
build/ci/evergreen.yml
internal/cli/deployments/options/deployment_opts.go
internal/decryption/log_record.go
test/e2e/atlas/deployments_local_nocli_test.go

Failed Task: mongodb-atlas-cli-master-atlas_deployments_local_auth_e2e/e2e_local_deployments_ubuntu22
_Jira ticket:_ CLOUDP-284609
This change pulls localdev image from artifactory instead of docker, this is effectively caching the image in our infra the only drawback is we might run slightly outdated images which for CLI tests should not be a big deal, more updated tests should live in the image repo anyways

CLOUDP-284609 Failed Task: mongodb-atlas-cli-master-atlas_deployments_local_auth_e2e/e2e_local_deployments_ubuntu22

---

internal/cli/root/builder.go

When refreshing our refresh token we print:
```go
_, _ = log.Warningf("Could not refresh access token: %s\n", err.Error())
```
This is unnecessary since we also return the error to the caller function, which also logs the error.
Before:
```
mongodb-atlas-cli-master on  fix-double-auth-error [$] via 🐹 v1.23.3
❯ ./bin/atlas cluster watch Cluster03739
Could not refresh access token: session expired
Please note that your session expires periodically.
If you use Atlas CLI for automation, see https://www.mongodb.com/docs/atlas/cli/stable/atlas-cli-automate/ for best practices.
To login, run: atlas auth login
Error: session expired
Please note that your session expires periodically.
If you use Atlas CLI for automation, see https://www.mongodb.com/docs/atlas/cli/stable/atlas-cli-automate/ for …
```

Flyby: Remove duplicate logging when refresh token expired

---

.github/workflows/autoupdate-sdk.yaml

Create SDK PRs via apix-bot
_Jira ticket:_ CLOUDP-284685

CLOUDP-284685 Create SDK PRs via apix-bot

---

internal/oauth/oauth.go
internal/store/store.go
internal/transport/transport.go

Unify http transport
_Jira ticket:_ CLOUDP-279538

CLOUDP-279538 Unify http transport

---

test/e2e/atlas/kubernetes_config_generate_test.go

This fixes behaviour for a flaky e2e test. Currently, the e2e test asserts config generation and can spuriously pick up kinds generated by other e2e tests executed concurrently.
This fixes it by filtering them.
_Jira ticket:_ CLOUDP-284179

CLOUDP-284179: test/e2e/atlas: filter global kinds for certain e2e tests

---

internal/cli/clusters/create.go
internal/cli/clusters/describe.go
internal/cli/clusters/describe_test.go

This PR updates the `atlas cluster get` command to support Flex Cluster. The command tries to call the cluster API first and, in the event of a 400 error, calls the flex cluster APIs 
Here is the error that you get when using Cluster API with flex clusters                                                                                 
`Error: https://cloud.mongodb.com/api/atlas/v2/groups/663268874ddd3b236fd2f107/clusters/Cluster22 GET: HTTP 400 Bad Request (Error code: "CANNOT_USE_FLEX_CLUSTER_IN_CLUSTER_API") Detail: Flex cluster Cluster22 cannot be used in the Cluster API. Reason: Bad Request. Params: [Cluster22]`
<details>
<summary>Dedicated Cluster </summary>
```bash
./bin/atlas cluster get Cluster0 -P prod …
```

CLOUDP-285943: update `atlas cluster get` to support Flex Clusters

---

.github/workflows/code-health.yml

Coverage doesn't seem to have sufficient permissions to comment: https://github.com/mongodb/mongodb-atlas-cli/actions/runs/12117387295/job/33784007552

Added write permissions to code-health workflow

---

docs/command/atlas-users.txt
internal/cli/users/users.go

A user filed docs feedback that pointed out that no "atlas users list" command is available. This PR removes mention of it from the top-level docs page and --help.
_Jira ticket:_ https://jira.mongodb.org/browse/DOCSP-45722

(DOCSP-45722) Removes mention of a users list command since there is none available

---

docs/command/atlas-clusters-create.txt
internal/api/executor.go
internal/api/formatter.go
internal/api/formatter_test.go
internal/api/httprequest.go
internal/api/httprequest_test.go
internal/api/interface.go
internal/cli/api/api.go
internal/cli/api/command_request.go
internal/cli/api/command_request_test.go

- support for `--format`
- support content type
- support go templates
- support for `--output`
- `--output` is required when not piping `stdout` and content type is binary
- fixed bug where all flags were set even though the user did not set them + added more tests
_Jira ticket:_ CLOUDP-280747

CLOUDP-280747: Build a layer to handle --format

---

internal/cli/clusters/delete.go
internal/cli/clusters/delete_test.go

_Jira ticket:_ CLOUDP-285945
This PR updates `atlas cluster delete` to support Flex Clusters.
```
./bin/atlas cluster delete ClusterFlex -P prod                                                                                           
? This operation will delete the cluster and all of its data. Confirm your backup settings before terminating your cluster. This action cannot be undone.
Are you sure you want to terminate ClusterFlex? Yes
Deleting cluster 'ClusterFlex'
```
```
./bin/atlas cluster delete ClusterM10 -P prod --force                                                                                      
Deleting cluster 'ClusterM10'
```

CLOUDP-285945: Add support for Flex Clusters to `atlas cluster remove`

---

internal/cli/backup/snapshots/describe.go
internal/cli/backup/snapshots/describe_test.go
internal/cli/backup/snapshots/snapshots.go

Ticket: CLOUDP-285948
This PR adds support for Flex Cluster to `atlas backup snaphots get`
```json
./bin/atlas backup snapshots get 6760158f52708c22437edb7a --clusterName ClusterFlex -P prod -o json                               
{
"expiration": "2024-12-24T11:56:22Z",
"finishTime": "2024-12-16T11:58:50Z",
"id": "6760158f52708c22437edb7a",
"mongoDBVersion": "8.0.3",
"scheduledTime": "2024-12-16T11:56:22Z",
"startTime": "2024-12-16T11:57:09Z",
"status": "COMPLETED"
}
```
```bash
./bin/atlas backup snapshots get 6760158f52708c22437edb7a --clusterName ClusterFlex -P prod                                          
ID                         STATUS      MONGODB VERSION   START TIME                      FINISH TIME                     EXPIRATION
6760158f52708c22437edb7a   COMPLETED   8.0.3 …
```

CLOUDP-285948: add support for flex clusters to 'atlas backup snaphots get'

---

internal/cli/backup/snapshots/list.go
internal/cli/backup/snapshots/list_test.go

Ticket: CLOUDP-285949
This PR adds support for Flex Cluster to `atlas backup snapshot ls`
<details>
<summary>Flex Cluster </summary>
```
./bin/atlas backup snapshots list ClusterFlex -P prod
ID                         STATUS      MONGODB VERSION   START TIME                      FINISH TIME                     EXPIRATION
675acf673a6b85483b198fd9   COMPLETED   8.0.3             2024-12-12 11:56:29 +0000 UTC   2024-12-12 11:58:09 +0000 UTC   2024-12-20 11:56:22 +0000 UTC
675c210196f62d6daa176b5c   COMPLETED   8.0.3             2024-12-13 11:56:55 +0000 UTC   2024-12-13 11:58:34 +0000 UTC   2024-12-21 11:56:22 +0000 UTC
675d728f52708c2243e0b536   COMPLETED   8.0.3             2024-12-14 11:57:09 +0000 UTC   2024-12-14 11:58:50 +0000 UTC   2024-12-22 11:56:22 +0000 UTC …
```

CLOUDP-285949: add support for flex clusters to `atlas backup snaphots list`

---

internal/cli/backup/restores/list.go
internal/cli/backup/restores/list_test.go
internal/cli/backup/restores/restores.go

_Jira ticket:_ CLOUDP-285952
<details>
<summary> Flex Cluster </summary>
```bash
./bin/atlas backup restore list ClusterFlex -P prod                                                                                       
ID                         SNAPSHOT                   CLUSTER       TYPE      EXPIRES AT
676199f379377141139ad79c   6760158f52708c22437edb7a   ClusterFlex   RESTORE   2024-12-17 21:34:11 +0000 UTC
```
```json
./bin/atlas backup restore list ClusterFlex -P prod -o json                                                                               
{
"links": [
{
"href": "https://cloud.mongodb.com/api/atlas/v2/groups/663268874ddd3b236fd2f107/flexClusters/ClusterFlex/backup/restoreJobs?includeCount=true\u0026pageNum=1\u0026itemsPerPage=100",
"rel": "self"
}
],
"results": [
{ …
```

CLOUDP-285952: add support for flex clusters to `atlas backup restores list`

---

internal/cli/backup/restores/describe.go
internal/cli/backup/restores/describe_test.go
internal/cli/backup/restores/restores.go

_Jira ticket:_ CLOUDP-285953
This PR updates `atlas backup restores get` to support flex clusters.
<details>
<summary> Flex Cluster </summary>
```json
./bin/atlas backup restore get 676199f379377141139ad79c --clusterName ClusterFlex -P prod -o json                                   
{
"deliveryType": "RESTORE",
"expirationDate": "2024-12-17T21:34:11Z",
"id": "676199f379377141139ad79c",
"instanceName": "ClusterFlex",
"projectId": "663268874ddd3b236fd2f107",
"restoreFinishedDate": "2024-12-17T15:35:01Z",
"restoreScheduledDate": "2024-12-17T15:34:11Z",
"snapshotFinishedDate": "2024-12-16T11:58:50Z",
"snapshotId": "6760158f52708c22437edb7a",
"status": "COMPLETED",
"targetDeploymentItemName": "ClusterFlex",
"targetProjectId": "663268874ddd3b236fd2f107"
}
```
```bash
./bin/atlas backup restore …
```

CLOUDP-285953: add support for flex clusters to `atlas backup restores get`

---

go.mod
go.sum

Ticket: CLOUDP-291067
Security Vulnerability: https://github.com/mongodb/mongodb-atlas-cli/security/dependabot/15

CLOUDP-291067: upgrade x/net to fix security vulnerability

---

internal/cli/plugin/plugin_github_asset.go
internal/cli/plugin/plugin_github_asset_test.go

While I was working on the rust example, I noticed some issues.
I've improved the Atlas CLI plugin compatibility:
- also support architecture names used by rust triplets: `x86_64`, `aarch64`, `i386`, `x86`
- add more content types for gzip: `appliction/x-gtar`, `application/x-gzip`
- when the plugin is wrapped in a single directory aka `root/plugin/manifest.yml`, get rid of the wrapper directory in root -> `root/manifest.yml`

Make plugin support more flexible

---

internal/cli/backup/restores/describe.go

_Jira ticket:_ CLOUDP-291947
The `backup restore get` does not print the download URL for flex cluster because the current template uses an array instead of a string. This PR updates the template to use the correct type

CLOUDP-291947: fix template error with `backup restore get`

---

internal/cli/clusters/create.go
internal/cli/clusters/delete.go
internal/cli/clusters/update.go
internal/cli/clusters/upgrade.go

_Jira ticket:_ CLOUDP-292067
While testing locally I noticed that some cluster commands retrieve the projectID directly from the opts instead of using `ConfigProjectID`. We must use `ConfigProjectID` so that we retrieve the projectID from the config file when its value is not provided via flag.

CLOUDP-292067: fix bug on cluster commands when getting the projectId

---

build/ci/evergreen.yml

Attempting to make evergreen pick up snyk cron

removed . from variant_tags for snyk

---

build/ci/evergreen.yml

Reverts mongodb/mongodb-atlas-cli#3433
This PR is stopping the periodic builds from running, not fixing the original issue.
I noticed because I copied the "fix" as an example and my periodic build never worked.
After removing the dots in the tags, periodic builds work again.
PR: https://github.com/mongodb/mongodb-atlas-cli/pull/3512
Working periodic build run: https://spruce.mongodb.com/version/67769f6c31e0eb000723a0b7/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

Revert "fix: periodic builds not running"

---

internal/cli/auth/logout.go
internal/cli/refresher_opts.go
internal/oauth/oauth.go
internal/store/store.go
internal/transport/transport.go

Refresh bearer token inside store
_Jira ticket:_ CLOUDP-279516
moving to `golang.org/x/oauth2` is beyond the scope of this PR

CLOUDP-279516 Refresh bearer token inside store

---

internal/cli/setup/cluster_setup.go
internal/cli/setup/setup_cmd.go

- Followed up why the endpoint stopped working because apparently we expect TENANT for providing the versions, I'm actually removing the need to set cloud provider here

chore: set provider to tenant if M0,M2 or M5

---

build/ci/evergreen.yml
test/e2e/atlas/plugin_first_class_test.go

Adds an e2e test as a part of the Evergreen workflow to verify that the K8s plugin is successfully installed.
_Jira ticket:_ [CLOUDP-293169](https://jira.mongodb.org/browse/CLOUDP-293169)

test: Adds e2e test to verify k8s plugin installs

---

build/ci/copy.bara.sky.template

Updates Copybara actions such that kubernetes docs are not removed from the docs repos.
This method was tested in a PoC [here](https://github.com/mongodb/atlas-cli-plugin-example/commit/c36cd6bd6c2102b0c3d1510a92021b01945ba41c) using github actions instead of Evergreen. The resulting PR in a fork of Docs Atlas CLI was [this](https://github.com/cveticm/docs-atlas-cli-fork/pull/17), where no K8s docs are modified despite not being present in the test plugin repo, as expected.
_Jira ticket:_ [CLOUDP-293170](https://jira.mongodb.org/browse/CLOUDP-293170)

CLOUDP-293170: Update copybara to exclude k8s docs

---

internal/kubernetes/operator/install.go
test/e2e/atlas/kubernetes_operator_install_test.go

_Jira ticket:_ CLOUDP-293859
This fixes the re-enabled tests that have been turned on as part of https://github.com/mongodb/mongodb-atlas-cli/pull/3530.

CLOUDP-293859: test/e2e/atlas/kube: fix tests

---

internal/cli/alerts/acknowledge.go
internal/cli/alerts/settings/create.go
internal/cli/alerts/settings/update.go
internal/cli/alerts/settings/validator.go

Had this staged, mainly make the validation methods take the `opts` as a receiver instead of an arg since it makes more sense that way

chore: make opts a receiver for validation functions

---

internal/cli/plugin/plugin_github_asset.go
internal/cli/plugin/plugin_github_asset_test.go
internal/cli/plugin/update.go
internal/cli/plugin/update_test.go

Support for pre-release+metadata (full semver support)
_Jira ticket:_ CLOUDP-294346

CLOUDP-294346: [AtlasCLI] Support pre-releases format in CLI plugin versions

---

internal/cli/backup/restores/start.go
internal/kubernetes/operator/project/project.go
internal/kubernetes/operator/project/project_test.go

Flex: Fix bug with restore jobs, TargetProjectID is optional
_Jira ticket:_ [CLOUDP-296190](https://jira.mongodb.org/browse/CLOUDP-296190)

CLOUDP-296190: [Flex Clusters] --targetProjectId is not handled properly

---

internal/plugin/plugin.go
internal/telemetry/event.go

Added the following telemetry data for plugins:
- `plugin_install_type`
- `plugin_github_owner`
- `plugin_github_repository`
- `plugin_version`
_Jira ticket:_ CLOUDP-290565

CLOUDP-290565: [AtlasCLI] Add telemetry metadata to generic plugin calls

---

docs/command/atlas.txt
internal/cli/plugin/first_class.go
tools/docs/main.go

The current logic in the doc generator tool removes all plugins for being included in the docs generation. This has resulted in a change in `atlas.txt` where ```* :ref:`atlas-kubernetes` - Manage Kubernetes resources.```  is removed from the document.
This ticket modifies logic in the docs generator tool to include first class plugin commands. 
_Jira ticket:_ CLOUDP-296375

CLOUDP-296375: Adds k8s command to gen docs command tree

---

internal/cli/deployments/options/deployment_opts.go
internal/config/profile.go

Look for a custom "Atlas local development" image in the following places and order:
1. `ATLAS_LOCAL_DEPLOYMENT_IMAGE` environment variable
2. `local_deployment_image` profile setting
3. Fallback to hardcoded `docker.io/mongodb/mongodb-atlas-local` (can still be overridden by build)
_Jira ticket:_ CLOUDP-295015

CLOUDP-295015: [Local Atlas Experience] Add support for private Docker registries

---

build/ci/copy.bara.sky.template

This adds an exclude to the destination_files for copybara for the Atlas CLI docs repo so that the handwritten atlas-api file we are adding in the following PR is never overwritten by copybara: https://github.com/mongodb/docs-atlas-cli/pull/838
**Please note, I am having trouble running copybara locally at the moment so I am unable to test this, but this should prevent overwriting the file**
https://jira.mongodb.org/browse/DOCSP-46837

(DOCSP-46837) Adds an exclude to avoid overwriting handwritten atlas-api file

---

internal/cli/deployments/connect.go
internal/cli/deployments/connect_test.go
internal/cli/deployments/delete.go
internal/cli/deployments/delete_test.go
internal/cli/deployments/logs.go
internal/cli/deployments/logs_test.go
internal/cli/deployments/options/deployment_opts_remove.go
internal/cli/deployments/options/deployment_opts_telemetry.go
internal/cli/deployments/pause.go
internal/cli/deployments/pause_test.go
internal/cli/deployments/search/indexes/create.go
internal/cli/deployments/search/indexes/create_test.go
internal/cli/deployments/search/indexes/delete.go
internal/cli/deployments/search/indexes/delete_test.go
internal/cli/deployments/search/indexes/describe.go
internal/cli/deployments/search/indexes/describe_test.go
internal/cli/deployments/search/indexes/list.go
internal/cli/deployments/search/indexes/list_test.go
internal/cli/deployments/setup.go
internal/cli/deployments/setup_test.go
internal/cli/deployments/start.go
internal/cli/deployments/start_test.go
internal/mocks/mock_deployment_opts_telemetry.go

_Jira ticket:_ CLOUDP-297205
- Decouples UUID collection into it's own method
- For pause and delete, moves collection to happen before the core command is ran and after selection is done, so that we can collect the UUID for the right deployments
- For other commands that end up with a healthy deployment, we collect at `PostRun`
- Deployments list does not do any collection

CLOUDP-297205: Fix duplicated telemetry and early uuid collection

---

internal/cli/config/set.go
internal/config/profile.go

Improved property handling in `profile.go`
Originally, we had: `GlobalProperties` and `Properties`.
- `GlobalProperties` contains only global properties
- `Properties` on the other hand should contain `GlobalProperties` + the properties in the profile, which is not clear
Changes:
- Renamed `Properties` -> `AllProperties`
- Introduced `ProfileProperties`
-  `AllProperties` now returns a combination of `GlobalProperties` + `ProfileProperties`
This should avoid bugs in the future.
_Jira ticket:_ CLOUDP-297944

CLOUDP-297944: [AtlasCLI] Improve config properties handling

---

.github/workflows/autoupdate-sdk.yaml
.github/workflows/code-health.yml
.github/workflows/dependabot.yml
.github/workflows/docker-release.yml
.github/workflows/e2e-tests.yml
.github/workflows/issues.yml

Pin third-party GitHub Actions to a specific SHA
_Jira ticket:_ CLOUDP-297955

CLOUDP-297955: Pin third-party GitHub Actions to a specific SHA

---

docs/command/atlas-clusters-create.txt
docs/command/atlas-clusters-update.txt
internal/cli/clusters/clusters.go
internal/cli/clusters/create.go
internal/cli/clusters/update.go

Improved:
- Help message when using `--tier` on `atlas cluster create` and `atlas cluster update`
- Improved docs for both pages too.
_Jira ticket:_ CLOUDP-295930

CLOUDP-295930: Update help docs for clusters for shimming logic

---

test/e2e/atlas/clusters_upgrade_test.go

This PR removes the e2e test that upgrade a cluster to M2 since M2 and M5 are not deprecated.

CLOUDP-298862: remove unsupported test feature

---

internal/cli/backup/restores/start.go
internal/cli/backup/restores/start_test.go
internal/cli/backup/restores/watch.go
internal/mocks/mock_cloud_provider_backup.go
internal/store/cloud_provider_backup.go
test/e2e/atlas/backup_flex_test.go
test/e2e/atlas/backup_restores_test.go

_Jira ticket:_ CLOUDP-299544
Bug:
The `atlas backup restore start download` returns `MISSING_ATTRIBUTE` error when trying a restore download with a Dedicated Cluster. The reason is that we are wrongly calling the Flex API.
This PR updates the command logic to get the cluster first to see if is flex or not, and then call the right API.
```bash
atlas backup restore start download --clusterName Cluster0 --snapshotId 67a645ae781f9601bf0925bb -P prod
Error: https://cloud.mongodb.com/api/atlas/v2/groups/663268874ddd3b236fd2f107/flexClusters/Cluster0/backup/restoreJobs POST: HTTP 400 Bad Request (Error code: "MISSING_ATTRIBUTE") Detail: The required attribute targetProjectId was not specified. Reason: Bad Request. Params: [targetProjectId], BadRequestDetail:
```
Fix:
```bash
./bin/atlas backup …
```

CLOUDP-299544: `atlas backup restore start download` requires targetProjectId for dedicated cluster

---

internal/kubernetes/operator/config_exporter.go
internal/kubernetes/operator/project/customroles_test.go
internal/kubernetes/operator/project/ipaccesslist.go
internal/kubernetes/operator/project/ipaccesslist_test.go
internal/kubernetes/operator/project/privateendpoints_test.go
internal/kubernetes/operator/project/project.go
internal/kubernetes/operator/project/project_test.go
test/e2e/atlas/kubernetes_config_generate_test.go

This PR add the support to export the new custom resource for IP Access List
_Jira ticket:_ CLOUDP-283513

CLOUDP-283513: IP Access List new resource

---

internal/api/api.go
tools/api-generator/convert.go
tools/api-generator/fixtures/07-sunset.yaml

fix x-sunset should be defined at responses
_Jira ticket:_ CLOUDP-299959

CLOUDP-299959 fix x-sunset should be defined at responses

---

internal/api/executor.go
internal/api/interface.go
internal/api/watcher.go
internal/api/watcher_test.go
internal/cli/api/api.go
internal/cli/api/watcher.go

Added `--watch` support for autogenerated commands.
Introduced two watcher structs:
- `api.Watcher`: Takes care of executing the API call and verifying the output
- `cli.Watcher`: Takes care of calling `api.Watcher` in a loop, cancellation, showing spinner
Changes to Executor:
- I had to move formatting out of the executor because we need to feed the original request's unformatted response to the watcher.
- I only save the response to memory when a watcher is enabled; if not, I pass the HTTP reader to the formatted without storing the response in memory.
- Executing a command now also exposes the HTTPCode so that we can watch the HTTP code
Testing:
- I added new unit tests for most functions, which should cover most cases
- I tested manually by adding the watcher configuration for …

CLOUDP-297411: Implement --watch support

---

internal/cli/plugin/plugin_github_asset.go

Improves error message for failure on retrieving github assets by explicitly noting Github access is required. 
_Future works:_ When [DOCSP-46527](https://jira.mongodb.org/browse/DOCSP-46527) is completed, a link to the troubleshooting docs outlining this will be included.
_Jira ticket:_ [CLOUDP-297379](https://jira.mongodb.org/browse/CLOUDP-297379)

CLOUDP-297379: Improve plugin install/update error message

---

go.mod
go.sum
internal/cli/plugin/plugin_github_asset.go

Seems like with some recent changes some dependencies that used to be indirect were made direct but we never moved them around for easy finding

task: fix go mod grouping

---

internal/mongodbclient/collection.go

CLOUDP-300554: fix lastversion fields

---

internal/api/commands.go
internal/plugin/plugin.go
tools/api-generator/.snapshots/04-spec-with-overrides.yaml.snapshot
tools/api-generator/.snapshots/08-watchers.yaml.snapshot
tools/api-generator/commands.go.tmpl
tools/api-generator/convert.go
tools/api-generator/fixtures/06-spec-with-cli-specific-extensions.yaml
tools/api-generator/fixtures/08-watchers.yaml
tools/api-generator/overlays/watchers.yaml
tools/api-generator/watcher.go

- added watcher settings validation
- fixed existing watchers
- fix parameters bug
_Jira ticket:_ CLOUDP-300050

CLOUDP-300050: validate spec on update PRs

---

.github/workflows/code-health.yml

Remove apix-bot from coverage comment
_Jira ticket:_ CLOUDP-299258

CLOUDP-299258 Remove apix-bot from coverage comment

---

internal/file/file.go
internal/file/file_test.go
test/e2e/atlas/clusters_file_test.go
test/e2e/atlas/data/create_index_test-unknown-fields.json

- Print warning when JSON/Yaml contains unknown fields
- Added unit tests
- Added e2e tests
_Jira ticket:_ CLOUDP-302438

CLOUDP-302438: [AtlasCLI] Print warning when user provides unsupported fields in JSON/YAML files

---

.github/workflows/code-health.yml
.golangci.yml
Makefile
go.mod
internal/cli/datafederation/logs_test.go
internal/telemetry/tracker_test.go
internal/validate/validate_test.go
test/e2e/config/config_test.go

Was having some issues with the old linter locally, tried to update to fix them and it works so let's keep it on latest

[task] update golangci-lint to 1.64.6

---

tools/genevergreen/generate/generate.go
tools/genevergreen/generate/generate_test.go

CLOUDP-303934
MDB5.0 has been EOL since last year, let's stop publishing to the repo and drop support for it

CLOUDP-303934: Drop mdb5.0 from atlascli

---

build/ci/evergreen.yml
test/e2e/atlas/backup_flex_test.go
test/e2e/atlas/cleanup_test.go
test/e2e/atlas/clusters_file_test.go
test/e2e/atlas/helper_test.go
test/e2e/atlas/setup_failure_test.go
test/e2e/config/config_test.go
test/e2e/iam/atlas_orgs_test.go

Remove references to MCLI which was the legacy namespace from the monoglci days, and update to the Atlas documented one `MONGODB_ATLAS`

[tests] remove references to MCLI

---

Makefile
internal/cli/api/api.go
tools/docs/main.go
tools/docs/transformations.go

Add operationId to API commands and restructure docs generation tool
_Jira ticket:_ CLOUDP-304933

CLOUDP-304933 Add operationId to API commands and restructure docs generation tool

---

docs/command/atlas-api-clusterOutageSimulation-endOutageSimulation.txt
docs/command/atlas-api-clusterOutageSimulation-startOutageSimulation.txt
internal/api/commands.go
tools/api-generator/overlays/watchers.yaml

- added `--watch` to cluster outage simulation commands start/end
_Jira ticket:_ CLOUDP-305570
Ran these commands:
`outage_simulation.json`
```
{
"outageFilters": [
{
"cloudProvider": "AWS",
"regionName": "EU_WEST_3",
"type": "REGION"
}
]
}
```
```sh
atlas api clusterOutageSimulation startOutageSimulation --version 2023-01-01 --clusterName Cluster0 --file outage_simulation.json --watch
```
```sh
atlas api clusterOutageSimulation endOutageSimulation --version 2023-01-01 --clusterName Cluster0 --watch
```

CLOUDP-305570: Add --watch to Outage simulation

---

internal/cli/dbusers/update.go
test/e2e/atlas/dbusers_test.go

_Jira ticket:_ CLOUDP-305822
The `atlas dbusers update [USER] --password [PASS]` sets the roles and scope array to empty.
Set the roles and scope in the request body only when the user provides their flags.
```json
atlas dbusers get Quickstart-1635259359 -P dev -o dev
{
"awsIAMType": "NONE",
"databaseName": "admin",
"groupId": "5e4e593f70dfbf1010295836",
"labels": [],
"ldapAuthType": "NONE",
"links": [
{
"href": "https://cloud-dev.mongodb.com/api/atlas/v2/groups/5e4e593f70dfbf1010295836/databaseUsers/admin/Quickstart-1635259359",
"rel": "self"
}
],
"oidcAuthType": "NONE",
"roles": [
{
"databaseName": "admin",
"roleName": "atlasAdmin"
}
],
"scopes": [],
"username": "Quickstart-1635259359",
"x509Type": "NONE"
}
```
```json
atlas dbusers update Quickstart-1635259359  --password 'test' -P dev …
```

CLOUDP-305822: `atlas dbusers update [USER] --password [PASS]`is resetting the roles to an empty array

---

docs/command/atlas-projects-apiKeys-create.txt
internal/cli/projects/apikeys/create.go

Adds example to `atlas projects apiKeys create` outlining how to use the command with multiple lesser privilege roles. 
Allowing for UI role names has not been implemented now that [linked documentation](https://www.mongodb.com/docs/atlas/reference/user-roles/) explicits the mapping of role names across UI and CLI/API/etc.
_Jira ticket:_ [CLOUDP-298177](https://jira.mongodb.org/browse/CLOUDP-298177)

CLOUDP-298177: Improve apiKey creation examples

---

internal/api/httprequest.go
internal/api/httprequest_test.go
tools/cmd/api-generator/convert_metadata.go
tools/cmd/api-generator/overlays/examples_project_ip_access_list.yaml
tools/cmd/docs/metadata.go

Added examples for:
- `createProjectIpAccessList`
- `deleteProjectIpAccessList`
- `getProjectIpAccessListStatus`
- `getProjectIpList`
- `listProjectIpAccessLists`
_Jira ticket:_ CLOUDP-303343

CLOUDP-303343: Create example for auto-generated projectIPAcessList CRUD operations

---

.github/workflows/update-e2e-tests.yml

simply add label `update-snapshots` to any PR, the tool will update them
follow up from https://github.com/mongodb/mongodb-atlas-cli/pull/3760

chore: update test snapshots for a given PR

---

test/e2e/helper_test.go

[atlas_gov_performance_advisor_e2e](https://evergreen.mongodb.com/task/mongodb_atlas_cli_master_e2e_atlas_gov_clusters_atlas_gov_performance_advisor_e2e_5619801f7de4d40cc20a5668fac229f4e100f760_25_03_26_17_17_46) is flaky on evergreen. The latest build failed with this [error](https://evergreen.mongodb.com/test_log/mongodb_atlas_cli_master_e2e_atlas_gov_clusters_atlas_gov_performance_advisor_e2e_5619801f7de4d40cc20a5668fac229f4e100f760_25_03_26_17_17_46/2?test_name=f74df5f3ca2a0136a6ef7c5c99be743a#L4) related to the cluster name generated by the e2e logic:
```
POST: HTTP 400 Bad Request (Error code: "CLUSTER_NAME_PREFIX_INVALID") Detail: Cluster name "performanceAdvisor-538-5619801f7de4d40cc20a5668fac229f4e100f760" is invalid. Atlas truncates cluster names to 23 characters which results …
```

CLOUDP-309119: laky Test: `atlas_gov_performance_advisor_e2e`

---

go.mod

[packate_goreleaser](https://evergreen.mongodb.com/task/mongodb_atlas_cli_master_goreleaser_atlascli_snapshot_package_goreleaser_08e275995977046fc45f4a0453014eff01a4e828_25_04_01_09_02_28) is failing on waterfall. The reason is that go 1.24.1 is not yet supported in evergreen.

fix: goreleaser evergreent task

---

docs/command/atlas-deployments-connect.txt
internal/cli/deployments/connect.go
internal/cli/deployments/options/deployment_opts_connect_with.go
internal/usage/usage.go
internal/vscode/vscode.go
internal/vscode/vscode_test.go

Adds new connection option VsCode (MongoDB for VSCode) for `atlas deployment connect` command.
Restructures `vscode.go` and adds unit testing.
Logic is same as described in #3798, on selecting `vscode` as connection option:
1. the connection string is obtained
2. the vscode extension deeplink is built and called
3. vscode will open with the connection saved under name `<deployment-name> (<deployment-type>)`
Notes:
* For local deployments with username and password set, the user must provide these details for a connection string with correct authorisation to be generated. Similar to the other connection options (mongosh, compass), no warning is provided if these details are not provided; the user will be connected to the deployment but unable to access any contents of the deployment.
_Jira …

CLOUDP-308812: Adds vscode connection option to deployment connect

---

docs/command/atlas-deployments-delete.txt
internal/cli/deployments/delete.go

`atlas deployment delete` will not include logic to remove VsCode connections when deleting a deployment as a part of this epic.
This work adds a message informing users of this behaviour and that these connections must be removed manually, pointing to MongoDB for VsCode documentation.
_Jira ticket:_ [CLOUDP-310542](https://jira.mongodb.org/browse/CLOUDP-310542)

CLOUDP-310542: Add message to remove vscode connections from `atlas deployment delete` help text

---

build/ci/evergreen.yml
internal/cli/deployments/setup.go
internal/cli/deployments/setup_test.go
test/e2e/data/db_seed_fail/fail.sh
test/e2e/deployments_local_seed_fail_test.go

`--debug` now includes docker logs when `atlas deployment setup` fails
_Jira ticket:_ CLOUDP-306589

CLOUDP-306589: Extend `--debug` to include Docker logs on `atlas deployments setup --type local`

---

build/ci/release.yml

This commit adjusts our package_goreleaser task to dual write release
artifacts to the new cdn-origin-mongocli bucket. Eventually we will
remove writes to the old downloads bucket from this task.

DEVPROD-16721: dual write release files to new bucket

---

internal/container/podman.go

The seed tests are not the cause; they revealed another issue due to the increased test coverage.
There's an issue with passing volumes to the Podman implementation.
_Jira ticket:_ CLOUDP-312241
I queued the following tasks on Evergreen as part of this PR (which were failing)
Task name | Build variant
-- | --
atlas_deployments_local_seed | E2E Local Deployments Tests (rhel8/podman)
atlas_deployments_local_seed | E2E Local Deployments Tests (rhel9/podman)

CLOUDP-312241: [AtlasCLI] Podman local seed tests fail with Podman issue

---

build/ci/release.yml

This commit adjusts the role we use to write to our new bucket. The previous role will only work when we separate out Atlas CLI from Mongo CLI's infrastructure. Because the two share a common bucket for now, I've swapped over to the appropriate role with access to that bucket.

DEVPROD-16721: switch role used for writes to new bucket

---

tools/cmd/genevergreen/generate/generate.go
tools/cmd/genevergreen/generate/generate_test.go
tools/cmd/release/main.go

_Jira ticket:_ CLOUDP-317690
Ubuntu20.04 has reached EOL

CLOUDP-317690: [AtlasCLI] Drop ubuntu20.04 support

---

internal/cli/deployments/search/indexes/create.go

_Jira ticket:_ CLOUDP-316626
The CLI is marshing directly the SDK struct into Bson for the `createSearchIndex` this cause fields in the structs such as `charFilters` to be transformed in their lowercase version `charfilters`.
```bash
atlas deployments search indexes create --deploymentName local9975 --type LOCAL -f search-index.json --watch
Error: (UnknownError) "userCommand.indexes[0].analyzers[0]" unrecognized fields ["charfilters", "tokenfilters"]
```
As we are doing with other index such as `ClusterSearchIndex`, we first marsh the struct into json and then marsh into Bson to keep the same field names of the original SDK struct.
```bash
./bin/atlas deployments search indexes create --deploymentName local9975 --type LOCAL -f search-index.json --watch
Search index created with ID: …
```

CLOUDP-316626: createSearchIndex command is marshaled incorrectly

---

build/ci/release.yml

This commit removes writes to the downloads.mongodb.org S3 bucket. We have been serving traffic for atlascli from the new cdn-origin-mongocli bucket for a few weeks now without any disruption, so we should be safe to remove writing to the old bucket and complete the migration.

 DEVPROD-17956: remove writes to s3://downloads.mongodb.org

---

.github/workflows/update-ssdlc-report.yaml

Fixes `update-compliance-report` GitHub action from failing when applying labels by removing non-existing label and creating new label `compliance`.
Successful run: [action](https://github.com/mongodb/mongodb-atlas-cli/actions/runs/15531716648), [PR](https://github.com/mongodb/mongodb-atlas-cli/pull/3944)
_Jira ticket:_ [CLOUDP-322905](https://jira.mongodb.org/browse/CLOUDP-322905)

CLOUDP-322905: Fix `update-compliance-report` GitHub action

---

internal/cli/clusters/create_test.go
internal/mocks/mock_clusters.go
internal/store/clusters.go
internal/watchers/cluster.go

_Jira ticket:_ CLOUDP-323473
- Since watchers only return state and name of the cluster, we can already use the latest SDK for all clusters watchers
- https://spruce.mongodb.com/version/6846d50e01104b0007bd2d5b/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

CLOUDP-323473: Migrate watchers to latest SDK

---

Dockerfile

Fixed Docker build issues by updating base images + repositories.
Example failure: https://github.com/mongodb/mongodb-atlas-cli/actions/runs/15539188936/job/43745605276?pr=3950
_Jira ticket:_ CLOUDP-319569

CLOUDP-319569: [Local Dev] Container fails to start (intermittently); docker compose, TestContainers & GitHub Actions

---

build/ci/copy.bara.sky.template

we're consolidating our documentation repositories. Tomorrow we will move the source for the Atlas CLI documentation into the core mongodb docs repository. This updates the copybara config that creates a pull request to copy the generated docs files to the Atlas CLI docs.
We're moving the Atlas docs later so that section of the config will not change yet.

updating copybara config

---

internal/cli/backup/restores/describe.go
internal/cli/backup/restores/describe_test.go
internal/cli/backup/restores/list.go
internal/cli/backup/restores/list_test.go
internal/cli/backup/restores/restores.go
internal/cli/backup/restores/watch.go
internal/cli/backup/snapshots/describe.go
internal/cli/backup/snapshots/describe_test.go
internal/cli/backup/snapshots/list.go
internal/cli/backup/snapshots/list_test.go
internal/cli/backup/snapshots/snapshots.go
internal/cli/backup/snapshots/watch.go

_Jira ticket:_ CLOUDP-326352
- Fix fallback logic for backup snapshot/restore commands to handle CLUSTER_NOT_FOUND (deleted clusters) by trying the regular API after Flex API fails.
- Error code constants are now defined once per package and exported.
- Removed duplicate constant declarations and import cycles.
- Updated unit tests to use the exported constants.

CLOUDP-326352: Fixes backup commands to fallback to flex if not found

---

internal/cli/root/builder.go
internal/store/store.go
internal/transport/transport.go
test/e2e/brew/brew_test.go

This change migrates the auth check logic to run during transport instead of in the prerun of the root command.
**1. Remove validation from `atlas` prerun**
Now the default transport client has a wrapper which calls the default RoundTrip and, on response status 401: Unauthorized, the following error is bubbled up:
```
Error: Get "https://cloud.mongodb.com/api/atlas/v2/groups?includeCount=true&itemsPerPage=100&pageNum=1": this action requires authentication
To log in using your Atlas username and password, run: atlas auth login
To set credentials using API keys, run: atlas config init
```
The same behaviour is preserved as, if neither API Keys or Access Token are present, the default transport will be used and, if used to call a cmd that requires auth, it will error with similar messaging. …

CLOUDP-329791: Refactor auth check

---

internal/cli/backup/exports/jobs/watch.go
internal/cli/backup/restores/watch.go
internal/cli/backup/restores/watch_test.go
internal/cli/backup/snapshots/watch.go

AtlasCLI command atlas backup restore watch does not return errors
_Jira ticket:_ CLOUDP-333673

CLOUDP-333673 AtlasCLI command `atlas backup restore watch` does not return errors

---

internal/cli/root/builder.go

A merge to master done [here](https://github.com/mongodb/mongodb-atlas-cli/commit/2d6fbbff9aeb1a6f2fbbe0ac34afddaf08fd851d) resulted in work from #4036 being overwritten by the revert of the same work in master #4035. This PR restores that work.

chore: Restores changes from #4036

---

cmd/atlas/atlas.go
internal/cli/auth/login.go
internal/cli/config/set.go
internal/cli/deployments/list_test.go
internal/cli/deployments/options/deployment_opts.go
internal/cli/deployments/test/fixture/deployment_atlas.go
internal/cli/organizations/create.go
internal/cli/profile.go
internal/cli/setup/setup_cmd.go
internal/config/migrate.go
internal/config/migrate_test.go
internal/config/profile.go
internal/store/store.go
internal/store/store_test.go
internal/validate/validate.go
internal/validate/validate_test.go

* Adds support for **new profile attributes**:
* `clientID`: Service Account client ID
* `clientSecret`: Service Account client secret
* `authType`: string representing the type of authentication used by the profile
* Adds support for **new global config attribute** `version`.
* This version is not CLI version but version of the config. This is to support migrations when config logic is changed.
* Added **config migration** to loadConfig. After the config and profile are loaded in:
* Checks if config is already version == 2
* Returns
* Calculates and sets `authType` for every profile
* Saves config
* This migration will be expanded in future to migrate credentials to secure storage. There is no concern introducing the migration in two steps as the migration will not be released until …

CLOUDP-330235: Update config to support service accounts

---

.github/workflows/code-health.yml
Makefile
README.md

move to coveralls.io
_Jira ticket:_ CLOUDP-324670

CLOUDP-324670 move coverage to coveralls.io

---

internal/cli/deployments/diagnostics.go

Fixed nil pointer dereference error when there are no errors
_Jira ticket:_ CLOUDP-336714

CLOUDP-336714: [AtlasCLI] atlas_deployments_local_nocli_e2e fails

---

internal/cli/auth/logout.go
internal/cli/auth/logout_mock_test.go
internal/cli/auth/logout_test.go

This reverts commit eb92a2689092ab96eb92eff1b111767c864c0def.

Revert "CLOUDP-333260: Delete api key from profile on logout (#4094)"

---

.github/workflows/update-e2e-tests.yml
cmd/atlas/atlas.go

Failed to update test snapshots, follow up from https://github.com/mongodb/mongodb-atlas-cli/pull/4108

CLOUDP-337035 Failed to update test snapshots

---

internal/cli/auth/logout.go
internal/cli/auth/logout_test.go
internal/cli/config/delete.go
internal/config/profile.go
internal/config/profile_test.go

_Jira ticket:_ CLOUDP-329800
- Uses the same prompt as logout to run ` config delete` 
- Uses a similar approach to deployments setup to call logout
- Sends profile data on context
- Fixes panic no `ProfileFromContext`

CLOUDP-329800: Remove force when calling logout

---

build/ci/evergreen.yml
cmd/atlas/atlas.go
test/e2e/atlas/search_nodes/searchnodes/search_nodes_test.go
test/e2e/config/migration/migration_test.go
test/internal/helper.go

- Added an e2e test to verify that the config migration is working (MacOS)
1. Set up a config in legacy format
2. Set up a temporary keyring independent of the global keyring
3. Run `atlas`
4. Verify that the config doesn't contain our secrets anymore
5. Verify that the keyring contains our secrets
- Print a warning when insecure storage is being used.
_Jira ticket:_ CLOUDP-333521
- Manual testing
- Successful [evergreen run](https://spruce.mongodb.com/version/689c673ff909ee000723070f/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

CLOUDP-333521: [AtlasCLI] [Mac] Write e2e test for migration to secure storage

---

internal/cli/auth/logout.go
internal/cli/auth/logout_mock_test.go
internal/cli/auth/logout_test.go
internal/transport/transport.go

* Logs out of SA profile
* Revokes token 
* Sets SA credentials to ""
* Adjust SA logout unit tests
```
$ bin/atlas logout -P oauth2
? Are you sure you want to log out of service account <clientID>? Yes
Successfully logged out of '<clientID>'
```
_Jira ticket:_ [CLOUDP-337696](https://jira.mongodb.org/browse/CLOUDP-337696)

CLOUDP-337696: Enable logout from Service Account

---

build/ci/evergreen.yml
internal/cli/auth/logout.go
internal/cli/commonerrors/errors.go
internal/cli/config/set.go
internal/config/profile.go
internal/transport/transport.go
internal/validate/validate.go
test/e2e/atlas/serviceAccount/service_account_test.go
test/internal/atlas_e2e_test_generator.go
test/internal/helper.go

Adds e2e test for service account. this test:
* Provisions an SA using existing e2e profile
* Sets up new profile with SA credentials
* Runs basic command with SA profile
* Logs out of SA profile
* Deletes SA
SA is provisioned using `atlas api` cmds. This approach was chosen over direct curl calls as use of existing CLI cmds to provision resources is precedent in e2e testing and greatly simplifies retrieving digest credentials for making the call.
* Logout will ignore oauth2 error "This specific service account doesn't exist" when revoking SA token and proceed with logout.
* Fix to setting TokenURL & RevokeURL
* Amend ErrUnauthorized to mention SA
_Jira ticket:_ [CLOUDP-329808](https://jira.mongodb.org/browse/CLOUDP-329808)

CLOUDP-329808: Adds service account e2e test

---

internal/cli/auth/logout.go

during testing, noticed that logging out of empty default resulted in prompt message 
` ? Are you sure you want to log out of profile default?%!(EXTRA string=default)`
To address this, I changed which parameters are injected by the promptMessage method. 
Success message now says profile name instead of public api key/client id/ user account
See below for changes to messaging
```
// empty default
// before
> bin/atlas logout
? Are you sure you want to log out of profile default?%!(EXTRA string=default) Yes
Successfully logged out of 'default'
// after
> bin/atlas logout
? Are you sure you want to log out of profile default? Yes
Successfully logged out of 'default'
```
```
// service account
// before
> bin/atlas logout
? Are you sure you want to log out of profile sa with service account …
```

chore: improves logout messaging

---

internal/cli/plugin/first_class.go
internal/plugin/plugin.go
test/e2e/kubernetes/pluginfirstclass/plugin_first_class_test.go

uncomments plugin version verification done in [CLOUDP-339293](https://jira.mongodb.org/browse/CLOUDP-339293)
**Note:** The e2e test `test/e2e/kubernetes/pluginfirstclass TestPluginKubernetes` will fail until the release of `atlas-cli-plugin-kubernetes v1.1.7`
_Jira ticket:_ [CLOUDP-340658](https://jira.mongodb.org/browse/CLOUDP-340658)

CLOUDP-340658: enable plugin version verification

---

.github/workflows/code-health.yml
.github/workflows/update-e2e-tests.yml
scripts/add-e2e-profiles.sh

_Jira ticket:_ CLOUDP-342259
- We were trying to clean up more than needed (see this evg [patch](https://spruce.mongodb.com/task/mongodb_atlas_cli_master_e2e_cleanup_atlas_cleanup_e2e_68ba40a2fd28d7000749e0df_25_09_05_01_45_06/tests?execution=0&sorts=STATUS%3AASC)), including our cloud-dev project that contains clusters that shouldn't be deleted. I added them as env variables to the cleanup step.
- Missing config in cleanup authentication
- Updating telemetry in some profiles

CLOUDP-342259: Fix e2e test clean up

---

test/e2e/atlas/search/search/search_test.go

_Jira ticket:_ CLOUDP-342259
This fixes the search e2e tests, we were trying to list an index that was already deleted. 
[atlas_search_e2e](https://spruce.mongodb.com/task/mongodb_atlas_cli_master_e2e_atlas_clusters_atlas_search_e2e_patch_80d80e776fd2f947a6d183a211a628b635d41ad1_68bef95289fefa00072bd87a_25_09_08_15_42_11?execution=0)

CLOUDP-342259: fixes search e2e test

---

.github/workflows/code-health.yml
.github/workflows/update-e2e-tests.yml
build/ci/evergreen.yml
scripts/add-e2e-profiles.sh
test/e2e/config/config/config_test.go
test/internal/helper.go

Removes warning `Warning: Secure storage is not available, falling back to insecure storage [...]` by adding global config property `silence_storage_warning`
* [before](https://parsley.mongodb.com/evergreen/mongodb_atlas_cli_master_e2e_generic_atlas_generic_e2e_feaebe104365505f810ce40822e87803706c3fcf_25_09_09_10_03_08/0/task?bookmarks=0,498) 
* [after](https://parsley.mongodb.com/evergreen/mongodb_atlas_cli_master_e2e_generic_atlas_generic_e2e_patch_feaebe104365505f810ce40822e87803706c3fcf_68c018b42e90580007ce7057_25_09_09_12_08_22/0/task) 
* [before](https://github.com/mongodb/mongodb-atlas-cli/actions/runs/17579058771/job/49930970919)
* [after](https://github.com/mongodb/mongodb-atlas-cli/actions/runs/17582061233/job/49940589778?pr=4208)

chore: Adds silence_storage_warning=true to e2e tests and profiles

---

build/ci/release.yml
build/package/docker/meta/amazonlinux2023-rpm.Dockerfile
build/package/docker/meta/centos8-rpm.Dockerfile
build/package/docker/meta/debian11-deb.Dockerfile
build/package/docker/meta/debian12-deb.Dockerfile
build/package/docker/meta/docker-build.sh
build/package/docker/meta/rhel9-rpm.Dockerfile
build/package/docker/meta/suse15-rpm.Dockerfile
build/package/docker/meta/ubuntu20.04-deb.Dockerfile
build/package/docker/meta/ubuntu22.04-deb.Dockerfile
build/package/docker/meta/ubuntu24.04-deb.Dockerfile
build/package/docker/repo/amazonlinux2023.Dockerfile
build/package/docker/repo/centos8.Dockerfile
build/package/docker/repo/debian11.Dockerfile
build/package/docker/repo/debian12.Dockerfile
build/package/docker/repo/docker-build.sh
build/package/docker/repo/rhel9.Dockerfile
build/package/docker/repo/suse15.Dockerfile
build/package/docker/repo/ubuntu20.04.Dockerfile
build/package/docker/repo/ubuntu22.04.Dockerfile
build/package/docker/repo/ubuntu24.04.Dockerfile
internal/cli/deployments/options/deployment_opts.go
internal/cli/deployments/setup.go
internal/cli/deployments/setup_test.go
test/e2e/atlas/deployments/local/auth/deprecated/deploymentslocalauthindexdeprecated/deployments_local_auth_index_deprecated_test.go
test/e2e/atlas/deployments/local/auth/new/deploymentslocalauth/deployments_local_auth_test.go
test/e2e/atlas/deployments/local/noauth/deploymentslocalnoauth/deployments_local_noauth_test.go
tools/cmd/genevergreen/generate/generate.go
tools/cmd/genevergreen/generate/generate_test.go
tools/cmd/genevergreen/generate/publish.go

_Jira ticket:_ CLOUDP-346295
This is the first PR for this task, adding support for 8.2 first, will try to automate based on atlas local framework in the next PR. I think the 8.2 failures are because we didn't publish yet to 8.2

CLOUDP-346295: add MDB 8.2
